BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBB BBBB BBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
     XX XXXXXXXXXXXXXX gettext('Home') XXXX XXXXXXXX
     XX XXXXXXXXXXXFFFFFFFFXXXX XXXXXXXX
     XX XXXXXXXXXXFFFFFFFFXXXX XXXXXXXX
      gettext('Delete multiple objects') 
XXXXXX
BBBBBBBB

BBBBB BBBBBBB
BB BBBBBBBBBBBBB BB BBBBBBBBB
    BB BBBBBBBBBBBBB
        XXX gettext("Deleting the selected %(objects_name)s would result in deleting related objects, but your account doesn't have permission to delete the following types of objects:") SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSS SS SSSSSSSS SSSSSSS SSSSSSSS SSS SSSS SSSSSSS SSSSSSS SSSS SSSSSSSSSS SS SSSSSS SSS SSSSSSSSS SSSSS SS SSSSSSSSXXXX
        XXXX
        BBB BBB BB BBBBBBBBBBBBB
            XXXXXXXXX
        BBBBBB
        XXXXX
    BBBBB
    BB BBBBBBBBB
        XXX gettext('Deleting the selected %(objects_name)s would require deleting the following protected related objects:') SSSSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSS SSSSS SSSSSSS SSSSSSSS SSS SSSSSSSSS SSSSSSSSS SSSSSSS SSSSSSSSXXXX
        XXXX
        BBB BBB BB BBBBBBBBB
            XXXXXXXXX
        BBBBBB
        XXXXX
    BBBBB
BBBB
    XXX gettext('Are you sure you want to delete the selected %(objects_name)s? All of the following objects and their related items will be deleted:') SSS SSS SSSS SSS SSSS SS SSSSSS SSS SSSSSSSS SSSSSSSSSSSSSSSSS SSS SS SSS SSSSSSSSS SSSSSSS SSS SSSSS SSSSSSS SSSSS SSSS SS SSSSSSSSXXXX
    BBB BBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBB
        XXXXFFFFFFFFFFFFFFXXXXX
    BBBBBB
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    XXXXX
    BBB BBB BB BBBBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXFFFFFFFFFFX XX
    BBBBBB
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX
    XXXXXX XXXXXXXXXXXXX XXXXXXX gettext("Yes, I'm sure") X XX
    XXXXXX
    XXXXXXX
BBBBB
BBBBBBBB
