# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################


# Argentina
AR_regions = [
    ((u'C',    u'Buenos Aires (Capital Federal)'),[
        (u'1', u'Agronomía'),
        (u'2', u'Almagro'),
        (u'3', u'Balvanera'),
        (u'4', u'Barracas'),
        (u'5', u'Belgrano'),
        (u'6', u'Boedo'),
        (u'7', u'Caballito'),
        (u'8', u'Chacarita'),
        (u'9', u'Coghlan'),
        (u'10', u'Colegiales'),
        (u'11', u'Constitución'),
        (u'12', u'Flores'),
        (u'13', u'Floresta'),
        (u'14', u'La Boca'),
        (u'15', u'La Paternal'),
        (u'16', u'Liniers'),
        (u'17', u'Mataderos'),
        (u'18', u'Monte Castro'),
        (u'19', u'Montserrat'),
        (u'20', u'Nueva Pompeya'),
        (u'21', u'Núñez'),
        (u'22', u'Palermo'),
        (u'23', u'Parque Avellaneda'),
        (u'24', u'Parque Chacabuco'),
        (u'25', u'Parque Chas'),
        (u'26', u'Parque Patricios'),
        (u'27', u'Puerto Madero'),
        (u'28', u'Recoleta'),
        (u'29', u'Retiro'),
        (u'30', u'Saavedra'),
        (u'31', u'San Cristóbal'),
        (u'32', u'San Nicolás'),
        (u'33', u'San Telmo'),
        (u'34', u'Vélez Sársfield'),
        (u'35', u'Versalles'),
        (u'36', u'Villa Crespo'),
        (u'37', u'Villa del Parque'),
        (u'38', u'Villa Devoto'),
        (u'39', u'Villa Lugano'),
        (u'40', u'Villa Luro'),
        (u'41', u'Villa Mitre'),
        (u'42', u'Villa Ortúzar'),
        (u'43', u'Villa Pueyrredón'),
        (u'44', u'Villa Real'),
        (u'45', u'Villa Riachuelo'),
        (u'46', u'Villa Santa Rita'),
        (u'47', u'Villa Soldati'),
        (u'48', u'Villa Urquiza'),
    ]),    
    ((u'B',    u'Buenos Aires (Provincia)'),[
        (u'1', u'Adolfo Alsina (Carhué)'),
        (u'2', u'Adolfo Gonzales Chaves'),
        (u'3', u'Alberti'),
        (u'4', u'Almirante Brown (Adrogué)'),
        (u'5', u'Arrecifes'),
        (u'6', u'Avellaneda'),
        (u'7', u'Ayacucho'),
        (u'8', u'Azul'),
        (u'9', u'Bahía Blanca'),
        (u'10', u'Balcarce'),
        (u'11', u'Baradero'),
        (u'12', u'Benito Juárez'),
        (u'13', u'Berazategui'),
        (u'14', u'Berisso'),
        (u'15', u'Bolívar (San Carlos de Bolívar)'),
        (u'16', u'Bragado'),
        (u'17', u'Brandsen'),
        (u'18', u'Campana'),
        (u'19', u'Cañuelas'),
        (u'20', u'Capitán Sarmiento'),
        (u'21', u'Carlos Casares'),
        (u'22', u'Carlos Tejedor'),
        (u'23', u'Carmen de Areco'),
        (u'24', u'Castelli'),
        (u'25', u'Chacabuco'),
        (u'26', u'Chascomús)'),
        (u'27', u'Chivilcoy'),
        (u'28', u'Colón'),
        (u'29', u'Coronel Dorrego'),
        (u'30', u'Coronel Pringles'),
        (u'31', u'Coronel Rosales (Punta Alta)'),
        (u'32', u'Coronel Suárez'),
        (u'33', u'Daireaux'),
        (u'34', u'Dolores'),
        (u'35', u'Ensenada'),
        (u'36', u'Escobar (Belén de Escobar)'),
        (u'37', u'Esteban Echeverría (Monte Grande)'),
        (u'38', u'Exaltación de la Cruz (Capilla del Señor)'),
        (u'39', u'Ezeiza (José María Ezeiza)'),
        (u'40', u'Florencio Varela'),
        (u'41', u'Florentino Ameghino'),
        (u'42', u'General Alvarado (Miramar)'),
        (u'43', u'General Alvear'),
        (u'44', u'General Arenales'),
        (u'45', u'General Belgrano'),
        (u'46', u'General Guido'),
        (u'47', u'General La Madrid'),
        (u'48', u'General Las Heras'),
        (u'49', u'General Lavalle'),
        (u'50', u'General Madariaga (General Juan Madariaga)'),
        (u'51', u'General Paz (Ranchos)'),
        (u'52', u'General Pinto'),
        (u'53', u'General Pueyrredón (Mar del Plata)'),
        (u'54', u'General Rodríguez'),
        (u'55', u'General San Martín'),
        (u'56', u'General Viamonte'),
        (u'57', u'General Villegas'),
        (u'58', u'Guaminí'),
        (u'59', u'Hipólito Yrigoyen (Henderson)'),
        (u'60', u'Hurlingham'),
        (u'61', u'Ituzaingo'),
        (u'62', u'José C. Paz'),
        (u'63', u'Junín'),
        (u'64', u'La Costa (Mar del Tuyú)'),
        (u'65', u'La Matanza (San Justo)'),
        (u'66', u'La Plata'),
        (u'67', u'Lanús'),
        (u'68', u'Laprida'),
        (u'69', u'Las Flores'),
        (u'70', u'Leandro N. Alem (Vedia)'),
        (u'71', u'Lezama'),
        (u'72', u'Lincoln'),
        (u'73', u'Lobería'),
        (u'74', u'Lobos'),
        (u'75', u'Lomas de Zamora'),
        (u'76', u'Luján'),
        (u'77', u'Magdalena'),
        (u'78', u'Maipú'),
        (u'79', u'Malvinas Argentinas (Los Polvorines)'),
        (u'80', u'Mar Chiquita (Coronel Vidal)'),
        (u'81', u'Marcos Paz'),
        (u'82', u'Mercedes'),
        (u'83', u'Merlo'),
        (u'84', u'Monte Hermoso'),
        (u'85', u'Moreno'),
        (u'86', u'Morón'),
        (u'87', u'Navarro'),
        (u'88', u'Necochea'),
        (u'89', u'Nueve de Julio'),
        (u'90', u'Olavarría'),
        (u'91', u'Patagones (Carmen de Patagones)'),
        (u'92', u'Pehuajó'),
        (u'93', u'Pellegrini'),
        (u'94', u'Pergamino'),
        (u'95', u'Pila'),
        (u'96', u'Pilar'),
        (u'97', u'Pinamar'),
        (u'98', u'Presidente Perón (Guernica)'),
        (u'99', u'Puán'),
        (u'100', u'Punta Indio (Verónica)'),
        (u'101', u'Quilmes'),
        (u'102', u'Ramallo'),
        (u'103', u'Rauch'),
        (u'104', u'Rivadavia (América)'),
        (u'105', u'Rojas'),
        (u'106', u'Roque Pérez'),
        (u'107', u'Saavedra (Pigüé)'),
        (u'108', u'Saladillo'),
        (u'109', u'Salto'),
        (u'110', u'Salliqueló'),
        (u'111', u'San Andrés de Giles'),
        (u'112', u'San Antonio de Areco'),
        (u'113', u'San Cayetano'),
        (u'114', u'San Fernando'),
        (u'115', u'San Isidro'),
        (u'116', u'San Miguel'),
        (u'117', u'San Miguel del Monte (Monte)'),
        (u'118', u'San Nicolás (San Nicolás de los Arroyos)'),
        (u'119', u'San Pedro'),
        (u'120', u'San Vicente'),
        (u'121', u'Suipacha'),
        (u'122', u'Tandil'),
        (u'123', u'Tapalqué'),
        (u'124', u'Tigre'),
        (u'125', u'Tordillo (General Conesa)'),
        (u'126', u'Tornquist'),
        (u'127', u'Trenque Lauquen'),
        (u'128', u'Tres Arroyos'),
        (u'129', u'Tres de Febrero (Caseros)'),
        (u'130', u'Tres Lomas'),
        (u'131', u'Veinticinco de Mayo'),
        (u'132', u'Vicente López (Olivos)'),
        (u'133', u'Villa Gesell'),
        (u'134', u'Villarino (Médanos)'),
        (u'135', u'Zárate'),
        ]),
    ((u"K", u"Catamarca"), [
        (u"AM",  u"Ambato"),
        (u"AC",  u"Ancasti"),
        (u"AG",  u"Andalgalá"),
        (u"AS",  u"Antofagasta de la Sierra"),
        (u"BE",  u"Belén"),
        (u"CA",  u"Capayán"),
        (u"CT",  u"Capital (Catamarca)"),
        (u"EA",  u"El Alto"),
        (u"FE",  u"Fray Mamerto Esquiú"),
        (u"LP",  u"La Paz"),
        (u"PA",  u"Paclín"),
        (u"PO",  u"Pomán"),
        (u"SM",  u"Santa María"),
        (u"SR",  u"Santa Rosa"),
        (u"TI",  u"Tinogasta"),
        (u"VV",  u"Valle Viejo"),
        ]),

    ((u"H", u"Chaco"), [
        (u"AB",  u"Almirante Brown"),
        (u"BE",  u"Bermejo"),
        (u"CH",  u"Chacabuco"),
        (u"CF",  u"Comandante Fernández"),
        (u"DC",  u"Doce de Octubre"),
        (u"DA",  u"Dos de Abril"),
        (u"FJ",  u"Fray Justo Santa María de Oro"),
        (u"GB",  u"General Belgrano"),
        (u"GD",  u"General Donovan"),
        (u"GG",  u"General Güemes"),
        (u"IN",  u"Independencia"),
        (u"LI",  u"Libertad"),
        (u"LM",  u"Libertador General San Martín"),
        (u"MA",  u"Maipú"),
        (u"MF",  u"Mayor Luis J. Fontana"),
        (u"NJ",  u"Nueve de Julio"),
        (u"OH",  u"O'Higgins"),
        (u"PP",  u"Presidencia de la Plaza"),
        (u"PM",  u"Primero de Mayo"),
        (u"QU",  u"Quitilipi"),
        (u"SF",  u"San Fernando"),
        (u"SL",  u"San Lorenzo"),
        (u"SC",  u"Sargento Cabral"),
        (u"TA",  u"Tapenagá"),
        (u"VM",  u"Veinticinco de Mayo"),
        ]),

    ((u"U", u"Chubut"), [
        (u"BI",  u"Biedma"),
        (u"CU",  u"Cushamen"),
        (u"ES",  u"Escalante"),
        (u"FA",  u"Florentino Ameghino"),
        (u"FU",  u"Futaleufú"),
        (u"GM",  u"Gaiman"),
        (u"GS",  u"Gastre"),
        (u"LA",  u"Languiñeo"),
        (u"MA",  u"Mártires"),
        (u"PI",  u"Paso de Indios"),
        (u"RA",  u"Rawson"),
        (u"RS",  u"Río Senguer"),
        (u"SA",  u"Sarmiento"),
        (u"TH",  u"Tehuelches"),
        (u"TN",  u"Telsen"),
        ]),

    ((u"W", u"Corrientes"), [
        (u"BV",  u"Bella Vista"),
        (u"BA",  u"Berón de Astrada"),
        (u"CN",  u"Capital (Corrientes)"),
        (u"CO",  u"Concepción"),
        (u"CC",  u"Curuzú Cuatiá"),
        (u"EM",  u"Empedrado"),
        (u"ES",  u"Esquina"),
        (u"GA",  u"General Alvear"),
        (u"GP",  u"General Paz"),
        (u"GO",  u"Goya"),
        (u"IT",  u"Itatí"),
        (u"IZ",  u"Ituzaingó"),
        (u"LA",  u"Lavalle"),
        (u"MB",  u"Mburucuyá"),
        (u"ME",  u"Mercedes"),
        (u"MC",  u"Monte Caseros"),
        (u"PL",  u"Paso de los Libres"),
        (u"SL",  u"Saladas"),
        (u"SC",  u"San Cosme"),
        (u"SP",  u"San Luis del Palmar"),
        (u"SM",  u"San Martín"),
        (u"SG",  u"San Miguel"),
        (u"SR",  u"San Roque"),
        (u"ST",  u"Santo Tomé"),
        (u"SA",  u"Sauce"),
        ]),

    ((u"X", u"Córdoba"), [
        (u"CA",  u"Calamuchita"),
        (u"CB",  u"Capital (Córdoba)"),
        (u"CO",  u"Colón"),
        (u"CE",  u"Cruz del Eje"),
        (u"GR",  u"General Roca"),
        (u"GM",  u"General San Martín"),
        (u"IS",  u"Ischilín"),
        (u"JC",  u"Juárez Celman"),
        (u"MJ",  u"Marcos Juárez"),
        (u"MI",  u"Minas"),
        (u"PO",  u"Pocho"),
        (u"PP",  u"Presidente Roque Sáenz Peña"),
        (u"PU",  u"Punilla"),
        (u"RC",  u"Río Cuarto"),
        (u"RP",  u"Río Primero"),
        (u"RS",  u"Río Seco"),
        (u"RG",  u"Río Segundo"),
        (u"SA",  u"San Alberto"),
        (u"SV",  u"San Javier"),
        (u"SJ",  u"San Justo"),
        (u"SM",  u"Santa María"),
        (u"SO",  u"Sobremonte"),
        (u"TA",  u"Tercero Arriba"),
        (u"TO",  u"Totoral"),
        (u"TU",  u"Tulumba"),
        (u"UN",  u"Unión"),
        ]),

    ((u"E", u"Entre Ríos"), [
        (u"CO",  u"Colón"),
        (u"CC",  u"Concordia"),
        (u"DI",  u"Diamante"),
        (u"FC",  u"Federación"),
        (u"FE",  u"Federal"),
        (u"FL",  u"Feliciano"),
        (u"GG",  u"Gualeguay"),
        (u"GC",  u"Gualeguaychú"),
        (u"II",  u"Islas del Ibicuy"),
        (u"LP",  u"La Paz"),
        (u"NO",  u"Nogoyá"),
        (u"PA",  u"Paraná"),
        (u"SS",  u"San Salvador"),
        (u"TA",  u"Tala"),
        (u"UR",  u"Uruguay"),
        (u"VC",  u"Victoria"),
        (u"VG",  u"Villaguay"),
        ]),

    ((u"P", u"Formosa"), [
        (u"BE",  u"Bermejo"),
        (u"FO",  u"Formosa"),
        (u"LA",  u"Laishi"),
        (u"MA",  u"Matacos"),
        (u"PA",  u"Patiño"),
        (u"PG",  u"Pilagás"),
        (u"PM",  u"Pilcomayo"),
        (u"PR",  u"Pirané"),
        (u"RL",  u"Ramón Lista"),
        ]),

    ((u"Y", u"Jujuy"), [
        (u"CO",  u"Cochinoca"),
        (u"DB",  u"Doctor Manuel Belgrano"),
        (u"EC",  u"El Carmen"),
        (u"HU",  u"Humahuaca"),
        (u"LE",  u"Ledesma"),
        (u"PA",  u"Palpalá"),
        (u"RI",  u"Rinconada"),
        (u"SA",  u"San Antonio"),
        (u"SP",  u"San Pedro"),
        (u"SB",  u"Santa Bárbara"),
        (u"SC",  u"Santa Catalina"),
        (u"SU",  u"Susques"),
        (u"TI",  u"Tilcara"),
        (u"TU",  u"Tumbaya"),
        (u"VG",  u"Valle Grande"),
        (u"YA",  u"Yavi"),
        ]),

    ((u"L", u"La Pampa"), [
        (u"AT",  u"Atreucó"),
        (u"CL",  u"Caleu Caleu"),
        (u"SR",  u"Capital (Santa Rosa)"),
        (u"CA",  u"Catriló"),
        (u"CH",  u"Chalileo"),
        (u"CP",  u"Chapaleufú"),
        (u"CC",  u"Chical Có"),
        (u"CO",  u"Conhelo"),
        (u"CU",  u"Curacó"),
        (u"GU",  u"Guatraché"),
        (u"HU",  u"Hucal"),
        (u"UC",  u"Lihuel Calel"),
        (u"LM",  u"Limay Mahuida"),
        (u"LO",  u"Loventué"),
        (u"MA",  u"Maracó"),
        (u"PU",  u"Puelén"),
        (u"QQ",  u"Quemú Quemú"),
        (u"RA",  u"Rancul"),
        (u"RE",  u"Realicó"),
        (u"TO",  u"Toay"),
        (u"TR",  u"Trenel"),
        (u"UT",  u"Utracán"),
        ]),

    ((u"F", u"La Rioja"), [
        (u"AR",  u"Arauco"),
        (u"LR",  u"Capital (La Rioja)"),
        (u"CB",  u"Castro Barros"),
        (u"CM",  u"Chamical"),
        (u"CL",  u"Chilecito"),
        (u"CV",  u"Coronel Felipe Varela"),
        (u"FA",  u"Famatina"),
        (u"GP",  u"General Angel Vicente Peñaloza"),
        (u"GB",  u"General Belgrano"),
        (u"GQ",  u"General Juan Facundo Quiroga"),
        (u"GL",  u"General Lamadrid"),
        (u"GO",  u"General Ocampo"),
        (u"GM",  u"General San Martín"),
        (u"IN",  u"Independencia"),
        (u"RP",  u"Rosario Vera Peñaloza"),
        (u"SS",  u"San Blas de los Sauces"),
        (u"SA",  u"Sanagasta"),
        (u"VI",  u"Vinchina"),
        ]),

    ((u"M", u"Mendoza"), [
        (u"MZ",  u"Capital (Mendoza)"),
        (u"GA",  u"General Alvear"),
        (u"GC",  u"Godoy Cruz"),
        (u"GU",  u"Guaymallén"),
        (u"JU",  u"Junín"),
        (u"LP",  u"La Paz"),
        (u"LH",  u"Las Heras"),
        (u"LA",  u"Lavalle"),
        (u"LC",  u"Luján de Cuyo"),
        (u"MP",  u"Maipú"),
        (u"ML",  u"Malargüe"),
        (u"RI",  u"Rivadavia"),
        (u"SC",  u"San Carlos"),
        (u"SM",  u"San Martín"),
        (u"SR",  u"San Rafael"),
        (u"ST",  u"Santa Rosa"),
        (u"TN",  u"Tunuyán"),
        (u"TP",  u"Tupungato"),
        ]),

    ((u"N", u"Misiones"), [
        (u"AP",  u"Apóstoles"),
        (u"CG",  u"Cainguás"),
        (u"CD",  u"Candelaria"),
        (u"PS",  u"Capital (Posadas)"),
        (u"CO",  u"Concepción"),
        (u"ED",  u"Eldorado"),
        (u"GB",  u"General Manuel Belgrano"),
        (u"GU",  u"Guaraní"),
        (u"IG",  u"Iguazú"),
        (u"LA",  u"Leandro N. Alem"),
        (u"LM",  u"Libertador General San Martín"),
        (u"MO",  u"Montecarlo"),
        (u"OB",  u"Oberá"),
        (u"SI",  u"San Ignacio"),
        (u"SJ",  u"San Javier"),
        (u"SP",  u"San Pedro"),
        (u"VM",  u"Veinticinco de Mayo"),
        ]),

    ((u"Q", u"Neuquén"), [
        (u"AL",  u"Aluminé"),
        (u"AN",  u"Añelo"),
        (u"CL",  u"Catán Lil"),
        (u"CM",  u"Chos Malal"),
        (u"CC",  u"Collón Curá"),
        (u"CO",  u"Confluencia"),
        (u"HU",  u"Huiliches"),
        (u"LA",  u"Lacar"),
        (u"LO",  u"Loncopué"),
        (u"LL",  u"Los Lagos"),
        (u"MI",  u"Minas"),
        (u"PE",  u"Pehuenches"),
        (u"PI",  u"Picunches"),
        (u"PL",  u"Picún Leufú"),
        (u"ZA",  u"Zapala"),
        (u"NO",  u"Ñorquín"),
        ]),

    ((u"R", u"Río Negro"), [
        (u"AA",  u"Adolfo Alsina"),
        (u"AV",  u"Avellaneda"),
        (u"BA",  u"Bariloche"),
        (u"CO",  u"Conesa"),
        (u"EC",  u"El Cuy"),
        (u"GR",  u"General Roca"),
        (u"NJ",  u"Nueve de julio"),
        (u"PM",  u"Pichi Mahuida"),
        (u"PI",  u"Pilcaniyeu"),
        (u"SA",  u"San Antonio"),
        (u"VA",  u"Valcheta"),
        (u"VM",  u"Veinticinco de Mayo"),
        (u"NO",  u"Ñorquinco"),
        ]),

    ((u"A", u"Salta"), [
        (u"AN",  u"Anta"),
        (u"CA",  u"Cachi"),
        (u"CF",  u"Cafayate"),
        (u"SA",  u"Capital (Salta)"),
        (u"CE",  u"Cerrillos"),
        (u"CH",  u"Chicoana"),
        (u"GG",  u"General Güemes"),
        (u"GM",  u"General José de San Martín"),
        (u"GU",  u"Guachipas"),
        (u"IR",  u"Iruya"),
        (u"LC",  u"La Caldera"),
        (u"LD",  u"La Candelaria"),
        (u"LP",  u"La Poma"),
        (u"LV",  u"La Viña"),
        (u"LA",  u"Los Andes"),
        (u"ME",  u"Metán"),
        (u"MO",  u"Molinos"),
        (u"OR",  u"Orán"),
        (u"RI",  u"Rivadavia"),
        (u"RL",  u"Rosario de Lerma"),
        (u"RF",  u"Rosario de la Frontera"),
        (u"SC",  u"San Carlos"),
        (u"SV",  u"Santa Victoria"),
        ]),

    ((u"J", u"San Juan"), [
        (u"AL",  u"Albardón"),
        (u"AN",  u"Angaco"),
        (u"CL",  u"Calingasta"),
        (u"SJ",  u"Capital (San Juan)"),
        (u"CC",  u"Caucete"),
        (u"CH",  u"Chimbas"),
        (u"IG",  u"Iglesia"),
        (u"JA",  u"Jáchal"),
        (u"NU",  u"Nueve de Julio"),
        (u"PO",  u"Pocito"),
        (u"RA",  u"Rawson"),
        (u"RI",  u"Rivadavia"),
        (u"SM",  u"San Martín"),
        (u"SL",  u"Santa Lucía"),
        (u"SA",  u"Sarmiento"),
        (u"UL",  u"Ullum"),
        (u"VF",  u"Valle Fértil"),
        (u"VM",  u"Veinticinco de Mayo"),
        (u"ZO",  u"Zonda"),
        ]),

    ((u"D", u"San Luis"), [
        (u"AY",  u"Ayacucho"),
        (u"BE",  u"Belgrano"),
        (u"CH",  u"Chacabuco"),
        (u"CP",  u"Coronel Pringles"),
        (u"GP",  u"General Pedernera"),
        (u"GD",  u"Gobernador Dupuy"),
        (u"JU",  u"Junín"),
        (u"LC",  u"La Capital"),
        (u"LM",  u"Libertador General San Martín"),
        ]),

    ((u"Z", u"Santa Cruz"), [
        (u"CA",  u"Corpen Aike"),
        (u"DE",  u"Deseado"),
        (u"GA",  u"Güer Aike"),
        (u"LA",  u"Lago Argentino"),
        (u"LB",  u"Lago Buenos Aires"),
        (u"MA",  u"Magallanes"),
        (u"RC",  u"Río Chico"),
        ]),

    ((u"S", u"Santa Fe"), [
        (u"BE",  u"Belgrano"),
        (u"CR",  u"Caseros"),
        (u"CL",  u"Castellanos"),
        (u"CO",  u"Constitución"),
        (u"GA",  u"Garay"),
        (u"GL",  u"General López"),
        (u"GO",  u"General Obligado"),
        (u"IR",  u"Iriondo"),
        (u"LP",  u"La Capital"),
        (u"LC",  u"Las Colonias"),
        (u"NJ",  u"Nueve de Julio"),
        (u"RO",  u"Rosario"),
        (u"SC",  u"San Cristóbal"),
        (u"SV",  u"San Javier"),
        (u"SR",  u"San Jerónimo"),
        (u"SJ",  u"San Justo"),
        (u"SL",  u"San Lorenzo"),
        (u"SM",  u"San Martín"),
        (u"VE",  u"Vera"),
        ]),

    ((u"G", u"Santiago del Estero"), [
        (u"AG",  u"Aguirre"),
        (u"AL",  u"Alberdi"),
        (u"AT",  u"Atamisqui"),
        (u"AV",  u"Avellaneda"),
        (u"BA",  u"Banda"),
        (u"BE",  u"Belgrano"),
        (u"SE",  u"Capital (Santiago del Estero)"),
        (u"CH",  u"Choya"),
        (u"CO",  u"Copo"),
        (u"FI",  u"Figueroa"),
        (u"GT",  u"General Taboada"),
        (u"GU",  u"Guasayán"),
        (u"JM",  u"Jiménez"),
        (u"JI",  u"Juan Felipe Ibarra"),
        (u"LO",  u"Loreto"),
        (u"MI",  u"Mitre"),
        (u"MO",  u"Moreno"),
        (u"OJ",  u"Ojo de Agua"),
        (u"PE",  u"Pellegrini"),
        (u"QU",  u"Quebrachos"),
        (u"RI",  u"Rivadavia"),
        (u"RO",  u"Robles"),
        (u"RH",  u"Río Hondo"),
        (u"SV",  u"Salavina"),
        (u"SM",  u"San Martín"),
        (u"SR",  u"Sarmiento"),
        (u"SI",  u"Silípica"),
        ]),

    ((u"V", u"Tierra del Fuego"), [
        (u"RG",  u"Río Grande"),
        (u"US",  u"Ushuaia"),
        ]),

    ((u"T", u"Tucumán"), [
        (u"BU",  u"Burruyacú"),
        (u"TM",  u"Capital (Tucumán)"),
        (u"CH",  u"Chicligasta"),
        (u"CA",  u"Cruz Alta"),
        (u"FA",  u"Famaillá"),
        (u"GR",  u"Graneros"),
        (u"JA",  u"Juan B. Alberdi"),
        (u"LC",  u"La Cocha"),
        (u"LE",  u"Leales"),
        (u"LU",  u"Lules"),
        (u"MO",  u"Monteros"),
        (u"RC",  u"Río Chico"),
        (u"SI",  u"Simoca"),
        (u"TV",  u"Tafí Viejo"),
        (u"TD",  u"Tafí del Valle"),
        (u"TR",  u"Trancas"),
        (u"YB",  u"Yerba Buena"),
        ]),
]