# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

AU_regions = [
    ((u"NS", u"New South Wales"), [
        (u"AL",  u"Albury"),
        (u"AD",  u"Armidale Dumaresq"),
        (u"AS",  u"Ashfield"),
        (u"AU",  u"Auburn"),
        (u"BA",  u"Ballina"),
        (u"BN",  u"Balranald"),
        (u"BS",  u"Bankstown"),
        (u"BZ",  u"Barraba"),
        (u"BT",  u"Bathurst"),
        (u"BK",  u"Baulkham Hills"),
        (u"BV",  u"Bega Valley"),
        (u"BE",  u"Bellingen"),
        (u"BG",  u"Berrigan"),
        (u"BI",  u"Bingara"),
        (u"BC",  u"Blacktown"),
        (u"BD",  u"Bland"),
        (u"BL",  u"Blayney"),
        (u"BM",  u"Blue Mountains"),
        (u"BX",  u"Bogan"),
        (u"BO",  u"Bombala"),
        (u"BW",  u"Boorowa"),
        (u"BB",  u"Botany Bay"),
        (u"BQ",  u"Bourke"),
        (u"BR",  u"Brewarrina"),
        (u"BH",  u"Broken Hill"),
        (u"BU",  u"Burwood"),
        (u"BY",  u"Byron"),
        (u"CE",  u"Cabonne"),
        (u"CN",  u"Camden"),
        (u"CT",  u"Campbelltown"),
        (u"CC",  u"Canada Bay"),
        (u"CA",  u"Canterbury"),
        (u"CH",  u"Carrathool"),
        (u"CD",  u"Central Darling"),
        (u"CS",  u"Cessnock"),
        (u"CR",  u"Cobar"),
        (u"CF",  u"Coffs Harbour"),
        (u"CG",  u"Conargo"),
        (u"CL",  u"Coolah"),
        (u"CO",  u"Coolamon"),
        (u"CM",  u"Cooma-Monaro"),
        (u"CB",  u"Coonabarabran"),
        (u"CJ",  u"Coonamble"),
        (u"CQ",  u"Cootamundra"),
        (u"CP",  u"Copmanhurst"),
        (u"CV",  u"Corowa"),
        (u"CW",  u"Cowra"),
        (u"CK",  u"Crookwell"),
        (u"CU",  u"Culcairn"),
        (u"DE",  u"Deniliquin"),
        (u"DB",  u"Dubbo"),
        (u"DG",  u"Dungog"),
        (u"EU",  u"Eurobodalla"),
        (u"EV",  u"Evans"),
        (u"FA",  u"Fairfield"),
        (u"FO",  u"Forbes"),
        (u"GG",  u"Gilgandra"),
        (u"GI",  u"Glen Innes"),
        (u"GC",  u"Gloucester"),
        (u"GF",  u"Gosford"),
        (u"GB",  u"Goulburn"),
        (u"GR",  u"Grafton"),
        (u"GL",  u"Great Lakes"),
        (u"GT",  u"Greater Taree"),
        (u"GH",  u"Griffith"),
        (u"GU",  u"Gundagai"),
        (u"GD",  u"Gunnedah"),
        (u"GN",  u"Gunning"),
        (u"GY",  u"Guyra"),
        (u"HD",  u"Harden"),
        (u"HA",  u"Hastings"),
        (u"HW",  u"Hawkesbury"),
        (u"HY",  u"Hay"),
        (u"HB",  u"Holbrook"),
        (u"HO",  u"Holroyd"),
        (u"HR",  u"Hornsby"),
        (u"HM",  u"Hume"),
        (u"HH",  u"Hunters Hill"),
        (u"HV",  u"Hurstville"),
        (u"IN",  u"Inverell"),
        (u"JE",  u"Jerilderie"),
        (u"JU",  u"Junee"),
        (u"KE",  u"Kempsey"),
        (u"KI",  u"Kiama"),
        (u"KO",  u"Kogarah"),
        (u"KU",  u"Ku-ring-gai"),
        (u"KY",  u"Kyogle"),
        (u"LA",  u"Lachlan"),
        (u"LM",  u"Lake Macquarie"),
        (u"LC",  u"Lane Cove"),
        (u"LE",  u"Leeton"),
        (u"LH",  u"Leichhardt"),
        (u"LI",  u"Lismore"),
        (u"LG",  u"Lithgow"),
        (u"LV",  u"Liverpool"),
        (u"LO",  u"Lockhart"),
        (u"MC",  u"Maclean"),
        (u"MD",  u"Maitland"),
        (u"MA",  u"Manilla"),
        (u"MN",  u"Manly"),
        (u"MV",  u"Marrickville"),
        (u"ME",  u"Merriwa"),
        (u"MP",  u"Moree Plains"),
        (u"MO",  u"Mosman"),
        (u"MG",  u"Mudgee"),
        (u"ML",  u"Mulwaree"),
        (u"MU",  u"Murray"),
        (u"MB",  u"Murrumbidgee"),
        (u"MR",  u"Murrurundi"),
        (u"MS",  u"Muswellbrook"),
        (u"NC",  u"Nambucca"),
        (u"NB",  u"Narrabri"),
        (u"ND",  u"Narrandera"),
        (u"NA",  u"Narromine"),
        (u"NE",  u"Newcastle"),
        (u"NS",  u"North Sydney"),
        (u"NU",  u"Nundle"),
        (u"OB",  u"Oberon"),
        (u"OR",  u"Orange"),
        (u"PK",  u"Parkes"),
        (u"PA",  u"Parramatta"),
        (u"PY",  u"Parry"),
        (u"PE",  u"Penrith"),
        (u"PI",  u"Pittwater"),
        (u"PS",  u"Port Stephens"),
        (u"PW",  u"Pristine Waters"),
        (u"QB",  u"Queanbeyan"),
        (u"QR",  u"Quirindi"),
        (u"RA",  u"Randwick"),
        (u"RV",  u"Richmond Valley"),
        (u"RO",  u"Rockdale"),
        (u"RD",  u"Ryde"),
        (u"RY",  u"Rylstone"),
        (u"SC",  u"Scone"),
        (u"SE",  u"Severn"),
        (u"SH",  u"Shellharbour"),
        (u"SL",  u"Shoalhaven"),
        (u"SI",  u"Singleton"),
        (u"SR",  u"Snowy River"),
        (u"SS",  u"South Sydney"),
        (u"ST",  u"Strathfield"),
        (u"SU",  u"Sutherland"),
        (u"SY",  u"Sydney"),
        (u"TL",  u"Tallaganda"),
        (u"TA",  u"Tamworth"),
        (u"TE",  u"Temora"),
        (u"TN",  u"Tenterfield"),
        (u"TU",  u"Tumbarumba"),
        (u"TT",  u"Tumut"),
        (u"TW",  u"Tweed"),
        (u"UR",  u"Uralla"),
        (u"UN",  u"Urana"),
        (u"WW",  u"Wagga Wagga"),
        (u"WK",  u"Wakool"),
        (u"WH",  u"Walcha"),
        (u"WA",  u"Walgett"),
        (u"WN",  u"Warren"),
        (u"WR",  u"Warringah"),
        (u"WV",  u"Waverley"),
        (u"WD",  u"Weddin"),
        (u"WT",  u"Wellington"),
        (u"WE",  u"Wentworth"),
        (u"WB",  u"Willoughby"),
        (u"WI",  u"Windouran"),
        (u"WC",  u"Wingecarribee"),
        (u"WL",  u"Wollondilly"),
        (u"WG",  u"Wollongong"),
        (u"WO",  u"Woollahra"),
        (u"WY",  u"Wyong"),
        (u"YL",  u"Yallaroi"),
        (u"YR",  u"Yarrowlumla"),
        (u"YS",  u"Yass"),
        (u"YO",  u"Young"),
        ]),

    ((u"NT", u"Northern Territory"), [
        (u"AS",  u"Alice Springs"),
        (u"AL",  u"Alpurrurulam"),
        (u"AN",  u"Angurugu"),
        (u"AM",  u"Anmatjere"),
        (u"AR",  u"Arltarlpilta"),
        (u"BA",  u"Barunga Manyallaluk"),
        (u"BE",  u"Belyuen"),
        (u"BI",  u"Binjari"),
        (u"BO",  u"Borroloola"),
        (u"CO",  u"Coomalie"),
        (u"CP",  u"Cox Peninsula"),
        (u"DG",  u"Daguragu"),
        (u"DR",  u"Darwin"),
        (u"EL",  u"Elliott District"),
        (u"JA",  u"Jabiru"),
        (u"JI",  u"Jilkminggan"),
        (u"KA",  u"Katherine"),
        (u"KU",  u"Kunbarllanjnja"),
        (u"LA",  u"Lajamanu"),
        (u"LI",  u"Litchfield"),
        (u"LT",  u"Ltyentye Purte"),
        (u"MG",  u"Marngarr"),
        (u"MT",  u"Mataranka"),
        (u"MI",  u"Milikapiti"),
        (u"NN",  u"Nauiyu Nambiyu"),
        (u"NG",  u"Nguiu"),
        (u"NU",  u"Numbulwar/Numburindi"),
        (u"PA",  u"Palmerston"),
        (u"PC",  u"Pine Creek"),
        (u"PI",  u"Pirlangimpi"),
        (u"TP",  u"Tapatijatjaka"),
        (u"TC",  u"Tennant Creek"),
        (u"TM",  u"Timber Creek"),
        (u"WN",  u"Walingeri-Ngumpinku"),
        (u"WR",  u"Wallace Rockhole"),
        (u"WA",  u"Watiyawanu"),
        (u"WU",  u"Wugularr"),
        (u"YU",  u"Yuendumu"),
        (u"YM",  u"Yugal Mangi"),
        ]),

    ((u"QL", u"Queensland"), [
        (u"AR",  u"Aramac"),
        (u"AT",  u"Atherton"),
        (u"AU",  u"Aurukun"),
        (u"BA",  u"Balonne"),
        (u"BN",  u"Banana"),
        (u"BC",  u"Barcaldine"),
        (u"BQ",  u"Barcoo"),
        (u"BH",  u"Bauhinia"),
        (u"BE",  u"Beaudesert"),
        (u"BY",  u"Belyando"),
        (u"BM",  u"Bendemere"),
        (u"BI",  u"Biggenden"),
        (u"BL",  u"Blackall"),
        (u"BF",  u"Boonah"),
        (u"BG",  u"Booringa"),
        (u"BO",  u"Boulia"),
        (u"BW",  u"Bowen"),
        (u"BR",  u"Brisbane"),
        (u"BS",  u"Broadsound"),
        (u"BU",  u"Bulloo"),
        (u"BB",  u"Bundaberg"),
        (u"BJ",  u"Bungil"),
        (u"BD",  u"Burdekin"),
        (u"BK",  u"Burke"),
        (u"BT",  u"Burnett"),
        (u"CB",  u"Caboolture"),
        (u"CS",  u"Cairns"),
        (u"CP",  u"Calliope"),
        (u"CD",  u"Caloundra"),
        (u"CY",  u"Cambooya"),
        (u"CW",  u"Cardwell"),
        (u"CA",  u"Carpentaria"),
        (u"CT",  u"Charters Towers"),
        (u"CG",  u"Cherbourg"),
        (u"CH",  u"Chinchilla"),
        (u"CF",  u"Clifton"),
        (u"CL",  u"Cloncurry"),
        (u"CK",  u"Cook"),
        (u"CO",  u"Cooloola"),
        (u"CN",  u"Crow's Nest"),
        (u"CR",  u"Croydon"),
        (u"DB",  u"Dalby"),
        (u"DR",  u"Dalrymple"),
        (u"DI",  u"Diamantina"),
        (u"DM",  u"Doomadgee"),
        (u"DG",  u"Douglas"),
        (u"DU",  u"Duaringa"),
        (u"EA",  u"Eacham"),
        (u"EI",  u"Eidsvold"),
        (u"EM",  u"Emerald"),
        (u"ES",  u"Esk"),
        (u"ET",  u"Etheridge"),
        (u"FI",  u"Fitzroy"),
        (u"FL",  u"Flinders"),
        (u"GT",  u"Gatton"),
        (u"GD",  u"Gayndah"),
        (u"GL",  u"Gladstone"),
        (u"GC",  u"Gold Coast"),
        (u"GO",  u"Goondiwindi"),
        (u"HE",  u"Herberton"),
        (u"HB",  u"Hervey Bay"),
        (u"HI",  u"Hinchinbrook"),
        (u"HO",  u"Hopevale"),
        (u"IL",  u"Ilfracombe"),
        (u"IN",  u"Inglewood"),
        (u"IP",  u"Ipswich"),
        (u"IS",  u"Isis"),
        (u"IF",  u"Isisford"),
        (u"JE",  u"Jericho"),
        (u"JS",  u"Johnstone"),
        (u"JD",  u"Jondaryan"),
        (u"KC",  u"Kilcoy"),
        (u"KK",  u"Kilkivan"),
        (u"KI",  u"Kingaroy"),
        (u"KL",  u"Kolan"),
        (u"KW",  u"Kowanyama"),
        (u"LA",  u"Laidley"),
        (u"LI",  u"Livingstone"),
        (u"LG",  u"Logan"),
        (u"LR",  u"Longreach"),
        (u"MK",  u"Mackay"),
        (u"ME",  u"Mareeba"),
        (u"MY",  u"Maroochy"),
        (u"MA",  u"Maryborough"),
        (u"MC",  u"McKinlay"),
        (u"ML",  u"Millmerran"),
        (u"MR",  u"Mirani"),
        (u"MV",  u"Miriam Vale"),
        (u"MN",  u"Monto"),
        (u"MO",  u"Mornington"),
        (u"MI",  u"Mount Isa"),
        (u"MM",  u"Mount Morgan"),
        (u"MD",  u"Mundubbera"),
        (u"MG",  u"Murgon"),
        (u"MU",  u"Murilla"),
        (u"MW",  u"Murweh"),
        (u"NA",  u"Nanango"),
        (u"NE",  u"Nebo"),
        (u"NO",  u"Noosa"),
        (u"PA",  u"Paroo"),
        (u"PD",  u"Peak Downs"),
        (u"PE",  u"Perry"),
        (u"PR",  u"Pine Rivers"),
        (u"PI",  u"Pittsworth"),
        (u"PO",  u"Pormpuraaw"),
        (u"QP",  u"Quilpie"),
        (u"RC",  u"Redcliffe"),
        (u"RL",  u"Redland"),
        (u"RI",  u"Richmond"),
        (u"RH",  u"Rockhampton"),
        (u"RM",  u"Roma"),
        (u"RS",  u"Rosalie"),
        (u"SA",  u"Sarina"),
        (u"ST",  u"Stanthorpe"),
        (u"TA",  u"Tambo"),
        (u"TR",  u"Tara"),
        (u"TM",  u"Taroom"),
        (u"TH",  u"Thuringowa"),
        (u"TI",  u"Tiaro"),
        (u"TW",  u"Toowoomba"),
        (u"TO",  u"Torres"),
        (u"TV",  u"Townsville"),
        (u"WG",  u"Waggamba"),
        (u"WB",  u"Wambo"),
        (u"WR",  u"Warroo"),
        (u"WA",  u"Warwick"),
        (u"WS",  u"Weipa South"),
        (u"WH",  u"Whitsunday"),
        (u"WI",  u"Winton"),
        (u"WD",  u"Wondai"),
        (u"WC",  u"Woocoo"),
        (u"WO",  u"Woorabinda"),
        (u"WW",  u"Wujal Wujal"),
        (u"YA",  u"Yarrabah"),
        ]),

    ((u"SA", u"South Australia"), [
        (u"AD",  u"Adelaide"),
        (u"AH",  u"Adelaide Hills"),
        (u"AL",  u"Alexandrina"),
        (u"BA",  u"Barossa"),
        (u"BW",  u"Barunga West"),
        (u"BB",  u"Berri and Barmera"),
        (u"BU",  u"Burnside"),
        (u"CA",  u"Campbelltown"),
        (u"CE",  u"Ceduna"),
        (u"CS",  u"Charles Sturt"),
        (u"CG",  u"Clare and Gilbert Valleys"),
        (u"CL",  u"Cleve"),
        (u"CP",  u"Coober Pedy"),
        (u"CO",  u"Coorong"),
        (u"CC",  u"Copper Coast"),
        (u"EL",  u"Elliston"),
        (u"FR",  u"Flinders Ranges"),
        (u"FH",  u"Franklin Harbour"),
        (u"GA",  u"Gawler"),
        (u"GO",  u"Goyder"),
        (u"GR",  u"Grant"),
        (u"HB",  u"Holdfast Bay"),
        (u"KI",  u"Kangaroo Island"),
        (u"KE",  u"Karoonda-East Murray"),
        (u"KB",  u"Kimba"),
        (u"LA",  u"Lacepede"),
        (u"LH",  u"Le Hunte"),
        (u"LI",  u"Light"),
        (u"LE",  u"Lower Eyre Peninsula"),
        (u"LW",  u"Loxton Waikerie"),
        (u"ML",  u"Mallala"),
        (u"MA",  u"Marion"),
        (u"MM",  u"Mid Murray"),
        (u"MI",  u"Mitcham"),
        (u"MB",  u"Mount Barker"),
        (u"MG",  u"Mount Gambier"),
        (u"MR",  u"Mount Remarkable"),
        (u"MU",  u"Murray Bridge"),
        (u"NL",  u"Naracoorte Lucindale"),
        (u"NA",  u"Northern Areas"),
        (u"NP",  u"Norwood Payneham and Saint Peters"),
        (u"ON",  u"Onkaparinga"),
        (u"OC",  u"Orroroo/Carrieton"),
        (u"OA",  u"Outback Areas"),
        (u"PB",  u"Peterborough"),
        (u"PF",  u"Playford"),
        (u"PE",  u"Port Adelaide Enfield"),
        (u"PA",  u"Port Augusta"),
        (u"PL",  u"Port Lincoln"),
        (u"PP",  u"Port Pirie"),
        (u"PR",  u"Prospect"),
        (u"RP",  u"Renmark Paringa"),
        (u"RO",  u"Robe"),
        (u"RD",  u"Roxby Downs"),
        (u"SA",  u"Salisbury"),
        (u"SM",  u"Southern Mallee"),
        (u"SB",  u"Streaky Bay"),
        (u"TA",  u"Tatiara"),
        (u"TT",  u"Tea Tree Gully"),
        (u"TB",  u"Tumby Bay"),
        (u"UN",  u"Unley"),
        (u"VH",  u"Victor Harbor"),
        (u"WF",  u"Wakefield"),
        (u"WV",  u"Walkerville"),
        (u"WR",  u"Wattle Range"),
        (u"WT",  u"West Torrens Thebarton"),
        (u"WH",  u"Whyalla"),
        (u"YA",  u"Yankalilla"),
        (u"YP",  u"Yorke Peninsula"),
        ]),

    ((u"TS", u"Tasmania"), [
        (u"BO",  u"Break O'Day"),
        (u"BR",  u"Brighton"),
        (u"BU",  u"Burnie"),
        (u"CC",  u"Central Coast"),
        (u"CH",  u"Central Highlands"),
        (u"CI",  u"Circular Head"),
        (u"CL",  u"Clarence"),
        (u"DV",  u"Derwent Valley"),
        (u"DE",  u"Devonport"),
        (u"DO",  u"Dorset"),
        (u"FL",  u"Flinders"),
        (u"GT",  u"George Town"),
        (u"GS",  u"Glamorgan-Spring Bay"),
        (u"GL",  u"Glenorchy"),
        (u"HO",  u"Hobart"),
        (u"HV",  u"Huon Valley"),
        (u"KE",  u"Kentish"),
        (u"KI",  u"King Island"),
        (u"KB",  u"Kingborough"),
        (u"LT",  u"Latrobe"),
        (u"LC",  u"Launceston"),
        (u"MV",  u"Meander Valley"),
        (u"NM",  u"Northern Midlands"),
        (u"SO",  u"Sorell"),
        (u"SM",  u"Southern Midlands"),
        (u"TA",  u"Tasman"),
        (u"WW",  u"Waratah-Wynyard"),
        (u"WC",  u"West Coast"),
        (u"WT",  u"West Tamar"),
        ]),

    ((u"VI", u"Victoria"), [
        (u"AL",  u"Alpine"),
        (u"AR",  u"Ararat"),
        (u"BA",  u"Ballarat"),
        (u"BY",  u"Banyule"),
        (u"BC",  u"Bass Coast"),
        (u"BB",  u"Baw Baw"),
        (u"BS",  u"Bayside"),
        (u"BO",  u"Boroondara"),
        (u"BR",  u"Brimbank"),
        (u"BU",  u"Buloke"),
        (u"CP",  u"Campaspe"),
        (u"CA",  u"Cardinia"),
        (u"CS",  u"Casey"),
        (u"CG",  u"Central Goldfields"),
        (u"CO",  u"Colac-Otway"),
        (u"CR",  u"Corangamite"),
        (u"DA",  u"Darebin"),
        (u"DE",  u"Delatite"),
        (u"EG",  u"East Gippsland"),
        (u"FR",  u"Frankston"),
        (u"GA",  u"Gannawarra"),
        (u"GE",  u"Glen Eira"),
        (u"GL",  u"Glenelg"),
        (u"GP",  u"Golden Plains"),
        (u"GB",  u"Greater Bendigo"),
        (u"GD",  u"Greater Dandenong"),
        (u"GG",  u"Greater Geelong"),
        (u"GS",  u"Greater Shepparton"),
        (u"HE",  u"Hepburn"),
        (u"HI",  u"Hindmarsh"),
        (u"HB",  u"Hobsons Bay"),
        (u"HO",  u"Horsham"),
        (u"HU",  u"Hume"),
        (u"IN",  u"Indigo"),
        (u"KI",  u"Kingston"),
        (u"KN",  u"Knox"),
        (u"LA",  u"Latrobe"),
        (u"LO",  u"Loddon"),
        (u"MR",  u"Macedon Ranges"),
        (u"MN",  u"Manningham"),
        (u"MB",  u"Maribyrnong"),
        (u"MH",  u"Maroondah"),
        (u"ME",  u"Melbourne"),
        (u"MT",  u"Melton"),
        (u"ML",  u"Mildura"),
        (u"MC",  u"Mitchell"),
        (u"MI",  u"Moira"),
        (u"MS",  u"Monash"),
        (u"MV",  u"Moonee Valley"),
        (u"MO",  u"Moorabool"),
        (u"MD",  u"Moreland"),
        (u"MP",  u"Mornington Peninsula"),
        (u"MA",  u"Mount Alexander"),
        (u"MY",  u"Moyne"),
        (u"MU",  u"Murrindindi"),
        (u"NI",  u"Nillumbik"),
        (u"NG",  u"Northern Grampians"),
        (u"PP",  u"Port Phillip"),
        (u"PY",  u"Pyrenees"),
        (u"QC",  u"Queenscliffe"),
        (u"SL",  u"South Gippsland"),
        (u"SG",  u"Southern Grampians"),
        (u"SN",  u"Stonnington"),
        (u"SB",  u"Strathbogie"),
        (u"SC",  u"Surf Coast"),
        (u"SH",  u"Swan Hill"),
        (u"TO",  u"Towong"),
        (u"WG",  u"Wangaratta"),
        (u"WR",  u"Warrnambool"),
        (u"WE",  u"Wellington"),
        (u"WW",  u"West Wimmera"),
        (u"WH",  u"Whitehorse"),
        (u"WS",  u"Whittlesea"),
        (u"WO",  u"Wodonga"),
        (u"WY",  u"Wyndham"),
        (u"YA",  u"Yarra"),
        (u"YR",  u"Yarra Ranges"),
        (u"YB",  u"Yarriambiack"),
        ]),

    ((u"WA", u"Western Australia"), [
        (u"AL",  u"Albany"),
        (u"AR",  u"Armadale"),
        (u"AS",  u"Ashburton"),
        (u"AM",  u"Augusta-Margaret River"),
        (u"BA",  u"Bassendean"),
        (u"BW",  u"Bayswater"),
        (u"BE",  u"Belmont"),
        (u"BV",  u"Beverley"),
        (u"BO",  u"Boddington"),
        (u"BB",  u"Boyup Brook"),
        (u"BG",  u"Bridgetown-Greenbushes"),
        (u"BK",  u"Brookton"),
        (u"BM",  u"Broome"),
        (u"BH",  u"Broomehill"),
        (u"BR",  u"Bruce Rock"),
        (u"BU",  u"Bunbury"),
        (u"BS",  u"Busselton"),
        (u"CG",  u"Cambridge"),
        (u"CN",  u"Canning"),
        (u"CP",  u"Capel"),
        (u"CM",  u"Carnamah"),
        (u"CA",  u"Carnarvon"),
        (u"CV",  u"Chapman Valley"),
        (u"CH",  u"Chittering"),
        (u"CL",  u"Claremont"),
        (u"CK",  u"Cockburn"),
        (u"CE",  u"Collie"),
        (u"CO",  u"Coolgardie"),
        (u"CW",  u"Coorow"),
        (u"CI",  u"Corrigin"),
        (u"CT",  u"Cottesloe"),
        (u"CR",  u"Cranbrook"),
        (u"CB",  u"Cuballing"),
        (u"CU",  u"Cue"),
        (u"CD",  u"Cunderdin"),
        (u"DL",  u"Dalwallinu"),
        (u"DN",  u"Dandaragan"),
        (u"DP",  u"Dardanup"),
        (u"DE",  u"Denmark"),
        (u"DW",  u"Derby-West Kimberley"),
        (u"DB",  u"Donnybrook-Balingup"),
        (u"DO",  u"Dowerin"),
        (u"DY",  u"Dumbleyung"),
        (u"DU",  u"Dundas"),
        (u"EF",  u"East Fremantle"),
        (u"EP",  u"East Pilbara"),
        (u"ES",  u"Esperance"),
        (u"EX",  u"Exmouth"),
        (u"FR",  u"Fremantle"),
        (u"GE",  u"Geraldton"),
        (u"GI",  u"Gingin"),
        (u"GN",  u"Gnowangerup"),
        (u"GM",  u"Goomalling"),
        (u"GS",  u"Gosnells"),
        (u"GR",  u"Greenough"),
        (u"HC",  u"Halls Creek"),
        (u"HA",  u"Harvey"),
        (u"IR",  u"Irwin"),
        (u"JE",  u"Jerramungup"),
        (u"JO",  u"Joondalup"),
        (u"KL",  u"Kalamunda"),
        (u"KB",  u"Kalgoorlie/Boulder"),
        (u"KT",  u"Katanning"),
        (u"KE",  u"Kellerberrin"),
        (u"KN",  u"Kent"),
        (u"KJ",  u"Kojonup"),
        (u"KO",  u"Kondinin"),
        (u"KR",  u"Koorda"),
        (u"KU",  u"Kulin"),
        (u"KW",  u"Kwinana"),
        (u"LG",  u"Lake Grace"),
        (u"LA",  u"Laverton"),
        (u"LE",  u"Leonora"),
        (u"MA",  u"Mandurah"),
        (u"MJ",  u"Manjimup"),
        (u"MT",  u"Meekatharra"),
        (u"MV",  u"Melville"),
        (u"MZ",  u"Menzies"),
        (u"ME",  u"Merredin"),
        (u"MI",  u"Mingenew"),
        (u"MR",  u"Moora"),
        (u"MO",  u"Morawa"),
        (u"MP",  u"Mosman Park"),
        (u"MG",  u"Mount Magnet"),
        (u"MM",  u"Mount Marshall"),
        (u"MB",  u"Mukinbudin"),
        (u"MW",  u"Mullewa"),
        (u"MN",  u"Mundaring"),
        (u"MU",  u"Murchison"),
        (u"MY",  u"Murray"),
        (u"NN",  u"Nannup"),
        (u"NB",  u"Narembeen"),
        (u"NS",  u"Narrogin"),
        (u"NT",  u"Narrogin"),
        (u"NE",  u"Nedlands"),
        (u"NG",  u"Ngaanyatjarraku"),
        (u"NH",  u"Northam"),
        (u"NR",  u"Northam"),
        (u"NP",  u"Northampton"),
        (u"NU",  u"Nungarin"),
        (u"PG",  u"Peppermint Grove"),
        (u"PJ",  u"Perenjori"),
        (u"PE",  u"Perth"),
        (u"PI",  u"Pingelly"),
        (u"PL",  u"Plantagenet"),
        (u"PO",  u"Port Hedland"),
        (u"QR",  u"Quairading"),
        (u"RA",  u"Ravensthorpe"),
        (u"RC",  u"Rockingham"),
        (u"RB",  u"Roebourne"),
        (u"SA",  u"Sandstone"),
        (u"SJ",  u"Serpentine-Jarrahdale"),
        (u"SB",  u"Shark Bay"),
        (u"SP",  u"South Perth"),
        (u"ST",  u"Stirling"),
        (u"SU",  u"Subiaco"),
        (u"SW",  u"Swan"),
        (u"TB",  u"Tambellup"),
        (u"TM",  u"Tammin"),
        (u"TS",  u"Three Springs"),
        (u"TO",  u"Toodyay"),
        (u"TR",  u"Trayning"),
        (u"UG",  u"Upper Gascoyne"),
        (u"VK",  u"Victoria Park"),
        (u"VP",  u"Victoria Plains"),
        (u"VI",  u"Vincent"),
        (u"WG",  u"Wagin"),
        (u"WD",  u"Wandering"),
        (u"WR",  u"Wanneroo"),
        (u"WO",  u"Waroona"),
        (u"WA",  u"West Arthur"),
        (u"WT",  u"Westonia"),
        (u"WC",  u"Wickepin"),
        (u"WS",  u"Williams"),
        (u"WL",  u"Wiluna"),
        (u"WB",  u"Wongan-Ballidu"),
        (u"WN",  u"Woodanilling"),
        (u"WY",  u"Wyalkatchem"),
        (u"WE",  u"Wyndham-East Kimberley"),
        (u"YA",  u"Yalgoo"),
        (u"YI",  u"Yilgarn"),
        (u"YO",  u"York"),
        ]),

]
