# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

BR_regions = [
    ((u"AC", u"Acre"), [
        (u"BR",  u"Brasileia"),
        (u"CS",  u"Cruzeiro do Sul"),
        (u"RB",  u"Rio Branco"),
        (u"SM",  u"Sena Madureira"),
        (u"TA",  u"Tarauacá"),
        ]),

    ((u"AL", u"Alagoas"), [
        (u"AS",  u"Alagoana do Sertão do São Francisco"),
        (u"AR",  u"Arapiraca"),
        (u"BA",  u"Batalha"),
        (u"LN",  u"Litoral Norte Alagoano"),
        (u"MC",  u"Maceió"),
        (u"MA",  u"Mata Alagoana"),
        (u"PI",  u"Palmeira dos Índios"),
        (u"PE",  u"Penedo"),
        (u"SI",  u"Santana do Ipanema"),
        (u"SS",  u"Serrana do Sertão Alagoano"),
        (u"SQ",  u"Serrana dos Quilombos"),
        (u"SM",  u"São Miguel dos Campos"),
        (u"TR",  u"Traipu"),
        ]),

    ((u"AP", u"Amapá"), [
        (u"AM",  u"Amapá"),
        (u"MC",  u"Macapá"),
        (u"MZ",  u"Mazagão"),
        (u"OI",  u"Oiapoque"),
        ]),

    ((u"AM", u"Amazonas"), [
        (u"AS",  u"Alto Solimões"),
        (u"BA",  u"Boca do Acre"),
        (u"CO",  u"Coari"),
        (u"IT",  u"Itacoatiara"),
        (u"JA",  u"Japurá"),
        (u"JU",  u"Juruá"),
        (u"MD",  u"Madeira"),
        (u"MN",  u"Manaus"),
        (u"PA",  u"Parintins"),
        (u"PU",  u"Purus"),
        (u"RN",  u"Rio Negro"),
        (u"RP",  u"Rio Preto da Eva"),
        (u"TE",  u"Tefé"),
        ]),

    ((u"BA", u"Bahia"), [
        (u"AL",  u"Alagoinhas"),
        (u"BA",  u"Barra"),
        (u"BR",  u"Barreiras"),
        (u"BJ",  u"Bom Jesus da Lapa"),
        (u"BO",  u"Boquira"),
        (u"BD",  u"Brumado"),
        (u"CA",  u"Catu"),
        (u"CO",  u"Cotegipe"),
        (u"ER",  u"Entre Rios"),
        (u"EC",  u"Euclides da Cunha"),
        (u"FS",  u"Feira de Santana"),
        (u"GU",  u"Guanambi"),
        (u"II",  u"Ilhéus-Itabuna"),
        (u"IR",  u"Irecê"),
        (u"IB",  u"Itaberaba"),
        (u"IT",  u"Itapetinga"),
        (u"JA",  u"Jacobina"),
        (u"JQ",  u"Jequié"),
        (u"JM",  u"Jeremoabo"),
        (u"JU",  u"Juazeiro"),
        (u"LB",  u"Livramento do Brumado"),
        (u"PA",  u"Paulo Afonso"),
        (u"PS",  u"Porto Seguro"),
        (u"RP",  u"Ribeira do Pombal"),
        (u"SV",  u"Salvador"),
        (u"SM",  u"Santa Maria da Vitória"),
        (u"SJ",  u"Santo Antônio de Jesus"),
        (u"SE",  u"Seabra"),
        (u"SB",  u"Senhor do Bonfim"),
        (u"SR",  u"Serrinha"),
        (u"VA",  u"Valença"),
        (u"VC",  u"Vitória da Conquista"),
        ]),

    ((u"CE", u"Ceará"), [
        (u"BC",  u"Baixo Curu"),
        (u"BJ",  u"Baixo Jaguaribe"),
        (u"BR",  u"Barro"),
        (u"BT",  u"Baturité"),
        (u"BS",  u"Brejo Santo"),
        (u"CN",  u"Canindé"),
        (u"CI",  u"Cariri"),
        (u"CR",  u"Caririacu"),
        (u"CV",  u"Cascavel"),
        (u"CA",  u"Chapada do Araripe"),
        (u"CH",  u"Chorozinho"),
        (u"CO",  u"Coreaú"),
        (u"FO",  u"Fortaleza"),
        (u"IB",  u"Ibiapaba"),
        (u"IG",  u"Iguatu"),
        (u"IP",  u"Ipu"),
        (u"IT",  u"Itapipoca"),
        (u"LM",  u"Lavras da Mangabeira"),
        (u"LA",  u"Litoral de Aracati"),
        (u"LC",  u"Litoral de Camocim e Acaraú"),
        (u"MC",  u"Medio Curu"),
        (u"MJ",  u"Medio Jaguaribe"),
        (u"ME",  u"Meruoca"),
        (u"PA",  u"Pacajus"),
        (u"SQ",  u"Santa Quiteria"),
        (u"SP",  u"Serra do Pereiro"),
        (u"SC",  u"Sertão de Crateus"),
        (u"SI",  u"Sertão de Inhamuns"),
        (u"SX",  u"Sertão de Quixeramobim"),
        (u"SS",  u"Sertão de Senador Pompeu"),
        (u"SO",  u"Sobral"),
        (u"UR",  u"Uruburetama"),
        (u"VA",  u"Várzea Alegre"),
        ]),

    ((u"DF", u"Distrito Federal"), [
        (u"DF",  u"Distrito Federal"),
        ]),

    ((u"ES", u"Espírito Santo"), [
        (u"AC",  u"Afonso Claudio"),
        (u"AL",  u"Alegre"),
        (u"BS",  u"Barra de São Francisco"),
        (u"CI",  u"Cachoeiro de Itapemirim"),
        (u"CO",  u"Colatina"),
        (u"GU",  u"Guarapari"),
        (u"IT",  u"Itapemirim"),
        (u"LI",  u"Linhares"),
        (u"MO",  u"Montanha"),
        (u"NV",  u"Nova Venecia"),
        (u"ST",  u"Santa Teresa"),
        (u"SM",  u"São Mateus"),
        (u"VI",  u"Vitória"),
        ]),

    ((u"GO", u"Goiás"), [
        (u"AN",  u"Anicuns"),
        (u"AP",  u"Anápolis"),
        (u"AR",  u"Aragarcas"),
        (u"CA",  u"Catalão"),
        (u"CE",  u"Ceres"),
        (u"CV",  u"Chapada dos Veadeiros"),
        (u"EB",  u"Entorno de Brasília"),
        (u"GO",  u"Goiânia"),
        (u"IP",  u"Iporá"),
        (u"MP",  u"Meia Ponte"),
        (u"PR",  u"Pires do Rio"),
        (u"PO",  u"Porangatu"),
        (u"QU",  u"Quirinópolis"),
        (u"RV",  u"Rio Vermelho"),
        (u"SG",  u"Sudoeste de Goiás"),
        (u"SM",  u"São Miguel do Araguaia"),
        (u"VR",  u"Vale do Rio dos Bois"),
        (u"VP",  u"Vão do Paraná"),
        ]),

    ((u"MA", u"Maranhão"), [
        (u"AM",  u"Alto Mearim e Grajaú"),
        (u"BM",  u"Baixada Maranhense"),
        (u"BP",  u"Baixo Parnaiba Maranhense"),
        (u"CX",  u"Caxias"),
        (u"CM",  u"Chapadas das Mangabeiras"),
        (u"CA",  u"Chapadas do Alto Itapecuru"),
        (u"CH",  u"Chapadinha"),
        (u"CO",  u"Codó"),
        (u"CN",  u"Coelho Neto"),
        (u"GB",  u"Gerais de Balsas"),
        (u"GU",  u"Gurupi"),
        (u"IZ",  u"Imperatriz"),
        (u"IM",  u"Itapecuru Mirim"),
        (u"LM",  u"Lençóis Maranhenses"),
        (u"LO",  u"Litoral Ocidental Maranhense"),
        (u"MM",  u"Medio Mearim"),
        (u"PI",  u"Pindaré"),
        (u"PF",  u"Porto Franco"),
        (u"PD",  u"Presidente Dutra"),
        (u"RO",  u"Rosario"),
        (u"SL",  u"São Luís"),
        ]),

    ((u"MT", u"Mato Grosso"), [
        (u"AF",  u"Alta Floresta"),
        (u"AA",  u"Alto Araguaia"),
        (u"AG",  u"Alto Guaporé"),
        (u"AN",  u"Alto Pantanal"),
        (u"AP",  u"Alto Paraguai"),
        (u"AT",  u"Alto Teles Pires"),
        (u"AS",  u"Arinos"),
        (u"AR",  u"Aripuana"),
        (u"CA",  u"Canarana"),
        (u"CO",  u"Colider"),
        (u"CU",  u"Cuiabá"),
        (u"JA",  u"Jauru"),
        (u"MA",  u"Medio Araguaia"),
        (u"NA",  u"Norte Araguaia"),
        (u"PT",  u"Paranatinga"),
        (u"PC",  u"Parecis"),
        (u"PL",  u"Primavera do Leste"),
        (u"RP",  u"Rondonópolis"),
        (u"RO",  u"Rosario Oeste"),
        (u"SI",  u"Sinop"),
        (u"TS",  u"Tangará da Serra"),
        (u"TE",  u"Tesouro"),
        ]),

    ((u"MS", u"Mato Grosso do Sul"), [
        (u"AT",  u"Alto Taquari"),
        (u"AQ",  u"Aquidauana"),
        (u"BP",  u"Baixo Pantanal"),
        (u"BO",  u"Bodoquena"),
        (u"CG",  u"Campo Grande"),
        (u"CA",  u"Cassilandia"),
        (u"DO",  u"Dourados"),
        (u"IG",  u"Iguatemi"),
        (u"NA",  u"Nova Andradina"),
        (u"PA",  u"Paranaiba"),
        (u"TL",  u"Três Lagoas"),
        ]),

    ((u"MG", u"Minas Gerais"), [
        (u"AI",  u"Aimores"),
        (u"AF",  u"Alfenas"),
        (u"AM",  u"Almenara"),
        (u"AN",  u"Andrelandia"),
        (u"AC",  u"Aracuaí"),
        (u"AX",  u"Araxá"),
        (u"BA",  u"Barbacena"),
        (u"BH",  u"Belo Horizonte"),
        (u"BO",  u"Bocaiuva"),
        (u"BD",  u"Bom Despacho"),
        (u"CB",  u"Campo Belo"),
        (u"CP",  u"Capelinha"),
        (u"CT",  u"Caratinga"),
        (u"CG",  u"Cataguases"),
        (u"CM",  u"Conceição do Mato Dentro"),
        (u"CL",  u"Conselheiro Lafaiete"),
        (u"CU",  u"Curvelo"),
        (u"DM",  u"Diamantina"),
        (u"DV",  u"Divinópolis"),
        (u"FO",  u"Formiga"),
        (u"FR",  u"Frutal"),
        (u"GV",  u"Governador Valadares"),
        (u"GM",  u"Grão Mogol"),
        (u"GU",  u"Guanhaes"),
        (u"IP",  u"Ipatinga"),
        (u"IB",  u"Itabira"),
        (u"IG",  u"Itaguara"),
        (u"IJ",  u"Itajubá"),
        (u"IT",  u"Ituiutaba"),
        (u"JB",  u"Janaúba"),
        (u"JR",  u"Januária"),
        (u"JF",  u"Juiz de Fora"),
        (u"LA",  u"Lavras"),
        (u"MH",  u"Manhuaçu"),
        (u"MT",  u"Mantena"),
        (u"MC",  u"Montes Claros"),
        (u"MU",  u"Muriaé"),
        (u"NA",  u"Nanuque"),
        (u"OL",  u"Oliveira"),
        (u"OP",  u"Ouro Preto"),
        (u"PU",  u"Paracatu"),
        (u"PM",  u"Pará de Minas"),
        (u"PS",  u"Passos"),
        (u"PT",  u"Patos de Minas"),
        (u"PO",  u"Patrocínio"),
        (u"PE",  u"Pecanha"),
        (u"PZ",  u"Pedra Azul"),
        (u"PP",  u"Pirapora"),
        (u"PI",  u"Piuí"),
        (u"PN",  u"Ponte Nova"),
        (u"PA",  u"Pouso Alegre"),
        (u"PC",  u"Poços de Caldas"),
        (u"SA",  u"Salinas"),
        (u"SR",  u"Santa Rita do Sapucaí"),
        (u"ST",  u"Sete Lagoas"),
        (u"SJ",  u"São João del Rei"),
        (u"SL",  u"São Lourenço"),
        (u"SS",  u"São Sebastião do Paraíso"),
        (u"TO",  u"Teófilo Otoni"),
        (u"TM",  u"Três Marias"),
        (u"UR",  u"Uberaba"),
        (u"UL",  u"Uberlândia"),
        (u"UB",  u"Ubá"),
        (u"UN",  u"Unaí"),
        (u"VA",  u"Varginha"),
        (u"VI",  u"Viçosa"),
        ]),

    ((u"PR", u"Paraná"), [
        (u"AP",  u"Apucarana"),
        (u"AS",  u"Assaí"),
        (u"AG",  u"Astorga"),
        (u"CM",  u"Campo Mourão"),
        (u"CN",  u"Capanema"),
        (u"CV",  u"Cascavel"),
        (u"CA",  u"Cerro Azul"),
        (u"CI",  u"Cianorte"),
        (u"CP",  u"Cornelio Procopio"),
        (u"CU",  u"Curitiba"),
        (u"FA",  u"Faxinal"),
        (u"FL",  u"Floraí"),
        (u"FI",  u"Foz do Iguaçu"),
        (u"FB",  u"Francisco Beltrão"),
        (u"GO",  u"Goioere"),
        (u"GU",  u"Guarapuava"),
        (u"IB",  u"Ibaiti"),
        (u"IR",  u"Irati"),
        (u"IV",  u"Ivaipora"),
        (u"JZ",  u"Jacarezinho"),
        (u"JG",  u"Jaguariaiva"),
        (u"LA",  u"Lapa"),
        (u"LO",  u"Londrina"),
        (u"MA",  u"Maringá"),
        (u"PM",  u"Palmas"),
        (u"PA",  u"Paranaguá"),
        (u"PV",  u"Paranavaí"),
        (u"PB",  u"Pato Branco"),
        (u"PI",  u"Pitanga"),
        (u"PG",  u"Ponta Grossa"),
        (u"PO",  u"Porecatu"),
        (u"PR",  u"Prudentópolis"),
        (u"RN",  u"Rio Negro"),
        (u"SM",  u"São Mateus do Sul"),
        (u"TB",  u"Telêmaco Borba"),
        (u"TO",  u"Toledo"),
        (u"UM",  u"Umuarama"),
        (u"UV",  u"União da Vitória"),
        (u"WB",  u"Wenceslau Braz"),
        ]),

    ((u"PB", u"Paraíba"), [
        (u"BP",  u"Brejo Paraibano"),
        (u"CA",  u"Cajazeiras"),
        (u"CG",  u"Campina Grande"),
        (u"CC",  u"Cariri Ocidental"),
        (u"CI",  u"Cariri Oriental"),
        (u"CR",  u"Catolé do Rocha"),
        (u"CM",  u"Curimataú Ocidental"),
        (u"CT",  u"Curimataú Oriental"),
        (u"ES",  u"Esperanca"),
        (u"GU",  u"Guarabira"),
        (u"IB",  u"Itabaiana"),
        (u"IP",  u"Itaporanga"),
        (u"JP",  u"João Pessoa"),
        (u"LN",  u"Litoral Norte"),
        (u"LS",  u"Litoral Sul"),
        (u"PA",  u"Patos"),
        (u"PI",  u"Piancó"),
        (u"SA",  u"Sapé"),
        (u"SC",  u"Seridó Ocidental Paraibano"),
        (u"SR",  u"Seridó Oriental Paraibano"),
        (u"ST",  u"Serra do Teixeira"),
        (u"SS",  u"Sousa"),
        (u"UM",  u"Umbuzeiro"),
        ]),

    ((u"PA", u"Pará"), [
        (u"AM",  u"Almeirim"),
        (u"AT",  u"Altamira"),
        (u"AR",  u"Arari"),
        (u"BE",  u"Belém"),
        (u"BR",  u"Bragantina"),
        (u"CM",  u"Cametá"),
        (u"CS",  u"Castanhal"),
        (u"CA",  u"Conceição do Araguaia"),
        (u"FB",  u"Furos de Breves"),
        (u"GU",  u"Guamá"),
        (u"IT",  u"Itaituba"),
        (u"MA",  u"Marabá"),
        (u"OB",  u"Obidos"),
        (u"PG",  u"Paragominas"),
        (u"PP",  u"Parauapebas"),
        (u"PO",  u"Portel"),
        (u"RE",  u"Redenção"),
        (u"SG",  u"Salgado"),
        (u"ST",  u"Santarém"),
        (u"SF",  u"São Felix do Xingu"),
        (u"TA",  u"Tomé Acu"),
        (u"TU",  u"Tucuruí"),
        ]),

    ((u"PE", u"Pernambuco"), [
        (u"AC",  u"Alto Capibaribe"),
        (u"AR",  u"Araripina"),
        (u"BP",  u"Brejo Pernambucano"),
        (u"FN",  u"Fernando de Noronha"),
        (u"GA",  u"Garanhuns"),
        (u"IM",  u"Itamaracá"),
        (u"IP",  u"Itaparica"),
        (u"MM",  u"Mata Meridional Pernambucana"),
        (u"MS",  u"Mata Setentrional Pernambucana"),
        (u"MC",  u"Medio Capibaribe"),
        (u"PA",  u"Pajeú"),
        (u"PE",  u"Petrolina"),
        (u"RE",  u"Recife"),
        (u"SA",  u"Salgueiro"),
        (u"SM",  u"Sertão do Moxotó"),
        (u"SU",  u"Suape"),
        (u"VM",  u"Vale do Ipanema"),
        (u"VJ",  u"Vale do Ipojuca"),
        (u"VS",  u"Vitória de Santo Antão"),
        ]),

    ((u"PI", u"Piauí"), [
        (u"AC",  u"Alto Medio Canindé"),
        (u"AG",  u"Alto Medio Gurgueia"),
        (u"AP",  u"Alto Parnaiba Piauiense"),
        (u"BP",  u"Baixo Parnaiba Piauiense"),
        (u"BE",  u"Bertolinia"),
        (u"CM",  u"Campo Maior"),
        (u"CE",  u"Chapadas do Extremo Sul Piauiense"),
        (u"FL",  u"Floriano"),
        (u"LP",  u"Litoral Piauiense"),
        (u"MP",  u"Medio Parnaiba Piauiense"),
        (u"PC",  u"Picos"),
        (u"PI",  u"Pio IX"),
        (u"SR",  u"São Raimundo Nonato"),
        (u"TE",  u"Teresina"),
        (u"VP",  u"Valença do Piauí"),
        ]),

    ((u"RN", u"Rio Grande do Norte"), [
        (u"AP",  u"Agreste Potiguar"),
        (u"AN",  u"Angicos"),
        (u"BV",  u"Baixa Verde"),
        (u"BP",  u"Borborema Potiguar"),
        (u"CA",  u"Chapada do Apodi"),
        (u"LN",  u"Litoral Nordeste"),
        (u"LS",  u"Litoral Sul"),
        (u"MU",  u"Macau"),
        (u"MB",  u"Macaíba"),
        (u"MO",  u"Medio Oeste"),
        (u"MS",  u"Mossoró"),
        (u"NA",  u"Natal"),
        (u"PF",  u"Pau dos Ferros"),
        (u"SC",  u"Seridó Ocidental"),
        (u"SR",  u"Seridó Oriental"),
        (u"SS",  u"Serra de Santana"),
        (u"SM",  u"Serra de São Miguel"),
        (u"UM",  u"Umarizal"),
        (u"VA",  u"Vale do Açu"),
        ]),

    ((u"RS", u"Rio Grande do Sul"), [
        (u"CS",  u"Cachoeira do Sul"),
        (u"CQ",  u"Camaquã"),
        (u"CC",  u"Campanha Central"),
        (u"CM",  u"Campanha Meridional"),
        (u"CO",  u"Campanha Ocidental"),
        (u"CZ",  u"Carazinho"),
        (u"CX",  u"Caxias do Sul"),
        (u"CL",  u"Cerro Largo"),
        (u"CA",  u"Cruz Alta"),
        (u"ER",  u"Erechim"),
        (u"FW",  u"Frederico Westphalen"),
        (u"GC",  u"Gramado-Canela"),
        (u"GU",  u"Guaporé"),
        (u"IJ",  u"Ijuí"),
        (u"JA",  u"Jaguarão"),
        (u"LP",  u"Lagoas dos Patos"),
        (u"LE",  u"Lajeado-Estrela"),
        (u"LL",  u"Litoral Lagunar"),
        (u"MI",  u"Mirim"),
        (u"MO",  u"Montenegro"),
        (u"NM",  u"Não-Me-Toque"),
        (u"OS",  u"Osorio"),
        (u"PF",  u"Passo Fundo"),
        (u"PE",  u"Pelotas"),
        (u"PA",  u"Porto Alegre"),
        (u"RS",  u"Restinga Seca"),
        (u"SV",  u"Sananduva"),
        (u"SC",  u"Santa Cruz do Sul"),
        (u"SM",  u"Santa Maria"),
        (u"SR",  u"Santa Rosa"),
        (u"SG",  u"Santiago"),
        (u"SA",  u"Santo Angelo"),
        (u"SS",  u"Serras de Sudeste"),
        (u"SO",  u"Soledade"),
        (u"SJ",  u"São Jeronimo"),
        (u"TP",  u"Três Passos"),
        (u"VA",  u"Vacaria"),
        ]),



    ((u"RJ", u"Rio de Janeiro (Cuidad)"), [
        (u"01",    u"Anchieta"),
        (u"02",    u"Bangu"),
        (u"03",    u"Barra da Tijuca"),
        (u"04",    u"Botafogo"),
        (u"05",    u"Campo Grande"),
        (u"06",    u"Centro"),
        (u"07",    u"Cidade de Deus"),
        (u"08",    u"Complexo do Alemão"),
        (u"09",    u"Copacabana"),
        (u"10",    u"Guaratiba"),
        (u"11",    u"Ilha de Paquetá"),
        (u"12",    u"Ilha do Governador"),
        (u"13",    u"Inhaúma"),
        (u"14",    u"Irajá"),
        (u"15",    u"Jacarepaguá"),
        (u"16",    u"Jacarezinho"),
        (u"17",    u"Lagoa"),
        (u"18",    u"Madureira"),
        (u"19",    u"Maré"),
        (u"20",    u"Méier"),
        (u"21",    u"Pavuna"),
        (u"22",    u"Penha"),
        (u"23",    u"Ramos"),
        (u"24",    u"Realengo"),
        (u"25",    u"Rio Comprido"),
        (u"26",    u"Rocinha"),
        (u"27",    u"Santa Cruz"),
        (u"28",    u"Santa Teresa"),
        (u"29",    u"São Cristovão"),
        (u"30",    u"Tijuca"),
        (u"31",    u"Vigário Geral"),
        (u"32",    u"Vila Isabel"),
        (u"33",    u"Zona Portuária"),

    ]),

    ((u"RJE", u"Rio de Janeiro (Estado)"), [
        (u"BI",  u"Bacia da Ilha Grande"),
        (u"BS",  u"Bacia de São João"),
        (u"BP",  u"Barra do Piraí"),
        (u"CG",  u"Campos dos Goytacazes"),
        (u"CC",  u"Cantagalo-Cordeiro"),
        (u"IG",  u"Itaguaí"),
        (u"IP",  u"Itaperuna"),
        (u"LA",  u"Lagos"),
        (u"MC",  u"Macacu-Caceribu"),
        (u"MA",  u"Macaé"),
        (u"NF",  u"Nova Friburgo"),
        (u"SM",  u"Santa Maria Madalena"),
        (u"SA",  u"Santo Antônio de Padua"),
        (u"SE",  u"Serrana"),
        (u"TR",  u"Três Rios"),
        (u"VP",  u"Vale do Paraiba Fluminense"),
        (u"VA",  u"Vassouras"),
        ]),

    ((u"RO", u"Rondônia"), [
        (u"AO",  u"Alvorada d'Oeste"),
        (u"AR",  u"Ariquemes"),
        (u"CA",  u"Cacoal"),
        (u"CO",  u"Colorado d'Oeste"),
        (u"GM",  u"Guajará-Mirim"),
        (u"JP",  u"Ji-Paraná"),
        (u"PV",  u"Porto Velho"),
        (u"VI",  u"Vilhena"),
        ]),

    ((u"RR", u"Roraima"), [
        (u"BV",  u"Boa Vista"),
        (u"CA",  u"Caracaraí"),
        (u"NR",  u"Nordeste de Roraima"),
        (u"SR",  u"Sudeste de Roraima"),
        ]),

    ((u"SC", u"Santa Catarina"), [
        (u"AR",  u"Araranguá"),
        (u"BL",  u"Blumenau"),
        (u"CL",  u"Campos de Lages"),
        (u"CA",  u"Canoinhas"),
        (u"CH",  u"Chapecó"),
        (u"CO",  u"Concórdia"),
        (u"CR",  u"Criciúma"),
        (u"CU",  u"Curitibanos"),
        (u"FL",  u"Florianópolis"),
        (u"IJ",  u"Itajaí"),
        (u"IP",  u"Ituporanga"),
        (u"JC",  u"Joacaba"),
        (u"JV",  u"Joinville"),
        (u"RS",  u"Rio do Sul"),
        (u"SB",  u"São Bento do Sul"),
        (u"SM",  u"São Miguel d'Oeste"),
        (u"TA",  u"Tabuleiro"),
        (u"TI",  u"Tijucas"),
        (u"TU",  u"Tubarão"),
        (u"XA",  u"Xanxere"),
        ]),

    ((u"SE", u"Sergipe"), [
        (u"AI",  u"Agreste de Itabaiana"),
        (u"AR",  u"Aracaju"),
        (u"BC",  u"Baixo Cotinguiba"),
        (u"BO",  u"Boquim"),
        (u"CA",  u"Carira"),
        (u"CO",  u"Cotinguiba"),
        (u"ES",  u"Estância"),
        (u"JA",  u"Japaratuba"),
        (u"NS",  u"Nossa Senhora das Dores"),
        (u"PR",  u"Propriá"),
        (u"SS",  u"Sergipana do Sertão do São Francisco"),
        (u"TB",  u"Tobias Barreto"),
        ]),


    ((u"SP", u"São Paulo (Cuidad)"), [
        (u"01",    u"Aricanduva"),
        (u"02",    u"Butantã"),
        (u"03",    u"Campo Limpo"),
        (u"04",    u"Capela do Socorro"),
        (u"05",    u"Casa Verde"),
        (u"06",    u"Cidade Ademar"),
        (u"07",    u"Cidade Tiradentes"),
        (u"08",    u"Ermelino Matarazzo"),
        (u"09",    u"Freguesia do Ó"),
        (u"10",    u"Guaianases"),
        (u"11",    u"Ipiranga"),
        (u"12",    u"Itaim Paulista"),
        (u"13",    u"Itaquera"),
        (u"14",    u"Jabaquara"),
        (u"15",    u"Lapa"),
        (u"16",    u"M'Boi Mirim"),
        (u"17",    u"Mooca"),
        (u"18",    u"Parelheiros"),
        (u"19",    u"Penha"),
        (u"20",    u"Perus"),
        (u"21",    u"Pinheiros"),
        (u"22",    u"Pirituba"),
        (u"23",    u"Santana"),
        (u"24",    u"Santo Amaro"),
        (u"25",    u"São Mateus"),
        (u"26",    u"São Miguel Paulista"),
        (u"27",    u"Sé"),
        (u"28",    u"Tremembé"),
        (u"29",    u"Vila Maria"),
        (u"30",    u"Vila Mariana"),
        (u"31",    u"Vila Prudente"),
        ]),



    ((u"SPE", u"São Paulo (Estado)"), [
        (u"AD",  u"Adamantina"),
        (u"AM",  u"Amparo"),
        (u"AN",  u"Andradina"),
        (u"AQ",  u"Araraquara"),
        (u"AC",  u"Araçatuba"),
        (u"AS",  u"Assis"),
        (u"AU",  u"Auriflama"),
        (u"AV",  u"Avaré"),
        (u"BN",  u"Bananal"),
        (u"BT",  u"Barretos"),
        (u"BU",  u"Bauru"),
        (u"BI",  u"Birigui"),
        (u"BO",  u"Botucatu"),
        (u"BP",  u"Bragança Paulista"),
        (u"CA",  u"Campinas"),
        (u"CJ",  u"Campos do Jordão"),
        (u"CB",  u"Capão Bonito"),
        (u"CG",  u"Caraguatatuba"),
        (u"CV",  u"Catanduva"),
        (u"DR",  u"Dracena"),
        (u"FE",  u"Fernandópolis"),
        (u"FC",  u"Franca"),
        (u"FR",  u"Franco da Rocha"),
        (u"GT",  u"Guaratinguetá"),
        (u"GL",  u"Guarulhos"),
        (u"IH",  u"Itanhaém"),
        (u"IS",  u"Itapecerica da Serra"),
        (u"IT",  u"Itapetininga"),
        (u"IP",  u"Itapeva"),
        (u"IV",  u"Ituverava"),
        (u"JB",  u"Jaboticabal"),
        (u"JL",  u"Jales"),
        (u"JA",  u"Jaú"),
        (u"JD",  u"Jundiaí"),
        (u"LM",  u"Limeira"),
        (u"LN",  u"Lins"),
        (u"MA",  u"Marília"),
        (u"MM",  u"Mogi Mirim"),
        (u"MC",  u"Mogi das Cruzes"),
        (u"ND",  u"Nhandeara"),
        (u"NH",  u"Novo Horizonte"),
        (u"OS",  u"Osasco"),
        (u"OU",  u"Ourinhos"),
        (u"PB",  u"Paraibuna-Paraitinga"),
        (u"PD",  u"Piedade"),
        (u"PC",  u"Piracicaba"),
        (u"PS",  u"Pirassununga"),
        (u"PP",  u"Presidente Prudente"),
        (u"RE",  u"Registro"),
        (u"RP",  u"Ribeirão Preto"),
        (u"RC",  u"Rio Claro"),
        (u"SA",  u"Santos"),
        (u"SO",  u"Sorocaba"),
        (u"SC",  u"São Carlos"),
        (u"SB",  u"São Joaquim da Barra"),
        (u"SR",  u"São José do Rio Preto"),
        (u"SJ",  u"São José dos Campos"),
        (u"SV",  u"São João da Boa Vista"),
        (u"TA",  u"Tatuí"),
        (u"TU",  u"Tupã"),
        (u"VO",  u"Votuporanga"),
        ]),

    ((u"TO", u"Tocantins"), [
        (u"AR",  u"Araguaína"),
        (u"BP",  u"Bico do Papagaio"),
        (u"DI",  u"Dianópolis"),
        (u"GU",  u"Gurupi"),
        (u"JA",  u"Jalapão"),
        (u"MT",  u"Miracema do Tocantins"),
        (u"PN",  u"Porto Nacional"),
        (u"RF",  u"Rio Formoso"),
        ]),

]
