# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

CA_regions = [
    ((u'AB',   u' Alberta'),[
        (u"AI", u"Airdrie"),
        (u"BA", u"Banff"),
        (u"BR", u"Brooks"),
        (u"CA", u"Calgary"), 
        (u"CR", u"Camrose"),	
        (u"CO", u"Cold Lake"),
        (u"ED", u"Edmonton"),
        (u"FO", u"Fort Saskatchewan"),
        (u"GR", u"Grande Prairie"),
        (u"LA", u"Lacombe"),
        (u"LE", u"Leduc"),
        (u"LT", u"Lethbridge"),
        (u"LL", u"Lloydminster"),
        (u"ME", u"Medicine Hat"),
        (u"RE", u"Red Deer"),
        (u"SP", u"Spruce Grove"),
        (u"ST", u"St. Albert"),
        (u"WE", u"Wetaskiwin"),
        ]),
    
    ((u"BC", u"British Columbia"), [
        (u"AC",  u"Alberni-Clayoquot"),
        (u"BN",  u"Bulkley-Nechako"),
        (u"CP",  u"Capital"),
        (u"CR",  u"Cariboo"),
        (u"CC",  u"Central Coast"),
        (u"CK",  u"Central Kootenay"),
        (u"CO",  u"Central Okanagan"),
        (u"CS",  u"Columbia-Shuswap"),
        (u"CX",  u"Comox-Strathcona"),
        (u"CV",  u"Cowichan Valley"),
        (u"EK",  u"East Kootenay"),
        (u"FL",  u"Fort Nelson-Liard"),
        (u"FV",  u"Fraser Valley"),
        (u"FF",  u"Fraser-Fort George"),
        (u"KS",  u"Kitimat-Stikine"),
        (u"KB",  u"Kootenay Boundary"),
        (u"MW",  u"Mount Waddington"),
        (u"NA",  u"Nanaimo"),
        (u"NO",  u"North Okanagan"),
        (u"OS",  u"Okanagan-Similkameen"),
        (u"PC",  u"Peace River"),
        (u"PW",  u"Powell River"),
        (u"SQ",  u"Skeena-Queen Charlotte"),
        (u"SL",  u"Squamish-Lillooet"),
        (u"ST",  u"Stikine"),
        (u"SC",  u"Sunshine Coast"),
        (u"TN",  u"Thompson-Nicola"),
        (u"GV",  u"Vancouver (Greater Vancouver)"), 
        ]),
    
    ((u'MB',   u' Manitoba'),[
        (u"BR", u"Brandon"), 
        (u"DA", u"Dauphin"),
        (u"FL", u"Flin Flon"),
        (u"MO", u"Morden"),
        (u"PO", u"Portage la Prairie"),
        (u"SE", u"Selkirk"),
        (u"ST", u"Steinbach"),
        (u"TH", u"The Pas"),
        (u"TO", u"Thompson"),
        (u"WI", u"Winkler"),
        (u"WI", u"Winnipeg"),
        ]),

    ((u"NB", u"New Brunswick"), [
        (u"AL",  u"Albert"),
        (u"CA",  u"Carleton"),
        (u"CH",  u"Charlotte"),
        (u"GL",  u"Gloucester"),
        (u"KE",  u"Kent"),
        (u"KI",  u"Kings"),
        (u"MA",  u"Madawaska"),
        (u"NO",  u"Northumberland"),
        (u"QU",  u"Queens"),
        (u"RE",  u"Restigouche"),
        (u"SJ",  u"Saint John"),
        (u"SU",  u"Sunbury"),
        (u"VI",  u"Victoria"),
        (u"WE",  u"Westmorland"),
        (u"YO",  u"York"),
        ]),

    ((u'NL',   u' Newfoundland and Labrador'),[]),

    
    ((u"NT", u"Northwest Territories"), [
        (u"FS",  u"Fort Smith"),
        (u"IN",  u"Inuvik"),
        ]),

    ((u"NS", u"Nova Scotia"), [
        (u"AP",  u"Annapolis"),
        (u"AG",  u"Antigonish"),
        (u"CB",  u"Cape Breton"),
        (u"CO",  u"Colchester"),
        (u"CU",  u"Cumberland"),
        (u"DI",  u"Digby"),
        (u"GU",  u"Guysborough"),
        (u"HL",  u"Halifax"),
        (u"HN",  u"Hants"),
        (u"IN",  u"Inverness"),
        (u"KI",  u"Kings"),
        (u"LU",  u"Lunenburg"),
        (u"PI",  u"Pictou"),
        (u"QU",  u"Queens"),
        (u"RI",  u"Richmond"),
        (u"SH",  u"Shelburne"),
        (u"VI",  u"Victoria"),
        (u"YA",  u"Yarmouth"),
        ]),

    ((u"NU", u"Nunavut"), [
        (u"QK",  u"Baffin	Qikiqtaaluk"),
        (u"KV",  u"Keewatin	Kivalliq"),
        (u"KT",  u"Kitikmeot	Kitikmeot"),
        ]),

    ((u"ON", u"Ontario"), [
        (u"AL",  u"Algoma"),
        (u"BN",  u"Brant"),
        (u"BC",  u"Bruce"),
        (u"CO",  u"Cochrane"),
        (u"DF",  u"Dufferin"),
        (u"DR",  u"Durham"),
        (u"EL",  u"Elgin"),
        (u"ES",  u"Essex"),
        (u"FR",  u"Frontenac"),
        (u"GR",  u"Grey"),
        (u"HD",  u"Haldimand"),
        (u"HB",  u"Haliburton"),
        (u"HT",  u"Halton"),
        (u"HW",  u"Hamilton-Wentworth"),
        (u"HS",  u"Hastings"),
        (u"HU",  u"Huron"),
        (u"KR",  u"Kenora"),
        (u"KT",  u"Kent"),
        (u"LM",  u"Lambton"),
        (u"LN",  u"Lanark"),
        (u"LG",  u"Leeds and Grenville"),
        (u"LA",  u"Lennox and Addington"),
        (u"MA",  u"Manitoulin"),
        (u"MI",  u"Middlesex"),
        (u"MU",  u"Muskoka"),
        (u"NG",  u"Niagara"),
        (u"NP",  u"Nipissing"),
        (u"NF",  u"Norfolk"),
        (u"NU",  u"Northumberland"),
        (u"OC",  u"Ottawa-Carleton"),
        (u"OX",  u"Oxford"),
        (u"PS",  u"Parry Sound"),
        (u"PL",  u"Peel"),
        (u"PT",  u"Perth"),
        (u"PB",  u"Peterborough"),
        (u"PR",  u"Prescott and Russell"),
        (u"PE",  u"Prince Edward"),
        (u"RR",  u"Rainy River"),
        (u"RE",  u"Renfrew"),
        (u"SC",  u"Simcoe"),
        (u"SD",  u"Stormont, Dundas and Glengarry"),
        (u"SU",  u"Sudbury"),
        (u"SB",  u"Sudbury"),
        (u"TB",  u"Thunder Bay"),
        (u"TI",  u"Timiskaming"),
        (u"TO",  u"Toronto"),
        (u"VI",  u"Victoria"),
        (u"WT",  u"Waterloo"),
        (u"WL",  u"Wellington"),
        (u"YO",  u"York"),
        ]),

    ((u"PE", u"Prince Edward Island"), [
        (u"KI",  u"Kings"),
        (u"PR",  u"Prince"),
        (u"QU",  u"Queens"),
        ]),

    ((u"QC", u"Quebec"), [
        (u"AB",  u"Abitibi"),
        (u"AO",  u"Abitibi-Ouest"),
        (u"AC",  u"Acton"),
        (u"AL",  u"Antoine-Labelle"),
        (u"AG",  u"Argenteuil"),
        (u"AT",  u"Arthabaska"),
        (u"AS",  u"Asbestos"),
        (u"AV",  u"Avignon"),
        (u"BS",  u"Beauce-Sartigan"),
        (u"BH",  u"Beauharnois-Salaberry"),
        (u"BL",  u"Bellechasse"),
        (u"BO",  u"Bonaventure"),
        (u"BM",  u"Brome-Missisquoi"),
        (u"BC",  u"Bécancour"),
        (u"CP",  u"Champlain"),
        (u"CV",  u"Charlevoix"),
        (u"CE",  u"Charlevoix-Est"),
        (u"CT",  u"Coaticook"),
        (u"DA",  u"D'Autray"),
        (u"DR",  u"Denis-Riverin"),
        (u"DE",  u"Desjardins"),
        (u"DM",  u"Deux-Montagnes"),
        (u"DU",  u"Drummond"),
        (u"FR",  u"Francheville"),
        (u"JO",  u"Joliette"),
        (u"KA",  u"Kamouraska"),
        (u"AM",  u"L'Amiante"),
        (u"AN",  u"L'Assomption"),
        (u"IS",  u"L'Islet"),
        (u"ER",  u"L'Érable"),
        (u"IO",  u"L'Île-d'Orléans"),
        (u"CB",  u"La Côte-de-Beaupré"),
        (u"CG",  u"La Côte-de-Gaspé"),
        (u"HC",  u"La Haute-Côte-Nord"),
        (u"HY",  u"La Haute-Yamaska"),
        (u"JC",  u"La Jacques-Cartier"),
        (u"MP",  u"La Matapédia"),
        (u"MI",  u"La Mitis"),
        (u"NB",  u"La Nouvelle-Beauce"),
        (u"RD",  u"La Rivière-du-Nord"),
        (u"VG",  u"La Vallée-de-la-Gatineau"),
        (u"VR",  u"La Vallée-du-Richelieu"),
        (u"LS",  u"Lac-Saint-Jean-Est"),
        (u"LJ",  u"Lajemmerais"),
        (u"LV",  u"Laval"),
        (u"BR",  u"Le Bas-Richelieu"),
        (u"CM",  u"Le Centre-de-la-Mauricie"),
        (u"DD",  u"Le Domaine-du-Roy"),
        (u"FS",  u"Le Fjord-du-Saguenay"),
        (u"GR",  u"Le Granit"),
        (u"HR",  u"Le Haut-Richelieu"),
        (u"HF",  u"Le Haut-Saint-François"),
        (u"HL",  u"Le Haut-Saint-Laurent"),
        (u"HM",  u"Le Haut-Saint-Maurice"),
        (u"VF",  u"Le Val-Saint-François"),
        (u"BA",  u"Les Basques"),
        (u"CC",  u"Les Chutes-de-la-Chaudière"),
        (u"CO",  u"Les Collines-de-l'Outaouais"),
        (u"ET",  u"Les Etchemins"),
        (u"JN",  u"Les Jardins-de-Napierville"),
        (u"LL",  u"Les Laurentides"),
        (u"MK",  u"Les Maskoutains"),
        (u"MU",  u"Les Moulins"),
        (u"PH",  u"Les Pays-d'en-Haut"),
        (u"IM",  u"Les Îles-de-la-Madeleine"),
        (u"LO",  u"Lotbinière"),
        (u"MN",  u"Manicouagan"),
        (u"MC",  u"Maria-Chapdelaine"),
        (u"MS",  u"Maskinongé"),
        (u"MT",  u"Matane"),
        (u"MW",  u"Matawinie"),
        (u"MG",  u"Memphrémagog"),
        (u"MB",  u"Minganie - Basse-Côte-Nord"),
        (u"ML",  u"Mirabel"),
        (u"MO",  u"Montcalm"),
        (u"MM",  u"Montmagny"),
        (u"MR",  u"Montréal (Communauté-Urbaine)"),
        (u"ME",  u"Mékinac"),
        (u"NY",  u"Nicolet-Yamaska"),
        (u"NQ",  u"Nord-du-Québec"),
        (u"OU",  u"Outaouais (Communauté-Urbaine)"),        
        (u"PB",  u"Pabok"),
        (u"PP",  u"Papineau"),
        (u"PN",  u"Pontiac"),
        (u"PR",  u"Portneuf"),
        (u"QU",  u"Québec (Communauté-Urbaine)"),
        (u"RM",  u"Rimouski-Neigette"),
        (u"RL",  u"Rivière-du-Loup"),
        (u"RC",  u"Robert-Cliche"),
        (u"RS",  u"Roussillon"),
        (u"RV",  u"Rouville"),
        (u"RN",  u"Rouyn-Noranda"),
        (u"SR",  u"Sept-Rivières - Caniapiscau"),
        (u"SH",  u"Sherbrooke"),
        (u"TB",  u"Thérèse-De Blainville"),
        (u"TM",  u"Témiscamingue"),
        (u"TT",  u"Témiscouata"),
        (u"VO",  u"Vallée-de-l'Or"),
        (u"VS",  u"Vaudreuil-Soulanges"),
        ]),
    
    ((u'SK',   u' Saskatchewan'),[
        (u"ES", u"Estevan"),
        (u"HU", u"Humboldt"),
        (u"LL", u"Lloydminster"),
        (u"MA", u"Martensville"),
        (u"ME", u"Meadow Lake"),
        (u"MF", u"Melfort"),
        (u"MV", u"Melville"),
        (u"MO", u"Moose Jaw"),
        (u"NO", u"North Battleford"),
        (u"PR", u"Prince Albert"),
        (u"RE", u"Regina"),
        (u"SA", u"Saskatoon"),
        (u"SW", u"Swift Current"),
        (u"WE", u"Weyburn"),
        (u"YO", u"Yorkton"),
        ]),
            
    ((u'YT',   u' Yukon Territory'),[]),
]
