# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

CN_regions = [
    ((u"AH", u"Anhui"), [
        (u"AC",  u"Anqing"),
        (u"AN",  u"Anqing"),
        (u"BE",  u"Bengbu"),
        (u"CH",  u"Chaohu"),
        (u"CX",  u"Chuxian"),
        (u"FU",  u"Fuyang"),
        (u"HE",  u"Hefei"),
        (u"HB",  u"Huaibei"),
        (u"HN",  u"Huainan"),
        (u"HZ",  u"Huizhou"),
        (u"LU",  u"Lu'an"),
        (u"MA",  u"Ma'anshan"),
        (u"SU",  u"Suxian"),
        (u"TO",  u"Tongling"),
        (u"WU",  u"Wuhu"),
        (u"XU",  u"Xuancheng"),
        ]),

    ((u"BJ", u"Beijing"), [
        (u"CP",  u"Changping"),
        (u"CY",  u"Chaoyang"),
        (u"CW",  u"Chongwen"),
        (u"DA",  u"Daxing"),
        (u"DO",  u"Dongcheng"),
        (u"FA",  u"Fangshan"),
        (u"FE",  u"Fengtai"),
        (u"HA",  u"Haidian"),
        (u"HU",  u"Huairou"),
        (u"ME",  u"Mentougou"),
        (u"MI",  u"Miyun"),
        (u"PI",  u"Pinggu"),
        (u"SJ",  u"Shijingshan"),
        (u"SY",  u"Shunyi"),
        (u"TO",  u"Tongxian"),
        (u"XI",  u"Xicheng"),
        (u"XU",  u"Xuanwu"),
        (u"YQ",  u"Yanqing"),
        (u"YS",  u"Yanshan"),
        ]),

    ((u"CQ", u"Chongqing"), [
        (u"CH",  u"Chongqing"),
        ]),

    ((u"FJ", u"Fujian"), [
        (u"FU",  u"Fuzhou"),
        (u"JY",  u"Jianyang"),
        (u"JJ",  u"Jinjiang"),
        (u"LX",  u"Longxi"),
        (u"LY",  u"Longyan"),
        (u"NI",  u"Ningde"),
        (u"PU",  u"Putian"),
        (u"SA",  u"Sanming"),
        (u"XI",  u"Xiamen"),
        ]),

    ((u"GS", u"Gansu"), [
        (u"DI",  u"Dingxi"),
        (u"GA",  u"Ganan Tibetan"),
        (u"JY",  u"Jiayuguan"),
        (u"JC",  u"Jinchang"),
        (u"JQ",  u"Jiuquan"),
        (u"LA",  u"Lanzhou"),
        (u"LI",  u"Linxia Hui"),
        (u"PI",  u"Pingliang"),
        (u"QI",  u"Qingyang"),
        (u"TI",  u"Tianshui"),
        (u"WD",  u"Wudu"),
        (u"WW",  u"Wuwei"),
        (u"ZH",  u"Zhangye"),
        ]),

    ((u"GD", u"Guangdong"), [
        (u"FO",  u"Foshan"),
        (u"GU",  u"Guangzhou"),
        (u"HU",  u"Huiyang"),
        (u"ME",  u"Meixian"),
        (u"ST",  u"Shantou"),
        (u"SH",  u"Shaoguan"),
        (u"SG",  u"Shaoguan"),
        (u"SZ",  u"Shenzhen"),
        (u"ZJ",  u"Zhanjiang"),
        (u"ZQ",  u"Zhaoqing"),
        (u"ZH",  u"Zhuhai"),
        ]),

    ((u"GX", u"Guangxi Zhuang"), [
        (u"BO",  u"Bose"),
        (u"GU",  u"Guilin"),
        (u"GC",  u"Guilin"),
        (u"HE",  u"Hechi"),
        (u"LC",  u"Liuzhou"),
        (u"LI",  u"Liuzhou"),
        (u"NC",  u"Nanning"),
        (u"NA",  u"Nanning"),
        (u"QI",  u"Qinzhou"),
        (u"WC",  u"Wuzhou"),
        (u"WU",  u"Wuzhou"),
        (u"YU",  u"Yulin"),
        ]),

    ((u"GZ", u"Guizhou"), [
        (u"AN",  u"Anshun"),
        (u"BI",  u"Bijie"),
        (u"GU",  u"Guiyang"),
        (u"LU",  u"Lupanshui"),
        (u"QD",  u"Qiandongnan Miao-Dong"),
        (u"QN",  u"Qiannan Buyi-Miao"),
        (u"QX",  u"Qianxinan Buyi-Miao"),
        (u"TO",  u"Tongren"),
        (u"ZU",  u"Zunyi"),
        ]),

    ((u"HA", u"Hainan"), [
        (u"HA",  u"Hainan"),
        (u"HL",  u"Hainan Li-Miao"),
        ]),

    ((u"HB", u"Hebei"), [
        (u"BA",  u"Baoding"),
        (u"CA",  u"Cangzhou"),
        (u"CH",  u"Chengde"),
        (u"HA",  u"Handan"),
        (u"HE",  u"Hengshui"),
        (u"LA",  u"Langfang"),
        (u"SH",  u"Shijiazhuang"),
        (u"SC",  u"Shijiazhuang"),
        (u"TA",  u"Tangshan"),
        (u"TC",  u"Tangshan"),
        (u"XI",  u"Xingtai"),
        (u"ZH",  u"Zhangjiakou"),
        ]),

    ((u"HL", u"Heilongjiang"), [
        (u"DH",  u"Da Hinggan Ling (Jagdaqi)"),
        (u"DQ",  u"Daqing"),
        (u"HA",  u"Harbin"),
        (u"HG",  u"Hegang"),
        (u"HH",  u"Heihe"),
        (u"HJ",  u"Hejiang"),
        (u"JI",  u"Jixi"),
        (u"MU",  u"Mudanjiang"),
        (u"NE",  u"Nenjiang"),
        (u"QI",  u"Qiqihar"),
        (u"SH",  u"Shuangyashan"),
        (u"SO",  u"Songhuajiang"),
        (u"SU",  u"Suihua"),
        (u"YI",  u"Yichun"),
        ]),

    ((u"HE", u"Henan"), [
        (u"AC",  u"Anyang"),
        (u"AN",  u"Anyang"),
        (u"HE",  u"Hebi"),
        (u"JI",  u"Jiaozuo"),
        (u"KC",  u"Kaifeng"),
        (u"KA",  u"Kaifeng"),
        (u"LC",  u"Luoyang"),
        (u"LU",  u"Luoyang"),
        (u"NA",  u"Nanyang"),
        (u"PI",  u"Pingdingshan"),
        (u"SH",  u"Shangqiu"),
        (u"XX",  u"Xinxiang"),
        (u"XC",  u"Xinxiang"),
        (u"XY",  u"Xinyang"),
        (u"XU",  u"Xuchang"),
        (u"ZZ",  u"Zhengzhou"),
        (u"ZK",  u"Zhoukou"),
        (u"ZM",  u"Zhumadian"),
        ]),

    ((u"HU", u"Hubei"), [
        (u"EN",  u"Enshi"),
        (u"HG",  u"Huanggang"),
        (u"HS",  u"Huangshi"),
        (u"JI",  u"Jingzhou"),
        (u"SS",  u"Shashi"),
        (u"SY",  u"Shiyan"),
        (u"WU",  u"Wuhan"),
        (u"XF",  u"Xiangfan"),
        (u"XY",  u"Xiangyang"),
        (u"XN",  u"Xianning"),
        (u"XG",  u"Xiaogan"),
        (u"YI",  u"Yichang"),
        (u"YC",  u"Yichang"),
        (u"YU",  u"Yunyang"),
        ]),

    ((u"HN", u"Hunan"), [
        (u"CD",  u"Changde"),
        (u"CS",  u"Changsha"),
        (u"CZ",  u"Chenzhou"),
        (u"HC",  u"Hengyang"),
        (u"HE",  u"Hengyang"),
        (u"HU",  u"Huaihua"),
        (u"LY",  u"Lianyuan"),
        (u"LL",  u"Lingling"),
        (u"SC",  u"Shaoyang"),
        (u"SH",  u"Shaoyang"),
        (u"XC",  u"Xiangtan"),
        (u"XT",  u"Xiangtan"),
        (u"XX",  u"Xiangxi Tujia-Miao"),
        (u"YI",  u"Yiyang"),
        (u"YU",  u"Yueyang"),
        (u"ZH",  u"Zhuzhou"),
        ]),

    ((u"JS", u"Jiangsu"), [
        (u"CH",  u"Changzhou"),
        (u"HU",  u"Huaiyin"),
        (u"LI",  u"Lianyungang"),
        (u"NJ",  u"Nanjing"),
        (u"NC",  u"Nantong"),
        (u"NT",  u"Nantong"),
        (u"SU",  u"Suzhou"),
        (u"SC",  u"Suzhou"),
        (u"WU",  u"Wuxi"),
        (u"XC",  u"Xuzhou"),
        (u"XU",  u"Xuzhou"),
        (u"YC",  u"Yancheng"),
        (u"YZ",  u"Yangzhou"),
        (u"ZH",  u"Zhenjiang"),
        ]),

    ((u"JX", u"Jiangxi"), [
        (u"FU",  u"Fuzhou"),
        (u"GA",  u"Ganzhou"),
        (u"JA",  u"Ji'an"),
        (u"JD",  u"Jingdezhen"),
        (u"JJ",  u"Jiujiang"),
        (u"JC",  u"Jiujiang"),
        (u"NA",  u"Nanchang"),
        (u"PI",  u"Pingxiang"),
        (u"SH",  u"Shangrao"),
        (u"YI",  u"Yichun"),
        ]),

    ((u"JL", u"Jilin"), [
        (u"BA",  u"Baicheng"),
        (u"CH",  u"Changchun"),
        (u"JI",  u"Jilin"),
        (u"SI",  u"Siping"),
        (u"TO",  u"Tonghua"),
        (u"YA",  u"Yanbian Korean"),
        ]),

    ((u"LN", u"Liaoning"), [
        (u"AN",  u"Anshan"),
        (u"BE",  u"Benxi"),
        (u"CH",  u"Chaoyang"),
        (u"DL",  u"Dalian"),
        (u"DD",  u"Dandong"),
        (u"FS",  u"Fushun"),
        (u"FX",  u"Fuxin"),
        (u"JI",  u"Jinzhou"),
        (u"LI",  u"Liaoyang"),
        (u"SH",  u"Shenyang"),
        (u"TI",  u"Tieling"),
        (u"YI",  u"Yingkou"),
        ]),

    ((u"NM", u"Nei Mongol"), [
        (u"AL",  u"Alxa"),
        (u"BT",  u"Baotou"),
        (u"BN",  u"Bayannur"),
        (u"HO",  u"Hohhot"),
        (u"HU",  u"Hulun Buir"),
        (u"IH",  u"Ih Ju"),
        (u"JI",  u"Jirem"),
        (u"JU",  u"Ju Ud"),
        (u"UL",  u"Ulanqab"),
        (u"WU",  u"Wuhai"),
        (u"XL",  u"Xilin Gol"),
        (u"XA",  u"Xing'an"),
        ]),

    ((u"NX", u"Ningxia Hui"), [
        (u"GU",  u"Guyuan"),
        (u"SH",  u"Shizuishan"),
        (u"YC",  u"Yinchuan"),
        (u"YN",  u"Yinnan"),
        ]),

    ((u"QH", u"Qinghai"), [
        (u"GO",  u"Golog Tibetan"),
        (u"HB",  u"Haibei Tibetan"),
        (u"HD",  u"Haidong"),
        (u"HN",  u"Hainan Tibetan"),
        (u"HX",  u"Haixi Mongolian-Tibetan-Kazak"),
        (u"HU",  u"Huangnan Tibetan"),
        (u"XI",  u"Xining"),
        (u"YU",  u"Yushu Tibetan"),
        ]),

    ((u"SA", u"Shaanxi"), [
        (u"AN",  u"Ankang"),
        (u"BA",  u"Baoji"),
        (u"HA",  u"Hanzhong"),
        (u"SH",  u"Shangluo"),
        (u"TO",  u"Tongchuan"),
        (u"WE",  u"Weinan"),
        (u"XA",  u"Xi'an"),
        (u"XY",  u"Xianyang"),
        (u"YA",  u"Yan'an"),
        (u"YU",  u"Yulin"),
        ]),

    ((u"SD", u"Shandong"), [
        (u"DE",  u"Dezhou"),
        (u"HE",  u"Heze"),
        (u"HU",  u"Huimin"),
        (u"JA",  u"Jinan"),
        (u"JG",  u"Jining"),
        (u"LC",  u"Liaocheng"),
        (u"LY",  u"Linyi"),
        (u"QI",  u"Qingdao"),
        (u"TA",  u"Tai'an"),
        (u"WE",  u"Weifang"),
        (u"YA",  u"Yantai"),
        (u"ZA",  u"Zaozhuang"),
        (u"ZI",  u"Zibo"),
        ]),

    ((u"SH", u"Shanghai"), [
        (u"BA",  u"Baoshan"),
        (u"CN",  u"Changning"),
        (u"CM",  u"Chongming"),
        (u"CS",  u"Chuansha"),
        (u"FE",  u"Fengxian"),
        (u"HO",  u"Hongkou"),
        (u"HU",  u"Huangpu"),
        (u"JD",  u"Jiading"),
        (u"JA",  u"Jing'an"),
        (u"JS",  u"Jinshan"),
        (u"LU",  u"Luwan"),
        (u"MI",  u"Minhang"),
        (u"NH",  u"Nanhui"),
        (u"NS",  u"Nanshi"),
        (u"PU",  u"Putuo"),
        (u"QI",  u"Qingpu"),
        (u"SH",  u"Shanghai"),
        (u"SO",  u"Songjiang"),
        (u"WU",  u"Wusong"),
        (u"XU",  u"Xuhui"),
        (u"YA",  u"Yangpu"),
        (u"ZH",  u"Zhabei"),
        ]),

    ((u"SX", u"Shanxi"), [
        (u"CH",  u"Changzhi"),
        (u"DA",  u"Datong"),
        (u"JD",  u"Jindongnan"),
        (u"JZ",  u"Jinzhong"),
        (u"LI",  u"Linfen"),
        (u"LU",  u"Luliang"),
        (u"TA",  u"Taiyuan"),
        (u"XI",  u"Xinxian"),
        (u"YB",  u"Yanbei"),
        (u"YQ",  u"Yangquan"),
        (u"YU",  u"Yuncheng"),
        ]),

    ((u"SC", u"Sichuan"), [
        (u"AB",  u"Aba Tibetan"),
        (u"CH",  u"Chengdu"),
        (u"DA",  u"Daxian"),
        (u"DU",  u"Dukou"),
        (u"FU",  u"Fuling"),
        (u"GA",  u"Garzê Tibetan"),
        (u"LE",  u"Leshan"),
        (u"LI",  u"Liangshan Yi"),
        (u"MI",  u"Mianyang"),
        (u"NA",  u"Nanchong"),
        (u"NE",  u"Neijiang"),
        (u"WA",  u"Wanxian"),
        (u"WE",  u"Wenjiang"),
        (u"YA",  u"Ya'an"),
        (u"YI",  u"Yibin"),
        (u"YO",  u"Yongchuan"),
        (u"ZI",  u"Zigong"),
        ]),

    ((u"TJ", u"Tianjin"), [
        (u"BA",  u"Baodi"),
        (u"BE",  u"Beijiao"),
        (u"DA",  u"Dagang"),
        (u"DO",  u"Dongjiao"),
        (u"HA",  u"Hangu"),
        (u"HB",  u"Hebei"),
        (u"HD",  u"Hedong"),
        (u"HP",  u"Heping"),
        (u"HX",  u"Hexi"),
        (u"HO",  u"Hongqiao"),
        (u"JH",  u"Jinghai"),
        (u"JX",  u"Jixian"),
        (u"NJ",  u"Nanjiao"),
        (u"NK",  u"Nankai"),
        (u"NI",  u"Ninghe"),
        (u"TA",  u"Tanggu"),
        (u"WU",  u"Wuqing"),
        (u"XI",  u"Xijiao"),
        ]),

    ((u"XJ", u"Xinjiang Uygur"), [
        (u"AK",  u"Aksu"),
        (u"AL",  u"Altay"),
        (u"BA",  u"Bayingolin Mongolian"),
        (u"BO",  u"Bortala Mongolian"),
        (u"CH",  u"Changji Hui"),
        (u"HA",  u"Hami"),
        (u"HO",  u"Hotan"),
        (u"IL",  u"Ili Kazak"),
        (u"KR",  u"Karamay"),
        (u"KS",  u"Kashi"),
        (u"KI",  u"Kizilsu Kirgiz"),
        (u"SH",  u"Shihezi"),
        (u"TA",  u"Tacheng"),
        (u"TU",  u"Turpan"),
        (u"UR",  u"Ürümqi"),
        ]),

    ((u"XZ", u"Xizang"), [
        (u"LH",  u"Lhasa"),
        (u"NA",  u"Nagqu"),
        (u"NG",  u"Ngari"),
        (u"QA",  u"Qamdo"),
        (u"SH",  u"Shannan"),
        (u"XI",  u"Xigazê"),
        ]),

    ((u"YN", u"Yunnan"), [
        (u"BA",  u"Baoshan"),
        (u"CH",  u"Chuxiong Yi"),
        (u"DA",  u"Dali Bai"),
        (u"DH",  u"Deihong Dai-Jingpo"),
        (u"DO",  u"Dongchuan"),
        (u"DQ",  u"Dêqên Tibetan"),
        (u"HO",  u"Honghe Hani-Yi"),
        (u"KU",  u"Kunming"),
        (u"LJ",  u"Lijiang"),
        (u"LC",  u"Linchang"),
        (u"NU",  u"Nujiang Lisu"),
        (u"QU",  u"Qujing"),
        (u"SI",  u"Simao"),
        (u"WE",  u"Wenshan Zhuang-Miao"),
        (u"XI",  u"Xishuangbanna Dai"),
        (u"YU",  u"Yuxi"),
        (u"ZH",  u"Zhaotong"),
        ]),

    ((u"ZJ", u"Zhejiang"), [
        (u"HA",  u"Hangzhou"),
        (u"JX",  u"Jiaxing"),
        (u"JH",  u"Jinhua"),
        (u"LI",  u"Lishui"),
        (u"NI",  u"Ningbo"),
        (u"NC",  u"Ningbo"),
        (u"SH",  u"Shaoxing"),
        (u"TA",  u"Taizhou"),
        (u"WE",  u"Wenzhou"),
        (u"ZH",  u"Zhoushan"),
        ]),

]
