# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

CO_regions = [
    ((u"AMA", u"Amazonas"),     [
        (u"EE",  u"El Encanto"),
        (u"LC",  u"La Chorrera"),
        (u"LP",  u"La Pedrera"),
        (u"LV",  u"La Victoria"),
        (u"LE",  u"Leticia"),
        (u"MI",  u"Mirití-Paraná"),
        (u"AL",  u"Puerto Alegria"),
        (u"AR",  u"Puerto Arica"),
        (u"PN",  u"Puerto Nariño"),
        (u"PS",  u"Puerto Santander"),
        (u"TA",  u"Tarapacá"),
        ]),

    ((u"ANT", u"Antioquia"), [
        (u"AB",  u"Abejorral"),
        (u"AQ",  u"Abriaquí"),
        (u"AJ",  u"Alejandría"),
        (u"AM",  u"Amagá"),
        (u"AF",  u"Amalfi"),
        (u"AD",  u"Andes"),
        (u"AL",  u"Angelópolis"),
        (u"AS",  u"Angostura"),
        (u"AN",  u"Anorí"),
        (u"AT",  u"Antioquia [, Santa Fe de]"),
        (u"AZ",  u"Anzá"),
        (u"AP",  u"Apartadó"),
        (u"AR",  u"Arboletes"),
        (u"AG",  u"Argelia"),
        (u"AA",  u"Armenia [Mantequilla]"),
        (u"BB",  u"Barbosa"),
        (u"BL",  u"Bello"),
        (u"BM",  u"Belmira"),
        (u"BN",  u"Betania"),
        (u"BT",  u"Betulia"),
        (u"BR",  u"Briceño"),
        (u"BU",  u"Buriticá"),
        (u"CD",  u"Caicedo"),
        (u"CL",  u"Caldas"),
        (u"CM",  u"Campamento"),
        (u"CA",  u"Caracolí"),
        (u"CT",  u"Caramanta"),
        (u"CP",  u"Carepa"),
        (u"CR",  u"Carolina [del Principe]"),
        (u"CU",  u"Caucasia"),
        (u"CG",  u"Cañasgordas"),
        (u"CH",  u"Chigorodó"),
        (u"CI",  u"Cisneros"),
        (u"CO",  u"Cocorná"),
        (u"CC",  u"Concepción"),
        (u"CN",  u"Concordia"),
        (u"CB",  u"Copacabana"),
        (u"CE",  u"Cáceres"),
        (u"DA",  u"Dabeiba"),
        (u"DM",  u"Don Matías"),
        (u"EJ",  u"Ebéjico"),
        (u"EB",  u"El Bagre"),
        (u"CV",  u"El Carmen de Viboral"),
        (u"SI",  u"El Santuario"),
        (u"ER",  u"Entrerríos"),
        (u"EN",  u"Envigado"),
        (u"FD",  u"Fredonia"),
        (u"FN",  u"Frontino"),
        (u"GL",  u"Giraldo"),
        (u"GT",  u"Girardota"),
        (u"GR",  u"Granada"),
        (u"GD",  u"Guadalupe"),
        (u"GU",  u"Guarne"),
        (u"GA",  u"Guatapé"),
        (u"GP",  u"Gómez Plata"),
        (u"HE",  u"Heliconia"),
        (u"HI",  u"Hispania"),
        (u"II",  u"Itagüí"),
        (u"IN",  u"Ituango"),
        (u"JA",  u"Jardín"),
        (u"JE",  u"Jericó"),
        (u"LC",  u"La Ceja"),
        (u"LE",  u"La Estrella"),
        (u"LP",  u"La Pintada"),
        (u"LU",  u"La Unión"),
        (u"LI",  u"Liborina"),
        (u"MC",  u"Maceo"),
        (u"MA",  u"Marinilla"),
        (u"ME",  u"Medellín"),
        (u"MO",  u"Montebello"),
        (u"MR",  u"Murindó"),
        (u"MT",  u"Mutatá"),
        (u"NA",  u"Nariño"),
        (u"NH",  u"Nechí"),
        (u"NC",  u"Necoclí"),
        (u"OL",  u"Olaya"),
        (u"PQ",  u"Pequé"),
        (u"PL",  u"Peñol"),
        (u"PU",  u"Pueblorrico"),
        (u"PB",  u"Puerto Berrío"),
        (u"PN",  u"Puerto Nare"),
        (u"PT",  u"Puerto Triunfo"),
        (u"RM",  u"Remedios"),
        (u"RT",  u"Retiro"),
        (u"RI",  u"Rionegro"),
        (u"SY",  u"Sabanalarga"),
        (u"ST",  u"Sabaneta"),
        (u"SG",  u"Salgar"),
        (u"SA",  u"San Andrés [de Cuerquia]"),
        (u"SC",  u"San Carlos"),
        (u"SF",  u"San Francisco"),
        (u"SM",  u"San Jerónimo"),
        (u"SJ",  u"San José de la Montaña"),
        (u"SX",  u"San Juan de Urabá"),
        (u"SL",  u"San Luis"),
        (u"SP",  u"San Pedro [de Los Milagros]"),
        (u"SU",  u"San Pedro de Urabá"),
        (u"SN",  u"San Rafael"),
        (u"SQ",  u"San Roque"),
        (u"SV",  u"San Vicente"),
        (u"SB",  u"Santa Bárbara"),
        (u"SR",  u"Santa Rosa de Osos"),
        (u"SD",  u"Santo Domingo"),
        (u"SE",  u"Segovia"),
        (u"SS",  u"Sonsón"),
        (u"SO",  u"Sopetrán"),
        (u"TZ",  u"Tarazá"),
        (u"TA",  u"Tarso"),
        (u"TI",  u"Titiribí"),
        (u"TO",  u"Toledo"),
        (u"TU",  u"Turbo"),
        (u"TM",  u"Támesis"),
        (u"UM",  u"Uramita"),
        (u"UO",  u"Urrao"),
        (u"VD",  u"Valdivia"),
        (u"VP",  u"Valparaíso"),
        (u"VG",  u"Vegachí"),
        (u"VN",  u"Venecia"),
        (u"VF",  u"Vigía del Fuerte"),
        (u"YL",  u"Yalí"),
        (u"YR",  u"Yarumal"),
        (u"YB",  u"Yolombó"),
        (u"YD",  u"Yondó"),
        (u"ZA",  u"Zaragoza"),
        (u"BO",  u"[Ciudad] Bolívar"),
        ]),

    ((u"ARA", u"Arauca"), [
        (u"AC",  u"Arauca"),
        (u"AQ",  u"Arauquita"),
        (u"CN",  u"Cravo Norte"),
        (u"FO",  u"Fortul"),
        (u"PR",  u"Puerto Rondón"),
        (u"SA",  u"Saravena"),
        (u"TA",  u"Tame"),
        ]),

    ((u"ATL", u"Atlántico"), [
        (u"BO",  u"Baranoa"),
        (u"BQ",  u"Barranquilla"),
        (u"CC",  u"Campo de la Cruz"),
        (u"CA",  u"Candelaria"),
        (u"GA",  u"Galapa"),
        (u"JU",  u"Juan de Acosta"),
        (u"LU",  u"Luruaco"),
        (u"ML",  u"Malambo"),
        (u"MN",  u"Manatí"),
        (u"PV",  u"Palmar de Varela"),
        (u"PI",  u"Piojó"),
        (u"PL",  u"Polonuevo"),
        (u"PD",  u"Ponedera"),
        (u"PC",  u"Puerto Colombia"),
        (u"RE",  u"Repelón"),
        (u"SG",  u"Sabanagrande"),
        (u"SA",  u"Sabanalarga"),
        (u"SL",  u"Santa Lucía"),
        (u"ST",  u"Santo Tomás"),
        (u"SO",  u"Soledad"),
        (u"SU",  u"Suan"),
        (u"TU",  u"Tubará"),
        (u"US",  u"Usiacurí"),
        ]),

    ((u"BOL", u"Bolívar"), [
        (u"AC",  u"Achí"),
        (u"AL",  u"Altos del Rosario"),
        (u"AN",  u"Arenal"),
        (u"AR",  u"Arjona"),
        (u"AH",  u"Arroyohondo"),
        (u"BA",  u"Barranco de Loba"),
        (u"CM",  u"Calamar"),
        (u"CN",  u"Cantagallo"),
        (u"CG",  u"Cartagena [de Indias]"),
        (u"CC",  u"Cicuco"),
        (u"CL",  u"Clemencia"),
        (u"CO",  u"Córdoba"),
        (u"EC",  u"El Carmen de Bolívar"),
        (u"EG",  u"El Guamo"),
        (u"EP",  u"El Peñon"),
        (u"HL",  u"Hatillo de Loba"),
        (u"MG",  u"Magangué"),
        (u"MH",  u"Mahates"),
        (u"MA",  u"Margarita"),
        (u"MB",  u"María la Baja"),
        (u"MP",  u"Mompós"),
        (u"MC",  u"Montecristo"),
        (u"MS",  u"Morales"),
        (u"PI",  u"Pinillos"),
        (u"RE",  u"Regidor"),
        (u"RV",  u"Río Viejo"),
        (u"SB",  u"San Cristobal"),
        (u"SE",  u"San Estanislao [de Kostka]"),
        (u"SF",  u"San Fernando"),
        (u"SJ",  u"San Jacinto"),
        (u"ST",  u"San Jacinto del Cauca"),
        (u"SN",  u"San Juan Nepomuceno"),
        (u"SM",  u"San Martín de Loba"),
        (u"SP",  u"San Pablo"),
        (u"SC",  u"Santa Catalina"),
        (u"SR",  u"Santa Rosa"),
        (u"SS",  u"Santa Rosa del Sur"),
        (u"SI",  u"Simití"),
        (u"SO",  u"Soplaviento"),
        (u"TA",  u"Talaigua Nuevo"),
        (u"TQ",  u"Tiquisio"),
        (u"TC",  u"Turbaco"),
        (u"TN",  u"Turbaná"),
        (u"VN",  u"Villanueva"),
        (u"ZA",  u"Zambrano"),
        ]),

    ((u"BOY", u"Boyacá"), [
        (u"AL",  u"Almeida"),
        (u"AQ",  u"Aquitania"),
        (u"AR",  u"Arcabuco"),
        (u"BL",  u"Belén"),
        (u"BB",  u"Berbeo"),
        (u"BT",  u"Beteitiva"),
        (u"BO",  u"Boavita"),
        (u"BY",  u"Boyacá"),
        (u"BR",  u"Briceño"),
        (u"BU",  u"Buenavista"),
        (u"BZ",  u"Busbanza"),
        (u"CD",  u"Caldas"),
        (u"CM",  u"Campohermoso"),
        (u"CE",  u"Cerinza"),
        (u"CN",  u"Chinavita"),
        (u"CQ",  u"Chiquinquirá"),
        (u"CS",  u"Chiscas"),
        (u"CA",  u"Chita"),
        (u"CR",  u"Chitaraque"),
        (u"CV",  u"Chivatá"),
        (u"CH",  u"Chivor"),
        (u"CZ",  u"Chíquiza"),
        (u"CG",  u"Ciénaga"),
        (u"CP",  u"Coper"),
        (u"CL",  u"Corrales"),
        (u"CO",  u"Covarachía"),
        (u"CU",  u"Cubará"),
        (u"CC",  u"Cucaita"),
        (u"CT",  u"Cuítiva"),
        (u"CB",  u"Cómbita"),
        (u"DU",  u"Duitama"),
        (u"EC",  u"El Cocuy"),
        (u"EE",  u"El Espino"),
        (u"FI",  u"Firavitoba"),
        (u"FL",  u"Floresta"),
        (u"GC",  u"Gachantivá"),
        (u"GG",  u"Garagoa"),
        (u"GM",  u"Guacamayas"),
        (u"GT",  u"Guateque"),
        (u"GY",  u"Guayatá"),
        (u"GU",  u"Guicán"),
        (u"GZ",  u"Gámeza"),
        (u"IZ",  u"Izá"),
        (u"JN",  u"Jenesano"),
        (u"JR",  u"Jericó"),
        (u"LC",  u"La Capilla"),
        (u"LU",  u"La Uvita"),
        (u"LV",  u"La Victoria"),
        (u"LB",  u"Labranzagrande"),
        (u"MC",  u"Macanal"),
        (u"MP",  u"Maripí"),
        (u"MF",  u"Miraflores"),
        (u"MA",  u"Mongua"),
        (u"MI",  u"Monguí"),
        (u"MQ",  u"Moniquirá"),
        (u"MV",  u"Motavita"),
        (u"MZ",  u"Muzo"),
        (u"NO",  u"Nobsa"),
        (u"NC",  u"Nuevo Colón"),
        (u"OI",  u"Oicatá"),
        (u"OT",  u"Otanche"),
        (u"PC",  u"Pachavita"),
        (u"PP",  u"Paipa"),
        (u"PJ",  u"Pajarito"),
        (u"PQ",  u"Panqueba"),
        (u"PA",  u"Pauna"),
        (u"PY",  u"Paya"),
        (u"PR",  u"Paz de Río"),
        (u"PE",  u"Pesca"),
        (u"PV",  u"Pisba"),
        (u"PB",  u"Puerto Boyacá"),
        (u"PZ",  u"Páez"),
        (u"QU",  u"Quípama"),
        (u"RM",  u"Ramiriquí"),
        (u"RO",  u"Rondón"),
        (u"RA",  u"Ráquira"),
        (u"SB",  u"Saboyá"),
        (u"SA",  u"Samacá"),
        (u"SD",  u"San Eduardo"),
        (u"JP",  u"San José de Pare"),
        (u"LG",  u"San Luis de Gaceno"),
        (u"SM",  u"San Mateo"),
        (u"MS",  u"San Miguel de Sema"),
        (u"SP",  u"San Pablo de Borbur"),
        (u"SX",  u"Santa María"),
        (u"RV",  u"Santa Rosa de Viterbo"),
        (u"SF",  u"Santa Sofía"),
        (u"SN",  u"Santana"),
        (u"SE",  u"Sativanorte"),
        (u"SV",  u"Sativasur"),
        (u"SI",  u"Siachoque"),
        (u"SO",  u"Soatá"),
        (u"SC",  u"Socha"),
        (u"ST",  u"Socotá"),
        (u"SG",  u"Sogamoso"),
        (u"SK",  u"Somondoco"),
        (u"SR",  u"Sora"),
        (u"SL",  u"Soracá"),
        (u"SQ",  u"Sotaquirá"),
        (u"SS",  u"Susacón"),
        (u"SU",  u"Sutamarchán"),
        (u"SZ",  u"Sutatenza"),
        (u"SH",  u"Sáchica"),
        (u"TA",  u"Tasco"),
        (u"TZ",  u"Tenza"),
        (u"TN",  u"Tibaná"),
        (u"TB",  u"Tibasosa"),
        (u"TI",  u"Tinjacá"),
        (u"TQ",  u"Tipacoque"),
        (u"TC",  u"Toca"),
        (u"TG",  u"Toguí"),
        (u"TP",  u"Topagá"),
        (u"TO",  u"Tota"),
        (u"TJ",  u"Tunja"),
        (u"TU",  u"Tunungua"),
        (u"TE",  u"Turmequé"),
        (u"TT",  u"Tuta"),
        (u"TS",  u"Tutazá"),
        (u"UM",  u"Umbita"),
        (u"VE",  u"Ventaquemada"),
        (u"LE",  u"Villa de Leyva"),
        (u"VI",  u"Viracachá"),
        (u"ZE",  u"Zetaquirá"),
        ]),

    ((u"CAL", u"Caldas"), [
        (u"AG",  u"Aguadas"),
        (u"AN",  u"Anserma"),
        (u"AR",  u"Aranzazú"),
        (u"BE",  u"Belalcázar"),
        (u"CH",  u"Chinchiná"),
        (u"FI",  u"Filadelfia"),
        (u"LD",  u"La Dorada"),
        (u"LM",  u"La Merced"),
        (u"ML",  u"Manizales"),
        (u"MZ",  u"Manzanares"),
        (u"MM",  u"Marmato"),
        (u"MQ",  u"Marquetalia"),
        (u"MD",  u"Marulanda"),
        (u"NE",  u"Neira"),
        (u"NO",  u"Norcasia"),
        (u"PL",  u"Palestina"),
        (u"PE",  u"Pensilvania"),
        (u"PC",  u"Pácora"),
        (u"RS",  u"Riosucio"),
        (u"RR",  u"Risaralda"),
        (u"SL",  u"Salamina"),
        (u"SA",  u"Samaná"),
        (u"SJ",  u"San José [de Caldas]"),
        (u"SU",  u"Supía"),
        (u"VC",  u"Victoria"),
        (u"VM",  u"Villamaría"),
        (u"VB",  u"Viterbo"),
        ]),

    ((u"CAQ", u"Caquetá"), [
        (u"AL",  u"Albania"),
        (u"BE",  u"Belén de los Andaquies"),
        (u"CA",  u"Cartagena del Chairá"),
        (u"CU",  u"Curillo"),
        (u"ED",  u"El Doncello"),
        (u"EP",  u"El Paujíl"),
        (u"FL",  u"Florencia"),
        (u"LM",  u"La Montañita"),
        (u"MI",  u"Milán"),
        (u"MO",  u"Morelia"),
        (u"PR",  u"Puerto Rico"),
        (u"SJ",  u"San José del Fragua"),
        (u"SV",  u"San Vicente del Caguán"),
        (u"SO",  u"Solano"),
        (u"ST",  u"Solita"),
        (u"VA",  u"Valparaíso"),
        ]),

    ((u"CAS", u"Casanare"), [
        (u"AG",  u"Aguazul"),
        (u"CH",  u"Chámeza"),
        (u"HA",  u"Hato Corozal"),
        (u"LS",  u"La Salina"),
        (u"MA",  u"Maní"),
        (u"MO",  u"Monterrey"),
        (u"NU",  u"Nunchía"),
        (u"OR",  u"Orocué"),
        (u"PA",  u"Paz de Ariporo"),
        (u"PO",  u"Pore"),
        (u"RE",  u"Recetor"),
        (u"SB",  u"Sabanalarga"),
        (u"SL",  u"San Luis de Palenque"),
        (u"SC",  u"Sácama"),
        (u"TN",  u"Tauramena"),
        (u"TR",  u"Trinidad"),
        (u"TM",  u"Támara"),
        (u"VN",  u"Villanueva"),
        (u"YO",  u"Yopal"),
        ]),

    ((u"CAU", u"Cauca"), [
        (u"AL",  u"Almaguer"),
        (u"AR",  u"Argelia"),
        (u"BB",  u"Balboa"),
        (u"BO",  u"Bolívar"),
        (u"BA",  u"Buenos Aires"),
        (u"CJ",  u"Cajibío"),
        (u"CD",  u"Caldonó"),
        (u"CT",  u"Caloto"),
        (u"CO",  u"Corinto"),
        (u"ET",  u"El Tambo"),
        (u"FL",  u"Florencia"),
        (u"GU",  u"Guapí"),
        (u"IN",  u"Inzá"),
        (u"JA",  u"Jambaló"),
        (u"LS",  u"La Sierra"),
        (u"LV",  u"La Vega"),
        (u"LO",  u"López [de Micay]"),
        (u"ME",  u"Mercaderes"),
        (u"MI",  u"Miranda"),
        (u"MO",  u"Morales"),
        (u"PD",  u"Padilla"),
        (u"PA",  u"Patía"),
        (u"PM",  u"Piamonte"),
        (u"PI",  u"Piendamó"),
        (u"PO",  u"Popayán"),
        (u"PT",  u"Puerto Tejada"),
        (u"PU",  u"Puracé"),
        (u"PZ",  u"Páez"),
        (u"RO",  u"Rosas"),
        (u"SS",  u"San Sebastián"),
        (u"SR",  u"Santa Rosa"),
        (u"SN",  u"Santander de Quilichao"),
        (u"SI",  u"Silvia"),
        (u"SO",  u"Sotará"),
        (u"SU",  u"Suárez"),
        (u"TQ",  u"Timbiquí"),
        (u"TM",  u"Timbío"),
        (u"TR",  u"Toribío"),
        (u"TT",  u"Totoró"),
        (u"VR",  u"Villa Rica"),
        ]),

    ((u"CES", u"Cesar"), [
        (u"AG",  u"Aguachica"),
        (u"AC",  u"Agustín Codazzi"),
        (u"AS",  u"Astrea"),
        (u"BE",  u"Becerril"),
        (u"BO",  u"Bosconia"),
        (u"CC",  u"Chimichagua"),
        (u"CG",  u"Chiriguaná"),
        (u"CU",  u"Curumaní"),
        (u"EC",  u"El Copey"),
        (u"EP",  u"El Paso"),
        (u"GA",  u"Gamarra"),
        (u"GO",  u"González"),
        (u"LG",  u"La Gloria"),
        (u"LJ",  u"La Jagua de Ibirico"),
        (u"RO",  u"La Paz"),
        (u"MA",  u"Manaure [Balcón del Cesar]"),
        (u"PA",  u"Pailitas"),
        (u"PE",  u"Pelaya"),
        (u"PB",  u"Pueblo Bello"),
        (u"RI",  u"Río de Oro"),
        (u"SA",  u"San Alberto"),
        (u"SD",  u"San Diego"),
        (u"SM",  u"San Martín"),
        (u"TA",  u"Tamalameque"),
        (u"VA",  u"Valledupar"),
        ]),

    ((u"CHO", u"Chocó"), [
        (u"AC",  u"Acandí"),
        (u"AL",  u"Alto Baudó"),
        (u"AT",  u"Atrato"),
        (u"BA",  u"Bagadó"),
        (u"BS",  u"Bahía Solano"),
        (u"BB",  u"Bajo Baudó"),
        (u"BO",  u"Bojayá"),
        (u"CO",  u"Condoto"),
        (u"SP",  u"El Cantón del San Pablo"),
        (u"EC",  u"El Carmen [de Atrato]"),
        (u"LI",  u"El Litoral del San Juan"),
        (u"IS",  u"Istmina"),
        (u"JU",  u"Juradó"),
        (u"LL",  u"Lloró"),
        (u"MA",  u"Medio Atrato"),
        (u"MB",  u"Medio Baudo"),
        (u"NO",  u"Novita"),
        (u"NU",  u"Nuquí"),
        (u"QU",  u"Quibdó"),
        (u"RQ",  u"Rio Quito"),
        (u"RI",  u"Riosucio"),
        (u"SJ",  u"San José del Palmar"),
        (u"SI",  u"Sipí"),
        (u"TA",  u"Tadó"),
        (u"UN",  u"Unguía"),
        (u"UP",  u"Union Panamericana"),
        ]),

    ((u"CUN", u"Cundinamarca"), [
        (u"AD",  u"Agua de Dios"),
        (u"AL",  u"Albán"),
        (u"AP",  u"Anapoima"),
        (u"AN",  u"Anolaima"),
        (u"AR",  u"Arbeláez"),
        (u"BE",  u"Beltrán"),
        (u"BI",  u"Bituima"),
        (u"BO",  u"Bojacá"),
        (u"CB",  u"Cabrera"),
        (u"CA",  u"Cachipay"),
        (u"CJ",  u"Cajicá"),
        (u"CP",  u"Caparrapí"),
        (u"CC",  u"Carmen de Carupa"),
        (u"CN",  u"Chaguaní"),
        (u"CE",  u"Chipaque"),
        (u"CH",  u"Choachí"),
        (u"CO",  u"Chocontá"),
        (u"CI",  u"Chía"),
        (u"CG",  u"Cogua"),
        (u"CT",  u"Cota"),
        (u"CU",  u"Cucunubá"),
        (u"CQ",  u"Cáqueza"),
        (u"EC",  u"El Colegio"),
        (u"EP",  u"El Peñon"),
        (u"ER",  u"El Rosal"),
        (u"FA",  u"Facatativá"),
        (u"FO",  u"Fosca"),
        (u"FZ",  u"Funza"),
        (u"FS",  u"Fusagasugá"),
        (u"FM",  u"Fómeque"),
        (u"FQ",  u"Fúquene"),
        (u"GL",  u"Gachalá"),
        (u"GP",  u"Gachancipá"),
        (u"GT",  u"Gachetá"),
        (u"GM",  u"Gama"),
        (u"GI",  u"Girardot"),
        (u"GR",  u"Granada"),
        (u"GC",  u"Guachetá"),
        (u"GD",  u"Guaduas"),
        (u"GU",  u"Guasca"),
        (u"GQ",  u"Guataquí"),
        (u"GV",  u"Guatavita"),
        (u"GS",  u"Guayabal de Síquima"),
        (u"GB",  u"Guayabetal"),
        (u"GZ",  u"Gutiérrez"),
        (u"JE",  u"Jerusalén"),
        (u"JU",  u"Junín"),
        (u"LC",  u"La Calera"),
        (u"LM",  u"La Mesa"),
        (u"LA",  u"La Palma"),
        (u"LP",  u"La Peña"),
        (u"LV",  u"La Vega"),
        (u"LE",  u"Lenguazaque"),
        (u"MC",  u"Machetá"),
        (u"MD",  u"Madrid"),
        (u"MN",  u"Manta"),
        (u"ME",  u"Medina"),
        (u"MO",  u"Mosquera"),
        (u"NA",  u"Nariño"),
        (u"NE",  u"Nemocón"),
        (u"NI",  u"Nilo"),
        (u"NM",  u"Nimaima"),
        (u"NO",  u"Nocaima"),
        (u"PC",  u"Pacho"),
        (u"PM",  u"Paime"),
        (u"PD",  u"Pandi"),
        (u"PB",  u"Paratebueno"),
        (u"PA",  u"Pasca"),
        (u"PS",  u"Puerto Salgar"),
        (u"PU",  u"Pulí"),
        (u"QN",  u"Quebradanegra"),
        (u"QT",  u"Quetame"),
        (u"QP",  u"Quipile"),
        (u"RR",  u"Rafael Reyes"),
        (u"RI",  u"Ricaurte"),
        (u"ST",  u"San Antonio del Tequendama"),
        (u"SB",  u"San Bernardo"),
        (u"SY",  u"San Cayetano"),
        (u"SF",  u"San Francisco"),
        (u"SJ",  u"San Juan de Río Seco"),
        (u"SA",  u"Sasaima"),
        (u"SE",  u"Sesquilé"),
        (u"SI",  u"Sibaté"),
        (u"SV",  u"Silvania"),
        (u"SM",  u"Simijaca"),
        (u"SH",  u"Soacha"),
        (u"SO",  u"Sopó"),
        (u"SQ",  u"Subachoque"),
        (u"SC",  u"Suesca"),
        (u"SP",  u"Supatá"),
        (u"SS",  u"Susa"),
        (u"SU",  u"Sutatausa"),
        (u"TB",  u"Tabio"),
        (u"TS",  u"Tausa"),
        (u"TE",  u"Tena"),
        (u"TJ",  u"Tenjo"),
        (u"TY",  u"Tibacuy"),
        (u"TI",  u"Tibirita"),
        (u"TM",  u"Tocaima"),
        (u"TC",  u"Tocancipá"),
        (u"TP",  u"Topaipí"),
        (u"UL",  u"Ubalá"),
        (u"UQ",  u"Ubaque"),
        (u"UB",  u"Ubaté [, Villa de San Diego de]"),
        (u"UN",  u"Une"),
        (u"UT",  u"Utica"),
        (u"OS",  u"Venecia"),
        (u"VE",  u"Vergara"),
        (u"VN",  u"Vianí"),
        (u"VG",  u"Villagómez"),
        (u"VP",  u"Villapinzón"),
        (u"VL",  u"Villeta"),
        (u"VI",  u"Viotá"),
        (u"YA",  u"Yacopí"),
        (u"ZC",  u"Zipacón"),
        (u"ZQ",  u"Zipaquirá"),
        ]),

    ((u"COR", u"Córdoba"), [
        (u"AY",  u"Ayapel"),
        (u"BU",  u"Buenavista"),
        (u"CA",  u"Canalete"),
        (u"CE",  u"Cereté"),
        (u"CM",  u"Chimá"),
        (u"CN",  u"Chinú"),
        (u"CO",  u"Ciénaga de Oro"),
        (u"CT",  u"Cotorra"),
        (u"LA",  u"La Apartada"),
        (u"LO",  u"Lorica [, Santa Cruz de]"),
        (u"LC",  u"Los Córdobas"),
        (u"MM",  u"Momil"),
        (u"ML",  u"Montelíbano"),
        (u"MR",  u"Montería"),
        (u"MT",  u"Moñitos"),
        (u"PR",  u"Planeta Rica"),
        (u"PN",  u"Pueblo Nuevo"),
        (u"PE",  u"Puerto Escondido"),
        (u"PL",  u"Puerto Libertador"),
        (u"PU",  u"Purísima"),
        (u"SH",  u"Sahagún [, San Bernardino de]"),
        (u"SS",  u"San Andrés de Sotavento"),
        (u"SA",  u"San Antero"),
        (u"SB",  u"San Bernardo del Viento"),
        (u"SC",  u"San Carlos"),
        (u"SP",  u"San Pelayo"),
        (u"TI",  u"Tierralta"),
        (u"VA",  u"Valencia"),
        ]),

    ((u"DC", u"Distrito Capital"), [
        (u"SF",  u"Santafé de Bogotá"),
        ]),

    ((u"GUA", u"Guainía"), [
        (u"CA",  u"Cacahual"),
        (u"GU",  u"Guaviare"),
        (u"LG",  u"La Guadalupe"),
        (u"MO",  u"Morichal Nuevo"),
        (u"PA",  u"Pana Pana"),
        (u"PC",  u"Puerto Colombia"),
        (u"SF",  u"San Felipe"),
        (u"IN",  u"[Puerto] Inírida"),
        ]),

    ((u"GUV", u"Guaviare"), [
        (u"CA",  u"Calamar"),
        (u"ER",  u"El Retorno"),
        (u"MI",  u"Miraflores"),
        (u"SJ",  u"San José del Guaviare"),
        ]),

    ((u"HUI", u"Huila"), [
        (u"AC",  u"Acevedo"),
        (u"AG",  u"Agrado"),
        (u"AI",  u"Aipe"),
        (u"AL",  u"Algeciras"),
        (u"AM",  u"Altamira"),
        (u"BA",  u"Baraya"),
        (u"CA",  u"Campoalegre"),
        (u"CO",  u"Colombia"),
        (u"EL",  u"Elías"),
        (u"GA",  u"Garzón"),
        (u"GI",  u"Gigante"),
        (u"GU",  u"Guadalupe"),
        (u"HO",  u"Hobo"),
        (u"IQ",  u"Iquira"),
        (u"IS",  u"Isnos"),
        (u"LA",  u"La Argentina"),
        (u"LP",  u"La Plata"),
        (u"NE",  u"Neiva"),
        (u"NA",  u"Nátaga"),
        (u"OP",  u"Oporapa"),
        (u"PC",  u"Paicol"),
        (u"PM",  u"Palermo"),
        (u"PS",  u"Palestina"),
        (u"PI",  u"Pital"),
        (u"PT",  u"Pitalito"),
        (u"RI",  u"Rivera"),
        (u"SB",  u"Saladoblanco"),
        (u"SA",  u"San Agustín"),
        (u"SM",  u"Santa María"),
        (u"SU",  u"Suaza"),
        (u"TA",  u"Tarquí"),
        (u"TL",  u"Tello"),
        (u"TR",  u"Teruel"),
        (u"TS",  u"Tesalia"),
        (u"TI",  u"Timaná"),
        (u"VV",  u"Villavieja"),
        (u"YA",  u"Yaguará"),
        ]),

    ((u"LAG", u"La Guajira"), [
        (u"BA",  u"Barrancas"),
        (u"DB",  u"Dibulla"),
        (u"DS",  u"Distracción"),
        (u"EM",  u"El Molino"),
        (u"FO",  u"Fonseca"),
        (u"HN",  u"Hatonuevo"),
        (u"LJ",  u"La Jagua del Pilar"),
        (u"MC",  u"Maicao"),
        (u"MN",  u"Manaure"),
        (u"RI",  u"Riohacha"),
        (u"SJ",  u"San Juan del Cesar"),
        (u"UB",  u"Uribia"),
        (u"UM",  u"Urumita"),
        (u"VN",  u"Villanueva"),
        ]),

    ((u"MAG", u"Magdalena"), [
        (u"AL",  u"Algarrobo"),
        (u"AC",  u"Aracataca"),
        (u"AG",  u"Ariguaní"),
        (u"CE",  u"Cerro de San Antonio"),
        (u"CH",  u"Chivolo"),
        (u"CI",  u"Ciénaga"),
        (u"CO",  u"Concordia"),
        (u"EB",  u"El Banco"),
        (u"EP",  u"El Piñón"),
        (u"ER",  u"El Retén"),
        (u"FU",  u"Fundación"),
        (u"GU",  u"Guamal"),
        (u"PE",  u"Pedraza"),
        (u"PC",  u"Pijiño del Carmen"),
        (u"PI",  u"Pivijay"),
        (u"PL",  u"Plato"),
        (u"PV",  u"Pueblo Viejo"),
        (u"RE",  u"Remolino"),
        (u"SB",  u"Sabanas de San Angel"),
        (u"SL",  u"Salamina"),
        (u"SS",  u"San Sebastián de Buenavista"),
        (u"SZ",  u"San Zenón"),
        (u"SA",  u"Santa Ana"),
        (u"SM",  u"Santa Marta"),
        (u"SI",  u"Sitionuevo"),
        (u"TE",  u"Tenerife"),
        (u"ZB",  u"Zona Bananera"),
        ]),

    ((u"MET", u"Meta"), [
        (u"AC",  u"Acacías"),
        (u"BA",  u"Barranca de Upía"),
        (u"CA",  u"Cabuyaro"),
        (u"CN",  u"Castilla la Nueva"),
        (u"CB",  u"Cubarral [, San Luis de]"),
        (u"CM",  u"Cumaral"),
        (u"EV",  u"El Calvario"),
        (u"EC",  u"El Castillo"),
        (u"ED",  u"El Dorado"),
        (u"FO",  u"Fuente de Oro"),
        (u"GR",  u"Granada"),
        (u"GU",  u"Guamal"),
        (u"LM",  u"La Macarena"),
        (u"LU",  u"La Uribe"),
        (u"LE",  u"Lejanías"),
        (u"MA",  u"Mapiripán"),
        (u"ME",  u"Mesetas"),
        (u"PC",  u"Puerto Concordia"),
        (u"PG",  u"Puerto Gaitán"),
        (u"PL",  u"Puerto Lleras"),
        (u"PZ",  u"Puerto López"),
        (u"PR",  u"Puerto Rico"),
        (u"RE",  u"Restrepo"),
        (u"SC",  u"San Carlos de Guaroa"),
        (u"SA",  u"San Juan de Arama"),
        (u"SJ",  u"San Juanito"),
        (u"SM",  u"San Martín"),
        (u"VV",  u"Villavicencio"),
        (u"VH",  u"Vista Hermosa"),
        ]),

    ((u"NAR", u"Nariño"), [
        (u"AB",  u"Albán"),
        (u"AD",  u"Aldana"),
        (u"AN",  u"Ancuyá"),
        (u"AR",  u"Arboleda"),
        (u"BA",  u"Barbacoas"),
        (u"BE",  u"Belén"),
        (u"BU",  u"Buesaco"),
        (u"CH",  u"Chachagüí"),
        (u"CL",  u"Colón"),
        (u"CS",  u"Consacá"),
        (u"CN",  u"Contadero"),
        (u"CD",  u"Cuaspud"),
        (u"CU",  u"Cumbal"),
        (u"CT",  u"Cumbitara"),
        (u"CO",  u"Córdoba"),
        (u"EC",  u"El Charco"),
        (u"EP",  u"El Peñol"),
        (u"ER",  u"El Rosario"),
        (u"EL",  u"El Tablón [de Gomez]"),
        (u"ET",  u"El Tambo"),
        (u"FP",  u"Francisco Pizarro"),
        (u"FU",  u"Funes"),
        (u"GC",  u"Guachucal"),
        (u"GT",  u"Guaitarilla"),
        (u"GM",  u"Gualmatán"),
        (u"IL",  u"Iles"),
        (u"IM",  u"Imués"),
        (u"IP",  u"Ipiales"),
        (u"LC",  u"La Cruz"),
        (u"LF",  u"La Florida"),
        (u"LL",  u"La Llanada"),
        (u"LT",  u"La Tola"),
        (u"LU",  u"La Unión"),
        (u"LE",  u"Leiva"),
        (u"LI",  u"Linares"),
        (u"LO",  u"Los Andes"),
        (u"MG",  u"Magüí"),
        (u"ML",  u"Mallama"),
        (u"MO",  u"Mosquera"),
        (u"OH",  u"Olaya Herrera"),
        (u"OS",  u"Ospina"),
        (u"PA",  u"Pasto [, San Juan de]"),
        (u"PC",  u"Policarpa"),
        (u"PT",  u"Potosí"),
        (u"PR",  u"Providencia"),
        (u"PU",  u"Puerres"),
        (u"PP",  u"Pupiales"),
        (u"RI",  u"Ricaurte"),
        (u"RO",  u"Roberto Payán"),
        (u"SM",  u"Samaniego"),
        (u"SN",  u"San Bernardo"),
        (u"SL",  u"San Lorenzo"),
        (u"SP",  u"San Pablo"),
        (u"SC",  u"San Pedro de Cartago"),
        (u"SD",  u"Sandoná"),
        (u"SB",  u"Santa Bárbara"),
        (u"SZ",  u"Santa Cruz"),
        (u"SY",  u"Sapuyes"),
        (u"TN",  u"Taminango"),
        (u"TG",  u"Tangua"),
        (u"TC",  u"Tumaco"),
        (u"TQ",  u"Túquerres"),
        (u"YA",  u"Yacuanquer"),
        ]),

    ((u"NSA", u"Norte de Santander"), [
        (u"AB",  u"Abrego"),
        (u"AR",  u"Arboledas"),
        (u"BO",  u"Bochalema"),
        (u"BU",  u"Bucarasica"),
        (u"CH",  u"Chinácota"),
        (u"CT",  u"Chitagá"),
        (u"CV",  u"Convención"),
        (u"CL",  u"Cucutilla"),
        (u"CR",  u"Cáchira"),
        (u"CA",  u"Cácota"),
        (u"CC",  u"Cúcuta [, San José de]"),
        (u"DU",  u"Durania"),
        (u"EC",  u"El Carmen"),
        (u"ET",  u"El Tarra"),
        (u"EZ",  u"El Zulia"),
        (u"GR",  u"Gramalote"),
        (u"HA",  u"Hacarí"),
        (u"HE",  u"Herrán"),
        (u"LE",  u"La Esperanza"),
        (u"LP",  u"La Playa [de Belén]"),
        (u"LB",  u"Labateca"),
        (u"LS",  u"Los Patios"),
        (u"LO",  u"Lourdes"),
        (u"MU",  u"Mutiscua"),
        (u"OC",  u"Ocaña"),
        (u"PA",  u"Pamplona"),
        (u"PT",  u"Pamplonita"),
        (u"PS",  u"Puerto Santander"),
        (u"RA",  u"Ragonvalia"),
        (u"SZ",  u"Salazar [de Las Palmas]"),
        (u"SX",  u"San Calixto"),
        (u"SC",  u"San Cayetano"),
        (u"SG",  u"Santiago"),
        (u"SR",  u"Sardinata"),
        (u"SI",  u"Silos [, Santo Domingo de]"),
        (u"TE",  u"Teorama"),
        (u"TI",  u"Tibú"),
        (u"TO",  u"Toledo"),
        (u"VC",  u"Villa Caro"),
        (u"VR",  u"Villa del Rosario"),
        ]),

    ((u"PUT", u"Putumayo"), [
        (u"CO",  u"Colón"),
        (u"MO",  u"Mocoa [, San Miguel de]"),
        (u"OR",  u"Orito"),
        (u"PA",  u"Puerto Asís"),
        (u"PC",  u"Puerto Caicedo"),
        (u"PG",  u"Puerto Guzmán"),
        (u"PL",  u"Puerto Leguízamo"),
        (u"SF",  u"San Francisco"),
        (u"SM",  u"San Miguel"),
        (u"SA",  u"Santiago"),
        (u"SI",  u"Sibundoy"),
        (u"VA",  u"Valle del Guamuez"),
        (u"VG",  u"Villagarzón"),
        ]),

    ((u"QUI", u"Quindío"), [
        (u"AR",  u"Armenia"),
        (u"BU",  u"Buenavista"),
        (u"CA",  u"Calarcá"),
        (u"CI",  u"Circasia"),
        (u"CO",  u"Córdoba"),
        (u"FI",  u"Filandia"),
        (u"GE",  u"Génova"),
        (u"LT",  u"La Tebaida"),
        (u"MO",  u"Montenegro"),
        (u"PI",  u"Pijao"),
        (u"QU",  u"Quimbaya"),
        (u"SA",  u"Salento"),
        ]),

    ((u"RIS", u"Risaralda"), [
        (u"AP",  u"Apía"),
        (u"BA",  u"Balboa"),
        (u"BE",  u"Belén de Umbría"),
        (u"DO",  u"Dosquebradas"),
        (u"GU",  u"Guática"),
        (u"LC",  u"La Celia"),
        (u"LV",  u"La Virginia"),
        (u"MA",  u"Marsella"),
        (u"MI",  u"Mistrato"),
        (u"PE",  u"Pereira"),
        (u"PR",  u"Pueblo Rico"),
        (u"QU",  u"Quinchía"),
        (u"SR",  u"Santa Rosa de Cabal"),
        (u"SA",  u"Santuario"),
        ]),

    ((u"SAP", u"San Andrés y Providencia"), [
        (u"PR",  u"Providencia [y Santa Catalina]"),
        (u"SA",  u"San Andrés"),
        ]),

    ((u"SAN", u"Santander"), [
        (u"AG",  u"Aguada"),
        (u"AL",  u"Albania"),
        (u"AR",  u"Aratoca"),
        (u"BS",  u"Barbosa"),
        (u"BH",  u"Barichara"),
        (u"BB",  u"Barrancabermeja"),
        (u"BE",  u"Betulia"),
        (u"BO",  u"Bolívar"),
        (u"BU",  u"Bucaramanga"),
        (u"CB",  u"Cabrera"),
        (u"CA",  u"California"),
        (u"CJ",  u"Capitanejo"),
        (u"CS",  u"Carcasí"),
        (u"CE",  u"Cepitá"),
        (u"CR",  u"Cerrito"),
        (u"CL",  u"Charalá"),
        (u"CH",  u"Charta"),
        (u"CM",  u"Chimá"),
        (u"CP",  u"Chipatá"),
        (u"CI",  u"Cimitarra"),
        (u"CC",  u"Concepción"),
        (u"CF",  u"Confines"),
        (u"CN",  u"Contratación"),
        (u"CO",  u"Coromoro"),
        (u"CU",  u"Curití"),
        (u"EC",  u"El Carmen [de Chucurí]"),
        (u"EG",  u"El Guacamayo"),
        (u"EP",  u"El Peñon"),
        (u"EY",  u"El Playón"),
        (u"EN",  u"Encino"),
        (u"ES",  u"Enciso"),
        (u"FL",  u"Floridablanca"),
        (u"EF",  u"Florián"),
        (u"GL",  u"Galán"),
        (u"GI",  u"Girón"),
        (u"GC",  u"Guaca"),
        (u"GD",  u"Guadalupe"),
        (u"GP",  u"Guapotá"),
        (u"GV",  u"Guavatá"),
        (u"GA",  u"Gámbita"),
        (u"GU",  u"Güepsa"),
        (u"HA",  u"Hato"),
        (u"JM",  u"Jesús María"),
        (u"JO",  u"Jordán"),
        (u"LB",  u"La Belleza"),
        (u"LP",  u"La Paz"),
        (u"LN",  u"Landázuri"),
        (u"LE",  u"Lebrija"),
        (u"LS",  u"Los Santos"),
        (u"MC",  u"Macaravita"),
        (u"MZ",  u"Matanza"),
        (u"MG",  u"Mogotes"),
        (u"MO",  u"Molagavita"),
        (u"MA",  u"Málaga"),
        (u"OC",  u"Ocamonte"),
        (u"OI",  u"Oiba"),
        (u"ON",  u"Onzaga"),
        (u"PL",  u"Palmar"),
        (u"PS",  u"Palmas del Socorro"),
        (u"PD",  u"Piedecuesta"),
        (u"PI",  u"Pinchote"),
        (u"PN",  u"Puente Nacional"),
        (u"PP",  u"Puerto Parra"),
        (u"PW",  u"Puerto Wilches"),
        (u"PR",  u"Páramo"),
        (u"RI",  u"Rionegro"),
        (u"ST",  u"Sabana de Torres"),
        (u"SA",  u"San Andrés"),
        (u"SN",  u"San Benito"),
        (u"SG",  u"San Gil"),
        (u"SQ",  u"San Joaquín"),
        (u"SJ",  u"San José de Miranda"),
        (u"SM",  u"San Miguel"),
        (u"SV",  u"San Vicente de Chucurí"),
        (u"SB",  u"Santa Bárbara"),
        (u"SH",  u"Santa Helena [del Opón]"),
        (u"SI",  u"Simacota"),
        (u"SO",  u"Socorro"),
        (u"SU",  u"Suaita"),
        (u"SC",  u"Sucre"),
        (u"SR",  u"Suratá"),
        (u"TO",  u"Tona"),
        (u"VS",  u"Valle de San José"),
        (u"VT",  u"Vetas"),
        (u"VN",  u"Villanueva"),
        (u"VZ",  u"Vélez"),
        (u"ZA",  u"Zapatoca"),
        ]),

    ((u"SUC", u"Sucre"), [
        (u"BU",  u"Buenavista"),
        (u"CA",  u"Caimito"),
        (u"CH",  u"Chalán"),
        (u"CS",  u"Colosó"),
        (u"CZ",  u"Corozal"),
        (u"GA",  u"Galeras"),
        (u"GU",  u"Guarandá"),
        (u"LU",  u"La Unión [de Sucre]"),
        (u"LP",  u"Los Palmitos"),
        (u"MA",  u"Majagual"),
        (u"MO",  u"Morroa"),
        (u"OV",  u"Ovejas"),
        (u"PA",  u"Palmito [, San Antonio de]"),
        (u"SA",  u"Sampués"),
        (u"SB",  u"San Benito Abad"),
        (u"SJ",  u"San Juan de Betulia"),
        (u"SM",  u"San Marcos"),
        (u"SO",  u"San Onofre"),
        (u"SP",  u"San Pedro"),
        (u"SL",  u"Sincelejo"),
        (u"SI",  u"Sincé"),
        (u"SU",  u"Sucre"),
        (u"TV",  u"Toluviejo"),
        (u"TO",  u"Tolú"),
        ]),

    ((u"TOL", u"Tolima"), [
        (u"AJ",  u"Alpujarra"),
        (u"AV",  u"Alvarado"),
        (u"AM",  u"Ambalema"),
        (u"AN",  u"Anzoátegui"),
        (u"AR",  u"Armero"),
        (u"AT",  u"Ataco"),
        (u"CJ",  u"Cajamarca"),
        (u"CA",  u"Carmen de Apicalá"),
        (u"CB",  u"Casabianca"),
        (u"CH",  u"Chaparral"),
        (u"CL",  u"Coello"),
        (u"CY",  u"Coyaima"),
        (u"CU",  u"Cunday"),
        (u"DO",  u"Dolores"),
        (u"ES",  u"Espinal"),
        (u"FA",  u"Falán"),
        (u"FL",  u"Flandes"),
        (u"FR",  u"Fresno"),
        (u"GU",  u"Guamo"),
        (u"HE",  u"Herveo"),
        (u"HO",  u"Honda"),
        (u"IB",  u"Ibagué"),
        (u"IC",  u"Icononzo"),
        (u"LE",  u"Lérida"),
        (u"LI",  u"Líbano"),
        (u"MA",  u"Mariquita [, San Sebastian de]"),
        (u"ME",  u"Melgar"),
        (u"MU",  u"Murillo"),
        (u"NA",  u"Natagaima"),
        (u"OR",  u"Ortega"),
        (u"PA",  u"Palocabildo"),
        (u"PI",  u"Piedras"),
        (u"PL",  u"Planadas"),
        (u"PR",  u"Prado"),
        (u"PU",  u"Purificación"),
        (u"RI",  u"Rioblanco"),
        (u"RC",  u"Roncesvalles"),
        (u"RR",  u"Rovira"),
        (u"SD",  u"Saldaña"),
        (u"SA",  u"San Antonio"),
        (u"SL",  u"San Luís"),
        (u"SI",  u"Santa Isabel"),
        (u"SU",  u"Suárez"),
        (u"VS",  u"Valle de San Juan"),
        (u"VE",  u"Venadillo"),
        (u"VH",  u"Villahermosa"),
        (u"VR",  u"Villarrica"),
        ]),

    ((u"VAC", u"Valle del Cauca"), [
        (u"AL",  u"Alcalá"),
        (u"AD",  u"Andalucía"),
        (u"AN",  u"Ansermanuevo"),
        (u"AR",  u"Argelia"),
        (u"BO",  u"Bolívar"),
        (u"BV",  u"Buenaventura"),
        (u"BU",  u"Buga [,Guadalajara de]"),
        (u"BG",  u"Bugalagrande"),
        (u"CC",  u"Caicedonia"),
        (u"CL",  u"Cali [, Santiago de]"),
        (u"CM",  u"Calima"),
        (u"CN",  u"Candelaria"),
        (u"CR",  u"Cartago"),
        (u"DA",  u"Dagua"),
        (u"EC",  u"El Cairo"),
        (u"ET",  u"El Cerrito"),
        (u"ED",  u"El Dovio"),
        (u"EA",  u"El Águila"),
        (u"FL",  u"Florida"),
        (u"GI",  u"Ginebra"),
        (u"GU",  u"Guacarí"),
        (u"JA",  u"Jamundí"),
        (u"LC",  u"La Cumbre"),
        (u"LU",  u"La Unión"),
        (u"LV",  u"La Victoria"),
        (u"OB",  u"Obando"),
        (u"PA",  u"Palmira"),
        (u"PR",  u"Pradera"),
        (u"RE",  u"Restrepo"),
        (u"RI",  u"Riofrío"),
        (u"RO",  u"Roldanillo"),
        (u"SP",  u"San Pedro"),
        (u"SE",  u"Sevilla"),
        (u"TO",  u"Toro"),
        (u"TR",  u"Trujillo"),
        (u"TU",  u"Tuluá"),
        (u"UL",  u"Ulloa"),
        (u"VE",  u"Versalles"),
        (u"VI",  u"Vijes"),
        (u"YO",  u"Yotoco"),
        (u"YU",  u"Yumbo"),
        (u"ZA",  u"Zarzal"),
        ]),

    ((u"VAU", u"Vaupés"), [
        (u"CA",  u"Carurú"),
        (u"MI",  u"Mitú"),
        (u"PC",  u"Pacoa"),
        (u"PP",  u"Papunahua"),
        (u"TA",  u"Taraira"),
        (u"YA",  u"Yavaraté"),
        ]),

    ((u"VID", u"Vichada"), [
        (u"CU",  u"Cumaribo"),
        (u"LP",  u"La Primavera"),
        (u"PC",  u"Puerto Carreño"),
        (u"SR",  u"Santa Rosalía"),
        ]),
    ]

    
