# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

HN_regions = [
    ((u"AT", u"Atlántida"), [
        (u"AR",  u"Arizona"),
        (u"EP",  u"El Porvenir"),
        (u"ES",  u"Esparta"),
        (u"JU",  u"Jutiapa"),
        (u"LC",  u"La Ceiba"),
        (u"LM",  u"La Masica"),
        (u"SF",  u"San Francisco"),
        (u"TE",  u"Tela"),
        ]),

    ((u"CH", u"Choluteca"), [
        (u"AP",  u"Apacilagua"),
        (u"CH",  u"Choluteca"),
        (u"CM",  u"Concepción de Maria"),
        (u"DU",  u"Duyure"),
        (u"EC",  u"El Corpus"),
        (u"ET",  u"El Triunfo"),
        (u"MA",  u"Marcovia"),
        (u"MO",  u"Morolica"),
        (u"NA",  u"Namasigue"),
        (u"OR",  u"Orocuina"),
        (u"PE",  u"Pespire"),
        (u"SF",  u"San Antonio de Flores"),
        (u"SI",  u"San Isidro"),
        (u"SJ",  u"San José"),
        (u"SM",  u"San Marcos de Colón"),
        (u"SY",  u"Santa Ana de Yusguare"),
        ]),

    ((u"CL", u"Colón"), [
        (u"BA",  u"Balfate"),
        (u"BO",  u"Bonito Oriental"),
        (u"IR",  u"Iriona"),
        (u"LI",  u"Limón"),
        (u"SA",  u"Sabá"),
        (u"SF",  u"Santa Fé"),
        (u"SR",  u"Santa Rosa de Aguán"),
        (u"SO",  u"Sonaguera"),
        (u"TO",  u"Tocoa"),
        (u"TR",  u"Trujillo"),
        ]),

    ((u"CM", u"Comayagua"), [
        (u"AJ",  u"Ajuterique"),
        (u"CO",  u"Comayagua"),
        (u"ER",  u"El Rosario"),
        (u"ES",  u"Esquías"),
        (u"HU",  u"Humuya"),
        (u"LB",  u"La Libertad"),
        (u"LT",  u"La Trinidad"),
        (u"LA",  u"Lamaní"),
        (u"LJ",  u"Las Lajas"),
        (u"LE",  u"Lejamaní"),
        (u"ME",  u"Meámbar"),
        (u"MO",  u"Minas de Oro"),
        (u"OA",  u"Ojo de Agua"),
        (u"SJ",  u"San Jerónimo"),
        (u"SC",  u"San José de Comayagua"),
        (u"SP",  u"San José del Potrero"),
        (u"SL",  u"San Luis"),
        (u"SS",  u"San Sebastián"),
        (u"SI",  u"Siguatepeque"),
        (u"TA",  u"Taulabe"),
        (u"VS",  u"Villa de San Antonio"),
        ]),

    ((u"CP", u"Copán"), [
        (u"CA",  u"Cabañas"),
        (u"CN",  u"Concepción"),
        (u"CR",  u"Copán Ruinas"),
        (u"CQ",  u"Corquín"),
        (u"CU",  u"Cucuyagua"),
        (u"DO",  u"Dolores"),
        (u"DN",  u"Dulce Nombre"),
        (u"EP",  u"El Paraíso"),
        (u"FL",  u"Florida"),
        (u"LJ",  u"La Jigua"),
        (u"LU",  u"La Unión"),
        (u"NA",  u"Nueva Arcadia"),
        (u"SG",  u"San Agustín"),
        (u"SA",  u"San Antonio"),
        (u"SM",  u"San Jerónimo"),
        (u"SJ",  u"San José"),
        (u"SO",  u"San Juan de Opoa"),
        (u"SN",  u"San Nicolás"),
        (u"SP",  u"San Pedro"),
        (u"SR",  u"Santa Rita"),
        (u"SC",  u"Santa Rosa de Copán"),
        (u"TC",  u"Trinidad de Copán"),
        (u"VE",  u"Veracruz"),
        ]),

    ((u"CR", u"Cortés"), [
        (u"CH",  u"Choloma"),
        (u"LL",  u"La Lima"),
        (u"OM",  u"Omoa"),
        (u"PI",  u"Pimienta"),
        (u"PO",  u"Potrerillos"),
        (u"PC",  u"Puerto Cortés"),
        (u"SA",  u"San Antonio de Cortés"),
        (u"SF",  u"San Francisco de Yojoa"),
        (u"SM",  u"San Manuel"),
        (u"SP",  u"San Pedro Sula"),
        (u"SC",  u"Santa Cruz de Yojoa"),
        (u"VI",  u"Villanueva"),
        ]),

    ((u"EP", u"El Paraíso"), [
        (u"AL",  u"Alauca"),
        (u"DA",  u"Danlí"),
        (u"EP",  u"El Paraíso"),
        (u"GU",  u"Guinope"),
        (u"JA",  u"Jacaleapa"),
        (u"LI",  u"Liure"),
        (u"MO",  u"Morocelí"),
        (u"OR",  u"Oropolí"),
        (u"PO",  u"Potrerillos"),
        (u"SA",  u"San Antonio de Flores"),
        (u"SL",  u"San Lucas"),
        (u"SM",  u"San Matías"),
        (u"SO",  u"Soledad"),
        (u"TP",  u"Teupasenti"),
        (u"TX",  u"Texiguat"),
        (u"TR",  u"Trojes"),
        (u"VA",  u"Vado Ancho"),
        (u"YA",  u"Yauyupe"),
        (u"YU",  u"Yuscarán"),
        ]),

    ((u"FM", u"Francisco Morazán"), [
        (u"AL",  u"Alubarén"),
        (u"CE",  u"Cedros"),
        (u"CU",  u"Curarén"),
        (u"DC",  u"Distrito Central"),
        (u"EP",  u"El Porvenir"),
        (u"GU",  u"Guaimaca"),
        (u"LL",  u"La Libertad"),
        (u"LV",  u"La Venta"),
        (u"LE",  u"Lepaterique"),
        (u"MT",  u"Maraita"),
        (u"ML",  u"Marale"),
        (u"NA",  u"Nueva Armenia"),
        (u"OJ",  u"Ojojona"),
        (u"OR",  u"Orica"),
        (u"RE",  u"Reitoca"),
        (u"SG",  u"Sabanagrande"),
        (u"SO",  u"San Antonio de Oriente"),
        (u"SB",  u"San Buenaventura"),
        (u"SI",  u"San Ignacio"),
        (u"SJ",  u"San Juan de Flores"),
        (u"SM",  u"San Miguelito"),
        (u"SA",  u"Santa Ana"),
        (u"SL",  u"Santa Lucía"),
        (u"TL",  u"Talanga"),
        (u"TT",  u"Tatumbla"),
        (u"VA",  u"Valle de Ángeles"),
        (u"VC",  u"Vallecillo"),
        (u"VS",  u"Villa de San Francisco"),
        ]),

    ((u"GD", u"Gracias a Dios"), [
        (u"AH",  u"Ahuas"),
        (u"BL",  u"Brus Laguna"),
        (u"JF",  u"Juan Francisco Bulnes"),
        (u"PL",  u"Puerto Lempira"),
        (u"RV",  u"Ramón Villeda Morales"),
        (u"WA",  u"Wampusirpi"),
        ]),

    ((u"IN", u"Intibucá"), [
        (u"CA",  u"Camasca"),
        (u"CL",  u"Colomoncagua"),
        (u"CN",  u"Concepción"),
        (u"DO",  u"Dolores"),
        (u"IN",  u"Intibucá"),
        (u"JO",  u"Jesús de Otoro"),
        (u"LE",  u"La Esperanza"),
        (u"MD",  u"Magdalena"),
        (u"MS",  u"Masaguara"),
        (u"SA",  u"San Antonio"),
        (u"SF",  u"San Francisco de Opalaca"),
        (u"SI",  u"San Isidro"),
        (u"SJ",  u"San Juan"),
        (u"SS",  u"San Marcos de la Sierra"),
        (u"SM",  u"San Miguelito"),
        (u"SL",  u"Santa Lucía"),
        (u"YA",  u"Yamaranguila"),
        ]),

    ((u"IB", u"Islas de la Bahía"), [
        (u"GU",  u"Guanaja"),
        (u"JS",  u"José Santos Guardiola"),
        (u"RO",  u"Roatán"),
        (u"UT",  u"Utila"),
        ]),

    ((u"LP", u"La Paz"), [
        (u"AG",  u"Aguaqueterique"),
        (u"CB",  u"Cabañas"),
        (u"CN",  u"Cane"),
        (u"CH",  u"Chinacla"),
        (u"GU",  u"Guajiquiro"),
        (u"LP",  u"La Paz"),
        (u"LA",  u"Lauterique"),
        (u"MA",  u"Marcala"),
        (u"MO",  u"Mercedes de Oriente"),
        (u"OP",  u"Opatoro"),
        (u"SN",  u"San Antonio del Norte"),
        (u"SJ",  u"San José"),
        (u"SU",  u"San Juan"),
        (u"ST",  u"San Pedro de Tutule"),
        (u"SA",  u"Santa Ana"),
        (u"SE",  u"Santa Elena"),
        (u"SM",  u"Santa María"),
        (u"SP",  u"Santiago de Puringla"),
        (u"YA",  u"Yarula"),
        ]),

    ((u"LE", u"Lempira"), [
        (u"BE",  u"Belen"),
        (u"CA",  u"Candelaria"),
        (u"CO",  u"Cololaca"),
        (u"ER",  u"Erandique"),
        (u"GR",  u"Gracias"),
        (u"GC",  u"Gualcince"),
        (u"GT",  u"Guarita"),
        (u"LC",  u"La Campa"),
        (u"LI",  u"La Iguala"),
        (u"LU",  u"La Unión"),
        (u"LV",  u"La Virtud"),
        (u"LF",  u"Las Flores"),
        (u"LE",  u"Lepaera"),
        (u"MA",  u"Mapulaca"),
        (u"PI",  u"Piraera"),
        (u"SA",  u"San Andrés"),
        (u"SF",  u"San Francisco"),
        (u"SJ",  u"San Juan Guarita"),
        (u"SH",  u"San Manuel Colohete"),
        (u"SM",  u"San Marcos de Caiquín"),
        (u"SR",  u"San Rafael"),
        (u"SS",  u"San Sebastian"),
        (u"SC",  u"Santa Cruz"),
        (u"TG",  u"Talgua"),
        (u"TB",  u"Tambla"),
        (u"TO",  u"Tomalá"),
        (u"VA",  u"Valladolid"),
        (u"VI",  u"Virginia"),
        ]),

    ((u"OC", u"Ocotepeque"), [
        (u"BG",  u"Belén Gualcho"),
        (u"CO",  u"Concepción"),
        (u"DM",  u"Dolores Merendon"),
        (u"FR",  u"Fraternidad"),
        (u"LE",  u"La Encarnación"),
        (u"LL",  u"La Labor"),
        (u"LU",  u"Lucerna"),
        (u"ME",  u"Mercedes"),
        (u"OC",  u"Ocotepeque"),
        (u"SF",  u"San Fernando"),
        (u"SV",  u"San Francisco del Valle"),
        (u"SJ",  u"San Jorge"),
        (u"SM",  u"San Marcos"),
        (u"ST",  u"Santa Fé"),
        (u"SE",  u"Sensenti"),
        (u"SI",  u"Sinuapa"),
        ]),

    ((u"OL", u"Olancho"), [
        (u"CP",  u"Campamento"),
        (u"CT",  u"Catacamas"),
        (u"CO",  u"Concordia"),
        (u"DN",  u"Dulce Nombre de Culmí"),
        (u"ER",  u"El Rosario"),
        (u"EN",  u"Esquipulas del Norte"),
        (u"GL",  u"Gualaco"),
        (u"GR",  u"Guarizama"),
        (u"GT",  u"Guata"),
        (u"GY",  u"Guayape"),
        (u"JA",  u"Jano"),
        (u"JU",  u"Juticalpa"),
        (u"LU",  u"La Unión"),
        (u"MG",  u"Mangulile"),
        (u"MT",  u"Manto"),
        (u"PA",  u"Patuca"),
        (u"SA",  u"Salamá"),
        (u"SE",  u"San Esteban"),
        (u"SB",  u"San Francisco de Becerra"),
        (u"SP",  u"San Francisco de la Paz"),
        (u"SM",  u"Santa Maria del Real"),
        (u"SI",  u"Silca"),
        (u"YO",  u"Yocón"),
        ]),

    ((u"SB", u"Santa Bárbara"), [
        (u"AR",  u"Arada"),
        (u"AT",  u"Atima"),
        (u"AZ",  u"Azacualpa"),
        (u"CE",  u"Ceguaca"),
        (u"CH",  u"Chinda"),
        (u"CN",  u"Concepción del Norte"),
        (u"CS",  u"Concepción del Sur"),
        (u"EN",  u"El Nispero"),
        (u"GU",  u"Gualala"),
        (u"IL",  u"Ilama"),
        (u"LV",  u"Las Vegas"),
        (u"MA",  u"Macuelizo"),
        (u"NA",  u"Naranjito"),
        (u"NF",  u"Nueva Frontera"),
        (u"NC",  u"Nuevo Celilac"),
        (u"PE",  u"Petoa"),
        (u"PR",  u"Protección"),
        (u"QU",  u"Quimistán"),
        (u"SF",  u"San Francisco de Ojuera"),
        (u"SJ",  u"San José de Colinas"),
        (u"SL",  u"San Luis"),
        (u"SM",  u"San Marcos"),
        (u"SN",  u"San Nicolás"),
        (u"SP",  u"San Pedro Zacapa"),
        (u"SV",  u"San Vicente Centenario"),
        (u"SB",  u"Santa Bárbara"),
        (u"SR",  u"Santa Rita"),
        (u"TR",  u"Trinidad"),
        ]),

    ((u"VA", u"Valle"), [
        (u"AL",  u"Alianza"),
        (u"AM",  u"Amapala"),
        (u"AR",  u"Aramecina"),
        (u"CA",  u"Caridad"),
        (u"GO",  u"Goascorán"),
        (u"LA",  u"Langue"),
        (u"NA",  u"Nacaome"),
        (u"SF",  u"San Francisco de Coray"),
        (u"SL",  u"San Lorenzo"),
        ]),

    ((u"YO", u"Yoro"), [
        (u"AR",  u"Arenal"),
        (u"EN",  u"El Negrito"),
        (u"EP",  u"El Progreso"),
        (u"JO",  u"Jocón"),
        (u"MO",  u"Morazán"),
        (u"OL",  u"Olanchito"),
        (u"SR",  u"Santa Rita"),
        (u"SU",  u"Sulaco"),
        (u"VI",  u"Victoria"),
        (u"YT",  u"Yorito"),
        (u"YO",  u"Yoro"),
        ]),

]
