# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

JP_regions = [
    ((u"AI", u"Aichi"), [
        (u"AC",  u"Aichi"),
        (u"AM",  u"Ama"),
        (u"AN",  u"Anjo"),
        (u"AT",  u"Atsumi"),
        (u"BS",  u"Bisai"),
        (u"CR",  u"Chiryu"),
        (u"CG",  u"Chita"),
        (u"CS",  u"Chita"),
        (u"GM",  u"Gamagori"),
        (u"HG",  u"Haguri"),
        (u"HD",  u"Handa"),
        (u"HZ",  u"Hazu"),
        (u"HN",  u"Hekinan"),
        (u"HK",  u"Higashikamo"),
        (u"HI",  u"Hoi"),
        (u"IC",  u"Ichinomiya"),
        (u"IZ",  u"Inazawa"),
        (u"IY",  u"Inuyama"),
        (u"IW",  u"Iwakura"),
        (u"KR",  u"Kariya"),
        (u"KG",  u"Kasugai"),
        (u"KS",  u"Kitashitara"),
        (u"KM",  u"Komaki"),
        (u"KN",  u"Konan"),
        (u"MS",  u"Minamishitara"),
        (u"NG",  u"Nagoya"),
        (u"NK",  u"Nakashima"),
        (u"NM",  u"Nishikamo"),
        (u"NI",  u"Nishikasugai"),
        (u"NO",  u"Nishio"),
        (u"NS",  u"Nisshin"),
        (u"NW",  u"Niwa"),
        (u"NT",  u"Nukata"),
        (u"OB",  u"Obu"),
        (u"OK",  u"Okazaki"),
        (u"OW",  u"Owariasahi"),
        (u"ST",  u"Seto"),
        (u"SH",  u"Shinshiro"),
        (u"TM",  u"Takahama"),
        (u"TK",  u"Tokai"),
        (u"TN",  u"Tokoname"),
        (u"TY",  u"Toyoake"),
        (u"TH",  u"Toyohashi"),
        (u"TW",  u"Toyokawa"),
        (u"TT",  u"Toyota"),
        (u"TS",  u"Tsushima"),
        ]),

    ((u"AK", u"Akita"), [
        (u"AK",  u"Akita"),
        (u"HR",  u"Hiraka"),
        (u"HN",  u"Honjo"),
        (u"KW",  u"Kawabe"),
        (u"KG",  u"Kazuno"),
        (u"KS",  u"Kazuno"),
        (u"KK",  u"Kitaakita"),
        (u"MK",  u"Minamiakita"),
        (u"NS",  u"Noshiro"),
        (u"OD",  u"Odate"),
        (u"OG",  u"Oga"),
        (u"OC",  u"Ogachi"),
        (u"OM",  u"Omagari"),
        (u"SM",  u"Semboku"),
        (u"YM",  u"Yamamoto"),
        (u"YK",  u"Yokote"),
        (u"YR",  u"Yuri"),
        (u"YZ",  u"Yuzawa"),
        ]),

    ((u"AO", u"Aomori"), [
        (u"AM",  u"Aomori"),
        (u"GS",  u"Goshogawara"),
        (u"HC",  u"Hachinohe"),
        (u"HT",  u"Higashitsugaru"),
        (u"HR",  u"Hirosaki"),
        (u"KM",  u"Kamikita"),
        (u"KT",  u"Kitatsugaru"),
        (u"KR",  u"Kuroishi"),
        (u"MT",  u"Minamitsugaru"),
        (u"MS",  u"Misawa"),
        (u"MU",  u"Mutsu"),
        (u"NK",  u"Nakatsugaru"),
        (u"NT",  u"Nishitsugaru"),
        (u"SN",  u"Sannohe"),
        (u"SH",  u"Shimokita"),
        (u"TW",  u"Towada"),
        ]),

    ((u"CH", u"Chiba"), [
        (u"AB",  u"Abiko"),
        (u"AS",  u"Asahi"),
        (u"AW",  u"Awa"),
        (u"CB",  u"Chiba"),
        (u"CE",  u"Chosei"),
        (u"CH",  u"Choshi"),
        (u"FN",  u"Funabashi"),
        (u"FT",  u"Futtsu"),
        (u"HK",  u"Higashikatsushika"),
        (u"IH",  u"Ichihara"),
        (u"IK",  u"Ichikawa"),
        (u"IB",  u"Inba"),
        (u"IZ",  u"Inzai"),
        (u"IS",  u"Isumi"),
        (u"KJ",  u"Kaijo"),
        (u"KY",  u"Kamagaya"),
        (u"KW",  u"Kamogawa"),
        (u"KS",  u"Kashiwa"),
        (u"KT",  u"Katori"),
        (u"KU",  u"Katsuura"),
        (u"KM",  u"Kimitsu"),
        (u"KR",  u"Kisarazu"),
        (u"MT",  u"Matsudo"),
        (u"MB",  u"Mobara"),
        (u"NG",  u"Nagareyama"),
        (u"NS",  u"Narashino"),
        (u"NT",  u"Narita"),
        (u"ND",  u"Noda"),
        (u"SK",  u"Sakura"),
        (u"SM",  u"Sambu"),
        (u"SW",  u"Sawara"),
        (u"SD",  u"Sodegaura"),
        (u"SS",  u"Sosa"),
        (u"TT",  u"Tateyama"),
        (u"TG",  u"Togane"),
        (u"UR",  u"Urayasu"),
        (u"YM",  u"Yachimata"),
        (u"YY",  u"Yachiyo"),
        (u"YK",  u"Yokaichiba"),
        (u"YT",  u"Yotsukaido"),
        ]),

    ((u"EH", u"Ehime"), [
        (u"HW",  u"Higashiuwa"),
        (u"HJ",  u"Hojo"),
        (u"IM",  u"Imabari"),
        (u"IS",  u"Iyo"),
        (u"IG",  u"Iyo"),
        (u"IY",  u"Iyomishima"),
        (u"KM",  u"Kamiukena"),
        (u"KW",  u"Kawanoe"),
        (u"KT",  u"Kita"),
        (u"KU",  u"Kitauwa"),
        (u"MT",  u"Matsuyama"),
        (u"MW",  u"Minamiuwa"),
        (u"NH",  u"Niihama"),
        (u"NW",  u"Nishiuwa"),
        (u"OC",  u"Ochi"),
        (u"ON",  u"Onsen"),
        (u"OZ",  u"Ozu"),
        (u"SJ",  u"Saijo"),
        (u"SH",  u"Shuso"),
        (u"TO",  u"Toyo"),
        (u"UM",  u"Uma"),
        (u"UW",  u"Uwajima"),
        (u"YW",  u"Yawatahama"),
        ]),

    ((u"FI", u"Fukui"), [
        (u"AS",  u"Asuwa"),
        (u"FK",  u"Fukui"),
        (u"IM",  u"Imadate"),
        (u"KT",  u"Katsuyama"),
        (u"MK",  u"Mikata"),
        (u"NJ",  u"Nanjo"),
        (u"NY",  u"Nyu"),
        (u"OB",  u"Obama"),
        (u"OI",  u"Oi"),
        (u"OG",  u"Ono"),
        (u"OS",  u"Ono"),
        (u"OY",  u"Onyu"),
        (u"SB",  u"Sabae"),
        (u"SK",  u"Sakai"),
        (u"TK",  u"Takefu"),
        (u"TS",  u"Tsuruga"),
        (u"YS",  u"Yoshida"),
        ]),

    ((u"FO", u"Fukuoka"), [
        (u"AM",  u"Amagi"),
        (u"AS",  u"Asakura"),
        (u"BZ",  u"Buzen"),
        (u"CG",  u"Chikugo"),
        (u"CJ",  u"Chikujo"),
        (u"CS",  u"Chikushi"),
        (u"CN",  u"Chikushino"),
        (u"DZ",  u"Dazaifu"),
        (u"FK",  u"Fukuoka"),
        (u"IZ",  u"Iizuka"),
        (u"IT",  u"Itoshima"),
        (u"KH",  u"Kaho"),
        (u"KS",  u"Kasuga"),
        (u"KY",  u"Kasuya"),
        (u"KK",  u"Kitakyushu"),
        (u"KG",  u"Koga"),
        (u"KT",  u"Kurate"),
        (u"KM",  u"Kurume"),
        (u"MB",  u"Maebaru"),
        (u"MI",  u"Mii"),
        (u"MK",  u"Miike"),
        (u"MY",  u"Miyako"),
        (u"MZ",  u"Mizuma"),
        (u"MG",  u"Munakata"),
        (u"MS",  u"Munakata"),
        (u"NK",  u"Nakama"),
        (u"NG",  u"Nogata"),
        (u"OG",  u"Ogori"),
        (u"OK",  u"Okawa"),
        (u"OM",  u"Omuta"),
        (u"ON",  u"Onga"),
        (u"OJ",  u"Onojo"),
        (u"TS",  u"Tagawa"),
        (u"TG",  u"Tagawa"),
        (u"UK",  u"Ukiha"),
        (u"YM",  u"Yamada"),
        (u"YT",  u"Yamato"),
        (u"YG",  u"Yame"),
        (u"YS",  u"Yame"),
        (u"YN",  u"Yanagawa"),
        (u"YK",  u"Yukuhashi"),
        ]),

    ((u"FS", u"Fukushima"), [
        (u"AD",  u"Adachi"),
        (u"AZ",  u"Aizuwakamatsu"),
        (u"DT",  u"Date"),
        (u"FK",  u"Fukushima"),
        (u"FT",  u"Futaba"),
        (u"HR",  u"Haramachi"),
        (u"HS",  u"Higashishirakawa"),
        (u"II",  u"Ishikawa"),
        (u"IK",  u"Iwaki"),
        (u"IS",  u"Iwase"),
        (u"KW",  u"Kawanuma"),
        (u"KZ",  u"Kitaaizu"),
        (u"KK",  u"Kitakata"),
        (u"KR",  u"Koriyama"),
        (u"MZ",  u"Minamiaizu"),
        (u"NH",  u"Nihommatsu"),
        (u"NS",  u"Nishishirakawa"),
        (u"ON",  u"Onuma"),
        (u"SH",  u"Shirakawa"),
        (u"SS",  u"Soma"),
        (u"SG",  u"Soma"),
        (u"SK",  u"Sukagawa"),
        (u"TM",  u"Tamura"),
        (u"YM",  u"Yama"),
        ]),

    ((u"GF", u"Gifu"), [
        (u"AN",  u"Anpachi"),
        (u"EG",  u"Ena"),
        (u"ES",  u"Ena"),
        (u"FW",  u"Fuwa"),
        (u"GF",  u"Gifu"),
        (u"GJ",  u"Gujo"),
        (u"HS",  u"Hashima"),
        (u"HG",  u"Hashima"),
        (u"IB",  u"Ibi"),
        (u"KZ",  u"Kaizu"),
        (u"KK",  u"Kakamigahara"),
        (u"KM",  u"Kamo"),
        (u"KG",  u"Kani"),
        (u"KS",  u"Kani"),
        (u"MS",  u"Mashita"),
        (u"MN",  u"Mino"),
        (u"MK",  u"Minokamo"),
        (u"MZ",  u"Mizunami"),
        (u"MT",  u"Motosu"),
        (u"MG",  u"Mugi"),
        (u"NK",  u"Nakatsugawa"),
        (u"OG",  u"Ogaki"),
        (u"ON",  u"Ono"),
        (u"SK",  u"Seki"),
        (u"TJ",  u"Tajimi"),
        (u"TK",  u"Takayama"),
        (u"TS",  u"Toki"),
        (u"TG",  u"Toki"),
        (u"YM",  u"Yamagata"),
        (u"YR",  u"Yoro"),
        (u"YS",  u"Yoshiki"),
        ]),

    ((u"GM", u"Gumma"), [
        (u"AG",  u"Agatsuma"),
        (u"AN",  u"Annaka"),
        (u"FJ",  u"Fujioka"),
        (u"GM",  u"Gumma"),
        (u"IS",  u"Isesaki"),
        (u"KN",  u"Kanra"),
        (u"KR",  u"Kiryu"),
        (u"KG",  u"Kitagumma"),
        (u"MB",  u"Maebashi"),
        (u"NT",  u"Nitta"),
        (u"NM",  u"Numata"),
        (u"OR",  u"Ora"),
        (u"OT",  u"Ota"),
        (u"SW",  u"Sawa"),
        (u"ST",  u"Seta"),
        (u"SH",  u"Shibukawa"),
        (u"TK",  u"Takasaki"),
        (u"TA",  u"Tano"),
        (u"TT",  u"Tatebayashi"),
        (u"TM",  u"Tomioka"),
        (u"TO",  u"Tone"),
        (u"US",  u"Usui"),
        (u"YM",  u"Yamada"),
        ]),

    ((u"HS", u"Hiroshima"), [
        (u"AK",  u"Aki"),
        (u"AS",  u"Ashina"),
        (u"FC",  u"Fuchu"),
        (u"FS",  u"Fukayasu"),
        (u"FM",  u"Fukuyama"),
        (u"FT",  u"Futami"),
        (u"HT",  u"Hatsukaichi"),
        (u"HB",  u"Hiba"),
        (u"HH",  u"Higashihiroshima"),
        (u"HR",  u"Hiroshima"),
        (u"IN",  u"Innoshima"),
        (u"JN",  u"Jinseki"),
        (u"KM",  u"Kamo"),
        (u"KN",  u"Konu"),
        (u"KR",  u"Kure"),
        (u"MH",  u"Mihara"),
        (u"MT",  u"Mitsugi"),
        (u"MS",  u"Miyoshi"),
        (u"NM",  u"Numakuma"),
        (u"ON",  u"Onomichi"),
        (u"OT",  u"Otake"),
        (u"SK",  u"Saeki"),
        (u"SR",  u"Sera"),
        (u"SH",  u"Shobara"),
        (u"TA",  u"Takata"),
        (u"TH",  u"Takehara"),
        (u"TT",  u"Toyota"),
        (u"YM",  u"Yamagata"),
        ]),

    ((u"HK", u"Hokkaido"), [
        (u"AC",  u"Abashiri"),
        (u"AS",  u"Abashiri"),
        (u"AK",  u"Akabira"),
        (u"AH",  u"Asahikawa"),
        (u"AB",  u"Ashibetsu"),
        (u"BB",  u"Bibai"),
        (u"CH",  u"Chitose"),
        (u"DT",  u"Date"),
        (u"EB",  u"Ebetsu"),
        (u"EN",  u"Eniwa"),
        (u"FK",  u"Fukagawa"),
        (u"FR",  u"Furano"),
        (u"HK",  u"Hakodate"),
        (u"HD",  u"Hidaka"),
        (u"HM",  u"Hiyama"),
        (u"IB",  u"Iburi"),
        (u"IS",  u"Ishikari"),
        (u"IC",  u"Ishikari"),
        (u"IW",  u"Iwamizawa"),
        (u"KK",  u"Kamikawa"),
        (u"KH",  u"Kitahiroshima"),
        (u"KM",  u"Kitami"),
        (u"KC",  u"Kushiro"),
        (u"KS",  u"Kushiro"),
        (u"MK",  u"Mikasa"),
        (u"MM",  u"Mombetsu"),
        (u"MR",  u"Muroran"),
        (u"NR",  u"Nayoro"),
        (u"NC",  u"Nemuro"),
        (u"NS",  u"Nemuro"),
        (u"NB",  u"Noboribetsu"),
        (u"OB",  u"Obihiro"),
        (u"OS",  u"Oshima"),
        (u"OT",  u"Otaru"),
        (u"RS",  u"Rumoi"),
        (u"RC",  u"Rumoi"),
        (u"SP",  u"Sapporo"),
        (u"SH",  u"Shibetsu"),
        (u"SB",  u"Shiribeshi"),
        (u"SR",  u"Sorachi"),
        (u"SY",  u"Soya"),
        (u"SN",  u"Sunagawa"),
        (u"TK",  u"Takikawa"),
        (u"TC",  u"Tokachi"),
        (u"TM",  u"Tomakomai"),
        (u"UT",  u"Utashinai"),
        (u"WK",  u"Wakkanai"),
        (u"YB",  u"Yubari"),
        ]),

    ((u"HG", u"Hyogo"), [
        (u"AI",  u"Aioi"),
        (u"AK",  u"Akashi"),
        (u"AG",  u"Ako"),
        (u"AS",  u"Ako"),
        (u"AM",  u"Amagasaki"),
        (u"AA",  u"Asago"),
        (u"AY",  u"Ashiya"),
        (u"HK",  u"Hikami"),
        (u"HM",  u"Himeji"),
        (u"IB",  u"Ibo"),
        (u"IT",  u"Itami"),
        (u"IZ",  u"Izushi"),
        (u"KK",  u"Kako"),
        (u"KG",  u"Kakogawa"),
        (u"KZ",  u"Kanzaki"),
        (u"KS",  u"Kasai"),
        (u"KT",  u"Kato"),
        (u"KA",  u"Kawabe"),
        (u"KW",  u"Kawanishi"),
        (u"KN",  u"Kinosaki"),
        (u"KB",  u"Kobe"),
        (u"MH",  u"Mihara"),
        (u"MT",  u"Mikata"),
        (u"MK",  u"Miki"),
        (u"MN",  u"Mino"),
        (u"NN",  u"Nishinomiya"),
        (u"NW",  u"Nishiwaki"),
        (u"ON",  u"Ono"),
        (u"SN",  u"Sanda"),
        (u"SS",  u"Sasayama"),
        (u"SY",  u"Sayo"),
        (u"SK",  u"Shikama"),
        (u"SH",  u"Shiso"),
        (u"SM",  u"Sumoto"),
        (u"TK",  u"Taka"),
        (u"TR",  u"Takarazuka"),
        (u"TG",  u"Takasago"),
        (u"TT",  u"Tatsuno"),
        (u"TY",  u"Toyooka"),
        (u"TS",  u"Tsuna"),
        (u"YB",  u"Yabu"),
        ]),

    ((u"IB", u"Ibaraki"), [
        (u"HB",  u"Higashiibaraki"),
        (u"HT",  u"Hitachi"),
        (u"HN",  u"Hitachinaka"),
        (u"HO",  u"Hitachiota"),
        (u"IN",  u"Inashiki"),
        (u"IS",  u"Ishioka"),
        (u"IW",  u"Iwai"),
        (u"KM",  u"Kasama"),
        (u"KG",  u"Kashima"),
        (u"KS",  u"Kashima"),
        (u"KB",  u"Kitaibaraki"),
        (u"KT",  u"Kitasoma"),
        (u"KO",  u"Koga"),
        (u"KJ",  u"Kuji"),
        (u"MB",  u"Makabe"),
        (u"MT",  u"Mito"),
        (u"MK",  u"Mitsukaido"),
        (u"NK",  u"Naka"),
        (u"NM",  u"Namegata"),
        (u"NH",  u"Niihari"),
        (u"NB",  u"Nishiibaraki"),
        (u"RG",  u"Ryugasaki"),
        (u"SS",  u"Sashima"),
        (u"SD",  u"Shimodate"),
        (u"ST",  u"Shimotsuma"),
        (u"TA",  u"Taga"),
        (u"TK",  u"Takahagi"),
        (u"TR",  u"Toride"),
        (u"TC",  u"Tsuchiura"),
        (u"TS",  u"Tsukuba"),
        (u"TG",  u"Tsukuba"),
        (u"US",  u"Ushiku"),
        (u"YS",  u"Yuki"),
        (u"YG",  u"Yuki"),
        ]),

    ((u"IS", u"Ishikawa"), [
        (u"EN",  u"Enuma"),
        (u"FG",  u"Fugeshi"),
        (u"HS",  u"Hakui"),
        (u"HG",  u"Hakui"),
        (u"IS",  u"Ishikawa"),
        (u"KG",  u"Kaga"),
        (u"KH",  u"Kahoku"),
        (u"KN",  u"Kanazawa"),
        (u"KS",  u"Kashima"),
        (u"KM",  u"Komatsu"),
        (u"MT",  u"Matto"),
        (u"NN",  u"Nanao"),
        (u"NM",  u"Nomi"),
        (u"SS",  u"Suzu"),
        (u"SG",  u"Suzu"),
        (u"WJ",  u"Wajima"),
        ]),

    ((u"IW", u"Iwate"), [
        (u"ES",  u"Esashi"),
        (u"HM",  u"Hanamaki"),
        (u"HN",  u"Hienuki"),
        (u"HW",  u"Higashiiwai"),
        (u"IC",  u"Ichinoseki"),
        (u"IS",  u"Isawa"),
        (u"IW",  u"Iwate"),
        (u"KI",  u"Kamaishi"),
        (u"KH",  u"Kamihei"),
        (u"KS",  u"Kesen"),
        (u"KK",  u"Kitakami"),
        (u"KJ",  u"Kuji"),
        (u"KN",  u"Kunohe"),
        (u"MK",  u"Miyako"),
        (u"MZ",  u"Mizusawa"),
        (u"MR",  u"Morioka"),
        (u"NG",  u"Ninohe"),
        (u"NS",  u"Ninohe"),
        (u"NW",  u"Nishiiwai"),
        (u"OF",  u"Ofunato"),
        (u"RK",  u"Rikuzentakata"),
        (u"SH",  u"Shimohei"),
        (u"SW",  u"Shiwa"),
        (u"TN",  u"Tono"),
        (u"WG",  u"Waga"),
        ]),

    ((u"KG", u"Kagawa"), [
        (u"AT",  u"Ayauta"),
        (u"KG",  u"Kagawa"),
        (u"KN",  u"Kanonji"),
        (u"KT",  u"Kita"),
        (u"MR",  u"Marugame"),
        (u"MT",  u"Mitoyo"),
        (u"NK",  u"Nakatado"),
        (u"OK",  u"Okawa"),
        (u"SK",  u"Sakaide"),
        (u"SH",  u"Shozu"),
        (u"TK",  u"Takamatsu"),
        (u"ZN",  u"Zentsuji"),
        ]),

    ((u"KS", u"Kagoshima"), [
        (u"AR",  u"Aira"),
        (u"AK",  u"Akune"),
        (u"HK",  u"Hioki"),
        (u"IS",  u"Ibusuki"),
        (u"IG",  u"Ibusuki"),
        (u"IA",  u"Isa"),
        (u"IZ",  u"Izumi"),
        (u"IM",  u"Izumi"),
        (u"KG",  u"Kagoshima"),
        (u"KS",  u"Kagoshima"),
        (u"KN",  u"Kanoya"),
        (u"KD",  u"Kaseda"),
        (u"KW",  u"Kawanabe"),
        (u"KT",  u"Kimotsuki"),
        (u"KK",  u"Kokubu"),
        (u"KM",  u"Kumage"),
        (u"KU",  u"Kushikino"),
        (u"MK",  u"Makurazaki"),
        (u"NZ",  u"Naze"),
        (u"NN",  u"Nishinoomote"),
        (u"OK",  u"Okuchi"),
        (u"OS",  u"Oshima"),
        (u"ST",  u"Satsuma"),
        (u"SN",  u"Sendai"),
        (u"SO",  u"So"),
        (u"TR",  u"Tarumizu"),
        ]),

    ((u"KN", u"Kanagawa"), [
        (u"AK",  u"Aiko"),
        (u"AG",  u"Ashigarakami"),
        (u"AS",  u"Ashigarashimo"),
        (u"AT",  u"Atsugi"),
        (u"AY",  u"Ayase"),
        (u"CH",  u"Chigasaki"),
        (u"EB",  u"Ebina"),
        (u"FJ",  u"Fujisawa"),
        (u"HD",  u"Hadano"),
        (u"HR",  u"Hiratsuka"),
        (u"IS",  u"Isehara"),
        (u"KM",  u"Kamakura"),
        (u"KW",  u"Kawasaki"),
        (u"KZ",  u"Koza"),
        (u"MA",  u"Minamiashigara"),
        (u"MG",  u"Miura"),
        (u"MS",  u"Miura"),
        (u"NK",  u"Naka"),
        (u"OD",  u"Odawara"),
        (u"SG",  u"Sagamihara"),
        (u"TS",  u"Tsukui"),
        (u"YM",  u"Yamato"),
        (u"YH",  u"Yokohama"),
        (u"YS",  u"Yokosuka"),
        (u"ZM",  u"Zama"),
        (u"ZS",  u"Zushi"),
        ]),

    ((u"KC", u"Kochi"), [
        (u"AW",  u"Agawa"),
        (u"AG",  u"Aki"),
        (u"AS",  u"Aki"),
        (u"HT",  u"Hata"),
        (u"KM",  u"Kami"),
        (u"KC",  u"Kochi"),
        (u"MR",  u"Muroto"),
        (u"NG",  u"Nagaoka"),
        (u"NK",  u"Nakamura"),
        (u"NN",  u"Nankoku"),
        (u"SK",  u"Sukumo"),
        (u"SS",  u"Susaki"),
        (u"TK",  u"Takaoka"),
        (u"TS",  u"Tosa"),
        (u"TG",  u"Tosa"),
        (u"TZ",  u"Tosashimizu"),
        ]),

    ((u"KM", u"Kumamoto"), [
        (u"AM",  u"Amakusa"),
        (u"AR",  u"Arao"),
        (u"AK",  u"Ashikita"),
        (u"AS",  u"Aso"),
        (u"HT",  u"Hitoyoshi"),
        (u"HN",  u"Hondo"),
        (u"KM",  u"Kamimashiki"),
        (u"KT",  u"Kamoto"),
        (u"KG",  u"Kikuchi"),
        (u"KS",  u"Kikuchi"),
        (u"KA",  u"Kuma"),
        (u"KU",  u"Kumamoto"),
        (u"MN",  u"Minamata"),
        (u"SH",  u"Shimomashiki"),
        (u"TS",  u"Tamana"),
        (u"TG",  u"Tamana"),
        (u"UB",  u"Ushibuka"),
        (u"US",  u"Uto"),
        (u"UG",  u"Uto"),
        (u"YM",  u"Yamaga"),
        (u"YG",  u"Yatsushiro"),
        (u"YS",  u"Yatsushiro"),
        ]),

    ((u"KY", u"Kyoto"), [
        (u"AM",  u"Amata"),
        (u"AB",  u"Ayabe"),
        (u"FK",  u"Fukuchiyama"),
        (u"FN",  u"Funai"),
        (u"JY",  u"Joyo"),
        (u"KM",  u"Kameoka"),
        (u"KA",  u"Kasa"),
        (u"KK",  u"Kitakuwada"),
        (u"KU",  u"Kumano"),
        (u"KS",  u"Kuse"),
        (u"KN",  u"Kyotanabe"),
        (u"KT",  u"Kyoto"),
        (u"MZ",  u"Maizuru"),
        (u"MY",  u"Miyazu"),
        (u"MK",  u"Muko"),
        (u"NG",  u"Nagaokakyo"),
        (u"NK",  u"Naka"),
        (u"OT",  u"Otokuni"),
        (u"SR",  u"Soraku"),
        (u"TK",  u"Takeno"),
        (u"TS",  u"Tsuzuki"),
        (u"UJ",  u"Uji"),
        (u"YW",  u"Yawata"),
        (u"YS",  u"Yosa"),
        ]),

    ((u"ME", u"Mie"), [
        (u"AG",  u"Age"),
        (u"AM",  u"Ayama"),
        (u"HS",  u"Hisai"),
        (u"IC",  u"Ichishi"),
        (u"II",  u"Iinan"),
        (u"IN",  u"Inabe"),
        (u"IS",  u"Ise"),
        (u"KY",  u"Kameyama"),
        (u"KM",  u"Kitamuro"),
        (u"KN",  u"Kumano"),
        (u"KG",  u"Kuwana"),
        (u"KS",  u"Kuwana"),
        (u"MT",  u"Matsusaka"),
        (u"MI",  u"Mie"),
        (u"MM",  u"Minamimuro"),
        (u"NB",  u"Nabari"),
        (u"NG",  u"Naga"),
        (u"OW",  u"Owase"),
        (u"SH",  u"Shima"),
        (u"SS",  u"Suzuka"),
        (u"SG",  u"Suzuka"),
        (u"TK",  u"Taki"),
        (u"TB",  u"Toba"),
        (u"TS",  u"Tsu"),
        (u"UN",  u"Ueno"),
        (u"WT",  u"Watarai"),
        (u"YK",  u"Yokkaichi"),
        ]),

    ((u"MG", u"Miyagi"), [
        (u"FR",  u"Furukawa"),
        (u"IG",  u"Igu"),
        (u"IS",  u"Ishinomaki"),
        (u"IW",  u"Iwanuma"),
        (u"KK",  u"Kakuda"),
        (u"KM",  u"Kami"),
        (u"KT",  u"Katta"),
        (u"KS",  u"Kesennuma"),
        (u"KH",  u"Kurihara"),
        (u"KR",  u"Kurokawa"),
        (u"MG",  u"Miyagi"),
        (u"MN",  u"Mono"),
        (u"MT",  u"Motoyoshi"),
        (u"NT",  u"Natori"),
        (u"OS",  u"Oshika"),
        (u"SN",  u"Sendai"),
        (u"SB",  u"Shibata"),
        (u"SD",  u"Shida"),
        (u"SO",  u"Shiogama"),
        (u"SR",  u"Shiroishi"),
        (u"TG",  u"Tagajo"),
        (u"TT",  u"Tamatsukuri"),
        (u"TD",  u"Toda"),
        (u"TM",  u"Tome"),
        (u"WT",  u"Watari"),
        ]),

    ((u"MZ", u"Miyazaki"), [
        (u"EB",  u"Ebino"),
        (u"HM",  u"Higashimorokata"),
        (u"HS",  u"Higashiusuki"),
        (u"HG",  u"Hyuga"),
        (u"KM",  u"Kitamorokata"),
        (u"KB",  u"Kobayashi"),
        (u"KY",  u"Koyu"),
        (u"KS",  u"Kushima"),
        (u"MN",  u"Minaminaka"),
        (u"MK",  u"Miyakonojo"),
        (u"MG",  u"Miyazaki"),
        (u"MS",  u"Miyazaki"),
        (u"NC",  u"Nichinan"),
        (u"NM",  u"Nishimorokata"),
        (u"NS",  u"Nishiusuki"),
        (u"NB",  u"Nobeoka"),
        (u"ST",  u"Saito"),
        ]),

    ((u"NN", u"Nagano"), [
        (u"CI",  u"Chiisagata"),
        (u"CN",  u"Chino"),
        (u"HN",  u"Hanishina"),
        (u"HC",  u"Higashichikuma"),
        (u"ID",  u"Iida"),
        (u"IM",  u"Iiyama"),
        (u"IN",  u"Ina"),
        (u"KI",  u"Kamiina"),
        (u"KM",  u"Kamiminochi"),
        (u"KT",  u"Kamitakai"),
        (u"KS",  u"Kiso"),
        (u"KZ",  u"Kitaazumi"),
        (u"KK",  u"Kitasaku"),
        (u"KG",  u"Komagane"),
        (u"KR",  u"Komoro"),
        (u"KO",  u"Koshoku"),
        (u"MT",  u"Matsumoto"),
        (u"MZ",  u"Minamiazumi"),
        (u"MS",  u"Minamisaku"),
        (u"NG",  u"Nagano"),
        (u"NK",  u"Nakano"),
        (u"OK",  u"Okaya"),
        (u"OM",  u"Omachi"),
        (u"SK",  u"Saku"),
        (u"SR",  u"Sarashina"),
        (u"SI",  u"Shimoina"),
        (u"SM",  u"Shimominochi"),
        (u"ST",  u"Shimotakai"),
        (u"SJ",  u"Shiojiri"),
        (u"SS",  u"Suwa"),
        (u"SG",  u"Suwa"),
        (u"SZ",  u"Suzaka"),
        (u"UD",  u"Ueda"),
        ]),

    ((u"NS", u"Nagasaki"), [
        (u"FK",  u"Fukue"),
        (u"HS",  u"Higashisonogi"),
        (u"HR",  u"Hirado"),
        (u"IK",  u"Iki"),
        (u"IS",  u"Isahaya"),
        (u"KM",  u"Kitamatsuura"),
        (u"KT",  u"Kitatakaki"),
        (u"MT",  u"Matsuura"),
        (u"MM",  u"Minamimatsuura"),
        (u"MK",  u"Minamitakaki"),
        (u"NG",  u"Nagasaki"),
        (u"NS",  u"Nishisonogi"),
        (u"OM",  u"Omura"),
        (u"SS",  u"Sasebo"),
        (u"SH",  u"Shimabara"),
        (u"TS",  u"Tsushima"),
        ]),

    ((u"NR", u"Nara"), [
        (u"GJ",  u"Gojo"),
        (u"GS",  u"Gose"),
        (u"IS",  u"Ikoma"),
        (u"IG",  u"Ikoma"),
        (u"KB",  u"Kashiba"),
        (u"KH",  u"Kashihara"),
        (u"KK",  u"Kitakatsuragi"),
        (u"NR",  u"Nara"),
        (u"SK",  u"Sakurai"),
        (u"SH",  u"Shiki"),
        (u"SM",  u"Soekami"),
        (u"TK",  u"Takaichi"),
        (u"TN",  u"Tenri"),
        (u"UD",  u"Uda"),
        (u"YB",  u"Yamabe"),
        (u"YR",  u"Yamatokoriyama"),
        (u"YT",  u"Yamatotakada"),
        (u"YS",  u"Yoshino"),
        ]),

    ((u"NI", u"Niigata"), [
        (u"AR",  u"Arai"),
        (u"GS",  u"Gosen"),
        (u"HM",  u"Higashikambara"),
        (u"HK",  u"Higashikubiki"),
        (u"IT",  u"Itoigawa"),
        (u"IW",  u"Iwafune"),
        (u"JT",  u"Joetsu"),
        (u"KM",  u"Kamo"),
        (u"KR",  u"Kariwa"),
        (u"KW",  u"Kashiwazaki"),
        (u"KK",  u"Kitakambara"),
        (u"KN",  u"Kitauonuma"),
        (u"KS",  u"Koshi"),
        (u"MK",  u"Minamikambara"),
        (u"MN",  u"Minamiuonuma"),
        (u"MT",  u"Mitsuke"),
        (u"MR",  u"Murakami"),
        (u"NG",  u"Nagaoka"),
        (u"NM",  u"Nakakambara"),
        (u"NK",  u"Nakakubiki"),
        (u"NU",  u"Nakauonuma"),
        (u"NT",  u"Niigata"),
        (u"NS",  u"Niitsu"),
        (u"NB",  u"Nishikambara"),
        (u"NI",  u"Nishikubiki"),
        (u"OJ",  u"Ojiya"),
        (u"RT",  u"Ryotsu"),
        (u"SD",  u"Sado"),
        (u"SJ",  u"Sanjo"),
        (u"ST",  u"Santo"),
        (u"SB",  u"Shibata"),
        (u"SR",  u"Shirone"),
        (u"TC",  u"Tochio"),
        (u"TK",  u"Tokamachi"),
        (u"TY",  u"Toyosaka"),
        (u"TS",  u"Tsubame"),
        ]),

    ((u"OT", u"Oita"), [
        (u"BP",  u"Beppu"),
        (u"BN",  u"Bungotakada"),
        (u"HM",  u"Hayami"),
        (u"HK",  u"Higashikunisaki"),
        (u"HS",  u"Hita"),
        (u"HG",  u"Hita"),
        (u"KM",  u"Kitaamabe"),
        (u"KT",  u"Kitsuki"),
        (u"KS",  u"Kusu"),
        (u"MM",  u"Minamiamabe"),
        (u"NT",  u"Nakatsu"),
        (u"NR",  u"Naoiri"),
        (u"NK",  u"Nishikunisaki"),
        (u"OG",  u"Oita"),
        (u"OS",  u"Oita"),
        (u"ON",  u"Ono"),
        (u"SK",  u"Saiki"),
        (u"SH",  u"Shimoge"),
        (u"TK",  u"Taketa"),
        (u"TS",  u"Tsukumi"),
        (u"US",  u"Usa"),
        (u"UG",  u"Usa"),
        (u"UK",  u"Usuki"),
        ]),

    ((u"OY", u"Okayama"), [
        (u"AD",  u"Aida"),
        (u"AK",  u"Akaiwa"),
        (u"AS",  u"Asakuchi"),
        (u"AT",  u"Atetsu"),
        (u"BZ",  u"Bizen"),
        (u"IB",  u"Ibara"),
        (u"JB",  u"Jobo"),
        (u"KS",  u"Kasaoka"),
        (u"KT",  u"Katsuta"),
        (u"KW",  u"Kawakami"),
        (u"KB",  u"Kibi"),
        (u"KJ",  u"Kojima"),
        (u"KM",  u"Kume"),
        (u"KR",  u"Kurashiki"),
        (u"MN",  u"Maniwa"),
        (u"MT",  u"Mitsu"),
        (u"NM",  u"Niimi"),
        (u"OD",  u"Oda"),
        (u"OY",  u"Okayama"),
        (u"OK",  u"Oku"),
        (u"SH",  u"Shitsuki"),
        (u"SJ",  u"Soja"),
        (u"TK",  u"Takahashi"),
        (u"TN",  u"Tamano"),
        (u"TM",  u"Tomata"),
        (u"TS",  u"Tsukubo"),
        (u"TY",  u"Tsuyama"),
        (u"WK",  u"Wake"),
        ]),

    ((u"ON", u"Okinawa"), [
        (u"GN",  u"Ginowan"),
        (u"GS",  u"Gushikawa"),
        (u"HR",  u"Hirara"),
        (u"IG",  u"Ishigaki"),
        (u"IK",  u"Ishikawa"),
        (u"IT",  u"Itoman"),
        (u"KN",  u"Kunigami"),
        (u"MK",  u"Miyako"),
        (u"NG",  u"Nago"),
        (u"NH",  u"Naha"),
        (u"NK",  u"Nakagami"),
        (u"OK",  u"Okinawa"),
        (u"SH",  u"Shimajiri"),
        (u"UR",  u"Urasoe"),
        (u"YM",  u"Yaeyama"),
        ]),

    ((u"OS", u"Osaka"), [
        (u"DT",  u"Daito"),
        (u"FJ",  u"Fujiidera"),
        (u"HB",  u"Habikino"),
        (u"HN",  u"Hannan"),
        (u"HS",  u"Higashiosaka"),
        (u"HR",  u"Hirakata"),
        (u"IB",  u"Ibaraki"),
        (u"IK",  u"Ikeda"),
        (u"IZ",  u"Izumi"),
        (u"IO",  u"Izumiotsu"),
        (u"IS",  u"Izumisano"),
        (u"KM",  u"Kadoma"),
        (u"KZ",  u"Kaizuka"),
        (u"KR",  u"Kashiwara"),
        (u"KT",  u"Katano"),
        (u"KW",  u"Kawachinagano"),
        (u"KD",  u"Kishiwada"),
        (u"MT",  u"Matsubara"),
        (u"MK",  u"Minamikawachi"),
        (u"MN",  u"Minoh"),
        (u"MS",  u"Mishima"),
        (u"MR",  u"Moriguchi"),
        (u"NG",  u"Neyagawa"),
        (u"OS",  u"Osaka"),
        (u"OY",  u"Osakasayama"),
        (u"SK",  u"Sakai"),
        (u"SM",  u"Semboku"),
        (u"SS",  u"Sennan"),
        (u"SG",  u"Sennan"),
        (u"ST",  u"Settsu"),
        (u"SH",  u"Shijonawate"),
        (u"SU",  u"Suita"),
        (u"TI",  u"Takaishi"),
        (u"TT",  u"Takatsuki"),
        (u"TN",  u"Tondabayashi"),
        (u"TK",  u"Toyonaka"),
        (u"TY",  u"Toyono"),
        (u"YA",  u"Yao"),
        ]),

    ((u"SG", u"Saga"), [
        (u"FJ",  u"Fujitsu"),
        (u"HM",  u"Higashimatsuura"),
        (u"IM",  u"Imari"),
        (u"KN",  u"Kanzaki"),
        (u"KR",  u"Karatsu"),
        (u"KA",  u"Kashima"),
        (u"KI",  u"Kishima"),
        (u"MK",  u"Miyaki"),
        (u"NM",  u"Nishimatsuura"),
        (u"OG",  u"Ogi"),
        (u"SS",  u"Saga"),
        (u"SG",  u"Saga"),
        (u"TE",  u"Takeo"),
        (u"TU",  u"Taku"),
        (u"TS",  u"Tosu"),
        ]),

    ((u"ST", u"Saitama"), [
        (u"AG",  u"Ageo"),
        (u"AS",  u"Asaka"),
        (u"CG",  u"Chichibu"),
        (u"CS",  u"Chichibu"),
        (u"FJ",  u"Fujimi"),
        (u"FK",  u"Fukaya"),
        (u"GD",  u"Gyoda"),
        (u"HN",  u"Hanno"),
        (u"HY",  u"Hanyu"),
        (u"HS",  u"Hasuda"),
        (u"HT",  u"Hatogaya"),
        (u"HD",  u"Hidaka"),
        (u"HM",  u"Higashimatsuyama"),
        (u"HK",  u"Hiki"),
        (u"HJ",  u"Honjo"),
        (u"IS",  u"Iruma"),
        (u"IG",  u"Iruma"),
        (u"IW",  u"Iwatsuki"),
        (u"KF",  u"Kamifukuoka"),
        (u"KB",  u"Kasukabe"),
        (u"KW",  u"Kawagoe"),
        (u"KH",  u"Kawaguchi"),
        (u"KZ",  u"Kazo"),
        (u"KA",  u"Kitaadachi"),
        (u"KK",  u"Kitakatsushika"),
        (u"KM",  u"Kitamoto"),
        (u"KS",  u"Kitasaitama"),
        (u"KD",  u"Kodama"),
        (u"KN",  u"Konosu"),
        (u"KO",  u"Koshigaya"),
        (u"KU",  u"Kuki"),
        (u"KG",  u"Kumagaya"),
        (u"MS",  u"Minamisaitama"),
        (u"MT",  u"Misato"),
        (u"NZ",  u"Niiza"),
        (u"OK",  u"Okegawa"),
        (u"OM",  u"Omiya"),
        (u"OS",  u"Osato"),
        (u"SD",  u"Sakado"),
        (u"ST",  u"Satte"),
        (u"SM",  u"Sayama"),
        (u"SH",  u"Shiki"),
        (u"SK",  u"Soka"),
        (u"TD",  u"Toda"),
        (u"TK",  u"Tokorozawa"),
        (u"TS",  u"Tsurugashima"),
        (u"UR",  u"Urawa"),
        (u"WK",  u"Wako"),
        (u"WR",  u"Warabi"),
        (u"YS",  u"Yashio"),
        (u"YN",  u"Yono"),
        (u"YK",  u"Yoshikawa"),
        ]),

    ((u"SH", u"Shiga"), [
        (u"EC",  u"Echi"),
        (u"GM",  u"Gamo"),
        (u"HZ",  u"Higashiazai"),
        (u"HK",  u"Hikone"),
        (u"IK",  u"Ika"),
        (u"IN",  u"Inukami"),
        (u"KN",  u"Kanzaki"),
        (u"KK",  u"Koka"),
        (u"KR",  u"Kurita"),
        (u"KS",  u"Kusatsu"),
        (u"MR",  u"Moriyama"),
        (u"NG",  u"Nagahama"),
        (u"OM",  u"Omihachiman"),
        (u"OT",  u"Otsu"),
        (u"SK",  u"Sakata"),
        (u"SH",  u"Shiga"),
        (u"TK",  u"Takashima"),
        (u"YS",  u"Yasu"),
        (u"YK",  u"Yokaichi"),
        ]),

    ((u"SM", u"Shimane"), [
        (u"GT",  u"Gotsu"),
        (u"HM",  u"Hamada"),
        (u"HK",  u"Hikawa"),
        (u"HR",  u"Hirata"),
        (u"IS",  u"Iishi"),
        (u"IZ",  u"Izumo"),
        (u"KN",  u"Kanoashi"),
        (u"MS",  u"Masuda"),
        (u"MT",  u"Matsue"),
        (u"MN",  u"Mino"),
        (u"NK",  u"Naka"),
        (u"NM",  u"Nima"),
        (u"NT",  u"Nita"),
        (u"NG",  u"Nogi"),
        (u"OC",  u"Ochi"),
        (u"OD",  u"Oda"),
        (u"OH",  u"Ohara"),
        (u"OK",  u"Oki"),
        (u"YS",  u"Yasugi"),
        (u"YT",  u"Yatsuka"),
        ]),

    ((u"SZ", u"Shizuoka"), [
        (u"AT",  u"Atami"),
        (u"FS",  u"Fuji"),
        (u"FG",  u"Fuji"),
        (u"FE",  u"Fujieda"),
        (u"FN",  u"Fujinomiya"),
        (u"FK",  u"Fukuroi"),
        (u"GT",  u"Gotemba"),
        (u"HB",  u"Haibara"),
        (u"HK",  u"Hamakita"),
        (u"HM",  u"Hamamatsu"),
        (u"HN",  u"Hamana"),
        (u"IH",  u"Ihara"),
        (u"IN",  u"Inasa"),
        (u"IT",  u"Ito"),
        (u"IS",  u"Iwata"),
        (u"IG",  u"Iwata"),
        (u"KK",  u"Kakegawa"),
        (u"KM",  u"Kamo"),
        (u"KS",  u"Kosai"),
        (u"MS",  u"Mishima"),
        (u"NM",  u"Numazu"),
        (u"OG",  u"Ogasa"),
        (u"SD",  u"Shida"),
        (u"SH",  u"Shimada"),
        (u"SZ",  u"Shimizu"),
        (u"SM",  u"Shimoda"),
        (u"SK",  u"Shizuoka"),
        (u"SC",  u"Shuchi"),
        (u"SN",  u"Sunto"),
        (u"SS",  u"Susono"),
        (u"TG",  u"Tagata"),
        (u"TN",  u"Tenryu"),
        (u"YZ",  u"Yaizu"),
        ]),

    ((u"TC", u"Tochigi"), [
        (u"AK",  u"Ashikaga"),
        (u"AS",  u"Aso"),
        (u"HG",  u"Haga"),
        (u"IM",  u"Imaichi"),
        (u"KM",  u"Kamitsuga"),
        (u"KN",  u"Kanuma"),
        (u"KW",  u"Kawachi"),
        (u"KR",  u"Kuroiso"),
        (u"MK",  u"Mooka"),
        (u"NS",  u"Nasu"),
        (u"NK",  u"Nikko"),
        (u"OT",  u"Otawara"),
        (u"OM",  u"Oyama"),
        (u"SN",  u"Sano"),
        (u"ST",  u"Shimotsuga"),
        (u"SO",  u"Shioya"),
        (u"TC",  u"Tochigi"),
        (u"UT",  u"Utsunomiya"),
        (u"YT",  u"Yaita"),
        ]),

    ((u"TS", u"Tokushima"), [
        (u"AN",  u"Anan"),
        (u"AW",  u"Awa"),
        (u"IT",  u"Itano"),
        (u"KF",  u"Kaifu"),
        (u"KT",  u"Katsuura"),
        (u"KM",  u"Komatsushima"),
        (u"MM",  u"Mima"),
        (u"MS",  u"Miyoshi"),
        (u"MD",  u"Myodo"),
        (u"MZ",  u"Myozai"),
        (u"NK",  u"Naka"),
        (u"NR",  u"Naruto"),
        (u"OE",  u"Oe"),
        (u"TK",  u"Tokushima"),
        ]),

    ((u"TK", u"Tokyo"), [
        (u"AR",  u"Akiruno"),
        (u"AS",  u"Akishima"),
        (u"CH",  u"Chofu"),
        (u"FC",  u"Fuchu"),
        (u"FS",  u"Fussa"),
        (u"HJ",  u"Hachijo"),
        (u"HO",  u"Hachioji"),
        (u"HR",  u"Hamura"),
        (u"HK",  u"Higashikurume"),
        (u"HM",  u"Higashimurayama"),
        (u"HY",  u"Higashiyamato"),
        (u"HN",  u"Hino"),
        (u"HA",  u"Hoya"),
        (u"IN",  u"Inagi"),
        (u"KS",  u"Kiyose"),
        (u"KD",  u"Kodaira"),
        (u"KG",  u"Koganei"),
        (u"KK",  u"Kokubunji"),
        (u"KM",  u"Komae"),
        (u"KN",  u"Kunitachi"),
        (u"MC",  u"Machida"),
        (u"MT",  u"Mitaka"),
        (u"MK",  u"Miyake"),
        (u"MM",  u"Musashimurayama"),
        (u"MS",  u"Musashino"),
        (u"NT",  u"Nishitama"),
        (u"OG",  u"Ogasawara"),
        (u"OM",  u"Ome"),
        (u"OS",  u"Oshima"),
        (u"TC",  u"Tachikawa"),
        (u"TM",  u"Tama"),
        (u"TN",  u"Tanashi"),
        (u"TK",  u"Tokyo"),
        ]),

    ((u"TT", u"Tottori"), [
        (u"HN",  u"Hino"),
        (u"IW",  u"Iwami"),
        (u"KT",  u"Ketaka"),
        (u"KR",  u"Kurayoshi"),
        (u"SH",  u"Saihaku"),
        (u"SK",  u"Sakaiminato"),
        (u"TH",  u"Tohaku"),
        (u"TT",  u"Tottori"),
        (u"YZ",  u"Yazu"),
        (u"YN",  u"Yonago"),
        ]),

    ((u"TY", u"Toyama"), [
        (u"HT",  u"Higashitonami"),
        (u"HM",  u"Himi"),
        (u"IM",  u"Imizu"),
        (u"KM",  u"Kaminiikawa"),
        (u"KR",  u"Kurobe"),
        (u"NK",  u"Nakaniikawa"),
        (u"NM",  u"Namerikawa"),
        (u"NE",  u"Nei"),
        (u"NT",  u"Nishitonami"),
        (u"OB",  u"Oyabe"),
        (u"SH",  u"Shimoniikawa"),
        (u"SM",  u"Shinminato"),
        (u"TK",  u"Takaoka"),
        (u"TN",  u"Tonami"),
        (u"TM",  u"Toyama"),
        (u"UZ",  u"Uozu"),
        ]),

    ((u"WK", u"Wakayama"), [
        (u"AG",  u"Arida"),
        (u"AS",  u"Arida"),
        (u"GB",  u"Gobo"),
        (u"HS",  u"Hashimoto"),
        (u"HD",  u"Hidaka"),
        (u"HM",  u"Higashimuro"),
        (u"IT",  u"Ito"),
        (u"KN",  u"Kainan"),
        (u"KS",  u"Kaiso"),
        (u"NG",  u"Naga"),
        (u"NM",  u"Nishimuro"),
        (u"SH",  u"Shingu"),
        (u"TN",  u"Tanabe"),
        (u"WK",  u"Wakayama"),
        ]),

    ((u"YT", u"Yamagata"), [
        (u"AK",  u"Akumi"),
        (u"HM",  u"Higashimurayama"),
        (u"HN",  u"Higashine"),
        (u"HK",  u"Higashiokitama"),
        (u"HT",  u"Higashitagawa"),
        (u"KY",  u"Kaminoyama"),
        (u"KM",  u"Kitamurayama"),
        (u"MG",  u"Mogami"),
        (u"MR",  u"Murayama"),
        (u"NG",  u"Nagai"),
        (u"NN",  u"Nanyo"),
        (u"NM",  u"Nishimurayama"),
        (u"NK",  u"Nishiokitama"),
        (u"NT",  u"Nishitagawa"),
        (u"OB",  u"Obanazawa"),
        (u"SG",  u"Sagae"),
        (u"SK",  u"Sakata"),
        (u"SH",  u"Shinjo"),
        (u"TN",  u"Tendo"),
        (u"TS",  u"Tsuruoka"),
        (u"YM",  u"Yamagata"),
        (u"YN",  u"Yonezawa"),
        ]),

    ((u"YC", u"Yamaguchi"), [
        (u"AB",  u"Abu"),
        (u"AS",  u"Asa"),
        (u"HG",  u"Hagi"),
        (u"HK",  u"Hikari"),
        (u"HF",  u"Hofu"),
        (u"IW",  u"Iwakuni"),
        (u"KD",  u"Kudamatsu"),
        (u"KG",  u"Kuga"),
        (u"KM",  u"Kumage"),
        (u"MG",  u"Mine"),
        (u"MS",  u"Mine"),
        (u"NG",  u"Nagato"),
        (u"ON",  u"Onoda"),
        (u"OS",  u"Oshima"),
        (u"OT",  u"Otsu"),
        (u"SB",  u"Saba"),
        (u"SS",  u"Shimonoseki"),
        (u"SN",  u"Shinnanyo"),
        (u"TK",  u"Tokuyama"),
        (u"TR",  u"Toyoura"),
        (u"TS",  u"Tsuno"),
        (u"UB",  u"Ube"),
        (u"YM",  u"Yamaguchi"),
        (u"YN",  u"Yanai"),
        (u"YS",  u"Yoshiki"),
        ]),

    ((u"YN", u"Yamanashi"), [
        (u"EN",  u"Enzan"),
        (u"FJ",  u"Fujiyoshida"),
        (u"HM",  u"Higashiyamanashi"),
        (u"HT",  u"Higashiyatsushiro"),
        (u"KK",  u"Kitakoma"),
        (u"KT",  u"Kitatsuru"),
        (u"KF",  u"Kofu"),
        (u"MK",  u"Minamikoma"),
        (u"MT",  u"Minamitsuru"),
        (u"NK",  u"Nakakoma"),
        (u"NR",  u"Nirasaki"),
        (u"NT",  u"Nishiyatsushiro"),
        (u"OT",  u"Otsuki"),
        (u"TS",  u"Tsuru"),
        (u"YM",  u"Yamanashi"),
        ]),

]
