# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# Korea (south)
KR_regions = [
    ((u'PU',  u'Busan'), [
        (u"01",    u"Buk-gu (북구; 北區)"),
        (u"02",    u"Busanjin-gu (부산진구; 釜山鎭區)"),
        (u"03",    u"Dong-gu (동구; 東區)"),
        (u"04",    u"Dongnae-gu (동래구; 東萊區)"),
        (u"05",    u"Gangseo-gu (강서구; 江西區)"),
        (u"06",    u"Geumjeong-gu (금정구; 金井區)"),
        (u"07",    u"Haeundae-gu (해운대구; 海雲臺區)"),
        (u"08",    u"Jung-gu (중구; 中區)"),
        (u"09",    u"Nam-gu (남구; 南區)"),
        (u"10",    u"Saha-gu (사하구; 沙下區)"),
        (u"11",    u"Sasang-gu (사상구; 沙上區)"),
        (u"12",    u"Seo-gu (서구; 西區)"),
        (u"13",    u"Suyeong-gu (수영구; 水營區)"),
        (u"14",    u"Yeongdo-gu (영도구; 影島區)"),
        (u"15",    u"Yeonje-gu (연제구; 蓮堤區)"),
        (u"16",    u"Gijang-gun (기장군; 機張郡)"),        
        ]),
    ((u'GB',  u'Chungcheongbuk-do'), [
        (u"01",    u"Boeun (보은군, 報恩郡)"),
        (u"02",    u"Cheongju (청주시, 淸州市, capital)"),
        (u"03",    u"Cheongwon (청원군, 淸原郡)"),
        (u"04",    u"Chungju (충주시, 忠州市)"),
        (u"05",    u"Danyang (단양군, 丹陽郡)"),
        (u"06",    u"Eumseong (음성군, 陰城郡)"),
        (u"07",    u"Goesan (괴산군, 槐山郡)"),
        (u"08",    u"Jecheon (제천시, 堤川市)"),
        (u"09",    u"Jincheon (진천군, 鎭川郡)"),
        (u"10",    u"Okcheon (옥천군, 沃川郡)"),
        (u"11",    u"Jeungpyeong (증평군; 曾坪郡)"),
        (u"12",    u"Yeongdong (영동군, 永同郡)"),
        ]),
    ((u'GN',  u'Chungcheongnam-do'), [
                (u"XX",    u"Asan (아산시, 牙山市)"),
        (u"01",    u"Boryeong (보령시, 保寧市)"),
        (u"02",    u"Buyeo (부여군, 扶餘郡)"),
        (u"03",    u"Cheonan (천안시, 天安市)"),
        (u"04",    u"Cheongyang (청양군, 青陽郡)"),
        (u"05",    u"Dangjin (당진군, 唐津郡)"),
        (u"06",    u"Geumsan (금산군, 錦山郡)"),
        (u"07",    u"Gongju (공주시, 公州市)"),
        (u"08",    u"Gyeryong (계룡시, 鷄龍市)"),
        (u"09",    u"Hongseong (홍성군, 洪城郡)"),
        (u"10",    u"Nonsan (논산시, 論山市)"),
        (u"11",    u"Seocheon (서천군, 舒川郡)"),
        (u"12",    u"Seosan (서산시, 瑞山市)"),
        (u"13",    u"Taean (태안군, 泰安郡)"),
        (u"14",    u"Yeongi (연기군, 燕岐郡)"),
        (u"15",    u"Yesan (예산군, 禮山郡)"),
        ]),
    ((u'TG',  u'Daegu'), [
        (u"01",    u"Jung-gu (중구, 中區)"),
        (u"02",    u"Dong-gu (동구, 東區)"),
        (u"03",    u"Seo-gu (서구, 西區)"),
        (u"04",    u"Nam-gu (남구, 南區)"),
        (u"05",    u"Buk-gu (북구, 北區)"),
        (u"06",    u"Suseong-gu (수성구, 壽城區)"),
        (u"07",    u"Dalseo-gu (달서구, 達西區)"),
        (u"08",    u"Dalseong-gun (달성군, 達城郡)"),
        ]),
    ((u'TJ',  u'Daejeon'), [
        (u"01",    u"Daedeok-gu (대덕구; 大德區)"),
        (u"02",    u"Dong-gu (동구; 東區)"),
        (u"03",    u"Jung-gu (중구; 中區)"),
        (u"04",    u"Seo-gu (서구; 西區)"),
        (u"05",    u"Yuseong-gu (유성구; 儒城區)"),
        ]),
    ((u'KW',  u'Gangwon-do'), [
        (u"01",    u"Cheorwon (철원군, 鐵原郡)"),
        (u"02",    u"Chuncheon (춘천시, 春川市, capital)"),
        (u"03",    u"Donghae (동해시, 東海市)"),
        (u"04",    u"Gangneung (강릉시, 江陵市)"),
        (u"05",    u"Goseong (고성군, 高城郡)"),
        (u"06",    u"Hoengseong (횡성군, 橫城郡)"),
        (u"07",    u"Hongcheon (홍천군, 洪川郡)"),
        (u"08",    u"Hwacheon (화천군, 華川郡)"),
        (u"09",    u"Inje (인제군, 麟蹄郡)"),
        (u"10",    u"Jeongseon (정선군, 旌善郡)"),
        (u"11",    u"Pyeongchang (평창군, 平昌郡)"),
        (u"12",    u"Samcheok (삼척시, 三陟市)"),
        (u"13",    u"Sokcho (속초시, 束草市)"),
        (u"14",    u"Taebaek (태백시, 太白市)"),
        (u"15",    u"Wonju (원주시, 原州市)"),
        (u"16",    u"Yanggu (양구군, 楊口郡)"),
        (u"17",    u"Yangyang (양양군, 襄陽郡)"),
        (u"18",    u"Yeongwol (영월군, 寧越郡)"),        
        ]),
    ((u'KJ',  u'Gwangju'), [
        (u"01",    u"Buk-gu (북구; 北區)"),
        (u"02",    u"Dong-gu (동구; 東區)"),
        (u"03",    u"Gwangsan-gu (광산구; 光山區)"),
        (u"04",    u"Nam-gu (남구; 南區)"),
        (u"05",    u"Seo-gu (서구; 西區)"),        
        ]),
    ((u'KG',  u'Gyeonggi-do'), [
        (u"01",    u"Suwon (수원시, 水原市, capital)"),
        (u"02",    u"Ansan (안산시, 安山市)"),
        (u"03",    u"Anseong (안성시, 安城市)"),
        (u"04",    u"Anyang (안양시, 安養市)"),
        (u"05",    u"Bucheon (부천시, 富川市)"),
        (u"06",    u"Dongducheon (동두천시, 東豆川市)"),
        (u"07",    u"Gimpo (김포시, 金浦市)"),
        (u"08",    u"Goyang (고양시, 高陽市)"),
        (u"09",    u"Gunpo (군포시, 軍浦市)"),
        (u"10",    u"Guri (구리시, 九里市)"),
        (u"11",    u"Gwacheon (과천시, 果川市)"),
        (u"12",    u"Gwangju (광주시, 廣州市)"),
        (u"13",    u"Gwangmyeong (광명시, 光明市)"),
        (u"14",    u"Hanam (하남시, 河南市)"),
        (u"15",    u"Hwaseong (화성시, 華城市)"),
        (u"16",    u"Icheon (이천시, 利川市)"),
        (u"17",    u"Namyangju (남양주시, 南楊州市)"),
        (u"18",    u"Osan (오산시, 烏山市)"),
        (u"19",    u"Paju (파주시, 坡州市)"),
        (u"20",    u"Pocheon (포천시, 抱川市)"),
        (u"21",    u"Pyeongtaek (평택시, 平澤市)"),
        (u"22",    u"Seongnam (성남시, 城南市)"),
        (u"23",    u"Siheung (시흥시, 始興市)"),
        (u"24",    u"Uijeongbu (의정부시, 議政府市)"),
        (u"25",    u"Uiwang (의왕시, 儀旺市)"),
        (u"26",    u"Yangju (양주시, 楊州市)"),
        (u"27",    u"Yongin (용인시, 龍仁市)"),        
        ]),
    ((u'KB',  u'Gyeongsangbuk-do'), [
        (u"01",    u"Andong (안동시; 安東市)"),
        (u"02",    u"Bonghwa (봉화군; 奉化郡)"),
        (u"03",    u"Cheongdo (청도군; 淸道郡)"),
        (u"04",    u"Cheongsong (청송군; 靑松郡)"),
        (u"05",    u"Chilgok (칠곡군; 漆谷郡)"),
        (u"06",    u"Gimcheon (김천시; 金泉市)"),
        (u"07",    u"Goryeong (고령군; 高靈郡)"),
        (u"08",    u"Gumi (구미시; 龜尾市)"),
        (u"09",    u"Gunwi (군위군; 軍威郡)"),
        (u"10",    u"Gyeongju (경주시; 慶州市)"),
        (u"11",    u"Gyeongsan (경산시; 慶山市)"),
        (u"12",    u"Mungyeong (문경시;聞慶市)"),
        (u"13",    u"Pohang (포항시; 浦項市)"),
        (u"14",    u"Sangju (상주시; 尙州市)"),
        (u"15",    u"Seongju (성주군; 星州郡)"),
        (u"16",    u"Uiseong (의성군; 義城郡)"),
        (u"17",    u"Uljin (울진군; 蔚珍郡)"),
        (u"18",    u"Ulleung (울릉군; 鬱陵郡)"),
        (u"19",    u"Yecheon (예천군; 醴泉郡)"),
        (u"20",    u"Yeongcheon (영천시; 永川市)"),
        (u"21",    u"Yeongdeok (영덕군; 盈德郡)"),
        (u"22",    u"Yeongju (영주시; 榮州市)"),
        (u"23",    u"Yeongyang (영양군; 英陽郡)"),        
        ]),
    ((u'KN',  u'Gyeongsangnam-do'), [
        (u"01",    u"Changwon (창원시; 昌原市, capital)"),
        (u"02",    u"Changnyeong (창녕군; 昌寧郡)"),
        (u"03",    u"Geoje (거제시; 巨濟市)"),
        (u"04",    u"Geochang (거창군; 居昌郡)"),
        (u"05",    u"Gimhae (김해시; 金海市)"),
        (u"06",    u"Goseong (고성군; 固城郡)"),
        (u"07",    u"Hadong (하동군; 河東郡)"),
        (u"08",    u"Haman (함안군; 咸安郡)"),
        (u"09",    u"Hapcheon (합천군; 陜川郡)"),
        (u"10",    u"Hamyang (함양군; 咸陽郡)"),
        (u"11",    u"Jinju (진주시; 晋州市)"),
        (u"12",    u"Miryang (밀양시; 密陽市)"),
        (u"13",    u"Namhae (남해군; 南海郡)"),
        (u"14",    u"Sacheon (사천시; 泗川市)"),
        (u"15",    u"Sancheong (산청군; 山淸郡)"),
        (u"16",    u"Tongyeong (통영시; 統營市)"),
        (u"17",    u"Uiryeong (의령군; 宜寧郡)"),
        (u"18",    u"Yangsan (양산시; 梁山市)"),        
        ]),
    ((u'IN',  u'Incheon'), [
        (u"01",    u"Bupyeong-gu (부평구; 富平區)"),
        (u"02",    u"Dong-gu (동구; 東區)"),
        (u"03",    u"Gyeyang-gu (계양구; 桂陽區)"),
        (u"04",    u"Jung-gu (중구; 中區)"),
        (u"05",    u"Nam-gu (남구; 南區)"),
        (u"06",    u"Namdong-gu (남동구; 南洞區)"),
        (u"07",    u"Seo-gu (서구; 西區)"),
        (u"08",    u"Yeonsu-gu (연수구; 延壽區)"),
        (u"09",    u"Ganghwa-gun (강화군; 江華郡)"),
        (u"10",    u"Ongjin-gun (옹진군; 甕津郡)"),        
        ]),
    ((u'CJ',  u'Jeju'), [
        (u"01",    u"Aeweol-eup (애월읍)"),
        (u"02",    u"Gujwa-eup (구좌읍)"),
        (u"03",    u"Hanrim-eup (한림읍)"),
        (u"04",    u"Jocheon-eup (조천읍)"),
        (u"05",    u"Chuja-myeon (추자면)"),
        (u"06",    u"Hangyeong-myeon (한경면)"),
        (u"07",    u"Udo-myeon (우도면)"),
        (u"08",    u"Ara-dong (아라동)"),
        (u"09",    u"Bonggae-dong (봉개동)"),
        (u"10",    u"Dodu-dong (도두동)"),
        (u"11",    u"Geonip-dong (건입동)"),
        (u"12",    u"Hwabuk-dong (화북동)"),
        (u"13",    u"Ido-1-dong (이도1동)"),
        (u"14",    u"Ido-2-dong (이도2동)"),
        (u"15",    u"Iho-dong (이호동)"),
        (u"16",    u"Ildo-1-dong (일도1동)"),
        (u"17",    u"Ildo-2-dong (일도2동)"),
        (u"18",    u"Nohyeong-dong (노형동)"),
        (u"19",    u"Oedo-dong (외도동)"),
        (u"20",    u"Ora-dong (오라동)"),
        (u"21",    u"Samdo-1-dong (삼도1동)"),
        (u"22",    u"Samdo-2-dong (삼도2동)"),
        (u"23",    u"Samyang-dong (삼양동)"),
        (u"24",    u"Yeon-dong (연동)"),
        (u"25",    u"Yongdam-1-dong (용담1동)"),
        (u"26",    u"Yongdam-2-dong (용담2동)"),        
        ]),
    ((u'CB',  u'Jeollabuk-do'), [
        (u"01",    u"Buan (부안군; 扶安郡)"),
        (u"02",    u"Gimje (김제시; 金堤市)"),
        (u"03",    u"Gochang (고창군; 高敞郡)"),
        (u"04",    u"Gunsan (군산시; 群山市)"),
        (u"05",    u"Iksan (익산시; 益山市)"),
        (u"06",    u"Imsil (임실군; 任實郡)"),
        (u"07",    u"Jangsu (장수군; 長水郡)"),
        (u"08",    u"Jeonju (전주시; 全州市, capital)"),
        (u"09",    u"Jeongeup (정읍시; 井邑市)"),
        (u"10",    u"Jinan (진안군; 鎭安郡)"),
        (u"11",    u"Muju (무주군; 茂朱郡)"),
        (u"12",    u"Namwon (남원시; 南原市)"),
        (u"13",    u"Sunchang (순창군; 淳昌郡)"),
        (u"14",    u"Wanju (완주군; 完州郡)"),        
        ]),
    ((u'CN',  u'Jeollanam-do'), [
        (u"01",    u"Boseong (보성군, 寶城郡)"),
        (u"02",    u"Damyang (담양군, 潭陽郡)"),
        (u"03",    u"Gangjin (강진군, 康津郡)"),
        (u"04",    u"Goheung (고흥군, 高興郡)"),
        (u"05",    u"Gokseong (곡성군, 谷城郡)"),
        (u"06",    u"Gurye (구례군, 求禮郡)"),
        (u"07",    u"Gwangyang (광양시, 光陽市)"),
        (u"08",    u"Haenam (해남군, 海南郡)"),
        (u"09",    u"Hampyeong (함평군, 咸平郡)"),
        (u"10",    u"Hwasun (화순군, 和順郡)"),
        (u"11",    u"Jangheung (장흥군, 長興郡)"),
        (u"12",    u"Jangseong (장성군, 長城郡)"),
        (u"13",    u"Jindo (진도군, 珍島郡)"),
        (u"14",    u"Mokpo (목포시, 木浦市)"),
        (u"15",    u"Muan (무안군, 務安郡)"),
        (u"16",    u"Naju (나주시, 羅州市)"),
        (u"17",    u"Sinan (신안군, 新安郡)"),
        (u"18",    u"Suncheon (순천시, 順天市)"),
        (u"19",    u"Wando (완도군, 莞島郡)"),
        (u"20",    u"Yeongam (영암군, 靈巖郡)"),
        (u"21",    u"Yeonggwang (영광군, 靈光郡)"),
        (u"22",    u"Yeosu (여수시, 麗水市)"),        
        ]),
    ((u'SO',  u'Seoul'), [
        (u"01",    u"Dobong (도봉구; 道峰區)"),
        (u"02",    u"Dongdaemun (동대문구; 東大門區)"),
        (u"03",    u"Dongjak (동작구; 銅雀區)"),
        (u"04",    u"Eunpyeong (은평구; 恩平區)"),
        (u"05",    u"Gangbuk (강북구; 江北區)"),
        (u"06",    u"Gangdong (강동구; 江東區)"),
        (u"07",    u"Gangnam (강남구; 江南區)"),
        (u"08",    u"Gangseo (강서구; 江西區)"),
        (u"09",    u"Geumcheon (금천구; 衿川區)"),
        (u"10",    u"Guro (구로구; 九老區)"),
        (u"11",    u"Gwanak (관악구; 冠岳區)"),
        (u"12",    u"Gwangjin (광진구; 廣津區)"),
        (u"13",    u"Jongno (종로구; 鍾路區)"),
        (u"14",    u"Jung (중구; 中區)"),
        (u"15",    u"Jungnang (중랑구; 中浪區)"),
        (u"16",    u"Mapo (마포구; 麻浦區)"),
        (u"17",    u"Nowon (노원구; 蘆原區)"),
        (u"18",    u"Seocho (서초구; 瑞草區)"),
        (u"19",    u"Seodaemun (서대문구; 西大門區)"),
        (u"20",    u"Seongbuk (성북구; 城北區)"),
        (u"21",    u"Seongdong (성동구; 城東區)"),
        (u"22",    u"Songpa (송파구; 松坡區)"),
        (u"23",    u"Yangcheon (양천구; 陽川區)"),
        (u"24",    u"Yeongdeungpo (영등포구; 永登浦區)"),
        (u"25",    u"Yongsan (용산구; 龍山區)"),        
        ]),
    ((u'UL',  u'Ulsan'), [
        (u"01",    u"Buk-gu (북구; 北區)"),
        (u"02",    u"Dong-gu (동구; 東區)"),
        (u"03",    u"Jung-gu (중구; 中區)"),
        (u"04",    u"Nam-gu (남구; 南區)"),
        (u"05",    u"Ulju-gun (울주군; 蔚州郡)"),        
        ]),
]
