# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

PY_regions = [
    ((u"PY-16", u"Alto Paraguay"), [
        (u"FO",  u"Fuerte Olimpo"),
        (u"LV",  u"La Victoria"),
        ]),

    ((u"PY-10", u"Alto Paraná"), [
        (u"CE",  u"Ciudad del Este"),
        (u"DM",  u"Doctor Juan León Mallorquín"),
        (u"DI",  u"Domingo Martínez de Irala"),
        (u"HE",  u"Hernandarias"),
        (u"IR",  u"Iruña"),
        (u"IT",  u"Itakyry"),
        (u"JO",  u"Juan Emilio O'Leary"),
        (u"LC",  u"Los Cedrales"),
        (u"MB",  u"Mbaracayú"),
        (u"MG",  u"Minga Guazú"),
        (u"MP",  u"Minga Porá"),
        (u"NR",  u"Naranjal"),
        (u"PF",  u"Presidente Franco"),
        (u"SA",  u"San Alberto"),
        (u"SC",  u"San Cristóbal"),
        (u"SR",  u"Santa Rita"),
        (u"SM",  u"Santa Rosa del Monday"),
        (u"YG",  u"Yguazú"),
        (u"NC",  u"Ñacunday"),
        ]),

    ((u"PY-13", u"Amambay"), [
        (u"BV",  u"Bella Vista"),
        (u"CB",  u"Capitán Bado"),
        (u"PC",  u"Pedro Juan Caballero"),
        ]),

    # note, our "standard" would indicate that the letter code here shouldn't have the country code appended, 
    # but for historical reasons, we leave it. (we could run a database cleanup to change this one day if necessary)
    ((u"PY-ASU", u"Asunción"), [
        (u"01",	  u"Bañado Santa Ana"),
        (u"02",	  u"Bañado Tacumbú"),
        (u"03",	  u"Banco San Miguel"),
        (u"04",	  u"Bella Vista"),
        (u"05",	  u"Botánico"),
        (u"06",	  u"Cañada del Ybyray"),
        (u"07",	  u"Ciudad Nueva"),
        (u"08",	  u"Dr. José Gaspar Rodriguez de Francia"),
        (u"09",	  u"Dr. Roberto L. Petit"),
        (u"10",	  u"Gral. Bernardino Caballero"),
        (u"11",	  u"Gral. José Eduvigis Díaz"),
        (u"12",	  u"Hipódromo"),
        (u"13",	  u"Itá Enramada"),
        (u"14",	  u"Itá Pyta Punta"),
        (u"15",	  u"Itay"),
        (u"16",	  u"Jara"),
        (u"17",	  u"La Catedral"),
        (u"18",	  u"La Encarnación"),
        (u"19",	  u"Las Carmelitas"),
        (u"20",	  u"Las Mercedes"),
        (u"21",	  u"Loma Pyta"),
        (u"22",	  u"Los Laureles"),
        (u"23",	  u"Luis Alberto de Herrera"),
        (u"24",	  u"Madame Elisa Alicia Lynch"),
        (u"25",	  u"Manora"),
        (u"26",	  u"Mbocayaty"),
        (u"27",	  u"Mburicaó"),
        (u"28",	  u"Mburucuyá"),
        (u"29",	  u"Mcal. Francisco Solano López"),
        (u"30",	  u"Mcal. José Félix Estigarribia"),
        (u"31",	  u"Nazareth"),
        (u"32",	  u"Ñu Guazú 16"),
        (u"33",	  u"Obrero"),
        (u"34",	  u"Panambí Reta"),
        (u"35",	  u"Panambí Verá"),
        (u"36",	  u"Pinoza"),
        (u"37",	  u"Pirizal"),
        (u"38",	  u"Recoleta"),
        (u"39",	  u"Republicano"),
        (u"40",	  u"Ricardo Brugada"),
        (u"41",	  u"Sajonia"),
        (u"42",	  u"Salvador del Mundo"),
        (u"43",	  u"San Antonio"),
        (u"44",	  u"San Blás"),
        (u"45",	  u"San Cristóbal"),
        (u"46",	  u"San Felipe"),
        (u"47",	  u"San Jorge"),
        (u"48",	  u"San Pablo"),
        (u"49",	  u"San Roque"),
        (u"50",	  u"San Vicente"),
        (u"51",	  u"Santa Ana"),
        (u"52",	  u"Santa María"),
        (u"53",	  u"Santa Rosa"),
        (u"54",	  u"Santísima Trinidad"),
        (u"55",	  u"Santo Domingo"),
        (u"56",	  u"Tablada Nueva"),
        (u"57",	  u"Tacumbú"),
        (u"58",	  u"Tembetary"),
        (u"59",	  u"Terminal"),
        (u"60",	  u"Tte. Silvio Pettirossi"),
        (u"61",	  u"Villa Aurelia"),
        (u"62",	  u"Villa Morra"),
        (u"63",	  u"Virgen de Fatima"),
        (u"64",	  u"Virgen de la Asunción"),
        (u"65",	  u"Virgen del Huerto"),
        (u"66",	  u"Vista Alegre"),
        (u"67",	  u"Ycua Sati"),
        (u"68",	  u"Zeballos Cué"),
        ]),

    ((u"PY-19", u"Boquerón"), [
        (u"ME",  u"Mariscal José Félix Estigarribia"),
        ]),

    ((u"PY-5", u"Caaguazú"), [
        (u"TF",  u"3 de Febrero"),
        (u"CG",  u"Caaguazú"),
        (u"CR",  u"Carayaó"),
        (u"CO",  u"Coronel Oviedo"),
        (u"DB",  u"Doctor Cecilio Báez"),
        (u"DE",  u"Doctor J. Eulogio Estigarribia"),
        (u"DF",  u"Doctor Juan Manuel Frutos"),
        (u"JO",  u"José Domingo Ocampos"),
        (u"LP",  u"La Pastora"),
        (u"ML",  u"Mariscal Francisco Solano López"),
        (u"NL",  u"Nueva Londres"),
        (u"TC",  u"R.I. 3 Corrales"),
        (u"RO",  u"Raúl Arsenio Oviedo"),
        (u"RE",  u"Repatriación"),
        (u"SJ",  u"San Joaquín"),
        (u"SA",  u"San José de los Arroyos"),
        (u"SM",  u"Santa Rosa del Mbutuy"),
        (u"SB",  u"Simón Bolívar"),
        (u"VA",  u"Vaquería (San Blas)"),
        (u"YH",  u"Yhú"),
        ]),

    ((u"PY-6", u"Caazapá"), [
        (u"AB",  u"Abaí"),
        (u"BV",  u"Buena Vista"),
        (u"CA",  u"Caazapá"),
        (u"DB",  u"Doctor Moisés S. Bertoni"),
        (u"FY",  u"Fulgencio Yegros"),
        (u"GM",  u"General Higinio Morínigo"),
        (u"MA",  u"Maciel"),
        (u"SN",  u"San Juan Nepomuceno"),
        (u"TA",  u"Tavaí"),
        (u"YU",  u"Yuty"),
        ]),

    ((u"PY-14", u"Canindeyú"), [
        (u"CC",  u"Corpus Christi"),
        (u"VC",  u"Curuguaty"),
        (u"GA",  u"General Francisco Caballero Alvarez"),
        (u"IT",  u"Itanará"),
        (u"KA",  u"Katuete"),
        (u"LP",  u"La Paloma"),
        (u"NE",  u"Nueva Esperanza"),
        (u"SG",  u"Salto del Guairá"),
        (u"VY",  u"Villa Igatimí"),
        (u"YP",  u"Ypejhú"),
        ]),

    ((u"PY-11", u"Central"), [
        (u"AR",  u"Areguá"),
        (u"CA",  u"Capiatá"),
        (u"FM",  u"Fernando de la Mora"),
        (u"GU",  u"Guarambaré"),
        (u"IG",  u"Itauguá"),
        (u"IT",  u"Itá"),
        (u"JS",  u"Juan Augusto Saldívar"),
        (u"LA",  u"Lambaré"),
        (u"LI",  u"Limpio"),
        (u"LU",  u"Luque"),
        (u"MA",  u"Mariano Roque Alonso"),
        (u"NI",  u"Nueva Italia"),
        (u"SA",  u"San Antonio"),
        (u"SL",  u"San Lorenzo"),
        (u"VE",  u"Villa Elisa"),
        (u"VI",  u"Villeta"),
        (u"YC",  u"Ypacaraí"),
        (u"YN",  u"Ypané"),
        (u"NE",  u"Ñemby"),
        ]),

    ((u"PY-1", u"Concepción"), [
        (u"BE",  u"Belén"),
        (u"CO",  u"Concepción"),
        (u"HO",  u"Horqueta"),
        (u"LO",  u"Loreto"),
        (u"SL",  u"San Lázaro"),
        (u"YY",  u"Yby Ya'ú"),
        ]),

    ((u"PY-3", u"Cordillera"), [
        (u"AL",  u"Altos"),
        (u"AE",  u"Arroyos y Esteros"),
        (u"AT",  u"Atyrá"),
        (u"CC",  u"Caacupé"),
        (u"CR",  u"Caraguatay"),
        (u"EM",  u"Emboscada"),
        (u"EU",  u"Eusebio Ayala"),
        (u"IS",  u"Isla Pucú"),
        (u"IC",  u"Itacurubí de la Cordillera"),
        (u"JM",  u"Juan de Mena"),
        (u"LG",  u"Loma Grande"),
        (u"MY",  u"Mbocayaty del Yhaguy"),
        (u"NC",  u"Nueva Colombia"),
        (u"PI",  u"Piribebuy"),
        (u"PM",  u"Primero de Marzo"),
        (u"SB",  u"San Bernardino"),
        (u"SO",  u"San José Obrero"),
        (u"SE",  u"Santa Elena"),
        (u"TO",  u"Tobatí"),
        (u"VA",  u"Valenzuela"),
        ]),

    ((u"PY-4", u"Guairá"), [
        (u"BO",  u"Borja"),
        (u"CT",  u"Capitán Mauricio José Troche"),
        (u"IN",  u"Colonia Independencia"),
        (u"CM",  u"Coronel Martínez"),
        (u"DB",  u"Doctor Botrell"),
        (u"FC",  u"Félix Pérez Cardozo"),
        (u"GG",  u"General Eugenio A. Garay"),
        (u"IP",  u"Itapé"),
        (u"IB",  u"Iturbe"),
        (u"JF",  u"José A. Fassardi"),
        (u"MG",  u"Mbocayaty del Guairá"),
        (u"NT",  u"Natalicio Talavera"),
        (u"PY",  u"Paso Yobai"),
        (u"SS",  u"San Salvador"),
        (u"VI",  u"Villarrica"),
        (u"YG",  u"Yataity del Guairá"),
        (u"NU",  u"Ñumí"),
        ]),

    ((u"PY-7", u"Itapúa"), [
        (u"AV",  u"Alto Verá"),
        (u"BV",  u"Bella Vista"),
        (u"CA",  u"Cambyretá"),
        (u"CZ",  u"Capitán Meza"),
        (u"CM",  u"Capitán Miranda"),
        (u"CL",  u"Carlos Antonio López"),
        (u"CP",  u"Carmen del Paraná"),
        (u"CB",  u"Coronel Bogado"),
        (u"ED",  u"Edelira"),
        (u"EN",  u"Encarnación"),
        (u"FR",  u"Fram"),
        (u"GA",  u"General Artigas"),
        (u"GD",  u"General Delgado"),
        (u"HO",  u"Hohenau"),
        (u"IP",  u"Itapúa Poty"),
        (u"JE",  u"Jesús"),
        (u"JO",  u"José Leandro Oviedo"),
        (u"LP",  u"La Paz"),
        (u"MO",  u"Mayor Julio D. Otaño"),
        (u"NT",  u"Natalio"),
        (u"NA",  u"Nueva Alborada"),
        (u"OB",  u"Obligado"),
        (u"PI",  u"Pirapó"),
        (u"SC",  u"San Cosme y Damián"),
        (u"SJ",  u"San Juan del Paraná"),
        (u"SP",  u"San Pedro del Paraná"),
        (u"SR",  u"San Rafael del Paraná"),
        (u"TP",  u"Tomás Romero Pereira"),
        (u"TR",  u"Trinidad"),
        (u"YA",  u"Yatytay"),
        ]),

    ((u"PY-8", u"Misiones"), [
        (u"AY",  u"Ayolas"),
        (u"SI",  u"San Ignacio"),
        (u"SJ",  u"San Juan Bautista de las Misiones"),
        (u"SG",  u"San Miguel"),
        (u"SP",  u"San Patricio"),
        (u"SM",  u"Santa María"),
        (u"SR",  u"Santa Rosa"),
        (u"SA",  u"Santiago"),
        (u"VF",  u"Villa Florida"),
        (u"YA",  u"Yabebyry"),
        ]),

    ((u"PY-9", u"Paraguarí"), [
        (u"AC",  u"Acahay"),
        (u"CP",  u"Caapucú"),
        (u"CR",  u"Carapeguá"),
        (u"ES",  u"Escobar"),
        (u"GC",  u"General Bernardino Caballero"),
        (u"LC",  u"La Colmena"),
        (u"MB",  u"Mbuyapey"),
        (u"PA",  u"Paraguarí"),
        (u"PI",  u"Pirayú"),
        (u"QI",  u"Quiindy"),
        (u"QQ",  u"Quyquyhó"),
        (u"SG",  u"San Roque González de Santa Cruz"),
        (u"SA",  u"Sapucai"),
        (u"TE",  u"Tebicuarymí"),
        (u"YA",  u"Yaguarón"),
        (u"YC",  u"Ybycuí"),
        (u"YT",  u"Ybytimí"),
        ]),

    ((u"PY-15", u"Presidente Hayes"), [
        (u"BA",  u"Benjamín Aceval"),
        (u"JF",  u"José Falcón"),
        (u"NA",  u"Nanawa"),
        (u"PP",  u"Puerto Pinasco"),
        (u"VH",  u"Villa Hayes"),
        ]),

    ((u"PY-2", u"San Pedro"), [
        (u"VD",  u"25 de Diciembre"),
        (u"AN",  u"Antequera"),
        (u"CA",  u"Capiibary"),
        (u"CH",  u"Choré"),
        (u"GA",  u"General Elizardo Aquino"),
        (u"GR",  u"General Isidoro Resquín"),
        (u"GU",  u"Guayaibí"),
        (u"IR",  u"Itacurubí del Rosario"),
        (u"LI",  u"Lima"),
        (u"NG",  u"Nueva Germania"),
        (u"SE",  u"San Estanislao"),
        (u"SP",  u"San Pablo"),
        (u"SY",  u"San Pedro del Ycuamandiyú"),
        (u"SR",  u"Santa Rosa del Aguaray"),
        (u"TA",  u"Tacuatí"),
        (u"UN",  u"Unión"),
        (u"VR",  u"Villa del Rosario"),
        (u"YN",  u"Yataity del Norte"),
        ]),

    ((u"PY-12", u"Ñeembucú"), [
        (u"AL",  u"Alberdi"),
        (u"CE",  u"Cerrito"),
        (u"DE",  u"Desmochados"),
        (u"GD",  u"General José Eduvigis Díaz"),
        (u"GC",  u"Guazú Cuá"),
        (u"HU",  u"Humaitá"),
        (u"IU",  u"Isla Umbú"),
        (u"LA",  u"Laureles"),
        (u"MM",  u"Mayor José J. Martínez"),
        (u"PP",  u"Paso de Patria"),
        (u"PI",  u"Pilar"),
        (u"SN",  u"San Juan Bautista de Ñeembucú"),
        (u"TA",  u"Tacuaras"),
        (u"VF",  u"Villa Franca"),
        (u"VO",  u"Villa Oliva"),
        (u"VI",  u"Villalbín"),
        ]),
    ]
