# -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

RU_regions = [
    ((u"AD", u"Adygey"), [
        (u"AD",  u"Adygeysk (Teuchezh)"),
        (u"GI",  u"Giaginskiy"),
        (u"KO",  u"Koshekhabl'skiy"),
        (u"KR",  u"Krasnogvardeyskiy"),
        (u"MG",  u"Maykop"),
        (u"MR",  u"Maykopskiy"),
        (u"OK",  u"Oktyabr' (Takhtamukaysk)"),
        (u"SH",  u"Shovgenovskiy"),
        (u"TE",  u"Teuchezhskiy"),
        ]),

    ((u"AL", u"Altay"), [
        (u"AG",  u"Aleysk"),
        (u"AR",  u"Aleyskiy"),
        (u"AL",  u"Altayskiy"),
        (u"BV",  u"Baevskiy"),
        (u"BA",  u"Barnaul"),
        (u"BE",  u"Belokurikha"),
        (u"BG",  u"Biysk"),
        (u"BR",  u"Biyskiy"),
        (u"BL",  u"Blagoveshchenskiy"),
        (u"BU",  u"Burlinskiy"),
        (u"BY",  u"Bystroistokskiy"),
        (u"CH",  u"Charyshskiy"),
        (u"EG",  u"Egor'evskiy"),
        (u"EL",  u"El'tsovskiy"),
        (u"KA",  u"Kalmanskiy"),
        (u"KO",  u"Kamen'-na-Obi"),
        (u"KM",  u"Kamenskiy"),
        (u"KH",  u"Khabarskiy"),
        (u"KL",  u"Klyuchevskiy"),
        (u"KS",  u"Kosikhinskiy"),
        (u"KG",  u"Krasnogorskiy"),
        (u"KN",  u"Krasnoshchekovskiy"),
        (u"KR",  u"Krutikhinskiy"),
        (u"KD",  u"Kulundinskiy"),
        (u"KU",  u"Kur'inskiy"),
        (u"KY",  u"Kytmanovskiy"),
        (u"LO",  u"Loktevskiy"),
        (u"MA",  u"Mamontovskiy"),
        (u"MI",  u"Mikhaylovskiy"),
        (u"NE",  u"Nemetskiy"),
        (u"NA",  u"Novoaltaysk"),
        (u"NC",  u"Novochikhinskiy"),
        (u"PK",  u"Pankrushikhinskiy"),
        (u"PA",  u"Pavlovskiy"),
        (u"PE",  u"Pervomayskiy"),
        (u"PP",  u"Petropavlovskiy"),
        (u"PO",  u"Pospelikhinskiy"),
        (u"RE",  u"Rebrikhinskiy"),
        (u"RD",  u"Rodinskiy"),
        (u"RM",  u"Romanovskiy"),
        (u"RG",  u"Rubtsovsk"),
        (u"RR",  u"Rubtsovskiy"),
        (u"SB",  u"Shelabolikhinskiy"),
        (u"SP",  u"Shipunovskiy"),
        (u"SI",  u"Sibirskiy Parish"),
        (u"SG",  u"Slavgorod"),
        (u"SR",  u"Slavgorodskiy"),
        (u"SM",  u"Smolenskiy"),
        (u"SO",  u"Soloneshenskiy"),
        (u"ST",  u"Soltonskiy"),
        (u"SV",  u"Sovetskiy"),
        (u"SU",  u"Suetskiy"),
        (u"TB",  u"Tabunskiy"),
        (u"TA",  u"Tal'menskiy"),
        (u"TG",  u"Togul'skiy"),
        (u"TP",  u"Topchikhinskiy"),
        (u"TR",  u"Tret'yakovskiy"),
        (u"TT",  u"Troitskiy"),
        (u"TS",  u"Tselinnyy"),
        (u"TY",  u"Tyumentsevskiy"),
        (u"UG",  u"Uglovskiy"),
        (u"UK",  u"Ust'-Kalmanskiy"),
        (u"UP",  u"Ust'-Pristanskiy"),
        (u"VO",  u"Volchikhinskiy"),
        (u"YA",  u"Yarovoe"),
        (u"ZL",  u"Zalesovskiy"),
        (u"ZG",  u"Zarinsk"),
        (u"ZR",  u"Zarinskiy"),
        (u"ZV",  u"Zav'yalovskiy"),
        (u"ZM",  u"Zmeinogorsk"),
        (u"ZN",  u"Zmeinogorskiy"),
        (u"ZO",  u"Zonal'nyy"),
        ]),

    ((u"AM", u"Amur"), [
        (u"AR",  u"Arkharinskiy"),
        (u"BG",  u"Belogorsk"),
        (u"BR",  u"Belogorskiy"),
        (u"BV",  u"Blagoveshchensk"),
        (u"BL",  u"Blagoveshchenskiy"),
        (u"BU",  u"Bureyskiy"),
        (u"IV",  u"Ivanovskiy"),
        (u"KO",  u"Konstantinovskiy"),
        (u"MG",  u"Magdagachinskiy"),
        (u"MZ",  u"Mazanovskiy"),
        (u"MI",  u"Mikhaylovskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"RA",  u"Raychikhinsk"),
        (u"RO",  u"Romnenskiy"),
        (u"SL",  u"Selemdzhinskiy"),
        (u"SE",  u"Seryshevskiy"),
        (u"SG",  u"Shimanovsk"),
        (u"SR",  u"Shimanovskiy"),
        (u"SK",  u"Skovorodinskiy"),
        (u"SB",  u"Svobodnenskiy"),
        (u"SV",  u"Svobodnyy"),
        (u"TA",  u"Tambovskiy"),
        (u"TG",  u"Tynda"),
        (u"TR",  u"Tyndinskiy"),
        (u"UG",  u"Uglegorsk Parish"),
        (u"ZA",  u"Zavitinskiy"),
        (u"ZG",  u"Zeya"),
        (u"ZR",  u"Zeyskiy"),
        ]),

    ((u"AR", u"Arkhangel'sk"), [
        (u"AR",  u"Arkhangel'sk"),
        (u"KA",  u"Kargopol'skiy"),
        (u"KH",  u"Kholmogorskiy"),
        (u"KN",  u"Konoshskiy"),
        (u"KZ",  u"Koryazhma"),
        (u"KG",  u"Kotlas"),
        (u"KR",  u"Kotlasskiy"),
        (u"KB",  u"Krasnoborskiy"),
        (u"LN",  u"Lenskiy"),
        (u"LS",  u"Leshukonskiy"),
        (u"ME",  u"Mezenskiy"),
        (u"MI",  u"Mirnyy"),
        (u"NZ",  u"Novaya Zemlya"),
        (u"ND",  u"Novodvinsk"),
        (u"NY",  u"Nyandomskiy"),
        (u"OG",  u"Onega"),
        (u"OR",  u"Onezhskiy"),
        (u"PI",  u"Pinezhskiy"),
        (u"PL",  u"Plesetskiy"),
        (u"PR",  u"Primorskiy"),
        (u"SE",  u"Severodvinsk"),
        (u"SH",  u"Shenkurskiy"),
        (u"SO",  u"Solovetskiy"),
        (u"US",  u"Ust'yanskiy"),
        (u"VL",  u"Vel'skiy"),
        (u"VR",  u"Verhnetoemskiy"),
        (u"VK",  u"Viktoriya"),
        (u"VI",  u"Vilegodskiy"),
        (u"VN",  u"Vinogradovskiy"),
        (u"ZE",  u"Zemlya Frantsa-Iosifa"),
        ]),

    ((u"AS", u"Astrakhan'"), [
        (u"AG",  u"Akhtubinsk"),
        (u"AR",  u"Akhtubinskiy"),
        (u"AS",  u"Astrakhan'"),
        (u"CH",  u"Chernoyarskiy"),
        (u"IK",  u"Ikryaninskiy"),
        (u"KA",  u"Kamyzyakskiy"),
        (u"KH",  u"Kharabalinskiy"),
        (u"KR",  u"Krasnoyarskiy"),
        (u"LI",  u"Limanskiy"),
        (u"NA",  u"Narimanovskiy"),
        (u"PR",  u"Privolzhskiy"),
        (u"VO",  u"Volodarskiy"),
        (u"YE",  u"Yenotaevskiy"),
        (u"ZN",  u"Znamensk"),
        ]),

    ((u"BK", u"Bashkortostan"), [
        (u"AB",  u"Abzelilovskiy"),
        (u"AG",  u"Agidel'"),
        (u"AL",  u"Al'sheyevskiy"),
        (u"AR",  u"Arkhangel'skiy"),
        (u"AS",  u"Askinskiy"),
        (u"AU",  u"Aurgazinskiy"),
        (u"BN",  u"Bakalinskiy"),
        (u"BC",  u"Baltachevskiy"),
        (u"BM",  u"Baymak"),
        (u"BA",  u"Baymakskiy"),
        (u"BB",  u"Belebeevskiy"),
        (u"BE",  u"Belebey"),
        (u"BK",  u"Belokatayskiy"),
        (u"BT",  u"Belorets"),
        (u"BO",  u"Beloretskiy"),
        (u"BI",  u"Birsk"),
        (u"BR",  u"Birskiy"),
        (u"BZ",  u"Bizhbulyakskiy"),
        (u"BL",  u"Blagovarskiy"),
        (u"BG",  u"Blagoveshchensk"),
        (u"BS",  u"Blagoveshchenskiy"),
        (u"BY",  u"Burayevskiy"),
        (u"BU",  u"Burzyanskiy"),
        (u"BD",  u"Buzdyakskiy"),
        (u"CK",  u"Chekmagushevskiy"),
        (u"CS",  u"Chishminskiy"),
        (u"DG",  u"Davlekanovo"),
        (u"DR",  u"Davlekanovskiy"),
        (u"DU",  u"Duvanskiy"),
        (u"DT",  u"Dyurtyuli"),
        (u"DY",  u"Dyurtyulinskiy"),
        (u"FE",  u"Fedorovskiy"),
        (u"GA",  u"Gafuriyskiy"),
        (u"IG",  u"Iglinskiy"),
        (u"IL",  u"Ilishevskiy"),
        (u"IB",  u"Ishimbay"),
        (u"IS",  u"Ishimbayskiy"),
        (u"KL",  u"Kaltasinskiy"),
        (u"KD",  u"Karaidel'skiy"),
        (u"KM",  u"Karmaskalinskiy"),
        (u"KH",  u"Khaybullinskiy"),
        (u"KI",  u"Kiginskiy"),
        (u"KR",  u"Krasnokamskiy"),
        (u"KG",  u"Kugarchinskiy"),
        (u"KU",  u"Kumertau"),
        (u"KN",  u"Kushnarenkovskiy"),
        (u"KZ",  u"Kuyurgazinskiy"),
        (u"ME",  u"Mechetlinskiy"),
        (u"MG",  u"Meleuz"),
        (u"MR",  u"Meleuzovskiy"),
        (u"MZ",  u"Mezhgor'e"),
        (u"MI",  u"Mishkinskiy"),
        (u"MY",  u"Miyakinskiy"),
        (u"NE",  u"Neftekamsk"),
        (u"NU",  u"Nurimanovskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"SG",  u"Salavat"),
        (u"SR",  u"Salavatskiy"),
        (u"SH",  u"Sharanskiy"),
        (u"SI",  u"Sibay"),
        (u"SB",  u"Sterlibashevskiy"),
        (u"SM",  u"Sterlitamak"),
        (u"ST",  u"Sterlitamakskiy"),
        (u"TA",  u"Tatyshlinskiy"),
        (u"TR",  u"Tuymazinskiy"),
        (u"TG",  u"Tuymazy"),
        (u"UL",  u"Uchalinskiy"),
        (u"UC",  u"Uchaly"),
        (u"UG",  u"Ufa"),
        (u"UR",  u"Ufimskiy"),
        (u"YG",  u"Yanaul"),
        (u"YR",  u"Yanaul'skiy"),
        (u"YE",  u"Yermekeyevskiy"),
        (u"ZN",  u"Zianchurinskiy"),
        (u"ZL",  u"Zilairskiy"),
        ]),

    ((u"BL", u"Belgorod"), [
        (u"AG",  u"Alekseevka"),
        (u"AR",  u"Alekseevskiy"),
        (u"BG",  u"Belgorod"),
        (u"BR",  u"Belgorodskiy"),
        (u"BO",  u"Borisovskiy"),
        (u"CH",  u"Chernyanskiy"),
        (u"GR",  u"Grayvoronskiy"),
        (u"GG",  u"Gubkin"),
        (u"GB",  u"Gubkinskiy"),
        (u"IV",  u"Ivnyanskiy"),
        (u"KO",  u"Korochanskiy"),
        (u"KN",  u"Krasnenskiy"),
        (u"KG",  u"Krasnogvardeyskiy"),
        (u"KY",  u"Krasnoyaruzhskiy"),
        (u"NO",  u"Novooskol'skiy"),
        (u"PR",  u"Prokhorovskiy"),
        (u"RA",  u"Rakityanskiy"),
        (u"RO",  u"Roven'skiy"),
        (u"SG",  u"Shebekino"),
        (u"SR",  u"Shebekinskiy"),
        (u"ST",  u"Starooskol'skiy"),
        (u"SO",  u"Staryy Oskol"),
        (u"VG",  u"Valuyki"),
        (u"VR",  u"Valuyskiy"),
        (u"VE",  u"Veydelevskiy"),
        (u"VO",  u"Volokonovskiy"),
        (u"YA",  u"Yakovlevskiy"),
        ]),

    ((u"BR", u"Bryansk"), [
        (u"BS",  u"Brasovskiy"),
        (u"BG",  u"Bryansk"),
        (u"BR",  u"Bryanskiy"),
        (u"DU",  u"Dubrovskiy"),
        (u"DG",  u"Dyat'kovo"),
        (u"DR",  u"Dyat'kovskiy"),
        (u"GO",  u"Gordeevskiy"),
        (u"KA",  u"Karachevskiy"),
        (u"KL",  u"Kletnyanskiy"),
        (u"KV",  u"Klimovskiy"),
        (u"KR",  u"Klintsovskiy"),
        (u"KG",  u"Klintsy"),
        (u"KO",  u"Komarichskiy"),
        (u"KS",  u"Krasnogorskiy"),
        (u"MG",  u"Mglinskiy"),
        (u"NA",  u"Navlinskiy"),
        (u"NG",  u"Novozybkov"),
        (u"NR",  u"Novozybkovskiy"),
        (u"PC",  u"Pochepskiy"),
        (u"PG",  u"Pogarskiy"),
        (u"RO",  u"Rognedinskiy"),
        (u"SG",  u"Sel'tso"),
        (u"SE",  u"Sevskiy"),
        (u"ST",  u"Starodubskiy"),
        (u"SU",  u"Surazhskiy"),
        (u"SZ",  u"Suzemskiy"),
        (u"TR",  u"Trubchevskiy"),
        (u"UN",  u"Unechskiy"),
        (u"VY",  u"Vygonichskiy"),
        (u"ZR",  u"Zhiryatinskiy"),
        (u"ZK",  u"Zhukovskiy"),
        (u"ZL",  u"Zlynkovskiy"),
        ]),

    ((u"BU", u"Buryat"), [
        (u"BA",  u"Barguzinskiy"),
        (u"BZ",  u"Bauntovskiy-Zvenkiyiskiy"),
        (u"BI",  u"Bichurskiy"),
        (u"DZ",  u"Dzhidinskiy"),
        (u"GU",  u"Gusinoozersk"),
        (u"IV",  u"Ivolginskiy"),
        (u"KA",  u"Kabanskiy"),
        (u"KH",  u"Khorinskiy"),
        (u"KI",  u"Kizhinginskiy"),
        (u"KU",  u"Kurumkanskiy"),
        (u"KY",  u"Kyakhtinskiy"),
        (u"MK",  u"Mukhorshibirskiy"),
        (u"MY",  u"Muyskiy"),
        (u"OK",  u"Okinskiy"),
        (u"PR",  u"Pribaykal'skiy"),
        (u"SE",  u"Selenginskiy"),
        (u"SG",  u"Severobaykal'sk"),
        (u"SR",  u"Severobaykal'skiy"),
        (u"TA",  u"Tarbagatayskiy"),
        (u"TU",  u"Tunkinskiy"),
        (u"UL",  u"Ulan-Ude"),
        (u"YE",  u"Yeravninskiy"),
        (u"ZI",  u"Zaigraevskiy"),
        (u"ZK",  u"Zakamenskiy"),
        ]),

    ((u"CN", u"Chechnya"), [
        (u"AC",  u"Achkhoy-Martanovskiy"),
        (u"AR",  u"Argun"),
        (u"CH",  u"Cheberloevskiy"),
        (u"GA",  u"Galanchokhskiy"),
        (u"GR",  u"Groznenskiy"),
        (u"GG",  u"Groznyy"),
        (u"GD",  u"Gudermes"),
        (u"GM",  u"Gudermesskiy"),
        (u"IT",  u"Itum-Kalinskiy"),
        (u"ND",  u"Nadterechnyy"),
        (u"NR",  u"Naurskiy"),
        (u"NY",  u"Nozhay-Yurtovskiy"),
        (u"SG",  u"Shali"),
        (u"SR",  u"Shalinskiy"),
        (u"SA",  u"Sharoyskiy"),
        (u"ST",  u"Shatoyskiy (Sovetskiy)"),
        (u"SL",  u"Shelkovskiy"),
        (u"UG",  u"Urus-Martan"),
        (u"UR",  u"Urus-Martanovskiy"),
        (u"VE",  u"Vedenskiy"),
        ]),

    ((u"CL", u"Chelyabinsk"), [
        (u"AP",  u"Agapovskiy"),
        (u"AY",  u"Argayashskiy"),
        (u"AG",  u"Asha"),
        (u"AR",  u"Ashinskiy"),
        (u"BR",  u"Bredinskiy"),
        (u"CG",  u"Chebarkul'"),
        (u"CR",  u"Chebarkul'skiy"),
        (u"CL",  u"Chelyabinsk"),
        (u"CS",  u"Chesmenskiy"),
        (u"EM",  u"Emanzhelinsk"),
        (u"ET",  u"Etkul'skiy"),
        (u"KB",  u"Karabash"),
        (u"KR",  u"Kartalinskiy"),
        (u"KG",  u"Kartaly"),
        (u"KS",  u"Kasli"),
        (u"KT",  u"Kaslinskiy"),
        (u"KA",  u"Katav-Ivanovsk"),
        (u"KI",  u"Katav-Ivanovskiy"),
        (u"KZ",  u"Kizil'skiy"),
        (u"KP",  u"Kopeysk"),
        (u"KO",  u"Korkino"),
        (u"KM",  u"Krasnoarmeyskiy"),
        (u"KN",  u"Kunashakskiy"),
        (u"KU",  u"Kusinskiy"),
        (u"KY",  u"Kyshtym"),
        (u"LO",  u"Lokomotivnyy Parish"),
        (u"MA",  u"Magnitogorsk"),
        (u"MI",  u"Miass"),
        (u"NA",  u"Nagaybakskiy"),
        (u"NY",  u"Nyazepetrovskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OZ",  u"Ozersk"),
        (u"PL",  u"Plast"),
        (u"SG",  u"Satka"),
        (u"SR",  u"Satkinskiy"),
        (u"SN",  u"Snezhinsk"),
        (u"SO",  u"Sosnovskiy"),
        (u"TK",  u"Trekhgornyy (Trezhinsk)"),
        (u"TG",  u"Troitsk"),
        (u"TR",  u"Troitskiy"),
        (u"US",  u"Ust'-Katav"),
        (u"UV",  u"Uvel'skiy"),
        (u"UY",  u"Uyskiy"),
        (u"VA",  u"Varnenskiy"),
        (u"VE",  u"Verkhneural'skiy"),
        (u"VU",  u"Verkhniy Ufaley"),
        (u"YU",  u"Yuzhnoural'sk"),
        (u"ZL",  u"Zlatoust"),
        ]),

    ((u"CK", u"Chukot"), [
        (u"AG",  u"Anadyr'"),
        (u"AR",  u"Anadyrskiy"),
        (u"BE",  u"Beringovskiy"),
        (u"BI",  u"Bilibinskiy"),
        (u"CH",  u"Chaunskiy"),
        (u"CK",  u"Chukotskiy"),
        (u"IY",  u"Iyul'tinskiy"),
        (u"PR",  u"Providenskiy"),
        (u"SH",  u"Shmidtovskiy"),
        ]),

    ((u"CV", u"Chuvash"), [
        (u"AG",  u"Alatyr'"),
        (u"AR",  u"Alatyrskiy"),
        (u"AL",  u"Alikovskiy"),
        (u"BA",  u"Batyrevskiy"),
        (u"CR",  u"Cheboksarskiy"),
        (u"CG",  u"Cheboksary"),
        (u"IB",  u"Ibresinskiy"),
        (u"KG",  u"Kanash"),
        (u"KR",  u"Kanashskiy"),
        (u"KM",  u"Komsomol'skiy"),
        (u"KZ",  u"Kozlovskiy"),
        (u"KA",  u"Krasnoarmeyskiy"),
        (u"KC",  u"Krasnochetayskiy"),
        (u"MA",  u"Mariinsko-Posadskiy"),
        (u"MO",  u"Morgaushskiy"),
        (u"NO",  u"Novocheboksarsk"),
        (u"PO",  u"Poretsskiy"),
        (u"SH",  u"Shemurshinskiy"),
        (u"SR",  u"Shumerlinskiy"),
        (u"SG",  u"Shumerlya"),
        (u"TS",  u"Tsivil'skiy"),
        (u"UR",  u"Urmarskiy"),
        (u"VU",  u"Vurnarskiy"),
        (u"YD",  u"Yadrinskiy"),
        (u"YL",  u"Yal'chikskiy"),
        (u"YN",  u"Yantikovskiy"),
        ]),

    ((u"DA", u"Dagestan"), [
        (u"AG",  u"Agul'skiy"),
        (u"AT",  u"Akhtynskiy"),
        (u"AV",  u"Akhvakhskiy"),
        (u"AS",  u"Akushinskiy"),
        (u"BA",  u"Babayurtovskiy"),
        (u"BO",  u"Botlikhskiy"),
        (u"BG",  u"Buynaksk"),
        (u"BR",  u"Buynakskiy"),
        (u"CH",  u"Charodinskiy"),
        (u"DO",  u"Dagestanskie Ogni"),
        (u"DA",  u"Dakhadayevskiy"),
        (u"DG",  u"Derbent"),
        (u"DR",  u"Derbentskiy"),
        (u"DP",  u"Dokuzparinskiy"),
        (u"GE",  u"Gergebil'skiy"),
        (u"GM",  u"Gumbetovskiy"),
        (u"GN",  u"Gunibskiy"),
        (u"IZ",  u"Izberbash"),
        (u"KB",  u"Karabudokhkentskiy (Leninskiy)"),
        (u"KP",  u"Kaspiysk"),
        (u"KK",  u"Kayakentskiy"),
        (u"KA",  u"Kaytagskiy"),
        (u"KZ",  u"Kazbekovskiy"),
        (u"KG",  u"Khasavyurt"),
        (u"KR",  u"Khasavyurtovskiy"),
        (u"KV",  u"Khivskiy"),
        (u"KH",  u"Khunzakhskiy"),
        (u"KI",  u"Kizilyurt"),
        (u"KT",  u"Kizilyurtovskiy"),
        (u"KY",  u"Kizlyar"),
        (u"KL",  u"Kizlyarskiy"),
        (u"KU",  u"Kulinskiy"),
        (u"KM",  u"Kumtorkalinskiy"),
        (u"KS",  u"Kurakhskiy"),
        (u"LA",  u"Lakskiy"),
        (u"LE",  u"Levashinskiy"),
        (u"MG",  u"Magaramkentskiy"),
        (u"MK",  u"Makhachkala"),
        (u"NG",  u"Nogayskiy"),
        (u"NV",  u"Novolakskiy"),
        (u"RU",  u"Rutul'skiy"),
        (u"SE",  u"Sergokalinskiy"),
        (u"SH",  u"Shamil'skiy (Sovetskiy)"),
        (u"SU",  u"Suleyman-Stal'skiy"),
        (u"TB",  u"Tabasaranskiy"),
        (u"TR",  u"Tarumovskiy"),
        (u"TL",  u"Tlyaratinskiy"),
        (u"TM",  u"Tsumadinskiy"),
        (u"TS",  u"Tsuntinskiy"),
        (u"UN",  u"Untsukul'skiy"),
        (u"YU",  u"Yuzhno-Sukhokumsk"),
        ]),

    ((u"GA", u"Gorno-Altay"), [
        (u"CM",  u"Chemal'skiy"),
        (u"CO",  u"Choyskiy"),
        (u"GA",  u"Gorno-Altaysk"),
        (u"KA",  u"Kosh-Agachskiy"),
        (u"MA",  u"Mayminskiy"),
        (u"ON",  u"Ongudayskiy"),
        (u"SH",  u"Shebalinskiy"),
        (u"TU",  u"Turochakskiy"),
        (u"UL",  u"Ulaganskiy"),
        (u"US",  u"Ust'-Kanskiy"),
        (u"UK",  u"Ust'-Koksinskiy"),
        ]),

    ((u"IN", u"Ingush"), [
        (u"DZ",  u"Dzhayrakhskiy"),
        (u"KA",  u"Karabulak"),
        (u"MG",  u"Malgobek"),
        (u"MR",  u"Malgobekskiy"),
        (u"NG",  u"Nazran'"),
        (u"NR",  u"Nazranovskiy"),
        (u"SU",  u"Sunzhenskiy"),
        ]),

    ((u"IK", u"Irkutsk"), [
        (u"AL",  u"Alarskiy"),
        (u"AG",  u"Angarsk"),
        (u"AR",  u"Angarskiy"),
        (u"BA",  u"Balaganskiy"),
        (u"BY",  u"Bayandayevskiy"),
        (u"BR",  u"Bodaybinskiy"),
        (u"BG",  u"Bodaybo"),
        (u"BO",  u"Bokhanskiy"),
        (u"BT",  u"Bratsk"),
        (u"BK",  u"Bratskiy"),
        (u"CG",  u"Cheremkhovo"),
        (u"CR",  u"Cheremkhovskiy"),
        (u"CH",  u"Chunskiy"),
        (u"EK",  u"Ekhirit-Bulagatskiy"),
        (u"IG",  u"Irkutsk"),
        (u"IR",  u"Irkutskiy"),
        (u"KC",  u"Kachugskiy"),
        (u"KT",  u"Katangskiy"),
        (u"KL",  u"Kazachinsko-Lenskiy"),
        (u"KI",  u"Kirenskiy"),
        (u"KU",  u"Kuytunskiy"),
        (u"MA",  u"Mamsko-Chuyskiy"),
        (u"NI",  u"Nizhneilimskiy"),
        (u"NG",  u"Nizhneudinsk"),
        (u"NR",  u"Nizhneudinskiy"),
        (u"NU",  u"Nukutskiy"),
        (u"OL",  u"Ol'khonskiy"),
        (u"OS",  u"Osinskiy"),
        (u"SA",  u"Sayansk"),
        (u"SG",  u"Shelekhov"),
        (u"SR",  u"Shelekhovskiy"),
        (u"SL",  u"Slyudyanskiy"),
        (u"TG",  u"Tayshet"),
        (u"TR",  u"Tayshetskiy"),
        (u"TL",  u"Tulun"),
        (u"TN",  u"Tulunskiy"),
        (u"US",  u"Usol'e-Sibirskoe"),
        (u"UO",  u"Usol'skiy"),
        (u"UI",  u"Ust'-Ilimsk"),
        (u"UT",  u"Ust'-Ilimskiy"),
        (u"UG",  u"Ust'-Kut"),
        (u"UR",  u"Ust'-Kutskiy"),
        (u"UU",  u"Ust'-Udinskiy"),
        (u"ZA",  u"Zalarinskiy"),
        (u"ZH",  u"Zhigalovskiy"),
        (u"ZG",  u"Zima"),
        (u"ZR",  u"Ziminskiy"),
        ]),

    ((u"IV", u"Ivanovo"), [
        (u"FG",  u"Furmanov"),
        (u"FR",  u"Furmanovskiy"),
        (u"GA",  u"Gavrilovo-Posadskiy"),
        (u"IL",  u"Il’inskiy"),
        (u"IG",  u"Ivanovo"),
        (u"IR",  u"Ivanovskiy"),
        (u"KG",  u"Kineshema"),
        (u"KR",  u"Kineshemskiy"),
        (u"KO",  u"Komsomol’skiy"),
        (u"LE",  u"Lezhnevskiy"),
        (u"LU",  u"Lukhskiy"),
        (u"PA",  u"Palekhskiy"),
        (u"PE",  u"Pestyakovskiy"),
        (u"PR",  u"Privolzhskiy"),
        (u"PU",  u"Puchezhskiy"),
        (u"RO",  u"Rodnikovskiy"),
        (u"SA",  u"Savinskiy"),
        (u"SG",  u"Shuya"),
        (u"SR",  u"Shuyskiy"),
        (u"SO",  u"Sokol'skiy"),
        (u"TG",  u"Teykovo"),
        (u"TR",  u"Teykovskiy"),
        (u"VE",  u"Vernelandekhovskiy"),
        (u"VG",  u"Vichuga"),
        (u"VR",  u"Vichugskiy"),
        (u"YR",  u"Yur’evskiy"),
        (u"YZ",  u"Yuzhskiy"),
        (u"ZA",  u"Zavolzhskiy"),
        ]),

    ((u"KB", u"Kabardin-Balkar"), [
        (u"BA",  u"Baksanskiy"),
        (u"CG",  u"Chegemskiy"),
        (u"CR",  u"Cherekskiy (Sovetskiy)"),
        (u"EL",  u"El'brusskiy"),
        (u"MA",  u"Mayskiy"),
        (u"NA",  u"Nal'chik"),
        (u"PR",  u"Prokhladnenskiy"),
        (u"PG",  u"Prokhladniy"),
        (u"TE",  u"Terskiy"),
        (u"TY",  u"Tyrnyauz"),
        (u"UR",  u"Urvanskiy"),
        (u"ZO",  u"Zol'skiy"),
        ]),

    ((u"KN", u"Kaliningrad"), [
        (u"BG",  u"Bagrationovskiy"),
        (u"BL",  u"Baltiysk"),
        (u"CG",  u"Chernyakhovsk"),
        (u"CR",  u"Chernyakhovskiy"),
        (u"GU",  u"Gur'evskiy"),
        (u"GG",  u"Gusev"),
        (u"GR",  u"Gusevskiy"),
        (u"GV",  u"Gvardeyskiy"),
        (u"KA",  u"Kaliningrad"),
        (u"KR",  u"Krasnoznamenskiy"),
        (u"NG",  u"Neman"),
        (u"NR",  u"Nemanskiy"),
        (u"NE",  u"Nesterovskiy"),
        (u"OZ",  u"Ozerskiy"),
        (u"PI",  u"Pionerskiy"),
        (u"PO",  u"Polesskiy"),
        (u"PR",  u"Pravdinskiy"),
        (u"SL",  u"Slavskiy"),
        (u"SO",  u"Sovetsk"),
        (u"SG",  u"Svetlogorsk"),
        (u"SV",  u"Svetlyy"),
        (u"ZE",  u"Zelenogradskiy"),
        ]),

    ((u"KL", u"Kalmyk"), [
        (u"CH",  u"Chernozermel'skiy"),
        (u"EL",  u"Elista"),
        (u"GG",  u"Gorodovikovsk"),
        (u"GR",  u"Gorodovikovskiy"),
        (u"IK",  u"Iki-Burul'skiy"),
        (u"KE",  u"Ketchenerovskiy (Priozeroskiy)"),
        (u"LA",  u"Laganskiy (Kaspiyskiy)"),
        (u"MA",  u"Maloderbetovskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"PR",  u"Priyutnenskiy"),
        (u"SA",  u"Sarpinskiy"),
        (u"TS",  u"Tselinnyy"),
        (u"YA",  u"Yashaltinskiy"),
        (u"YK",  u"Yashkul'skiy"),
        (u"YU",  u"Yustinskiy"),
        ]),

    ((u"KG", u"Kaluga"), [
        (u"BB",  u"Babyninskiy"),
        (u"BR",  u"Baryatinskiy"),
        (u"BO",  u"Borovskiy"),
        (u"DU",  u"Duminichskiy"),
        (u"DZ",  u"Dzerzhinskiy"),
        (u"FE",  u"Ferzikovskiy"),
        (u"IZ",  u"Iznoskovskiy"),
        (u"KA",  u"Kaluga"),
        (u"KH",  u"Khvastovichskiy"),
        (u"KG",  u"Kirov"),
        (u"KR",  u"Kirovskiy"),
        (u"KO",  u"Kozel'skiy"),
        (u"KU",  u"Kuybyshevskiy"),
        (u"LG",  u"Lyudinov"),
        (u"LT",  u"Lyudinovskiy"),
        (u"MA",  u"Maloyaroslavetskiy"),
        (u"MD",  u"Medynskiy"),
        (u"MS",  u"Meshchovskiy"),
        (u"MO",  u"Mosal'skiy"),
        (u"OB",  u"Obninsk"),
        (u"PE",  u"Peremyshl'skiy"),
        (u"SP",  u"Spas-Demenskiy"),
        (u"SU",  u"Sukhinichskiy"),
        (u"TA",  u"Tarusskiy"),
        (u"UL",  u"Ul'yanovskiy"),
        (u"YU",  u"Yukhnovskiy"),
        (u"ZZ",  u"Zhizdrinskiy"),
        (u"ZK",  u"Zhukovskiy"),
        ]),

    ((u"KQ", u"Kamchatka"), [
        (u"AL",  u"Aleutskiy"),
        (u"BY",  u"Bystrinskiy"),
        (u"EG",  u"Elizovo"),
        (u"ER",  u"Elizovskiy"),
        (u"KA",  u"Karaginskiy"),
        (u"MI",  u"Mil'kovskiy"),
        (u"OL",  u"Olyutorskiy"),
        (u"PE",  u"Penzhinskiy"),
        (u"PK",  u"Petropavlovsk-Kamchatskiy"),
        (u"SO",  u"Sobolevskiy"),
        (u"TI",  u"Tigil'skiy"),
        (u"UB",  u"Ust'-Bol'sheretskiy"),
        (u"UK",  u"Ust'-Kamchatskiy"),
        (u"VI",  u"Vilyuchinsk"),
        (u"VU",  u"Vulkannyy Parish"),
        ]),

    ((u"KC", u"Karachay-Cherkess"), [
        (u"AD",  u"Adyge-Khabl'skiy"),
        (u"CH",  u"Cherkessk"),
        (u"KG",  u"Karachayevsk"),
        (u"KR",  u"Karachayevskiy"),
        (u"KH",  u"Khabezskiy"),
        (u"MA",  u"Malokarachayevskiy"),
        (u"PR",  u"Prikubanskiy"),
        (u"UR",  u"Urupskiy"),
        (u"US",  u"Ust'-Dzhegutinskiy"),
        (u"ZE",  u"Zelenchukskiy"),
        ]),

    ((u"KI", u"Karelia"), [
        (u"BE",  u"Belomorskiy"),
        (u"KA",  u"Kaleval'skiy"),
        (u"KG",  u"Kem'"),
        (u"KR",  u"Kemskiy"),
        (u"KN",  u"Kondopoga"),
        (u"KD",  u"Kondopozhskiy"),
        (u"KM",  u"Kostomuksh"),
        (u"LA",  u"Lakhdenpokhskiy"),
        (u"LO",  u"Loukhskiy"),
        (u"ME",  u"Medvezh'egorskiy"),
        (u"MU",  u"Muyezerskiy"),
        (u"OL",  u"Olonetskiy"),
        (u"PE",  u"Petrozavodsk"),
        (u"PG",  u"Pitkyaranta"),
        (u"PR",  u"Pitkyarantskiy"),
        (u"PN",  u"Prionezhskiy"),
        (u"PZ",  u"Pryazhinskiy"),
        (u"PU",  u"Pudozhskiy"),
        (u"SG",  u"Segezh"),
        (u"SR",  u"Segezhskiy"),
        (u"SO",  u"Sortaval'"),
        (u"SU",  u"Suoyarvskiy"),
        (u"VE",  u"Vepsskaya"),
        ]),

    ((u"KE", u"Kemerovo"), [
        (u"AN",  u"Anzhero-Sudzhensk"),
        (u"BG",  u"Belovo"),
        (u"BR",  u"Belovskiy"),
        (u"BZ",  u"Berezovskiy"),
        (u"CH",  u"Chebulinskiy"),
        (u"GG",  u"Gur'evsk"),
        (u"GU",  u"Gur'evskiy"),
        (u"IZ",  u"Izhmorskiy"),
        (u"KA",  u"Kaltan"),
        (u"KG",  u"Kemerovo"),
        (u"KR",  u"Kemerovskiy"),
        (u"KI",  u"Kiselevsk"),
        (u"KP",  u"Krapivinskiy"),
        (u"LG",  u"Leninsk-Kuznetskiy"),
        (u"LR",  u"Leninsk-Kuznetskiy"),
        (u"MG",  u"Mariynsk"),
        (u"MR",  u"Mariynskiy"),
        (u"MD",  u"Mezhdurechensk"),
        (u"MZ",  u"Mezhdurechenskiy"),
        (u"MY",  u"Myski"),
        (u"NG",  u"Novokuznetsk"),
        (u"NR",  u"Novokuznetskiy"),
        (u"OG",  u"Osinniki"),
        (u"OR",  u"Osinnikskiy"),
        (u"PG",  u"Prokop'evsk"),
        (u"PR",  u"Prokop'evskiy"),
        (u"PM",  u"Promyshlennovskiy"),
        (u"TG",  u"Tashtagol"),
        (u"TR",  u"Tashtagol'skiy"),
        (u"TA",  u"Tayga"),
        (u"TI",  u"Tisul'skiy"),
        (u"TK",  u"Topki"),
        (u"TP",  u"Topkinskiy"),
        (u"TY",  u"Tyazhinskiy"),
        (u"YS",  u"Yashkinskiy"),
        (u"YY",  u"Yayskiy"),
        (u"YG",  u"Yurga"),
        (u"YR",  u"Yurginskiy"),
        ]),

    ((u"KH", u"Khabarovsk"), [
        (u"AG",  u"Amursk"),
        (u"AR",  u"Amurskiy"),
        (u"AM",  u"Ayano-Mayskiy"),
        (u"BG",  u"Bikin"),
        (u"BR",  u"Bikinskiy"),
        (u"IL",  u"Imeni Lazo"),
        (u"IP",  u"Imeni Poliny Osipenko"),
        (u"KG",  u"Khabarovsk"),
        (u"KR",  u"Khabarovskiy"),
        (u"KA",  u"Komsomol'sk-na-Amure"),
        (u"KO",  u"Komsomol'skiy"),
        (u"NA",  u"Nanayskiy"),
        (u"NG",  u"Nikolaevsk-na-Amure"),
        (u"NR",  u"Nikolaevskiy"),
        (u"OK",  u"Okhotskiy"),
        (u"SO",  u"Solnechnyy"),
        (u"SG",  u"Sovetskaya Gavan'"),
        (u"SR",  u"Sovetsko-Gavanskiy"),
        (u"TU",  u"Tuguro-Chumikanskiy"),
        (u"UL",  u"Ul'chskiy"),
        (u"VA",  u"Vaninskiy"),
        (u"VE",  u"Verkhnebureinskiy"),
        (u"VY",  u"Vyazemskiy"),
        ]),

    ((u"KK", u"Khakass"), [
        (u"AB",  u"Abakan"),
        (u"AL",  u"Altayskiy"),
        (u"AS",  u"Askizskiy"),
        (u"BE",  u"Beyskiy"),
        (u"BO",  u"Bogradskiy"),
        (u"CH",  u"Chernogorsk"),
        (u"OR",  u"Ordzhonikidzevskiy"),
        (u"SA",  u"Sayanogorsk"),
        (u"SH",  u"Shirinskiy"),
        (u"TA",  u"Tashtypskiy"),
        (u"UA",  u"Ust'-Abakanskiy"),
        ]),

    ((u"KM", u"Khanty-Mansiy"), [
        (u"BG",  u"Beloyarsk"),
        (u"BR",  u"Beloyarskiy"),
        (u"BE",  u"Berezovskiy"),
        (u"KG",  u"Khanty-Mansiysk"),
        (u"KR",  u"Khanty-Mansiyskiy"),
        (u"KO",  u"Kogalym"),
        (u"KD",  u"Kondinskiy"),
        (u"LA",  u"Langepas"),
        (u"ME",  u"Megion"),
        (u"NG",  u"Nefteyugansk"),
        (u"NR",  u"Nefteyuganskiy"),
        (u"NZ",  u"Nizhnevartovsk"),
        (u"NV",  u"Nizhnevartovskiy"),
        (u"NY",  u"Nyagan'"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"PO",  u"Pokachi"),
        (u"PY",  u"Pyt'-Yakh"),
        (u"RA",  u"Raduga"),
        (u"SO",  u"Sovetskiy"),
        (u"SG",  u"Surgut"),
        (u"SR",  u"Surgutskiy"),
        (u"UR",  u"Uraysk"),
        (u"YU",  u"Yugorsk"),
        ]),

    ((u"KV", u"Kirov"), [
        (u"AF",  u"Afanas'evskiy"),
        (u"AR",  u"Arbazhskiy"),
        (u"BE",  u"Belokholunitskiy"),
        (u"BO",  u"Bogorodskiy"),
        (u"DA",  u"Darovskiy"),
        (u"FA",  u"Falenskiy"),
        (u"KK",  u"Kiknurskiy"),
        (u"KZ",  u"Kil'mezskiy"),
        (u"KV",  u"Kirov"),
        (u"KI",  u"Kirovo-Chepetsk"),
        (u"KC",  u"Kirovo-Chepetskiy"),
        (u"KT",  u"Kotel'nich"),
        (u"KO",  u"Kotel'nichskiy"),
        (u"KU",  u"Kumenskiy"),
        (u"LE",  u"Lebyazhskiy"),
        (u"LU",  u"Luzskiy"),
        (u"MA",  u"Malmyzhskiy"),
        (u"MU",  u"Murashinskiy"),
        (u"NA",  u"Nagorskiy"),
        (u"NE",  u"Nemskiy"),
        (u"NO",  u"Nolinskiy"),
        (u"OM",  u"Omutninskiy"),
        (u"OP",  u"Oparinskiy"),
        (u"OR",  u"Orichevskiy"),
        (u"OL",  u"Orlovskiy (Khalturinskiy)"),
        (u"PE",  u"Pervomayskiy Parish"),
        (u"PI",  u"Pizhanskiy"),
        (u"PO",  u"Podosinovskiy"),
        (u"SA",  u"Sanchurskiy"),
        (u"SH",  u"Shabalinskiy"),
        (u"SR",  u"Slobodskoy"),
        (u"SG",  u"Slobodskoy"),
        (u"SO",  u"Sovetskiy"),
        (u"SU",  u"Sunskiy"),
        (u"SV",  u"Svechinskiy"),
        (u"TU",  u"Tuzhinskiy"),
        (u"UN",  u"Uninskiy"),
        (u"UR",  u"Urzhumskiy"),
        (u"VK",  u"Verkhnekamskiy"),
        (u"VS",  u"Verkhoshizhemskiy"),
        (u"VG",  u"Vyatskie Polyany"),
        (u"VR",  u"Vyatsko-Polyanskiy"),
        (u"YA",  u"Yaranskiy"),
        (u"YU",  u"Yur'yanovskiy"),
        (u"ZU",  u"Zuevskiy"),
        ]),

    ((u"KO", u"Komi"), [
        (u"IN",  u"Inta"),
        (u"IZ",  u"Izhemskiy"),
        (u"KN",  u"Knyazhpogostskiy"),
        (u"KR",  u"Kortkerosskiy"),
        (u"KY",  u"Koygorodskiy"),
        (u"PE",  u"Pechora"),
        (u"PR",  u"Priluzskiy"),
        (u"SO",  u"Sosnogorsk"),
        (u"SK",  u"Syktyvdinskiy"),
        (u"SY",  u"Syktyvkar"),
        (u"SS",  u"Sysol'skiy"),
        (u"TR",  u"Troitsko-Pechorskiy"),
        (u"UD",  u"Udorskiy"),
        (u"UA",  u"Ukhta"),
        (u"US",  u"Usinsk"),
        (u"UK",  u"Ust'-Kulomskiy"),
        (u"UT",  u"Ust'-Tsilemskiy"),
        (u"UV",  u"Ust'-Vymskiy"),
        (u"VO",  u"Vorkuta"),
        (u"VU",  u"Vuktyl"),
        ]),

    ((u"KT", u"Kostroma"), [
        (u"AN",  u"Antropovskiy"),
        (u"BG",  u"Buy"),
        (u"BR",  u"Buyskiy"),
        (u"CH",  u"Chukhlomskiy"),
        (u"GG",  u"Galich"),
        (u"GR",  u"Galichskiy"),
        (u"KA",  u"Kadyyskiy"),
        (u"KO",  u"Kologrivskiy"),
        (u"KG",  u"Kostroma"),
        (u"KR",  u"Kostromskoy"),
        (u"KS",  u"Krasnosel'skiy"),
        (u"MA",  u"Makar'evskiy"),
        (u"MG",  u"Manturovo"),
        (u"MR",  u"Manturovskiy"),
        (u"ME",  u"Mezhevskiy"),
        (u"NT",  u"Nerekhta"),
        (u"NK",  u"Nerekhtskiy"),
        (u"NG",  u"Neya"),
        (u"NR",  u"Neyskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OS",  u"Ostrovskiy"),
        (u"PF",  u"Parfen'evskiy"),
        (u"PV",  u"Pavinskiy"),
        (u"PO",  u"Ponazyrevskiy"),
        (u"PY",  u"Pyshchugskiy"),
        (u"SR",  u"Shar'inskiy"),
        (u"SG",  u"Shar'ya"),
        (u"SO",  u"Soligalichskiy"),
        (u"SD",  u"Sudislavskiy"),
        (u"SS",  u"Susaninskiy"),
        (u"VK",  u"Vokhomskiy"),
        (u"VL",  u"Volgorechensk"),
        ]),

    ((u"KD", u"Krasnodar"), [
        (u"AB",  u"Abinskiy"),
        (u"AG",  u"Anapa"),
        (u"AR",  u"Anapskiy"),
        (u"AP",  u"Apsheronskiy"),
        (u"AM",  u"Armavir"),
        (u"BE",  u"Beloglinskiy"),
        (u"BG",  u"Belorechensk"),
        (u"BR",  u"Belorechenskiy"),
        (u"BK",  u"Bryukhovetskiy"),
        (u"DI",  u"Dinskiy"),
        (u"EG",  u"Eysk"),
        (u"ER",  u"Eyskiy"),
        (u"GE",  u"Gelendzhik"),
        (u"GO",  u"Goryachiy Klyuch"),
        (u"GU",  u"Gul'kevichskiy"),
        (u"KI",  u"Kalininskiy"),
        (u"KN",  u"Kanevskiy"),
        (u"KV",  u"Kavkazskiy"),
        (u"KO",  u"Korenovskiy"),
        (u"KA",  u"Krasnoarmeyskiy"),
        (u"KL",  u"Krasnodar"),
        (u"KP",  u"Kropotkin"),
        (u"KY",  u"Krylovskiy"),
        (u"KG",  u"Krymsk"),
        (u"KR",  u"Krymskiy"),
        (u"KU",  u"Kurganinskiy"),
        (u"KS",  u"Kushchevskiy"),
        (u"LG",  u"Labinsk"),
        (u"LR",  u"Labinskiy"),
        (u"LE",  u"Leningradskiy"),
        (u"MO",  u"Mostovskiy"),
        (u"NK",  u"Novokubanskiy"),
        (u"NP",  u"Novopokrovskiy"),
        (u"NR",  u"Novorossiysk"),
        (u"OT",  u"Otradnenskiy"),
        (u"PA",  u"Pavlovskiy"),
        (u"PR",  u"Primorsko-Akhtarskiy"),
        (u"SE",  u"Severskiy"),
        (u"SH",  u"Shcherbinovskiy"),
        (u"SG",  u"Slavyansk-na-Kubani"),
        (u"SR",  u"Slavyanskiy"),
        (u"SO",  u"Sochi"),
        (u"ST",  u"Starominskiy"),
        (u"TB",  u"Tbilisskiy"),
        (u"TE",  u"Temryukskiy"),
        (u"TG",  u"Tikhoretsk"),
        (u"TR",  u"Tikhoretskiy"),
        (u"TI",  u"Timashevskiy"),
        (u"TP",  u"Tuapse"),
        (u"TU",  u"Tuapsinskiy"),
        (u"US",  u"Uspenskiy"),
        (u"UL",  u"Ust'-Labinskiy"),
        (u"VY",  u"Vyselkovskiy"),
        ]),

    ((u"KX", u"Krasnoyarsk"), [
        (u"AB",  u"Abanskiy"),
        (u"AG",  u"Achinsk"),
        (u"AR",  u"Achinskiy"),
        (u"BA",  u"Balakhtinskiy"),
        (u"BY",  u"Baykitskiy"),
        (u"BE",  u"Berezovskiy"),
        (u"BI",  u"Birilyusskiy"),
        (u"BG",  u"Bogotol"),
        (u"BR",  u"Bogotol'skiy"),
        (u"BC",  u"Boguchanskiy"),
        (u"BM",  u"Bol'shemurtinskiy"),
        (u"BL",  u"Bol'sheuluyskiy"),
        (u"BD",  u"Borodino"),
        (u"DI",  u"Diksonskiy"),
        (u"DV",  u"Divnogorsk"),
        (u"DU",  u"Dudinka"),
        (u"DZ",  u"Dzerzhinskiy"),
        (u"EM",  u"Emel'yanovskiy"),
        (u"EG",  u"Eniseysk"),
        (u"ER",  u"Eniseyskiy"),
        (u"EK",  u"Ermakovskiy"),
        (u"ID",  u"Idrinskiy"),
        (u"IG",  u"Igarka"),
        (u"IL",  u"Ilanskiy"),
        (u"IM",  u"Ilimpiyskiy"),
        (u"IR",  u"Irbeyskiy"),
        (u"KG",  u"Kansk"),
        (u"KR",  u"Kanskiy"),
        (u"KA",  u"Karatuzskiy"),
        (u"KZ",  u"Kazachinskiy"),
        (u"KD",  u"Kedrovyy Parish"),
        (u"KE",  u"Kezhemskiy"),
        (u"KH",  u"Khatangskiy"),
        (u"KO",  u"Kozul'skiy"),
        (u"KT",  u"Krasnoturanskiy"),
        (u"KY",  u"Krasnoyarsk"),
        (u"KU",  u"Kuraginskiy"),
        (u"LE",  u"Lesosibirsk"),
        (u"MA",  u"Manskiy"),
        (u"MG",  u"Minusinsk"),
        (u"MR",  u"Minusinskiy"),
        (u"MO",  u"Motyginskiy"),
        (u"NG",  u"Nazarovo"),
        (u"NR",  u"Nazarovskiy"),
        (u"NI",  u"Nizhneingashskiy"),
        (u"NO",  u"Noril'sk"),
        (u"NV",  u"Novoselovskiy"),
        (u"PA",  u"Partizanskiy"),
        (u"PI",  u"Pirovskiy"),
        (u"PO",  u"Podgornyy Parish"),
        (u"RY",  u"Rybinskiy"),
        (u"SA",  u"Sayanskiy"),
        (u"SE",  u"Severo-Eniseyskiy"),
        (u"SG",  u"Sharypovo"),
        (u"SR",  u"Sharypovskiy"),
        (u"SH",  u"Shushenskiy"),
        (u"SL",  u"Solnechnyy Parish"),
        (u"SB",  u"Sosnovoborsk"),
        (u"SU",  u"Sukhobuzimskiy"),
        (u"TA",  u"Taseevskiy"),
        (u"TC",  u"Tungussko-Chunskiy"),
        (u"TU",  u"Turukhanskiy"),
        (u"TY",  u"Tyukhtetskiy"),
        (u"US",  u"Ust'-Yeniseyskiy"),
        (u"UY",  u"Uyarskiy"),
        (u"UZ",  u"Uzhurskiy"),
        (u"ZA",  u"Zaozernyy"),
        (u"ZE",  u"Zelenogorsk"),
        (u"ZH",  u"Zheleznogorsk"),
        ]),

    ((u"KU", u"Kurgan"), [
        (u"AL",  u"Al'menevskiy"),
        (u"BE",  u"Belozerskiy"),
        (u"CH",  u"Chastoozerskiy"),
        (u"DA",  u"Dalmatovskiy"),
        (u"KP",  u"Kargapol'skiy"),
        (u"KT",  u"Katayskiy"),
        (u"KE",  u"Ketovskiy"),
        (u"KG",  u"Kurgan"),
        (u"KU",  u"Kurtamyshskiy"),
        (u"LE",  u"Lebyazh'evskiy"),
        (u"MA",  u"Makushinskiy"),
        (u"MI",  u"Mishkinskiy"),
        (u"MO",  u"Mokroysovskiy"),
        (u"PE",  u"Petukhovskiy"),
        (u"PO",  u"Polovinskiy"),
        (u"PR",  u"Pritobol'nyy"),
        (u"SA",  u"Safakulevskiy"),
        (u"SG",  u"Shadrinsk"),
        (u"SR",  u"Shadrinskiy"),
        (u"SH",  u"Shatrovskiy"),
        (u"SC",  u"Shchuchanskiy"),
        (u"SM",  u"Shumikhinskiy"),
        (u"TS",  u"Tselinnyy"),
        (u"VA",  u"Vargashinskiy"),
        (u"YU",  u"Yurgam'shskiy"),
        (u"ZV",  u"Zverinogolovskiy"),
        ]),

    ((u"KS", u"Kursk"), [
        (u"BE",  u"Belovskiy"),
        (u"BO",  u"Bol'shesoldatskiy"),
        (u"CH",  u"Cheremisinovskiy"),
        (u"DM",  u"Dmitrievskiy"),
        (u"FA",  u"Fatezhskiy"),
        (u"GL",  u"Glushkovskiy"),
        (u"GO",  u"Gorshechenskiy"),
        (u"KA",  u"Kastorenskiy"),
        (u"KH",  u"Khomutovskiy"),
        (u"KN",  u"Konyshevskiy"),
        (u"KO",  u"Korenevskiy"),
        (u"KC",  u"Kurchatov"),
        (u"KU",  u"Kurchatovskiy"),
        (u"KG",  u"Kursk"),
        (u"KR",  u"Kurskiy"),
        (u"LG",  u"L'gov"),
        (u"LR",  u"L'govskiy"),
        (u"MA",  u"Manturovskiy"),
        (u"ME",  u"Medvenskiy"),
        (u"OB",  u"Oboyanskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"PO",  u"Ponyrovskiy"),
        (u"PR",  u"Pristenskiy"),
        (u"RY",  u"Ryl'skiy"),
        (u"SR",  u"Shchigrovskiy"),
        (u"SG",  u"Shchigry"),
        (u"SL",  u"Solntsevskiy"),
        (u"SV",  u"Sovetskiy"),
        (u"SU",  u"Sudzhanskiy"),
        (u"TI",  u"Timskiy"),
        (u"ZG",  u"Zheleznogorsk"),
        (u"ZR",  u"Zheleznogorskiy"),
        (u"ZO",  u"Zolotukhinskiy"),
        ]),

    ((u"LN", u"Leningrad"), [
        (u"BG",  u"Boksitogorsk"),
        (u"BR",  u"Boksitogorskiy"),
        (u"GG",  u"Gatchina"),
        (u"GR",  u"Gatchinskiy"),
        (u"IV",  u"Ivangorod"),
        (u"KN",  u"Kingisepp"),
        (u"KP",  u"Kingiseppskiy"),
        (u"KS",  u"Kirishi"),
        (u"KI",  u"Kirishskiy"),
        (u"KG",  u"Kirovsk"),
        (u"KR",  u"Kirovskiy"),
        (u"LP",  u"Lodeynopoe Pole"),
        (u"LD",  u"Lodeynopol'skiy"),
        (u"LO",  u"Lomonosovskiy"),
        (u"LG",  u"Luga"),
        (u"LR",  u"Luzhskiy"),
        (u"PI",  u"Pikalevo"),
        (u"PD",  u"Podporozh'e"),
        (u"PP",  u"Podporozhskiy"),
        (u"PG",  u"Priozersk"),
        (u"PR",  u"Priozerskiy"),
        (u"SH",  u"Shlissel'burg"),
        (u"SR",  u"Slantsevskiy"),
        (u"SG",  u"Slantsy"),
        (u"SB",  u"Sosnovyy Bor"),
        (u"TI",  u"Tikhvin"),
        (u"TV",  u"Tikhvinskiy"),
        (u"TR",  u"Tosnenskiy"),
        (u"TG",  u"Tosno"),
        (u"VK",  u"Volkhov"),
        (u"VO",  u"Volkhovskiy"),
        (u"VL",  u"Volosovskiy"),
        (u"VS",  u"Vsevolzhsk"),
        (u"VV",  u"Vsevolzhskiy"),
        (u"VG",  u"Vyborg"),
        (u"VR",  u"Vyborgskiy"),
        ]),

    ((u"LP", u"Lipetsk"), [
        (u"CH",  u"Chaplyginskiy"),
        (u"DG",  u"Dankov"),
        (u"DR",  u"Dankovskiy"),
        (u"DB",  u"Dobrinskiy"),
        (u"DV",  u"Dobrovskiy"),
        (u"DL",  u"Dolgorukovskiy"),
        (u"EG",  u"Elets"),
        (u"ER",  u"Eletskiy"),
        (u"GG",  u"Gryazi"),
        (u"GR",  u"Gryazinskiy"),
        (u"IZ",  u"Izmalkovskiy"),
        (u"KH",  u"Khlevenskiy"),
        (u"KR",  u"Krasninskiy"),
        (u"LE",  u"Lebedyanskiy"),
        (u"LT",  u"Lev-Tolstovskiy"),
        (u"LG",  u"Lipetsk"),
        (u"LR",  u"Lipetskiy"),
        (u"ST",  u"Stanovlyanskiy"),
        (u"TE",  u"Terbunskiy"),
        (u"US",  u"Usmanskiy"),
        (u"VO",  u"Volovskiy"),
        (u"ZA",  u"Zadonskiy"),
        ]),

    ((u"MG", u"Magadan"), [
        (u"KH",  u"Khasynskiy"),
        (u"MA",  u"Magadan"),
        (u"OL",  u"Ol'skiy"),
        (u"OM",  u"Omsukchanskiy"),
        (u"SE",  u"Severo-Evenskiy"),
        (u"SR",  u"Srednekanskiy"),
        (u"SU",  u"Susumanskiy"),
        (u"TE",  u"Ten'kinskiy"),
        (u"YA",  u"Yagodninskiy"),
        ]),

    ((u"ME", u"Mariy-El"), [
        (u"GO",  u"Gornomariyskiy"),
        (u"IO",  u"Ioshkar-Ola"),
        (u"KI",  u"Kilemarskiy"),
        (u"KO",  u"Koz'modem'yansk"),
        (u"KU",  u"Kuzhenerskiy"),
        (u"MA",  u"Mari-Turekskiy"),
        (u"ME",  u"Medvedevskiy"),
        (u"MO",  u"Morkinskiy"),
        (u"NO",  u"Novotor'yal'skiy"),
        (u"OR",  u"Orshanskiy"),
        (u"PA",  u"Paran'ginskiy"),
        (u"SE",  u"Sernurskiy"),
        (u"SO",  u"Sovetskiy"),
        (u"VG",  u"Volzhsk"),
        (u"VR",  u"Volzhskiy"),
        (u"YU",  u"Yurinskiy"),
        (u"ZV",  u"Zvenigovskiy"),
        ]),

    ((u"MR", u"Mordovia"), [
        (u"AR",  u"Ardatovskiy"),
        (u"AS",  u"Atyashevskiy"),
        (u"AT",  u"Atyur'evskiy"),
        (u"BB",  u"Bol'shebereznikovskiy"),
        (u"BI",  u"Bol'sheignatovskiy"),
        (u"CH",  u"Chamzinskiy"),
        (u"DU",  u"Dubenskiy"),
        (u"IC",  u"Ichalkovskiy"),
        (u"IN",  u"Insarskiy"),
        (u"KA",  u"Kadoshkinskiy"),
        (u"KO",  u"Kochkurovskiy"),
        (u"KG",  u"Kovylkino"),
        (u"KR",  u"Kovylkinskiy"),
        (u"KS",  u"Krasnoslobodskiy"),
        (u"LY",  u"Lyambirskiy"),
        (u"RO",  u"Romodanovskiy"),
        (u"RG",  u"Ruzaevka"),
        (u"RR",  u"Ruzayevskiy"),
        (u"SA",  u"Saransk"),
        (u"ST",  u"Staroshaygovskiy"),
        (u"TM",  u"Temnikovskiy"),
        (u"TN",  u"Ten'gushevskiy"),
        (u"TO",  u"Torbeevskiy"),
        (u"YE",  u"Yel'nikovskiy"),
        (u"ZU",  u"Zubovo-Polyanskiy"),
        ]),

    ((u"MC", u"Moscow City"), [
        (u"SE",  u"Severniy"),
        (u"SV",  u"Severovostochniy"),
        (u"SZ",  u"Severozapadniy"),
        (u"TS",  u"Tsentralniy"),
        (u"VO",  u"Vostochniy"),
        (u"YV",  u"Yugovostochniy"),
        (u"YZ",  u"Yugozapadniy"),
        (u"YU",  u"Yushniy"),
        (u"ZA",  u"Zapadniy"),
        (u"ZE",  u"Zelenograd"),
        ]),

    ((u"MS", u"Moskva"), [
        (u"BG",  u"Balashikha"),
        (u"BR",  u"Balashikhinskiy"),
        (u"BN",  u"Bronnitsy"),
        (u"CG",  u"Chekhov"),
        (u"CR",  u"Chekhovskiy"),
        (u"DG",  u"Dmitrov"),
        (u"DR",  u"Dmitrovskiy"),
        (u"DP",  u"Dolgopudnyy"),
        (u"DO",  u"Domodedovo"),
        (u"DD",  u"Domodedovskiy"),
        (u"DU",  u"Dubna"),
        (u"DZ",  u"Dzerzhinskyy"),
        (u"ER",  u"Egor'evsk"),
        (u"EG",  u"Egor'evskiy"),
        (u"EL",  u"Elektrostal'"),
        (u"FR",  u"Fryazino"),
        (u"IG",  u"Istra"),
        (u"IR",  u"Istrinskiy"),
        (u"IV",  u"Ivanteevka"),
        (u"KA",  u"Kashira"),
        (u"KI",  u"Kashirskiy"),
        (u"KK",  u"Khimki"),
        (u"KH",  u"Khimkinskiy"),
        (u"KL",  u"Klimovsk"),
        (u"KG",  u"Klin"),
        (u"KR",  u"Klinskiy"),
        (u"KO",  u"Kolomenskiy"),
        (u"KM",  u"Kolomna"),
        (u"KV",  u"Korolev (Kaliningrad)"),
        (u"KY",  u"Krasnoarmeysk"),
        (u"KS",  u"Krasnogorsk"),
        (u"KN",  u"Krasnogorskiy"),
        (u"KZ",  u"Krasnoznamensk"),
        (u"LE",  u"Leninskiy"),
        (u"LB",  u"Lobnya"),
        (u"LT",  u"Lotoshinskiy"),
        (u"LU",  u"Lukhovitskiy"),
        (u"LY",  u"Lytkarino"),
        (u"LR",  u"Lyuberetskiy"),
        (u"LG",  u"Lyuberetsy"),
        (u"MO",  u"Molodezhnyy Parish"),
        (u"MG",  u"Mozhaysk"),
        (u"MR",  u"Mozhayskiy"),
        (u"MY",  u"Mytishchi"),
        (u"MT",  u"Mytishchinskiy"),
        (u"NA",  u"Naro-Fominsk"),
        (u"NF",  u"Naro-Fominskiy"),
        (u"NG",  u"Noginsk"),
        (u"NR",  u"Noginskiy"),
        (u"OT",  u"Odintsovo"),
        (u"OD",  u"Odintsovskiy"),
        (u"OK",  u"Orekhovo-Zuevo"),
        (u"OZ",  u"Orekhovo-Zuevskiy"),
        (u"OR",  u"Ozerskiy"),
        (u"OG",  u"Ozery"),
        (u"PV",  u"Pavlovo-Posadskiy"),
        (u"PP",  u"Pavlovskiy Posad"),
        (u"PD",  u"Podol'sk"),
        (u"PO",  u"Podol'skiy"),
        (u"PK",  u"Prioksk Parish"),
        (u"PT",  u"Protvino"),
        (u"PU",  u"Pushchino"),
        (u"PG",  u"Pushkino"),
        (u"PR",  u"Pushkinskiy"),
        (u"RR",  u"Ramenskiy"),
        (u"RG",  u"Ramenskoe"),
        (u"RE",  u"Reutov"),
        (u"RO",  u"Roshal'"),
        (u"RU",  u"Ruzskiy"),
        (u"SP",  u"Serebryano-Prudskiy"),
        (u"SG",  u"Sergiev Posad (Zagorsk)"),
        (u"SR",  u"Sergievo-Posadskiy (Zagorskiy)"),
        (u"SE",  u"Serpukhov"),
        (u"SK",  u"Serpukhovskiy"),
        (u"SH",  u"Shakhovskoy"),
        (u"ST",  u"Shatura"),
        (u"SA",  u"Shaturskiy"),
        (u"SL",  u"Shchelkovo"),
        (u"SV",  u"Shchelkovskiy"),
        (u"SC",  u"Shcherbinka"),
        (u"SS",  u"Solnechnogorsk"),
        (u"SO",  u"Solnechnogorskiy"),
        (u"SN",  u"Stupino"),
        (u"SU",  u"Stupinskiy"),
        (u"TA",  u"Taldomskiy"),
        (u"TR",  u"Troitsk"),
        (u"VI",  u"Vidnoe"),
        (u"VL",  u"Volokolamsk"),
        (u"VK",  u"Volokolamskiy"),
        (u"VO",  u"Voskhod Parish"),
        (u"VG",  u"Voskresensk"),
        (u"VR",  u"Voskresenskiy"),
        (u"YU",  u"Yubileynyy"),
        (u"ZG",  u"Zaraysk"),
        (u"ZR",  u"Zarayskiy"),
        (u"ZZ",  u"Zheleznodorozhnyy"),
        (u"ZH",  u"Zhukovskiy"),
        (u"ZV",  u"Zvenigorod"),
        ]),

    ((u"MM", u"Murmansk"), [
        (u"AP",  u"Apatity"),
        (u"KA",  u"Kandalaksha"),
        (u"KI",  u"Kirovsk"),
        (u"KL",  u"Kol'skiy"),
        (u"KV",  u"Kovdorskiy"),
        (u"LE",  u"Levozerskiy"),
        (u"MO",  u"Monchegorsk"),
        (u"MU",  u"Murmansk"),
        (u"OL",  u"Olenegorsk"),
        (u"OS",  u"Ostrovnoy"),
        (u"PE",  u"Pechengskiy"),
        (u"PO",  u"Polyarnye"),
        (u"PZ",  u"Polyarnye Zori"),
        (u"SE",  u"Severomorsk"),
        (u"SK",  u"Skalistiy"),
        (u"SN",  u"Snezhnogorsk"),
        (u"TE",  u"Terskiy"),
        (u"ZA",  u"Zaozersk"),
        ]),

    ((u"NN", u"Nenets"), [
        (u"AM",  u"Amderma and Rural"),
        (u"IS",  u"Iskateley"),
        (u"NA",  u"Nar'yan-Mar"),
        ]),

    ((u"NZ", u"Nizhegorod"), [
        (u"AT",  u"Ardatovskiy"),
        (u"AG",  u"Arzamas"),
        (u"AR",  u"Arzamasskiy"),
        (u"BL",  u"Balakhna"),
        (u"BA",  u"Balakhninskiy"),
        (u"BO",  u"Bogorodsk"),
        (u"BD",  u"Bogorodskiy"),
        (u"BB",  u"Bol'sheboldinskiy"),
        (u"BM",  u"Bol'shemurashkinskiy"),
        (u"BG",  u"Bor"),
        (u"BR",  u"Borskiy"),
        (u"BU",  u"Buturlinskiy"),
        (u"CH",  u"Chkalovskiy"),
        (u"DA",  u"Dal'nekonstantinovskiy"),
        (u"DI",  u"Diveevskiy"),
        (u"DZ",  u"Dzerzhinsk"),
        (u"GA",  u"Gaginskiy"),
        (u"GG",  u"Gorodets"),
        (u"GR",  u"Gorodetskiy"),
        (u"KN",  u"Knyagininskiy"),
        (u"KV",  u"Koverninskiy"),
        (u"KB",  u"Krasnobakovskiy"),
        (u"KO",  u"Krasnooktyabr'skiy"),
        (u"KG",  u"Kstovo"),
        (u"KR",  u"Kstovskiy"),
        (u"KK",  u"Kulebaki"),
        (u"KU",  u"Kulebakskiy"),
        (u"LU",  u"Lukoyanovskiy"),
        (u"LY",  u"Lyskovskiy"),
        (u"NA",  u"Navashinskiy"),
        (u"NI",  u"Nizhniy Novgorod"),
        (u"PG",  u"Pavlovo"),
        (u"PR",  u"Pavlovskiy"),
        (u"PV",  u"Perevozskiy"),
        (u"PM",  u"Pervomayskiy"),
        (u"PI",  u"Pil'ninskiy"),
        (u"PO",  u"Pochinkovskiy"),
        (u"SA",  u"Sarov"),
        (u"SC",  u"Sechenovskiy"),
        (u"SM",  u"Semenovskiy"),
        (u"SG",  u"Sergachskiy"),
        (u"SK",  u"Shakhunskiy"),
        (u"SR",  u"Sharangskiy"),
        (u"ST",  u"Shatkovskiy"),
        (u"SO",  u"Sokol'skiy"),
        (u"SS",  u"Sosnovskiy"),
        (u"SP",  u"Spasskiy"),
        (u"TK",  u"Tonkinskiy"),
        (u"TS",  u"Tonshaevskiy"),
        (u"UR",  u"Urenskiy"),
        (u"VC",  u"Vachskiy"),
        (u"VD",  u"Vadskiy"),
        (u"VV",  u"Varnavinskiy"),
        (u"VE",  u"Vetluzhskiy"),
        (u"VL",  u"Volodarskiy"),
        (u"VT",  u"Vorotynskiy"),
        (u"VS",  u"Voskresenskiy"),
        (u"VZ",  u"Voznesenskiy"),
        (u"VG",  u"Vyksa"),
        (u"VR",  u"Vyksunskiy"),
        ]),

    ((u"NO", u"North Ossetia"), [
        (u"AL",  u"Alagirskiy"),
        (u"AR",  u"Ardonskiy"),
        (u"BE",  u"Beslan"),
        (u"DI",  u"Digorskiy"),
        (u"IR",  u"Irafskiy"),
        (u"KI",  u"Kirovskiy"),
        (u"MO",  u"Mozdokskiy"),
        (u"PB",  u"Pravoberezhnyy"),
        (u"PG",  u"Prigorodskiy"),
        (u"VL",  u"Vladikavkaz"),
        ]),

    ((u"NG", u"Novgorod"), [
        (u"BA",  u"Batetskiy"),
        (u"BG",  u"Borovichi"),
        (u"BR",  u"Borovichskiy"),
        (u"CH",  u"Chudovskiy"),
        (u"DE",  u"Demyanskiy"),
        (u"KH",  u"Kholmskiy"),
        (u"KV",  u"Khvoyninskiy"),
        (u"KR",  u"Krestetskiy"),
        (u"LY",  u"Lyubytinskiy"),
        (u"MV",  u"Malovisherskiy"),
        (u"MA",  u"Marevskiy"),
        (u"MO",  u"Moshenskiy"),
        (u"NO",  u"Novgorodskiy"),
        (u"OK",  u"Okulovskiy"),
        (u"PA",  u"Parfinskiy"),
        (u"PE",  u"Pestovskiy"),
        (u"PO",  u"Poddorskiy"),
        (u"SH",  u"Shimskiy"),
        (u"SO",  u"Soletskiy"),
        (u"SG",  u"Staraya Russa"),
        (u"SR",  u"Starorusskiy"),
        (u"VA",  u"Valdayskiy"),
        (u"BE",  u"Velikiy Novgorod"),
        (u"VO",  u"Volotovskiy"),
        ]),

    ((u"NS", u"Novosibirsk"), [
        (u"BA",  u"Baganskiy"),
        (u"BG",  u"Barabinsk"),
        (u"BR",  u"Barabinskiy"),
        (u"BE",  u"Berdsk"),
        (u"BO",  u"Bolotninskiy"),
        (u"CN",  u"Chanovskiy"),
        (u"CR",  u"Cherepanovskiy"),
        (u"CS",  u"Chistoozernyy"),
        (u"CL",  u"Chulymskiy"),
        (u"DO",  u"Dovolenskiy"),
        (u"IG",  u"Iskitim"),
        (u"IR",  u"Iskitimskiy"),
        (u"KS",  u"Karasukskiy"),
        (u"KA",  u"Kargatskiy"),
        (u"KN",  u"Kochenevskiy"),
        (u"KO",  u"Kochkovskiy"),
        (u"KL",  u"Kolyvanovskiy"),
        (u"KZ",  u"Krasnozerskiy"),
        (u"KU",  u"Kupinskiy"),
        (u"KG",  u"Kuybyshev"),
        (u"KR",  u"Kuybyshevskiy"),
        (u"KY",  u"Kyshtovskiy"),
        (u"MA",  u"Maslyaninskiy"),
        (u"MO",  u"Moshkovskiy"),
        (u"NG",  u"Novosibirsk"),
        (u"NR",  u"Novosibirskiy"),
        (u"OB",  u"Ob'"),
        (u"OR",  u"Ordynskiy"),
        (u"SE",  u"Severnyy"),
        (u"SU",  u"Suzunskiy"),
        (u"TG",  u"Tatarsk"),
        (u"TR",  u"Tatarskiy"),
        (u"TO",  u"Toguchinskiy"),
        (u"UB",  u"Ubinskiy"),
        (u"US",  u"Ust'-Tarkskiy"),
        (u"VE",  u"Vengerovskiy"),
        (u"ZD",  u"Zdvinskiy"),
        ]),

    ((u"OM", u"Omsk"), [
        (u"AZ",  u"Azovskiy Nemetskiy"),
        (u"BR",  u"Bol'sherechenskiy"),
        (u"BU",  u"Bol'sheukovskiy"),
        (u"CH",  u"Cherlakskiy"),
        (u"GO",  u"Gor'kovskiy"),
        (u"IG",  u"Isil'kul'"),
        (u"IR",  u"Isil'kul'skiy"),
        (u"KG",  u"Kalachinsk"),
        (u"KR",  u"Kalachinskiy"),
        (u"KS",  u"Kolosovskiy"),
        (u"KM",  u"Kormilovskiy"),
        (u"KT",  u"Krutinskiy"),
        (u"LY",  u"Lyubinskiy"),
        (u"MA",  u"Mar'yanovskiy"),
        (u"MO",  u"Moskalenskiy"),
        (u"MU",  u"Muromtsevskiy"),
        (u"NG",  u"Nazyvaevsk"),
        (u"NR",  u"Nazyvaevskiy"),
        (u"NI",  u"Nizhneomskiy"),
        (u"NO",  u"Novovarshavskiy"),
        (u"OD",  u"Odesskiy"),
        (u"OK",  u"Okoneshnikovskiy"),
        (u"OG",  u"Omsk"),
        (u"OR",  u"Omskiy"),
        (u"PA",  u"Pavlogradskiy"),
        (u"PO",  u"Poltavskiy"),
        (u"RU",  u"Russko-Polyanskiy"),
        (u"SA",  u"Sargatskiy"),
        (u"SE",  u"Sedel'nikovskiy"),
        (u"SH",  u"Sherbakul'skiy"),
        (u"TG",  u"Tara"),
        (u"TR",  u"Tarskiy"),
        (u"TA",  u"Tavricheskiy"),
        (u"TE",  u"Tevrizskiy"),
        (u"TK",  u"Tyukalinsk"),
        (u"TY",  u"Tyukalinskiy"),
        (u"US",  u"Ust'-Ishimskiy"),
        (u"ZN",  u"Znamenskiy"),
        ]),

    ((u"OL", u"Orel"), [
        (u"BO",  u"Bolkhovskiy"),
        (u"DM",  u"Dmitrovskiy"),
        (u"DO",  u"Dolzhanskiy"),
        (u"GL",  u"Glazunovskiy"),
        (u"KH",  u"Khotynetskiy"),
        (u"KL",  u"Kolpnyanskiy"),
        (u"KS",  u"Korsakovskiy"),
        (u"KZ",  u"Krasnozorenskiy"),
        (u"KR",  u"Kromskiy"),
        (u"LR",  u"Livenskiy"),
        (u"LG",  u"Livny"),
        (u"MA",  u"Maloarkhangel'skiy"),
        (u"MG",  u"Mtsensk"),
        (u"MR",  u"Mtsenskiy"),
        (u"ND",  u"Novodereven'kovskiy"),
        (u"NS",  u"Novosil'skiy"),
        (u"OG",  u"Orel"),
        (u"OR",  u"Orlovskiy"),
        (u"PO",  u"Pokrovskiy"),
        (u"SH",  u"Shablykinskiy"),
        (u"SO",  u"Soskovskiy"),
        (u"SV",  u"Sverdlovskiy"),
        (u"TR",  u"Trosnyanskiy"),
        (u"UR",  u"Uritskiy"),
        (u"VE",  u"Verkhovskiy"),
        (u"ZA",  u"Zalegoshchenskiy"),
        (u"ZN",  u"Znamenskiy"),
        ]),

    ((u"OB", u"Orenburg"), [
        (u"AG",  u"Abdulino"),
        (u"AR",  u"Abdulinskiy"),
        (u"AD",  u"Adamovskiy"),
        (u"AK",  u"Akbulakskiy"),
        (u"AL",  u"Aleksandrovskiy"),
        (u"AS",  u"Asekeevskiy"),
        (u"BE",  u"Belyaevskiy"),
        (u"BN",  u"Buguruslan"),
        (u"BU",  u"Buguruslanskiy"),
        (u"BG",  u"Buzuluk"),
        (u"BR",  u"Buzulukskiy"),
        (u"DO",  u"Dombarovskiy"),
        (u"GG",  u"Gay"),
        (u"GR",  u"Gayskiy"),
        (u"GC",  u"Grachevskiy"),
        (u"IL",  u"Ilekskiy"),
        (u"KO",  u"Komarovskiy Parish"),
        (u"KS",  u"Krasnogvardeyskiy"),
        (u"KU",  u"Kurmanaevskiy"),
        (u"KG",  u"Kuvandyk"),
        (u"KR",  u"Kuvandykskiy"),
        (u"KV",  u"Kvarkenskiy"),
        (u"MA",  u"Matveevskiy"),
        (u"ME",  u"Mednogorsk"),
        (u"NO",  u"Novoorskiy"),
        (u"NS",  u"Novosergievskiy"),
        (u"NT",  u"Novotroitsk"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OG",  u"Orenburg"),
        (u"OR",  u"Orenburgskiy"),
        (u"OS",  u"Orsk"),
        (u"PT",  u"Perevolotskiy"),
        (u"PM",  u"Pervomayskiy"),
        (u"PO",  u"Ponomarevskiy"),
        (u"SM",  u"Sakmarskiy"),
        (u"SA",  u"Saraktashskiy"),
        (u"SE",  u"Severnyy"),
        (u"SH",  u"Sharlykskiy"),
        (u"SI",  u"Sol'-Iletskiy"),
        (u"SG",  u"Sorochinsk"),
        (u"SR",  u"Sorochinskiy"),
        (u"SV",  u"Svetlinskiy"),
        (u"TA",  u"Tashlinskiy"),
        (u"TO",  u"Totskiy"),
        (u"TY",  u"Tyul'ganskiy"),
        (u"YR",  u"Yasnenskiy"),
        (u"YG",  u"Yasnyy"),
        ]),

    ((u"PZ", u"Penza"), [
        (u"BA",  u"Bashmakovskiy"),
        (u"BD",  u"Bednodem'yanovskiy"),
        (u"BK",  u"Bekovskiy"),
        (u"BL",  u"Belinskiy"),
        (u"BS",  u"Bessonovskiy"),
        (u"GO",  u"Gorodishchenskiy"),
        (u"IS",  u"Issinskiy"),
        (u"KM",  u"Kamenka"),
        (u"KN",  u"Kamenskiy"),
        (u"KK",  u"Kameshkirskiy"),
        (u"KL",  u"Kolyshleyskiy"),
        (u"KO",  u"Kondol'skiy"),
        (u"KG",  u"Kuznetsk"),
        (u"KR",  u"Kuznetskiy"),
        (u"LO",  u"Lopatinskiy"),
        (u"LU",  u"Luninskiy"),
        (u"MA",  u"Maloserdobinskiy"),
        (u"MO",  u"Mokshanskiy"),
        (u"NA",  u"Narovchatskiy"),
        (u"NE",  u"Neverkinskiy"),
        (u"NI",  u"Nikol'skiy"),
        (u"NR",  u"Nizhnelomovskiy"),
        (u"NG",  u"Nizhniy Lomov"),
        (u"PA",  u"Pachelmskiy"),
        (u"PG",  u"Penza"),
        (u"PR",  u"Penzenskiy"),
        (u"SG",  u"Serdobsk"),
        (u"SR",  u"Serdobskiy"),
        (u"SH",  u"Shemysheyskiy"),
        (u"SO",  u"Sosnovoborskiy"),
        (u"TA",  u"Tamalinskiy"),
        (u"VA",  u"Vadinskiy"),
        (u"ZA",  u"Zarechnyy"),
        (u"ZE",  u"Zemetchinskiy"),
        ]),

    ((u"PE", u"Perm'"), [
        (u"AL",  u"Aleksandrovsk"),
        (u"BA",  u"Bardymskiy"),
        (u"BE",  u"Berezniki"),
        (u"BZ",  u"Berezovskiy"),
        (u"BO",  u"Bol'shesosnovskiy"),
        (u"CA",  u"Chastinskiy"),
        (u"CG",  u"Chaykovskiy"),
        (u"CR",  u"Chaykovskiy"),
        (u"CD",  u"Cherdynskiy"),
        (u"CN",  u"Chernushinskiy"),
        (u"CU",  u"Chusovoy"),
        (u"CS",  u"Chusovskiy"),
        (u"DG",  u"Dobryanka"),
        (u"DR",  u"Dobryanskiy"),
        (u"EL",  u"Elovskiy"),
        (u"GA",  u"Gaynskiy"),
        (u"GO",  u"Gornozavodskiy"),
        (u"GR",  u"Gremyachinsk"),
        (u"GU",  u"Gubakha"),
        (u"IL",  u"Il'inskiy"),
        (u"KA",  u"Karagayskiy"),
        (u"KI",  u"Kishertskiy"),
        (u"KZ",  u"Kizel"),
        (u"KC",  u"Kochevskiy"),
        (u"KS",  u"Kosinskiy"),
        (u"KK",  u"Krasnokamsk"),
        (u"KV",  u"Krasnovisherskiy"),
        (u"KM",  u"Kudymkar"),
        (u"KD",  u"Kudymkarskiy"),
        (u"KU",  u"Kuedinskiy"),
        (u"KG",  u"Kungur"),
        (u"KR",  u"Kungurskiy"),
        (u"LG",  u"Lys'va"),
        (u"LR",  u"Lys'venskiy"),
        (u"NY",  u"Nytvenskiy"),
        (u"OC",  u"Ocherskiy"),
        (u"OK",  u"Okhanskiy"),
        (u"OT",  u"Oktyabr'skiy"),
        (u"OR",  u"Ordinskiy"),
        (u"OS",  u"Osinskiy"),
        (u"PG",  u"Perm'"),
        (u"PR",  u"Permskiy"),
        (u"SI",  u"Sivinskiy"),
        (u"SG",  u"Solikamsk"),
        (u"SR",  u"Solikamskiy"),
        (u"SU",  u"Suksunskiy"),
        (u"UI",  u"Uinskiy"),
        (u"US",  u"Usol'skiy"),
        (u"VE",  u"Vereshchaginskiy"),
        (u"YR",  u"Yurlinskiy"),
        (u"YS",  u"Yus'vinskiy"),
        (u"ZV",  u"Zvezdnyy Parish"),
        ]),

    ((u"PR", u"Primor'ye"), [
        (u"AN",  u"Anuchinskiy"),
        (u"AS",  u"Arsen'ev"),
        (u"AT",  u"Artem"),
        (u"BO",  u"Bol'shoy Kamen'"),
        (u"CR",  u"Chernigovskiy"),
        (u"CG",  u"Chuguevskiy"),
        (u"DG",  u"Dal'negorsk"),
        (u"DR",  u"Dal'negorskiy"),
        (u"DC",  u"Dal'nerechensk"),
        (u"DL",  u"Dal'nerechenskiy"),
        (u"FO",  u"Fokino"),
        (u"KA",  u"Kavalerovskiy"),
        (u"KK",  u"Khankayskiy"),
        (u"KS",  u"Khasanskiy"),
        (u"KO",  u"Khorol'skiy"),
        (u"KI",  u"Kirovskiy"),
        (u"KR",  u"Krasnoarmeyskiy"),
        (u"LA",  u"Lazovskiy"),
        (u"LG",  u"Lesozavodsk"),
        (u"LR",  u"Lesozavodskiy"),
        (u"MI",  u"Mikhaylovskiy"),
        (u"ND",  u"Nadezhdinskiy"),
        (u"NK",  u"Nakhodka"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OL",  u"Ol'ginskiy"),
        (u"PG",  u"Partizansk"),
        (u"PR",  u"Partizanskiy"),
        (u"PN",  u"Pogranichnyy"),
        (u"PZ",  u"Pozharskiy"),
        (u"SH",  u"Shkotovskiy"),
        (u"SD",  u"Spassk-Dal'nyy"),
        (u"SP",  u"Spasskiy"),
        (u"TE",  u"Terneyskiy"),
        (u"UG",  u"Ussuriysk"),
        (u"UR",  u"Ussuriyskiy"),
        (u"VL",  u"Vladivostok"),
        (u"YA",  u"Yakovlevskiy"),
        ]),

    ((u"PS", u"Pskov"), [
        (u"BE",  u"Bezhanitskiy"),
        (u"DE",  u"Dedovichskiy"),
        (u"DN",  u"Dnovskiy"),
        (u"GD",  u"Gdovskiy"),
        (u"KR",  u"Krasnogorodskiy"),
        (u"KU",  u"Kun'inskiy"),
        (u"LO",  u"Loknyanskiy"),
        (u"NE",  u"Nevel'skiy"),
        (u"NR",  u"Novorzhevskiy"),
        (u"NS",  u"Novosokol'nicheskiy"),
        (u"OP",  u"Opochetskiy"),
        (u"OG",  u"Ostrov"),
        (u"OR",  u"Ostrovskiy"),
        (u"PA",  u"Palkinskiy"),
        (u"PE",  u"Pechorskiy"),
        (u"PL",  u"Plyusskiy"),
        (u"PO",  u"Porkhovskiy"),
        (u"PG",  u"Pskov"),
        (u"PR",  u"Pskovskiy"),
        (u"PU",  u"Pushkino-Gorskiy"),
        (u"PS",  u"Pustoshkinskiy"),
        (u"PY",  u"Pytalovskiy"),
        (u"SE",  u"Sebezhskiy"),
        (u"ST",  u"Strugo-Krasnenskiy"),
        (u"US",  u"Usvyatskiy"),
        (u"VG",  u"Velikie Luki"),
        (u"VR",  u"Velikolukskiy"),
        ]),

    ((u"RO", u"Rostov"), [
        (u"AK",  u"Aksayskiy"),
        (u"AG",  u"Azov"),
        (u"AR",  u"Azovskiy"),
        (u"BA",  u"Bagaevskiy"),
        (u"BT",  u"Bataysk"),
        (u"BG",  u"Belaya Kalitva"),
        (u"BR",  u"Belokalitvinskiy"),
        (u"BO",  u"Bokovskiy"),
        (u"CH",  u"Chertkovskiy"),
        (u"DO",  u"Donetsk"),
        (u"DU",  u"Dubovskiy"),
        (u"EG",  u"Egorlykskiy"),
        (u"GU",  u"Gukovo"),
        (u"KA",  u"Kagal'nitskiy"),
        (u"KG",  u"Kamensk-Shakhtinskiy"),
        (u"KR",  u"Kamenskiy"),
        (u"KH",  u"Kasharskiy"),
        (u"KO",  u"Konstantinovskiy"),
        (u"KN",  u"Krasnosulinskiy"),
        (u"KS",  u"Krasnyy Sulin"),
        (u"KU",  u"Kuybyshevskiy"),
        (u"MA",  u"Martynovskiy"),
        (u"MK",  u"Matveevo-Kurganskiy"),
        (u"MG",  u"Millerovo"),
        (u"MR",  u"Millerovskiy"),
        (u"MI",  u"Milyutinskiy"),
        (u"MO",  u"Morozovskiy"),
        (u"MY",  u"Myasnikovskiy"),
        (u"NE",  u"Neklinovskiy"),
        (u"NC",  u"Novocherkassk"),
        (u"NS",  u"Novoshakhtinsk"),
        (u"OB",  u"Oblivskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OR",  u"Orlovskiy"),
        (u"PE",  u"Peschanokopskiy"),
        (u"PR",  u"Proletarskiy"),
        (u"RE",  u"Remontnenskiy"),
        (u"RN",  u"Rodionovo-Nesvetayskiy"),
        (u"RD",  u"Rostov-na-Donu"),
        (u"SG",  u"Sal'sk"),
        (u"SR",  u"Sal'skiy"),
        (u"SE",  u"Semikarakorskiy"),
        (u"SH",  u"Shakhty"),
        (u"SK",  u"Sholokhovskiy"),
        (u"SO",  u"Sovetskiy"),
        (u"TG",  u"Taganrog"),
        (u"TR",  u"Tarasovskiy"),
        (u"TT",  u"Tatsinskiy"),
        (u"TS",  u"Tselinskiy"),
        (u"TM",  u"Tsimlyanskiy"),
        (u"UD",  u"Ust'-Donetskiy"),
        (u"VK",  u"Verkhnedonskoy"),
        (u"VS",  u"Veselovskiy"),
        (u"VG",  u"Volgodonsk"),
        (u"VR",  u"Volgodonskiy"),
        (u"ZA",  u"Zavetinskiy"),
        (u"ZE",  u"Zernogradskiy"),
        (u"ZI",  u"Zimovnikovskiy"),
        (u"ZV",  u"Zverevo"),
        ]),

    ((u"RZ", u"Ryazan'"), [
        (u"CH",  u"Chuchkovskiy"),
        (u"ER",  u"Ermishevskiy"),
        (u"KA",  u"Kadomskiy"),
        (u"KG",  u"Kasimov"),
        (u"KR",  u"Kasimovskiy"),
        (u"KL",  u"Klepikovskiy"),
        (u"KO",  u"Korablinskiy"),
        (u"MK",  u"Mikhaylovskiy"),
        (u"ML",  u"Miloslavskiy"),
        (u"NO",  u"Novoderevenskiy"),
        (u"PI",  u"Pitelinskiy"),
        (u"PR",  u"Pronskiy"),
        (u"PU",  u"Putyatinskiy"),
        (u"RG",  u"Ryazan'"),
        (u"RR",  u"Ryazanskiy"),
        (u"RZ",  u"Ryazhskiy"),
        (u"RB",  u"Rybnovskiy"),
        (u"SK",  u"Sapozhkovskiy"),
        (u"SA",  u"Saraevskiy"),
        (u"SV",  u"Sasovo"),
        (u"SS",  u"Sasovskiy"),
        (u"ST",  u"Shatskiy"),
        (u"SL",  u"Shilovskiy"),
        (u"SG",  u"Skopin"),
        (u"SR",  u"Skopinskiy"),
        (u"SP",  u"Spasskiy"),
        (u"SZ",  u"Starozhilovskiy"),
        (u"UK",  u"Ukholovskiy"),
        (u"ZA",  u"Zakharovskiy"),
        ]),

    ((u"SP", u"Saint Petersburg City"), [
        (u"AD",  u"Admiralteyskiy"),
        (u"CE",  u"Centralniy"),
        (u"FR",  u"Frunzenskiy"),
        (u"KA",  u"Kalininskiy"),
        (u"KI",  u"Kirovskiy"),
        (u"KO",  u"Kolpinskiy"),
        (u"KG",  u"Krasnogvardeyskiy"),
        (u"KS",  u"Krasnoselskiy"),
        (u"KR",  u"Kronstadtskiy"),
        (u"KU",  u"Kurortniy"),
        (u"LO",  u"Lomonosovskiy"),
        (u"MO",  u"Moskovskiy"),
        (u"NE",  u"Nevskiy"),
        (u"PA",  u"Pavlovskiy"),
        (u"PD",  u"Petrodvortsovyiy"),
        (u"PG",  u"Petrogradskiy"),
        (u"PR",  u"Primorskiy"),
        (u"PU",  u"Pushkinskiy"),
        (u"VA",  u"Vasileostrovskiy"),
        (u"VY",  u"Vyborgskiy"),
        ]),

    ((u"SK", u"Sakha"), [
        (u"AB",  u"Abyyskiy"),
        (u"AL",  u"Aldanskiy"),
        (u"AI",  u"Allaikhovskiy"),
        (u"AM",  u"Amginskiy"),
        (u"AN",  u"Anabarskiy"),
        (u"BU",  u"Bulunskiy"),
        (u"CH",  u"Churapchinskiy"),
        (u"EV",  u"Eveno-Bytantayskiy"),
        (u"GO",  u"Gornyy"),
        (u"KH",  u"Khangalasskiy (Ordzhonikidzkiy)"),
        (u"KO",  u"Kobyayskiy"),
        (u"LE",  u"Lenskiy"),
        (u"ME",  u"Megino-Kangalasskiy"),
        (u"MR",  u"Mirninskiy"),
        (u"MG",  u"Mirnyy"),
        (u"MO",  u"Momskiy"),
        (u"NA",  u"Namskiy"),
        (u"NE",  u"Neryungri"),
        (u"NI",  u"Nizhnekolymskiy"),
        (u"NG",  u"Nyurba"),
        (u"NR",  u"Nyurbinskiy (Leninskiy)"),
        (u"OL",  u"Olekminskiy"),
        (u"ON",  u"Olenekskiy"),
        (u"OY",  u"Oymyakonskiy"),
        (u"PO",  u"Pokrovsk"),
        (u"SR",  u"Srednekolymskiy"),
        (u"SU",  u"Suntarskiy"),
        (u"TA",  u"Tattinskiy (Alekseyevskiy)"),
        (u"TO",  u"Tomponskiy"),
        (u"UA",  u"Ust'-Aldanskiy"),
        (u"UM",  u"Ust'-Mayskiy"),
        (u"UY",  u"Ust'-Yanskiy"),
        (u"VK",  u"Verkhnekolymskiy"),
        (u"VV",  u"Verkhnevilyuyskiy"),
        (u"VE",  u"Verkhoyanskiy"),
        (u"VI",  u"Vilyuyskiy"),
        (u"YA",  u"Yakutsk"),
        (u"ZH",  u"Zhiganskiy"),
        ]),

    ((u"SL", u"Sakhalin"), [
        (u"AG",  u"Aleksandrovsk-Sakhalinskiy"),
        (u"AR",  u"Aleksandrovsk-Sakhalinskiy"),
        (u"AN",  u"Anivskiy"),
        (u"DG",  u"Dolinsk"),
        (u"DR",  u"Dolinskiy"),
        (u"KG",  u"Kholmsk"),
        (u"KR",  u"Kholmskiy"),
        (u"KO",  u"Korsakov"),
        (u"KK",  u"Korsakovskiy"),
        (u"KU",  u"Kuril'skiy"),
        (u"MA",  u"Makarovskiy"),
        (u"NG",  u"Nevel'sk"),
        (u"NR",  u"Nevel'skiy"),
        (u"NO",  u"Noglikskiy"),
        (u"OG",  u"Okha"),
        (u"OR",  u"Okhinskiy"),
        (u"PG",  u"Poronaysk"),
        (u"PR",  u"Poronayskiy"),
        (u"SE",  u"Severo-Kuril'skiy"),
        (u"SM",  u"Smirnykhovskiy"),
        (u"TO",  u"Tomarinskiy"),
        (u"TY",  u"Tymovskiy"),
        (u"UG",  u"Uglegorsk"),
        (u"UR",  u"Uglegorskiy"),
        (u"YK",  u"Yuzhno-Kuril'skiy"),
        (u"YS",  u"Yuzhno-Sakhalinsk"),
        ]),

    ((u"SA", u"Samara"), [
        (u"AL",  u"Alekseevskiy"),
        (u"BE",  u"Bezenchukskiy"),
        (u"BT",  u"Bogatovskiy"),
        (u"BC",  u"Bol'shechernigovskiy"),
        (u"BG",  u"Bol'sheglushitskiy"),
        (u"BR",  u"Borskiy"),
        (u"CP",  u"Chapaevsk"),
        (u"CV",  u"Chelno-Vershinskiy"),
        (u"EL",  u"Elkhovskiy"),
        (u"IS",  u"Isaklinskiy"),
        (u"KM",  u"Kamyshlinskiy"),
        (u"KH",  u"Khvorostyanskiy"),
        (u"KG",  u"Kinel'"),
        (u"KC",  u"Kinel'-Cherkasskiy"),
        (u"KR",  u"Kinel'skiy"),
        (u"KL",  u"Klyavlinskiy"),
        (u"KO",  u"Koshkinskiy"),
        (u"KA",  u"Krasnoarmeyskiy"),
        (u"KY",  u"Krasnoyarskiy"),
        (u"NE",  u"Neftegorskiy"),
        (u"NO",  u"Novokuybyshevsk"),
        (u"OK",  u"Oktyabr'sk"),
        (u"OT",  u"Otradnyy"),
        (u"PE",  u"Pestravskiy"),
        (u"PG",  u"Pokhvistnevo"),
        (u"PR",  u"Pokhvistnevskiy"),
        (u"PV",  u"Privolzhskiy"),
        (u"SA",  u"Samara"),
        (u"SE",  u"Sergievskiy"),
        (u"SH",  u"Shentalinskiy"),
        (u"SI",  u"Shigonskiy"),
        (u"ST",  u"Stavropol'skiy"),
        (u"SG",  u"Syzran'"),
        (u"SR",  u"Syzranskiy"),
        (u"TO",  u"Tol'yatti"),
        (u"VO",  u"Volzhskiy"),
        (u"ZH",  u"Zhigulevsk"),
        ]),

    ((u"SR", u"Saratov"), [
        (u"AL",  u"Aleksandrovo-Gayskiy"),
        (u"AD",  u"Arkadakskiy"),
        (u"AG",  u"Atkarsk"),
        (u"AR",  u"Atkarskiy"),
        (u"BG",  u"Balakovo"),
        (u"BR",  u"Balakovskiy"),
        (u"BL",  u"Balashov"),
        (u"BS",  u"Balashovskiy"),
        (u"BA",  u"Baltayskiy"),
        (u"BK",  u"Bazarno-Karabulakskiy"),
        (u"DE",  u"Dergachevskiy"),
        (u"DU",  u"Dukhovnitskiy"),
        (u"EK",  u"Ekaterinovskiy"),
        (u"EG",  u"Engel's"),
        (u"ER",  u"Engel'sskiy"),
        (u"ES",  u"Ershovskiy"),
        (u"FE",  u"Fedorovskiy"),
        (u"IV",  u"Ivanteevskiy"),
        (u"KA",  u"Kalininskiy"),
        (u"KV",  u"Khvalynsk"),
        (u"KH",  u"Khvalynskiy"),
        (u"KG",  u"Krasnoarmeysk"),
        (u"KR",  u"Krasnoarmeyskiy"),
        (u"KK",  u"Krasnokutskiy"),
        (u"KP",  u"Krasnopartizanskiy"),
        (u"LY",  u"Lysogorskiy"),
        (u"MG",  u"Marks"),
        (u"MR",  u"Marksovskiy"),
        (u"NB",  u"Novoburasskiy"),
        (u"NU",  u"Novouzenskiy"),
        (u"OZ",  u"Ozinskiy"),
        (u"PE",  u"Perelyubskiy"),
        (u"PT",  u"Petrovsk"),
        (u"PV",  u"Petrovskiy"),
        (u"PI",  u"Piterskiy"),
        (u"PG",  u"Pugachev"),
        (u"PR",  u"Pugachevskiy"),
        (u"RM",  u"Romanovskiy"),
        (u"RV",  u"Rovenskiy"),
        (u"RG",  u"Rtishchevo"),
        (u"RR",  u"Rtishchevskiy"),
        (u"SA",  u"Samoylovskiy"),
        (u"SG",  u"Saratov"),
        (u"SR",  u"Saratovskiy"),
        (u"SH",  u"Shikhany"),
        (u"SO",  u"Sovetskiy"),
        (u"SV",  u"Svetlyy Parish"),
        (u"TA",  u"Tatishchevskiy"),
        (u"TU",  u"Turkovskiy"),
        (u"VG",  u"Vol'sk"),
        (u"VR",  u"Vol'skiy"),
        (u"VO",  u"Voskresenskiy"),
        ]),

    ((u"SM", u"Smolensk"), [
        (u"DM",  u"Demidovskiy"),
        (u"DS",  u"Desnogorsk"),
        (u"DO",  u"Dorogobuzhskiy"),
        (u"DU",  u"Dukhovshchinskiy"),
        (u"EL",  u"El'ninskiy"),
        (u"ER",  u"Ershichskiy"),
        (u"GG",  u"Gagarin"),
        (u"GR",  u"Gagarinskiy"),
        (u"GL",  u"Glinkovskiy"),
        (u"KA",  u"Kardymovskiy"),
        (u"KH",  u"Khislavichskiy"),
        (u"KZ",  u"Kholm-Zhirkovskiy"),
        (u"KR",  u"Krasninskiy"),
        (u"MO",  u"Monastyrshchinskiy"),
        (u"NO",  u"Novoduginskiy"),
        (u"PO",  u"Pochinkovskiy"),
        (u"RG",  u"Roslavl'"),
        (u"RR",  u"Roslavl'skiy"),
        (u"RU",  u"Rudnyanskiy"),
        (u"SV",  u"Safonovo"),
        (u"SF",  u"Safonovskiy"),
        (u"SH",  u"Shumyachskiy"),
        (u"SG",  u"Smolensk"),
        (u"SR",  u"Smolenskiy"),
        (u"SY",  u"Sychevskiy"),
        (u"TE",  u"Temkinskiy"),
        (u"UG",  u"Ugranskiy"),
        (u"VE",  u"Velizhskiy"),
        (u"VG",  u"Vyaz'ma"),
        (u"VR",  u"Vyazemskiy"),
        (u"YG",  u"Yartsevo"),
        (u"YR",  u"Yartsevskiy"),
        ]),

    ((u"ST", u"Stavropol'"), [
        (u"AL",  u"Aleksandrovskiy"),
        (u"AN",  u"Andropovskiy"),
        (u"AP",  u"Apanasenkovskiy"),
        (u"AR",  u"Arzgirskiy"),
        (u"BL",  u"Blagodarnenskiy"),
        (u"BG",  u"Budennovsk"),
        (u"BR",  u"Budennovskiy"),
        (u"ES",  u"Essentuki"),
        (u"GG",  u"Georgievsk"),
        (u"GR",  u"Georgievskiy"),
        (u"GC",  u"Grachevskiy"),
        (u"IP",  u"Ipatovskiy"),
        (u"IZ",  u"Izobil'nenskiy"),
        (u"KI",  u"Kirovskiy"),
        (u"KS",  u"Kislovodsk"),
        (u"KO",  u"Kochubeevskiy"),
        (u"KR",  u"Krasnogvardeyskiy"),
        (u"KY",  u"Kyrskiy"),
        (u"LR",  u"Lermontov"),
        (u"LV",  u"Levokumskiy"),
        (u"MG",  u"Mineral'nye Vody"),
        (u"MR",  u"Mineralovodskiy"),
        (u"NF",  u"Neftekumskiy"),
        (u"NV",  u"Nevinnomyssk"),
        (u"NA",  u"Novoaleksandrovskiy"),
        (u"NS",  u"Novoselitskiy"),
        (u"PE",  u"Petrovskiy"),
        (u"PR",  u"Predgornyy"),
        (u"PY",  u"Pyatigorsk"),
        (u"SH",  u"Shpakovskiy"),
        (u"SO",  u"Sovetskiy"),
        (u"SP",  u"Stavropol'"),
        (u"SN",  u"Stepnovskiy"),
        (u"TR",  u"Trunovskiy"),
        (u"TU",  u"Turkmenskiy"),
        (u"ZH",  u"Zheleznovodsk"),
        ]),

    ((u"SV", u"Sverdlovsk"), [
        (u"AC",  u"Achitskiy"),
        (u"AG",  u"Alapaevsk"),
        (u"AR",  u"Alapaevskiy"),
        (u"AT",  u"Artemovsk"),
        (u"AM",  u"Artemovskiy"),
        (u"AN",  u"Artinskiy"),
        (u"AS",  u"Asbest"),
        (u"BA",  u"Baykalovskiy"),
        (u"BY",  u"Beloyarskiy"),
        (u"BE",  u"Berezovskiy"),
        (u"BG",  u"Bogdanovich"),
        (u"BR",  u"Bogdanovichskiy"),
        (u"EK",  u"Ekaterinburg"),
        (u"GA",  u"Garinskiy"),
        (u"IG",  u"Irbit"),
        (u"IR",  u"Irbitskiy"),
        (u"IV",  u"Ivdel'"),
        (u"KC",  u"Kachkanar"),
        (u"KU",  u"Kamensk-Ural'skiy"),
        (u"KN",  u"Kamenskiy"),
        (u"KA",  u"Kamyshlov"),
        (u"KM",  u"Kamyshlovskiy"),
        (u"KP",  u"Karpinsk"),
        (u"KI",  u"Kirovgrad"),
        (u"KT",  u"Krasnotur'insk"),
        (u"KG",  u"Krasnoufimsk"),
        (u"KR",  u"Krasnoufimskiy"),
        (u"KS",  u"Krasnoural'sk"),
        (u"KV",  u"Kushva"),
        (u"LE",  u"Lesnoy"),
        (u"NG",  u"Nev'yansk"),
        (u"NR",  u"Nev'yanskiy"),
        (u"NS",  u"Nizhneserginskiy"),
        (u"NT",  u"Nizhniy Tagil"),
        (u"NZ",  u"Nizhniy Tura"),
        (u"NY",  u"Nizhnyaya Salda"),
        (u"NL",  u"Novolyalinskiy"),
        (u"NU",  u"Novoural'sk"),
        (u"PE",  u"Pervoural'sk"),
        (u"PO",  u"Polevskoy"),
        (u"PR",  u"Prigorodnyy"),
        (u"PY",  u"Pyshminskiy"),
        (u"RE",  u"Revda"),
        (u"RG",  u"Rezh"),
        (u"RR",  u"Rezhevskiy"),
        (u"SG",  u"Serov"),
        (u"SR",  u"Serovskiy"),
        (u"SU",  u"Severoural'sk"),
        (u"SH",  u"Shalinskiy"),
        (u"ST",  u"Slobodo-Turinskiy"),
        (u"SK",  u"Sukholozhskiy"),
        (u"SL",  u"Sukhoy Log"),
        (u"SV",  u"Svobodnyy Parish"),
        (u"SY",  u"Sysertskiy"),
        (u"TB",  u"Taborinskiy"),
        (u"TL",  u"Talitskiy"),
        (u"TG",  u"Tavda"),
        (u"TR",  u"Tavdinskiy"),
        (u"TM",  u"Tugulymskiy"),
        (u"TN",  u"Turinskiy"),
        (u"UR",  u"Ural'skiy Parish"),
        (u"VE",  u"Verkhnesaldinskiy"),
        (u"VP",  u"Verkhnyaya Pyshma"),
        (u"VS",  u"Verkhnyaya Salda"),
        (u"VT",  u"Verkhoturskiy"),
        (u"ZA",  u"Zarechnyy"),
        ]),

    ((u"TB", u"Tambov"), [
        (u"BO",  u"Bondarskiy"),
        (u"GA",  u"Gavrilovskiy"),
        (u"IN",  u"Inzhavinskiy"),
        (u"KG",  u"Kirsanov"),
        (u"KR",  u"Kirsanovskiy"),
        (u"KO",  u"Kotovsk"),
        (u"MG",  u"Michurinsk"),
        (u"MR",  u"Michurinskiy"),
        (u"MD",  u"Mordovskiy"),
        (u"MS",  u"Morshansk"),
        (u"MO",  u"Morshanskiy"),
        (u"MU",  u"Muchkapskiy"),
        (u"NI",  u"Nikiforovskiy"),
        (u"PR",  u"Pervomayskiy"),
        (u"PT",  u"Petrovskiy"),
        (u"PI",  u"Pichaevskiy"),
        (u"RG",  u"Rasskazovo"),
        (u"RR",  u"Rasskazovskiy"),
        (u"RZ",  u"Rzhaksinskiy"),
        (u"SA",  u"Sampurskiy"),
        (u"SO",  u"Sosnovskiy"),
        (u"ST",  u"Staroyur'evskiy"),
        (u"TG",  u"Tambov"),
        (u"TR",  u"Tambovskiy"),
        (u"TO",  u"Tokarevskiy"),
        (u"UM",  u"Umetskiy"),
        (u"UG",  u"Uvarovo"),
        (u"UR",  u"Uvarovskiy"),
        (u"ZH",  u"Zherdevskiy"),
        (u"ZN",  u"Znamenskiy"),
        ]),

    ((u"TT", u"Tatarstan"), [
        (u"AY",  u"Agryzskiy"),
        (u"AB",  u"Aksubayevskiy"),
        (u"AT",  u"Aktanyshskiy"),
        (u"AK",  u"Al'keevskiy"),
        (u"AG",  u"Al'met'evsk"),
        (u"AR",  u"Al'met'evskiy"),
        (u"AE",  u"Alekseevskiy"),
        (u"AP",  u"Apastovskiy"),
        (u"AS",  u"Arskiy"),
        (u"AN",  u"Atninskiy"),
        (u"AZ",  u"Aznakaevo"),
        (u"AV",  u"Aznakaevskiy"),
        (u"BA",  u"Baltasinskiy"),
        (u"BV",  u"Bavli"),
        (u"BL",  u"Bavlinskiy"),
        (u"BG",  u"Bugul'ma"),
        (u"BR",  u"Bugul'minskiy"),
        (u"BU",  u"Buinskiy"),
        (u"CH",  u"Cheremshanskiy"),
        (u"CG",  u"Chistopol'"),
        (u"CR",  u"Chistopol'skiy"),
        (u"DR",  u"Drozhzhanovskiy"),
        (u"KU",  u"Kamsko-Ust'inskiy"),
        (u"KY",  u"Kaybitskiy"),
        (u"KZ",  u"Kazan'"),
        (u"KK",  u"Kukmorskiy"),
        (u"KB",  u"Kuybyshev (Spasskiy)"),
        (u"LA",  u"Laishevskiy"),
        (u"LG",  u"Leninogorsk"),
        (u"LR",  u"Leninogorskiy"),
        (u"MA",  u"Mamadyshskiy"),
        (u"MD",  u"Mendeleyevskiy"),
        (u"MZ",  u"Menzelinskiy"),
        (u"MU",  u"Muslyumovskiy"),
        (u"NA",  u"Naberezhnye Chelny"),
        (u"NG",  u"Nizhnekamsk"),
        (u"NR",  u"Nizhnekamskiy"),
        (u"NO",  u"Novosheshminskiy"),
        (u"NU",  u"Nurlat"),
        (u"NL",  u"Nurlatskiy"),
        (u"PE",  u"Pestrechinskiy"),
        (u"RY",  u"Rybno-Slobodskiy"),
        (u"SB",  u"Sabinskiy"),
        (u"SR",  u"Sarmanovskiy"),
        (u"TE",  u"Tetyushskiy"),
        (u"TU",  u"Tukayevskiy"),
        (u"TY",  u"Tyulyachinskiy"),
        (u"VE",  u"Verkhneuslonskiy"),
        (u"VY",  u"Vysokogorskiy"),
        (u"YG",  u"Yelabuga"),
        (u"YR",  u"Yelabuzhskiy"),
        (u"YU",  u"Yutazinskiy"),
        (u"ZN",  u"Zainsk"),
        (u"ZA",  u"Zainskiy"),
        (u"ZG",  u"Zelenodol'sk"),
        (u"ZR",  u"Zelenodol'skiy"),
        ]),

    ((u"TO", u"Tomsk"), [
        (u"AL",  u"Aleksandrovskiy"),
        (u"AG",  u"Asino"),
        (u"AR",  u"Asinovskiy"),
        (u"BA",  u"Bakcharskiy"),
        (u"CH",  u"Chainskiy"),
        (u"KA",  u"Kargasokskiy"),
        (u"KE",  u"Kedrovyy"),
        (u"KG",  u"Kolpashevo"),
        (u"KR",  u"Kolpashevskiy"),
        (u"KO",  u"Kozhevnikovskiy"),
        (u"KS",  u"Krivosheinskiy"),
        (u"MO",  u"Molchanovskiy"),
        (u"PA",  u"Parabel'skiy"),
        (u"PE",  u"Pervomayskiy"),
        (u"SE",  u"Seversk"),
        (u"SH",  u"Shegarskiy"),
        (u"ST",  u"Strezhevoy"),
        (u"TE",  u"Tegul'detskiy"),
        (u"TG",  u"Tomsk"),
        (u"TR",  u"Tomskiy"),
        (u"VE",  u"Verkhneketskiy"),
        (u"ZY",  u"Zyryanskiy"),
        ]),

    ((u"TL", u"Tula"), [
        (u"AG",  u"Aleksin"),
        (u"AR",  u"Aleksinskiy"),
        (u"AN",  u"Arsen'evskiy"),
        (u"BE",  u"Belevskiy"),
        (u"BG",  u"Bogoroditsk"),
        (u"BR",  u"Bogoroditskiy"),
        (u"CH",  u"Chernskiy"),
        (u"DO",  u"Donskoy"),
        (u"DU",  u"Dubenskiy"),
        (u"EG",  u"Efremov"),
        (u"ER",  u"Efremovskiy"),
        (u"KA",  u"Kamenskiy"),
        (u"KG",  u"Kimovsk"),
        (u"KR",  u"Kimovskiy"),
        (u"KI",  u"Kireevskiy"),
        (u"KU",  u"Kurkinskiy"),
        (u"LE",  u"Leninskiy"),
        (u"NG",  u"Novomoskovsk"),
        (u"NR",  u"Novomoskovskiy"),
        (u"OD",  u"Odoevskiy"),
        (u"PL",  u"Plavskiy"),
        (u"SG",  u"Shchekino"),
        (u"SR",  u"Shchekinskiy"),
        (u"SU",  u"Suvorovskiy"),
        (u"TE",  u"Teplo-Ogarevskiy"),
        (u"TU",  u"Tula"),
        (u"UG",  u"Uzlovaya"),
        (u"UR",  u"Uzlovskiy"),
        (u"VE",  u"Venevskiy"),
        (u"VO",  u"Volovskiy"),
        (u"YA",  u"Yasnogorskiy"),
        (u"ZA",  u"Zaokskiy"),
        ]),

    ((u"TU", u"Tuva"), [
        (u"AK",  u"Ak-Dovurak"),
        (u"BK",  u"Barun-Khemchikskiy"),
        (u"BT",  u"Bay-Tayginskiy"),
        (u"CA",  u"Chaa-Khol'skiy"),
        (u"CK",  u"Chedi-Khol'skiy"),
        (u"DZ",  u"Dzun-Khemchikskiy"),
        (u"ER",  u"Erzinskiy"),
        (u"KA",  u"Kaa-Khemskiy"),
        (u"KG",  u"Kyzyl"),
        (u"KR",  u"Kyzylskiy"),
        (u"MO",  u"Mongun-Tayginskiy"),
        (u"OV",  u"Ovyurskiy"),
        (u"PI",  u"Piy-Khemskiy"),
        (u"SU",  u"Sut-Khol'skiy"),
        (u"TA",  u"Tandinskiy"),
        (u"TE",  u"Tes-Khemskiy"),
        (u"TO",  u"Todzhinskiy"),
        (u"UL",  u"Ulug-Khemskiy"),
        ]),

    ((u"TV", u"Tver'"), [
        (u"AN",  u"Andreapol'skiy"),
        (u"BE",  u"Bel'skiy"),
        (u"BT",  u"Bezhetsk"),
        (u"BZ",  u"Bezhetskiy"),
        (u"BG",  u"Bologoe"),
        (u"BR",  u"Bologovskiy"),
        (u"FI",  u"Firovskiy"),
        (u"KN",  u"Kalininskiy (Tverskoy)"),
        (u"KZ",  u"Kalyazinskiy"),
        (u"KA",  u"Kashin"),
        (u"KS",  u"Kashinskiy"),
        (u"KE",  u"Kesovogorskiy"),
        (u"KM",  u"Kimrskiy"),
        (u"KI",  u"Kimry"),
        (u"KG",  u"Konakovo"),
        (u"KR",  u"Konakovskiy"),
        (u"KK",  u"Krasnokholmskiy"),
        (u"KU",  u"Kuvshinovskiy"),
        (u"LE",  u"Lesnoy"),
        (u"LI",  u"Likhoslavl'skiy"),
        (u"MA",  u"Maksatikhinskiy"),
        (u"MO",  u"Molokovskiy"),
        (u"NG",  u"Nelidovo"),
        (u"NR",  u"Nelidovskiy"),
        (u"OL",  u"Oleninskiy"),
        (u"OG",  u"Ostashkov"),
        (u"OR",  u"Ostashkovskiy"),
        (u"OZ",  u"Ozernyy Parish"),
        (u"PE",  u"Penovskiy"),
        (u"RA",  u"Rameshkovskiy"),
        (u"RG",  u"Rzhev"),
        (u"RR",  u"Rzhevskiy"),
        (u"SA",  u"Sandovskiy"),
        (u"SE",  u"Selizharovskiy"),
        (u"SL",  u"Solnechnyy Parish"),
        (u"SN",  u"Sonkovskiy"),
        (u"SP",  u"Spirovskiy"),
        (u"ST",  u"Staritskiy"),
        (u"TO",  u"Toropetskiy"),
        (u"TG",  u"Torzhok"),
        (u"TR",  u"Torzhokskiy"),
        (u"TV",  u"Tver'"),
        (u"UR",  u"Udomel'skiy"),
        (u"UG",  u"Udomlya"),
        (u"VE",  u"Ves'egonskiy"),
        (u"VR",  u"Vyshnevolotskiy"),
        (u"VG",  u"Vyshniy Volochek"),
        (u"ZA",  u"Zapadnodvinskiy"),
        (u"ZH",  u"Zharkovskiy"),
        (u"ZU",  u"Zubtsovskiy"),
        ]),

    ((u"TY", u"Tyumen'"), [
        (u"AB",  u"Abatskiy"),
        (u"AZ",  u"Armizonskiy"),
        (u"AS",  u"Aromashevskiy"),
        (u"BE",  u"Berdyuzhskiy"),
        (u"GO",  u"Golyshmanovskiy"),
        (u"IS",  u"Isetskiy"),
        (u"IG",  u"Ishim"),
        (u"IR",  u"Ishimskiy"),
        (u"KA",  u"Kazanskiy"),
        (u"NI",  u"Nizhnetavdinskiy"),
        (u"OM",  u"Omutinskiy"),
        (u"SL",  u"Sladkovskiy"),
        (u"SO",  u"Sorokinskiy"),
        (u"TB",  u"Tobol'sk"),
        (u"TO",  u"Tobol'skiy"),
        (u"TG",  u"Tyumen'"),
        (u"TR",  u"Tyumenskiy"),
        (u"UP",  u"Uporovskiy"),
        (u"UV",  u"Uvatskiy"),
        (u"VA",  u"Vagayskiy"),
        (u"VI",  u"Vikulovskiy"),
        (u"YG",  u"Yalutorovsk"),
        (u"YR",  u"Yalutorovskiy"),
        (u"YA",  u"Yarkovskiy"),
        (u"YU",  u"Yurginskiy"),
        (u"ZG",  u"Zavodoukovsk"),
        (u"ZR",  u"Zavodoukovskiy"),
        ]),

    ((u"UD", u"Udmurt"), [
        (u"AL",  u"Alnashskiy"),
        (u"BA",  u"Balezinskiy"),
        (u"DE",  u"Debesskiy"),
        (u"GG",  u"Glazov"),
        (u"GR",  u"Glazovskiy"),
        (u"GK",  u"Grakhovskiy"),
        (u"IG",  u"Igrinskiy"),
        (u"IZ",  u"Izhevsk"),
        (u"KM",  u"Kambarskiy"),
        (u"KK",  u"Karakulinskiy"),
        (u"KE",  u"Kezskiy"),
        (u"KY",  u"Kiyasovskiy"),
        (u"KZ",  u"Kiznerskiy"),
        (u"KR",  u"Krasnogorskiy"),
        (u"MA",  u"Malopurginskiy"),
        (u"MG",  u"Mozhga"),
        (u"MR",  u"Mozhginskiy"),
        (u"SG",  u"Sarapul"),
        (u"SR",  u"Sarapul'skiy"),
        (u"SE",  u"Seltinskiy"),
        (u"SH",  u"Sharkanskiy"),
        (u"SY",  u"Syumsinskiy"),
        (u"UV",  u"Uvinskiy"),
        (u"VA",  u"Vavozhskiy"),
        (u"VG",  u"Votkinsk"),
        (u"VR",  u"Votkinskiy"),
        (u"YB",  u"Yakshur-Bod'inskiy"),
        (u"YA",  u"Yarskiy"),
        (u"YU",  u"Yukamenskiy"),
        (u"ZA",  u"Zav'yalovskiy"),
        ]),

    ((u"UL", u"Ul'yanovsk"), [
        (u"BG",  u"Barysh"),
        (u"BR",  u"Baryshskiy"),
        (u"BZ",  u"Bazarnosyzganskiy"),
        (u"CH",  u"Cherdaklinskiy"),
        (u"DI",  u"Dimitrovgrad"),
        (u"IN",  u"Inzenskiy"),
        (u"KA",  u"Karsunskiy"),
        (u"KU",  u"Kuzovatovskiy"),
        (u"MA",  u"Maynskiy"),
        (u"ME",  u"Melekesskiy"),
        (u"NI",  u"Nikolaevskiy"),
        (u"NM",  u"Novomalyklinskiy"),
        (u"NS",  u"Novospasskiy"),
        (u"PA",  u"Pavlovskiy"),
        (u"RA",  u"Radishchevskiy"),
        (u"SE",  u"Sengileevskiy"),
        (u"SK",  u"Starokulatkinskiy"),
        (u"SM",  u"Staromaynskiy"),
        (u"SU",  u"Surskiy"),
        (u"TE",  u"Teren'gul'skiy"),
        (u"TS",  u"Tsil'ninskiy"),
        (u"UG",  u"Ul'yanovsk"),
        (u"UR",  u"Ul'yanovskiy"),
        (u"VE",  u"Veshkaymskiy"),
        ]),

    ((u"VL", u"Vladimir"), [
        (u"AG",  u"Aleksandrov"),
        (u"AR",  u"Aleksandrovskiy"),
        (u"GO",  u"Gorokhovetskiy"),
        (u"GR",  u"Gus'-Khrustal'nyy"),
        (u"GG",  u"Gus'-Khrustal'nyy"),
        (u"KA",  u"Kameshkovskiy"),
        (u"KI",  u"Kirzhachskiy"),
        (u"KL",  u"Kol'chugino"),
        (u"KC",  u"Kol'chuginskiy"),
        (u"KG",  u"Kovrov"),
        (u"KR",  u"Kovrovskiy"),
        (u"ME",  u"Melenkovskiy"),
        (u"MG",  u"Murom"),
        (u"MR",  u"Muromskiy"),
        (u"PE",  u"Petushinskiy"),
        (u"RA",  u"Raduzhnyy"),
        (u"SE",  u"Selivanovskiy"),
        (u"SO",  u"Sobinka"),
        (u"SB",  u"Sobinskiy"),
        (u"SU",  u"Sudogodskiy"),
        (u"SG",  u"Suzdal'"),
        (u"SR",  u"Suzdal'skiy"),
        (u"VL",  u"Vladimir"),
        (u"VG",  u"Vyazniki"),
        (u"VR",  u"Vyaznikovskiy"),
        (u"YP",  u"Yur'ev-Pol'skiy"),
        ]),

    ((u"VG", u"Volgograd"), [
        (u"AL",  u"Alekseevskiy"),
        (u"BY",  u"Bykovskiy"),
        (u"CH",  u"Chernyshkovskiy"),
        (u"DA",  u"Danilovskiy"),
        (u"DU",  u"Dubovskiy"),
        (u"EL",  u"Elanskiy"),
        (u"FG",  u"Frolovo"),
        (u"FR",  u"Frolovskiy"),
        (u"GO",  u"Gorodishchenskiy"),
        (u"IL",  u"Ilovlinskiy"),
        (u"KA",  u"Kalachevskiy"),
        (u"KG",  u"Kamyshin"),
        (u"KR",  u"Kamyshinskiy"),
        (u"KI",  u"Kikvidzenskiy"),
        (u"KL",  u"Kletskiy"),
        (u"KT",  u"Kotel'nikovskiy"),
        (u"KV",  u"Kotovskiy"),
        (u"KU",  u"Kumylzhenskiy (Podtelkovskiy)"),
        (u"LE",  u"Leninskiy"),
        (u"MG",  u"Mikhaylovka"),
        (u"MR",  u"Mikhaylovskiy"),
        (u"NE",  u"Nekhaevskiy"),
        (u"NI",  u"Nikolaevskiy"),
        (u"NA",  u"Novoanninskiy"),
        (u"NN",  u"Novonikolaevskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"OL",  u"Ol'khovskiy"),
        (u"PA",  u"Pallasovskiy"),
        (u"RU",  u"Rudnyanskiy"),
        (u"SE",  u"Serafimovichskiy"),
        (u"SR",  u"Sredneakhtubinskiy"),
        (u"ST",  u"Staropoltavskiy"),
        (u"SU",  u"Surovikinskiy"),
        (u"SV",  u"Svetloyarskiy"),
        (u"UG",  u"Uryupinsk"),
        (u"UR",  u"Uryupinskiy"),
        (u"VG",  u"Volgograd (Tsaritsyn)"),
        (u"VZ",  u"Volzhskiy"),
        (u"ZH",  u"Zhirnovskiy"),
        ]),

    ((u"VO", u"Vologda"), [
        (u"BV",  u"Babaevskiy"),
        (u"BS",  u"Babushkinskiy"),
        (u"BE",  u"Belozerskiy"),
        (u"CH",  u"Chagodoshchenskiy"),
        (u"CG",  u"Cherepovets"),
        (u"CR",  u"Cherepovetskiy"),
        (u"GR",  u"Gryazovetskiy"),
        (u"KA",  u"Kaduyskiy"),
        (u"KH",  u"Kharovskiy"),
        (u"KG",  u"Kichmengsko-Gorodetskiy"),
        (u"KL",  u"Kirillovskiy"),
        (u"ME",  u"Mezhdurechenskiy"),
        (u"NI",  u"Nikol'skiy"),
        (u"NY",  u"Nyuksenskiy"),
        (u"SH",  u"Sheksninskiy"),
        (u"SG",  u"Sokol"),
        (u"SR",  u"Sokol'skiy"),
        (u"SY",  u"Syamzhenskiy"),
        (u"TA",  u"Tarnogskiy"),
        (u"TO",  u"Totemskiy"),
        (u"UK",  u"Ust'-Kubinskiy"),
        (u"UU",  u"Ustyuzhenskiy"),
        (u"VA",  u"Vashkinskiy"),
        (u"VU",  u"Velikiy Ustyug"),
        (u"VL",  u"Velikoustyugskiy"),
        (u"VE",  u"Verkhovazhskiy"),
        (u"VG",  u"Vologda"),
        (u"VR",  u"Vologodskiy"),
        (u"VO",  u"Vozhegodskiy"),
        (u"VY",  u"Vytegorskiy"),
        ]),

    ((u"VR", u"Voronezh"), [
        (u"AN",  u"Anninskiy"),
        (u"BB",  u"Bobrovskiy"),
        (u"BO",  u"Bogucharskiy"),
        (u"BG",  u"Borisoglebsk"),
        (u"BR",  u"Borisoglebskiy"),
        (u"BU",  u"Buturlinovskiy"),
        (u"ER",  u"Ertil'skiy"),
        (u"GR",  u"Gribanovskiy"),
        (u"KL",  u"Kalacheevskiy"),
        (u"KM",  u"Kamenskiy"),
        (u"KN",  u"Kantemirovskiy"),
        (u"KS",  u"Kashirskiy"),
        (u"KH",  u"Khokhol'skiy"),
        (u"LG",  u"Liski"),
        (u"LR",  u"Liskinskiy"),
        (u"NI",  u"Nizhnedevitskiy"),
        (u"NK",  u"Novokhoperskiy"),
        (u"NU",  u"Novousmanskiy"),
        (u"NV",  u"Novovoronezh"),
        (u"OL",  u"Ol'khovatskiy"),
        (u"OG",  u"Ostrogozhsk"),
        (u"OR",  u"Ostrogozhskiy"),
        (u"PN",  u"Paninskiy"),
        (u"PV",  u"Pavlovskiy"),
        (u"PE",  u"Petropavlovskiy"),
        (u"PD",  u"Podgorenskiy"),
        (u"PG",  u"Povorino"),
        (u"PR",  u"Povorinskiy"),
        (u"RA",  u"Ramonskiy"),
        (u"RE",  u"Rep'evskiy"),
        (u"RG",  u"Rossosh'"),
        (u"RR",  u"Rossoshanskiy"),
        (u"SE",  u"Semilukskiy"),
        (u"TA",  u"Talovskiy"),
        (u"TE",  u"Ternovskiy"),
        (u"VK",  u"Verkhnekhavskiy"),
        (u"VM",  u"Verkhnemamonskiy"),
        (u"VB",  u"Vorob'evskiy"),
        (u"VN",  u"Voronezh"),
        ]),

    ((u"YN", u"Yamal-Nenets"), [
        (u"GU",  u"Gubkinskyy"),
        (u"KR",  u"Krasnosel'kupskiy"),
        (u"LA",  u"Labytnangi"),
        (u"MU",  u"Muravlenko"),
        (u"NG",  u"Nadym"),
        (u"NR",  u"Nadymskiy"),
        (u"NU",  u"Novyy Urengoy"),
        (u"NY",  u"Noyabr'sk"),
        (u"PR",  u"Priural'skiy"),
        (u"PU",  u"Purovskiy"),
        (u"SA",  u"Salekhard"),
        (u"SH",  u"Shuryshkarskiy"),
        (u"TA",  u"Tazovskiy"),
        (u"YA",  u"Yamal'skiy"),
        ]),

    ((u"YS", u"Yaroslavl'"), [
        (u"BS",  u"Bol'shesel'skiy"),
        (u"BG",  u"Borisoglebskiy"),
        (u"BR",  u"Breytovskiy"),
        (u"DA",  u"Danilovskiy"),
        (u"GA",  u"Gavrilov-Yamskiy"),
        (u"LY",  u"Lyubimskiy"),
        (u"MY",  u"Myshkinskiy"),
        (u"NU",  u"Nekouzskiy"),
        (u"NS",  u"Nekrasovskiy"),
        (u"PG",  u"Pereslavl'-Zalesskiy"),
        (u"PR",  u"Pereslavskiy"),
        (u"PE",  u"Pervomayskiy"),
        (u"PO",  u"Poshekhonskiy"),
        (u"RS",  u"Rostov"),
        (u"RO",  u"Rostovskiy"),
        (u"RG",  u"Rybinsk"),
        (u"RR",  u"Rybinskiy"),
        (u"TG",  u"Tutaev"),
        (u"TR",  u"Tutaevskiy"),
        (u"UG",  u"Uglich"),
        (u"UR",  u"Uglichskiy"),
        (u"YG",  u"Yaroslavl'"),
        (u"YR",  u"Yaroslavskiy"),
        ]),

    ((u"YV", u"Yevrey"), [
        (u"BG",  u"Birobidzhan"),
        (u"BR",  u"Birobidzhanskiy"),
        (u"LE",  u"Leninskiy"),
        (u"OB",  u"Obluchenskiy"),
        (u"OK",  u"Oktyabr'skiy"),
        (u"SM",  u"Smidovichskiy"),
        ]),

    ((u"ZB", u"Zabaykal'ye"), [
        (u"AG",  u"Aginskiy"),
        (u"AK",  u"Akshinskiy"),
        (u"AL",  u"Aleksandrovo-Zavodskiy"),
        (u"BG",  u"Baley"),
        (u"BR",  u"Baleyskiy"),
        (u"BO",  u"Borzinskiy"),
        (u"BZ",  u"Borzya"),
        (u"CN",  u"Chernyshevskiy"),
        (u"CG",  u"Chita"),
        (u"CR",  u"Chitinskiy"),
        (u"DU",  u"Dul'durginskiy"),
        (u"GA",  u"Gazimuro-Zavodskiy"),
        (u"GO",  u"Gornyy Parish"),
        (u"KA",  u"Kalarskiy"),
        (u"KL",  u"Kalganskiy"),
        (u"KM",  u"Karymskiy"),
        (u"KH",  u"Khilokskiy"),
        (u"KC",  u"Krasnochikoyskiy"),
        (u"KG",  u"Krasnokamensk"),
        (u"KR",  u"Krasnokamenskiy"),
        (u"KY",  u"Kyrinskiy"),
        (u"MO",  u"Mogochinskiy"),
        (u"MY",  u"Mogoytuyskiy"),
        (u"NE",  u"Nerchinskiy"),
        (u"NZ",  u"Nerchinsko-Zavodskiy"),
        (u"OL",  u"Olovyanninskiy"),
        (u"ON",  u"Ononskiy"),
        (u"PR",  u"Petrovsk-Zabaykal'skiy"),
        (u"PG",  u"Petrovsk-Zabaykal'skiy"),
        (u"PI",  u"Priargunskiy"),
        (u"SP",  u"Shelopuginskiy"),
        (u"SK",  u"Shilkinskiy"),
        (u"SR",  u"Sretenskiy"),
        (u"TO",  u"Tungiro-Olekminskiy"),
        (u"TK",  u"Tungokochenskiy"),
        (u"UL",  u"Uletovskiy"),
        (u"ZA",  u"Zabaykal'skiy"),
        ]),
]
