 # -*- coding: utf-8 -*- 
################################################################################
# LexaLink Copyright information - do not remove this copyright notice
# Copyright (C) 2012 
#
# Lexalink - a free social network and dating platform for the Google App Engine. 
#
# Original author: Alexander Marquardt
# Documentation and additional information: http://www.LexaLink.com
# Git source code repository: https://github.com/lexalink/LexaLink.git 
#
# Please consider contributing your enhancements and modifications to the LexaLink community, 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

VE_regions = [   
    
    ((u"Z", u"Amazonas"), [
        (u"AO",  u"Alto Orinoco"),
        (u"AB",  u"Atabapo"),
        (u"AR",  u"Atures"),
        (u"AN",  u"Autana"),
        (u"MP",  u"Manapiare"),
        (u"MR",  u"Maroa"),
        (u"RN",  u"Río Negro"),
        ]),

    ((u"B", u"Anzoátegui"), [
        (u"AN",  u"Anaco"),
        (u"AR",  u"Aragua"),
        (u"DU",  u"Diego Bautista Urbaneja"),
        (u"FP",  u"Fernando de Peñalver"),
        (u"FM",  u"Francisco de Miranda"),
        (u"FC",  u"Francisco del Carmen Carvajal"),
        (u"GU",  u"Guanta"),
        (u"IN",  u"Independencia"),
        (u"JM",  u"José Gregorio Monagas"),
        (u"JS",  u"Juan Antonio Sotillo"),
        (u"JC",  u"Juan Manuel Cajigal"),
        (u"LI",  u"Libertad"),
        (u"MB",  u"Manuel Ezequiel Bruzual"),
        (u"PF",  u"Pedro María Freites"),
        (u"PI",  u"Píritu"),
        (u"SG",  u"San José de Guanipa"),
        (u"SC",  u"San Juan de Capistrano"),
        (u"SA",  u"Santa Ana"),
        (u"SB",  u"Simón Bolívar"),
        (u"SR",  u"Simón Rodríguez"),
        (u"AM",  u"Sir Artur McGregor"),
        ]),

    ((u"C", u"Apure"), [
        (u"AC",  u"Achaguas"),
        (u"BI",  u"Biruaca"),
        (u"MU",  u"Muñoz"),
        (u"PC",  u"Pedro Camejo"),
        (u"PA",  u"Páez"),
        (u"RG",  u"Rómulo Gallegos"),
        (u"SF",  u"San Fernando"),
        ]),

    ((u"D", u"Aragua"), [
        (u"BO",  u"Bolívar"),
        (u"CA",  u"Camatagua"),
        (u"FA",  u"Francisco Linares Alcántara"),
        (u"GI",  u"Girardot"),
        (u"JL",  u"José Angel Lamas"),
        (u"JF",  u"José Félix Ribas"),
        (u"JR",  u"José Rafael Revenga"),
        (u"LI",  u"Libertador"),
        (u"MI",  u"Mario Briceño Iragorry"),
        (u"OC",  u"Ocumare de la Costa de Oro"),
        (u"SC",  u"San Casimiro"),
        (u"SS",  u"San Sebastián"),
        (u"SM",  u"Santiago Mariño"),
        (u"SA",  u"Santos Michelena"),
        (u"SU",  u"Sucre"),
        (u"TO",  u"Tovar"),
        (u"UR",  u"Urdaneta"),
        (u"ZA",  u"Zamora"),
        ]),

    ((u"E", u"Barinas"), [
        (u"AT",  u"Alberto Arvelo Torrealba"),
        (u"AB",  u"Andrés Eloy Blanco"),
        (u"AS",  u"Antonio José de Sucre"),
        (u"AR",  u"Arismendi"),
        (u"BA",  u"Barinas"),
        (u"BO",  u"Bolívar"),
        (u"CP",  u"Cruz Paredes"),
        (u"EZ",  u"Ezequiel Zamora"),
        (u"OB",  u"Obispos"),
        (u"PE",  u"Pedraza"),
        (u"RO",  u"Rojas"),
        (u"SO",  u"Sosa"),
        ]),

    ((u"F", u"Bolívar"), [
        (u"CA",  u"Caroní"),
        (u"CE",  u"Cedeño"),
        (u"EC",  u"El Callao"),
        (u"GS",  u"Gran Sabana"),
        (u"HE",  u"Heres"),
        (u"PC",  u"Padre Pedro Chien"),
        (u"PI",  u"Piar"),
        (u"RL",  u"Raúl Leoni"),
        (u"RO",  u"Roscio"),
        (u"SI",  u"Sifontes"),
        (u"SU",  u"Sucre"),
        ]),

    ((u"G", u"Carabobo"), [
        (u"BE",  u"Bejuma"),
        (u"CA",  u"Carlos Arvelo"),
        (u"DI",  u"Diego Ibarra"),
        (u"GU",  u"Guacara"),
        (u"JM",  u"Juan José Mora"),
        (u"LI",  u"Libertador"),
        (u"LG",  u"Los Guayos"),
        (u"MI",  u"Miranda"),
        (u"MO",  u"Montalbán"),
        (u"NA",  u"Naguanagua"),
        (u"PC",  u"Puerto Cabello"),
        (u"SD",  u"San Diego"),
        (u"SJ",  u"San Joaquín"),
        (u"VA",  u"Valencia"),
        ]),

    ((u"H", u"Cojedes"), [
        (u"AN",  u"Anzoátegui"),
        (u"FA",  u"Falcón"),
        (u"GI",  u"Girardot"),
        (u"LB",  u"Lima Blanco"),
        (u"EP",  u"Pao de San Juan Bautista"),
        (u"RI",  u"Ricaurte"),
        (u"RG",  u"Rómulo Gallegos"),
        (u"SC",  u"San Carlos"),
        (u"TI",  u"Tinaco"),
        ]),

    ((u"Y", u"Delta Amacuro"), [
        (u"AD",  u"Antonio Díaz"),
        (u"CA",  u"Casacoima"),
        (u"PE",  u"Pedernales"),
        (u"TU",  u"Tucupita"),
        ]),

    ((u"W", u"Dependencias Federales"), [
        (u"DP",  u"Dependencias Federales"),
        ]),

    ((u"A", u"Distrito Capital"), [
        (u"LI",  u"Libertador"),
        ]),

    ((u"I", u"Falcón"), [
        (u"AC",  u"Acosta"),
        (u"BO",  u"Bolívar"),
        (u"BU",  u"Buchivacoa"),
        (u"CM",  u"Cacique Manaure"),
        (u"CR",  u"Carirubana"),
        (u"CL",  u"Colina"),
        (u"DA",  u"Dabajuro"),
        (u"DE",  u"Democracia"),
        (u"FA",  u"Falcón"),
        (u"FE",  u"Federación"),
        (u"JA",  u"Jacura"),
        (u"LT",  u"Los Taques"),
        (u"MU",  u"Mauroa"),
        (u"MD",  u"Miranda"),
        (u"MI",  u"Monseñor Iturriza"),
        (u"PA",  u"Palmasola"),
        (u"PE",  u"Petit"),
        (u"PI",  u"Píritu"),
        (u"SF",  u"San Francisco"),
        (u"SI",  u"Silva"),
        (u"SU",  u"Sucre"),
        (u"TO",  u"Tocopero"),
        (u"UN",  u"Unión"),
        (u"UR",  u"Urumaco"),
        (u"ZA",  u"Zamora"),
        ]),

    ((u"J", u"Guárico"), [
        (u"CA",  u"Camaguán"),
        (u"CH",  u"Chaguaramas"),
        (u"ES",  u"El Socorro"),
        (u"FM",  u"Francisco de Miranda"),
        (u"JF",  u"José Félix Ribas"),
        (u"JT",  u"José Tadeo Monagas"),
        (u"JR",  u"Juan Germán Roscio"),
        (u"JM",  u"Julián Mellado"),
        (u"LM",  u"Las Mercedes"),
        (u"LI",  u"Leonardo Infante"),
        (u"OR",  u"Ortíz"),
        (u"PZ",  u"Pedro Zaraza"),
        (u"SG",  u"San Gerónimo de Guayabal"),
        (u"SJ",  u"San José de Guaribe"),
        (u"SM",  u"Santa María de Ipire"),
        ]),

    ((u"K", u"Lara"), [
        (u"AB",  u"Andrés Eloy Blanco"),
        (u"CR",  u"Crespo"),
        (u"IR",  u"Iribarren"),
        (u"JI",  u"Jiménez"),
        (u"MO",  u"Morán"),
        (u"PA",  u"Palavecino"),
        (u"SP",  u"Simón Planas"),
        (u"TO",  u"Torres"),
        (u"UR",  u"Urdaneta"),
        ]),

    ((u"M", u"Miranda"), [
        (u"AC",  u"Acevedo"),
        (u"AB",  u"Andrés Bello"),
        (u"BA",  u"Baruta"),
        (u"BR",  u"Brión"),
        (u"BU",  u"Buroz"),
        (u"CA",  u"Carrizal"),
        (u"CH",  u"Chacao"),
        (u"CR",  u"Cristóbal Rojas"),
        (u"EH",  u"El Hatillo"),
        (u"GU",  u"Guaicaipuro"),
        (u"IN",  u"Independencia"),
        (u"LA",  u"Lander"),
        (u"LS",  u"Los Salias"),
        (u"PC",  u"Paz Castillo"),
        (u"PG",  u"Pedro Gual"),
        (u"PL",  u"Plaza"),
        (u"PA",  u"Páez"),
        (u"SB",  u"Simón Bolívar"),
        (u"SU",  u"Sucre"),
        (u"UR",  u"Urdaneta"),
        (u"ZA",  u"Zamora"),
        ]),

    ((u"N", u"Monagas"), [
        (u"AC",  u"Acosta"),
        (u"AG",  u"Aguasay"),
        (u"BO",  u"Bolívar"),
        (u"CA",  u"Caripe"),
        (u"CE",  u"Cedeño"),
        (u"EZ",  u"Ezequiel Zamora"),
        (u"LI",  u"Libertador"),
        (u"MA",  u"Maturín"),
        (u"PI",  u"Piar"),
        (u"PU",  u"Punceres"),
        (u"SB",  u"Santa Bárbara"),
        (u"SO",  u"Sotillo"),
        (u"UR",  u"Uracoa"),
        ]),

    ((u"L", u"Mérida"), [
        (u"AA",  u"Alberto Adriani"),
        (u"AB",  u"Andrés Bello"),
        (u"AS",  u"Antonio Pinto Salinas"),
        (u"AR",  u"Aricagua"),
        (u"AC",  u"Arzobispo Chacón"),
        (u"CE",  u"Campo Elías"),
        (u"CO",  u"Caracciolo Parra Olmedo"),
        (u"CQ",  u"Cardenal Quintero"),
        (u"GU",  u"Guaraque"),
        (u"JS",  u"Julio César Salas"),
        (u"JB",  u"Justo Briceño"),
        (u"LI",  u"Libertador"),
        (u"MI",  u"Miranda"),
        (u"OL",  u"Obispo Ramos de Lora"),
        (u"PN",  u"Padre Noguera"),
        (u"PL",  u"Pueblo Llano"),
        (u"RA",  u"Rangel"),
        (u"RD",  u"Rivas Dávila"),
        (u"SM",  u"Santos Marquina"),
        (u"SU",  u"Sucre"),
        (u"TO",  u"Tovar"),
        (u"TC",  u"Tulio Febres Cordero"),
        (u"ZE",  u"Zea"),
        ]),

    ((u"O", u"Nueva Esparta"), [
        (u"AC",  u"Antolín del Campo"),
        (u"AR",  u"Arismendi"),
        (u"DI",  u"Díaz"),
        (u"GA",  u"García"),
        (u"GO",  u"Gómez"),
        (u"MN",  u"Maneiro"),
        (u"MC",  u"Marcano"),
        (u"MA",  u"Mariño"),
        (u"PM",  u"Península de Macanao"),
        (u"TU",  u"Tubores"),
        (u"VI",  u"Villalba"),
        ]),

    ((u"P", u"Portuguesa"), [
        (u"AB",  u"Agua Blanca"),
        (u"AR",  u"Araure"),
        (u"ES",  u"Esteller"),
        (u"GE",  u"Guanare"),
        (u"GT",  u"Guanarito"),
        (u"MU",  u"Monseñor José Vicente de Unda"),
        (u"OS",  u"Ospino"),
        (u"PP",  u"Papelón"),
        (u"PZ",  u"Páez"),
        (u"SG",  u"San Genaro de Boconoito"),
        (u"SO",  u"San Rafael de Onoto"),
        (u"SR",  u"Santa Rosalía"),
        (u"SU",  u"Sucre"),
        (u"TU",  u"Turén"),
        ]),

    ((u"R", u"Sucre"), [
        (u"AB",  u"Andrés Eloy Blanco"),
        (u"AM",  u"Andrés Mata"),
        (u"AR",  u"Arismendi"),
        (u"BN",  u"Benítez"),
        (u"BR",  u"Bermúdez"),
        (u"BO",  u"Bolívar"),
        (u"CJ",  u"Cajigal"),
        (u"CA",  u"Cruz Salmerón Acosta"),
        (u"LI",  u"Libertador"),
        (u"MA",  u"Mariño"),
        (u"ME",  u"Mejía"),
        (u"MO",  u"Montes"),
        (u"RI",  u"Ribero"),
        (u"SU",  u"Sucre"),
        (u"VA",  u"Valdez"),
        ]),

    ((u"T", u"Trujillo"), [
        (u"AB",  u"Andrés Bello"),
        (u"BC",  u"Boconó"),
        (u"BL",  u"Bolívar"),
        (u"CN",  u"Candelaria"),
        (u"CR",  u"Carache"),
        (u"ES",  u"Escuque"),
        (u"JC",  u"José Felipe Márquez Cañizales"),
        (u"JE",  u"Juan Vicente Campo Elías"),
        (u"LC",  u"La Ceiba"),
        (u"MI",  u"Miranda"),
        (u"MC",  u"Monte Carmelo"),
        (u"MO",  u"Motatán"),
        (u"PT",  u"Pampanito"),
        (u"PA",  u"Pampán"),
        (u"RR",  u"Rafael Rangel"),
        (u"SR",  u"San Rafael de Carvajal"),
        (u"SU",  u"Sucre"),
        (u"TR",  u"Trujillo"),
        (u"UR",  u"Urdaneta"),
        (u"VA",  u"Valera"),
        ]),

    ((u"S", u"Táchira"), [
        (u"AB",  u"Andrés Bello"),
        (u"AC",  u"Antonio Rómulo Costa"),
        (u"AY",  u"Ayacucho"),
        (u"BO",  u"Bolívar"),
        (u"CA",  u"Cárdenas"),
        (u"CO",  u"Córdoba"),
        (u"FF",  u"Fernández Feo"),
        (u"FM",  u"Francisco de Miranda"),
        (u"GH",  u"García de Hevia"),
        (u"GU",  u"Guasimos"),
        (u"IN",  u"Independencia"),
        (u"JA",  u"Jauregui"),
        (u"JV",  u"José María Vargas"),
        (u"JU",  u"Junín"),
        (u"LI",  u"Libertad"),
        (u"LR",  u"Libertador"),
        (u"LO",  u"Lobatera"),
        (u"MI",  u"Michelena"),
        (u"PA",  u"Panamericano"),
        (u"PU",  u"Pedro María Ureña"),
        (u"RU",  u"Rafael Urdaneta"),
        (u"SM",  u"Samuel Darío Maldonado"),
        (u"SC",  u"San Cristóbal"),
        (u"SJ",  u"San Judas Tadeo"),
        (u"SE",  u"Seboruco"),
        (u"SR",  u"Simón Rodríguez"),
        (u"SU",  u"Sucre"),
        (u"TO",  u"Torbes"),
        (u"UR",  u"Uribante"),
        ]),

    ((u"X", u"Vargas"), [
        (u"VA",  u"Vargas"),
        ]),

    ((u"U", u"Yaracuy"), [
        (u"AB",  u"Arístides Bastidas"),
        (u"BO",  u"Bolívar"),
        (u"BR",  u"Bruzual"),
        (u"CO",  u"Cocorote"),
        (u"IN",  u"Independencia"),
        (u"JP",  u"José Antonio Páez"),
        (u"LT",  u"La Trinidad"),
        (u"MM",  u"Manuel Monge"),
        (u"NI",  u"Nirgua"),
        (u"PE",  u"Peña"),
        (u"SF",  u"San Felipe"),
        (u"SU",  u"Sucre"),
        (u"UR",  u"Urachiche"),
        (u"VE",  u"Veroes"),
        ]),

    ((u"V", u"Zulia"), [
        (u"AP",  u"Almirante Padilla"),
        (u"BA",  u"Baralt"),
        (u"CB",  u"Cabimas"),
        (u"CT",  u"Catatumbo"),
        (u"CO",  u"Colón"),
        (u"FP",  u"Francisco Javier Pulgar"),
        (u"JL",  u"Jesús Enrique Lossada"),
        (u"JS",  u"Jesús María Semprún"),
        (u"LU",  u"La Cañada de Urdaneta"),
        (u"LA",  u"Lagunillas"),
        (u"MP",  u"Machiques de Perijá"),
        (u"MA",  u"Mara"),
        (u"MC",  u"Maracaibo"),
        (u"MI",  u"Miranda"),
        (u"PA",  u"Páez"),
        (u"RP",  u"Rosario de Perijá"),
        (u"SF",  u"San Francisco"),
        (u"SR",  u"Santa Rita"),
        (u"SB",  u"Simón Bolívar"),
        (u"SU",  u"Sucre"),
        (u"VR",  u"Valmore Rodríguez"),
        ]),
]  